### ISSUE TITLE
Search Results Find Correct Content But Link To Wrong Page

### ISSUE THREAD

**Issue by massierick** [gctools-outilsgc/gcconnex#1001]
Some search results appear to be linking to incorrect pages. Not sure how, or why, but it is worth looking into I think. Here's one instance I came across, so you can try and replicate it to see if you can figure out what is causing it. 

I was trying to find this page: https://gcconnex.gc.ca/discussion/view/24953171/update-re-csps-b336-gctools-course-opportunity-for-ambassadors

It wasn't bookmarked, but I knew I could find it by searching "b336 massie". 

I entered those two terms in the GCConnex search (but with no quotes around it), and it brought up 4 results. The first two were to someones profile, the last two however appeared to be the right ones to the discussion topic and replies. Both are titled "Ambassadors Network for the GCTools : GCconnex"

I clicked on the link and got an error saying: 
"You must be a member of this group to view the requested page.
You do not have permission to view the requested page."

So I checked to see where the search result was linking, and it is linking here for some reason: 
https://gcconnex.gc.ca/groups/profile/6509207/fednor-demo

However, those discussions did not take place in this group  - they took place in the Ambassadors network group. 

Not sure why, but it seems that the search results are pulling a URL to the wrong group.

**Comment by ToferC** [comment]
Thanks for this, Rick. Approve investigation of search issue in next round
of search enhancements.

**Comment by pandurx** [comment]
I am currently looking into this
