### ISSUE TITLE
Organize search results by date modified

### ISSUE THREAD

**Issue by leducmartin** [gctools-outilsgc/gcconnex#1004]
User Story:
As a regular user, I need a way to organize my search results by the date each result was last modified, because I can use this information to identify the newest results and find the information I am looking for.

For examples, see the search on the TBS intranet, which allows sorting by date modified. Or see the search results page on Canada.ca, which supports filtering by date modified.

**Comment by pandurx** [comment]
Rajeev is implementing the functionality, will be a link that will allow sort feature.

**Comment by ToferC** [comment]
@pandurx - can you please confirm when this is going live? What action needs to be taken to unblock? Thanks!

**Comment by pandurx** [comment]
@ToferC as per the emails exchanged and discussions taken place, this will be implemented over the weekend (Saturday)
