### ISSUE TITLE
Unexpected error when performing an AJAX call. Maybe the connection to the server is lost.

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gcconnex#1009]
This error seems to appear when you leave GCconnex open for a long time (in this case over night) and return to the open window.  
Please remove this error message as the message provides no useful information to the user but makes the site look "broken" when it is not: the user can continue to use the site without consequence.

![ajax](https://cloud.githubusercontent.com/assets/22220521/25389131/c3105bda-299d-11e7-8f4f-5f4593106528.png)

**Comment by massierick** [comment]
Yes, this happens to me all the time. Doesn't cause any real issues, other than having to click a link again after the alert appears. But it is annoying.
