### ISSUE TITLE
Add language comprehension to other GCconnex content

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#1013]
The language comprehension tool is currently only applied to content in GCconnex discussions.  Please apply the same functionality to other gcconnex user comments in blogs, files, images, etc.  Wire posts would also be possible.

User Story:
As a user, I need to be able to understand and contribute to discussions in the official language of my choice.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
