### ISSUE TITLE
Don't use the `<i>` element for icons

### ISSUE THREAD

**Issue by nschonni** [gctools-outilsgc/gcconnex#1016]
Although the Font Awesome docs use this, the tag does have semantic meaning https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i
Bootstrap (and WET) switched to `<span>` for those http://getbootstrap.com/components/#glyphicons
This may come more from the Elgg core, I just noticed this looking at some of the code.

**Comment by ToferC** [comment]
Suggest this be part of best practices and review of plugins for content refresh.

**Comment by nschonni** [comment]
Nice 👍
