### ISSUE TITLE
Automated Password reset with email update feature

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1022]
As public servants move across government and change email address frequently and in high numbers, the Helpdesk is receiving high volumes of request to update user's email address and reset their password as 1. they forgot their password 2. they no longer have access to email address associated with their profile to request a password reset through the "forgot password" link.  Users will often omit to include their old email address (or further details) which would permit to easily find their profile, thus creating addition back and forth email between Helpdesk and the user to make sure we update the right profile.
It would be beneficial to have an automated password reset feature that allows the user to also update their email address if it has changed.  This may include an type of security question which once validated, would allow the user to be sent a password reset link to their new email address.

**Comment by ToferC** [comment]
Closing as not feasible.
