### ISSUE TITLE
Button for requesting group membership not working on BlackBerry

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1027]
The button Request membership doesn't work on blackberry despite other links on GCConnex working.

Last week, the "Executive Corner Launch" group was launched on GCconnex by an ADM at TBS, asking executives to join GCconnex and join the group "Executive Corner Launch". When using GCconnex from a BlackBerry (which is the case for many exécutives), the buttons for joining a group, or requesting membership are not working (show up but are not clickable). 
In addition, the buttons that appear on the BlackBerry screen seem to show all the group owner options, (such as manage membership request), even when not a group owner. See attached image.
![blackberry_group options](https://cloud.githubusercontent.com/assets/15378977/25585158/47cc3240-2e67-11e7-9afe-81f5e1534ea1.png)

Bug reported by Sylvain Levert - May 1, 2017.

**Comment by LemieuxGen** [comment]
@Troy-Lawson: would it be possible to have someone assigned to look at this bug is there's any time left in this sprint?

**Comment by Troy-Lawson** [comment]
i will try to merge this in tonight
