### ISSUE TITLE
Inactive buttons

### ISSUE THREAD

**Issue by gabrielcossette** [gctools-outilsgc/gcconnex#1030]
Hi,

I cannot reply to messages received in my GCconnex Inbox. I click on the top right Reply button and nothing happens. Tested with both Chrome and IE 11.

However, "Compose a message" does work.

Let me know if this issue is only related to my account or widespread.

Thanks!

**Comment by KevinChagnon** [comment]
When a user tries to a message by clicking on “Reply”, the Reply button does not respond
The button highlights however it does not respond when clicked. It is inactive.
![message reply](https://cloud.githubusercontent.com/assets/23527358/25806891/df007890-33d2-11e7-8aca-dc8d3d6185b4.jpg)

**Comment by KevinChagnon** [comment]
“Upload” button when Embedding a (new) file &  English title carries over to French Tab

When a user tries to Upload a new file through the Embed Content feature, the Upload button does not respond
The button highlights however it does not respond when clicked. It is inactive.

Also, the English title carries over to the French tab, modifications in the French tab title carry over to the English tab

![upload file1](https://cloud.githubusercontent.com/assets/23527358/25807024/631f551a-33d3-11e7-9ba0-d6e62afd030d.jpg)
![upload file2](https://cloud.githubusercontent.com/assets/23527358/25807042/75140dc4-33d3-11e7-9a86-de9f49b0ac39.jpg)

**Comment by KevinChagnon** [comment]
Tested reported inactive buttons and carry-over of English Title to French tab (reported in Upload file issue) and all work fine now.
