### ISSUE TITLE
"Save" button when creating a New Folder is inactive. 

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1031]
When a user tries to create a New Folder in the Files section, the Save button does not respond

The button highlights however it does not respond when clicked. It is inactive.

![new folder](https://cloud.githubusercontent.com/assets/23527358/25600067/3e25397e-2eaf-11e7-8ea4-864f0730ba73.JPG)

**Comment by Troy-Lawson** [comment]
should now be fixed
