### ISSUE TITLE
Training/Mentoring Request

### ISSUE THREAD

**Issue by massierick** [gctools-outilsgc/gcconnex#1033]
Hi,

Not sure if this is appropriate to post here or not - feel free to delete if not. 

I am very interested in helping fix issues and contribute to GCConnex. I have HTML, WET4, CSS and (basic) jQuery, PHP and Javascript skills. 

I can easily make feature upgrades on single (static) pages, but have been having trouble figuring out how to make site-wide changes on GCConnex and GCpedia. 

My Request:

Would someone be willing to train/mentor me on occasion?  What I envision:
When you come on to GitHub to perform upgrades or to fix issues listed on GitHub, you would be able to share your screen with me via webex, and simply talk through the process of what changes you are making. Maybe even allow me to ask some questions. 

I wouldn't want to be a hindrance, but I would find great value in being able to watch some of you work your magic. 

If anyone would be willing to do this for me, please let me know. I'd be so happy to learn more about the inner workings of GCConnex, and intend to pay back to the community once I can figure out how to make my upgrades/features available site-wide. 

Thanks for reading and taking the time to consider this!

**Comment by smellems** [comment]
This sounds very interesting Rick!  And we'd love to get your help with some of the Issues, maybe on GCcollab..  We could schedule a Webex with @markwooff or another dev to show the Elgg framework.  If you need help with installation and using Git, let me know.

Also check out the Elgg documentation for developers: http://learn.elgg.org/en/1.12/intro/development.html

**Comment by massierick** [comment]
Thanks! Just had a call from Jeff Outram, and sounds like I may be getting some help, and in turn, helping you all in return!

**Comment by ToferC** [comment]
@massierick - great! Closing issue and looking forward to working with you.
