### ISSUE TITLE
gcconnex: I would like to restrict the ability to upload files to a community page. I want only the group administrator and/or owner to be able to upload a file, but not the community members.

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#1039]
New Feature Request
As a New User, I need I would like to restrict the ability to upload files to a community page. I want only the group administrator and/or owner to be able to upload a file, but not the community members. because We are using GCconnex as a channel to distribute a dashboard which is updated on a regular basis. We want only the most recent version of the dashboard to be available on the community page. If members are allowed to upload files, they could overwrite the official and latest version.

tim.scapillato@tpsgc-pwgsc.gc.ca - 5/3/2017 14:03:10

**Comment by ToferC** [comment]
@KevinChagnon - please respond to user thanking them for suggestion and request that they ask group members not to upload files in the group description or in a separate widget. This is a fringe use case and doesn't warrant development action.  Closing issue.

**Comment by KevinChagnon** [comment]
Contacted user.
