### ISSUE TITLE
Justification for closed group

### ISSUE THREAD

**Issue by pandurx** [gctools-outilsgc/gcconnex#104]
We need to allow users to provide justification/reasoning or additional information when they try to join a closed group. Information will help the group owner to determine who they accept into the group.

Transferred from Leankit T137

**Comment by Troy-Lawson** [comment]
@pandurx was this ever implemented. I thought you were working on this? could be wrong

**Comment by pandurx** [comment]
There is a pull request for this functionality, but it requires upgrade because we revamped GCconnex

**Comment by pandurx** [comment]
the pull request was closed due to new infrastructure change, and not taking in any more enhancement
https://github.com/gctools-outilsgc/gcconnex/pull/107

should we have closed group implemented in new system, we can re-open this ticket
