### ISSUE TITLE
gcconnex: It would be great to add a button (similar to the minor change button), that only sends out one (1) email notification when new files are uploaded to a group using the multi-file option.

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#1052]
New Feature Request
As a Regular User, I need It would be great to add a button (similar to the minor change button), that only sends out one (1) email notification when new files are uploaded to a group using the multi-file option. because It is frustrating for members to receive seven or more (7+) back-to-back emails when one would suffice if that one email said "7 new files were uploaded to this group". Many members do not wish to, or know how to, turn off group notifications.

samuel.burke@pco-bcp.gc.ca - 5/5/2017 15:18:13

**Comment by LemieuxGen** [comment]
linked to issue #1055
