### ISSUE TITLE
gcconnex: I need the ability to hide (delete) the sidebar completely on GCconnex groups (where the group members and other side widgets appear).

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#1053]
Enhancement of existing feature
As a Regular User, I need I need the ability to hide (delete) the sidebar completely on GCconnex groups (where the group members and other side widgets appear). because If this sidebar was hidden, the description and other widgets could span the whole page, giving more of a feel of a real website, and increasing user experience. This would also allow for groups to appear much cleaner.

samuel.burke@Pco-bcp.gc.ca - 5/5/2017 15:23:21

**Comment by ToferC** [comment]
Review as part of group assessment work by @beckyjeong and content refresh.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
