### ISSUE TITLE
gcconnex: the ability to make widgets bilingual. In other words, when you edit text/images in a widget, you should be able to set the French and English text separately. 

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#1054]
Enhancement of existing feature
As a Regular User, I need the ability to make widgets bilingual. In other words, when you edit text/images in a widget, you should be able to set the French and English text separately.  because I have bilingual groups on GCconnex right now, that look really bad because the French has to go under the English in every widget. When you set a group to bilingual, there is a bar at the top that says "Ce contenu est aussi disponible en francais", but when you click français, the only thing that changes is the description.

samuel.burke@Pco-bcp.gc.ca - 5/5/2017 15:26:38

**Comment by ToferC** [comment]
Review as part of content refresh.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
