### ISSUE TITLE
Merge GCcollab back into GCconnex (Composer)

### ISSUE THREAD

**Issue by smellems** [gctools-outilsgc/gcconnex#1057]
Remove differences between GCconnex and GCcollab, either by moving customization to mods or merging changes from GCcollab into GCconnex.

The goal is to have a common "GCelgg" with custom platform specific mods being managed in separate repos ( gctools-outilsgc/gcconnex#1056 ).

**Comment by markwooff** [comment]
Most of the shared modules that have been customized on the GCcollab side have been moved to their own module (e.g. `gcRegistration` to `gcRegistration_collab`, `gc_splash_page` to `gc_splash_page_collab`, etc.). The originals would then sit in this "GCelgg" repo while we maintain our GCcollab-specific modules.

**Comment by smellems** [comment]
The `gcSplash` and `gcSplash_collab` should be two new repos.  The idea is that we would remove the GCcollab repo since it would be the same as GCconnex (GCelgg).  Then you can build one or the other using a different composer file

**Comment by nschonni** [comment]
It may be a separate issue, but looking at whether the changes between the Collab and Connex plug-ins can just be moved to config instead of code might be a good idea.
EX: If the differences for the Splash are just image and maybe translation, that could just be config boxes on the Admin side

**Comment by markwooff** [comment]
The differences between `gc_splash_page` and `gc_splash_page_collab` are small, it would make sense to have some sort of config to set the variables between the two platforms. In this case the differences are some links, text, and CSS.

@smellems is it possible to use composer to pull different data for a plugin? For example, passing through a `gcconnex` or `gccollab` flag to pull in the correct vars for each. If not, we could always create a small Elgg admin panel where you could choose between the two platforms.

**Comment by nschonni** [comment]
Looks like it is covered in the dev docs http://learn.elgg.org/en/stable/guides/settings.html. Looks like you could probably use the installer.php like https://github.com/gctools-outilsgc/gcconnex/blob/gcconnex/install/cli/travis_installer.php to config the instance specific stuff

**Comment by smellems** [comment]
As a first step, we will bring `gccollab` mods into the `gcconnex` repo.  The `gccollab` repo will become a copy of the `gcconnex` repo and all development will be on `gcconnex`.  There will be two plugin order config files to enable either `gcconnex `or `gccollab` mods.

Differences between core `gcconnex` and `gccollab` will be merged into `gcconnex` or moved to mods.

**Comment by markwooff** [comment]
That is correct. I will be submitting pull requests for the `gccollab` mods to be merged into the `gcconnex` repo. On my to-do list!

**Comment by markwooff** [comment]
PR https://github.com/gctools-outilsgc/gcconnex/pull/1167 has been submitted with all GCcollab-specific modules

**Comment by smellems** [comment]
Reopening this since development has continued on GCcollab repo and code has diverged again.  Need to merge changes to GCcollab into GCconnex and setup GCcollab to be deployed from GCconnex repo.

**Comment by Troy-Lawson** [comment]
to assign to mark

**Comment by markwooff** [comment]
@smellems branch has been made to finalize merging of GCcollab repo into GCconnex with the PR https://github.com/gctools-outilsgc/gcconnex/pull/1435. Once merged, we can have GCcollab pull directly from this repo while using a different `plugin_config.ini`
