### ISSUE TITLE
Wire - GCconnex & GCcollab - Share button

### ISSUE THREAD

**Issue by joymosk** [gctools-outilsgc/gcconnex#1058]
Ability for the Share button on the wire to easily share to a group or an individual via message or email. Right now, the share button is really a "repost on the wire".

**Comment by ToferC** [comment]
This would be a major change of functionality.  Suggest that this be blocked until we assess broader changes to the platform (consolidating blogs, discussions, etc.)

**Comment by ToferC** [comment]
Closing pending overall application review.
