### ISSUE TITLE
CSPS group not rendering (showing blue, unformatted and with Opps error)

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1069]
Canada School of Public Service group is not showing up properly. Looks fine when you look at the group page and you're not a member, but if you join the group, you see a blue screen, with the oops error at the bottom (see screen shot). Similar issue happened on April 13th for the GCTools group (See issue #967).
![csps group](https://cloud.githubusercontent.com/assets/15378977/25898782/77699f06-355b-11e7-9ad6-a68a25cb1565.JPG)

**Comment by LemieuxGen** [comment]
@piet0024 @Phanoix I think you both worked on a similar issue mid-April. Would it be possible to look at this issue today? The CSPS is having a big event today, and it would be important that there group works properly.
thanks!

**Comment by Phanoix** [comment]
fixed

**Comment by LemieuxGen** [comment]
@Phanoix Thanks! :)
