### ISSUE TITLE
My Profile - "We can help you fill out your profile!" function not working (Unclickable)

### ISSUE THREAD

**Issue by beckyjeong** [gctools-outilsgc/gcconnex#1073]
This issue may be specific to new users. I repeated the process multiple times (refreshing and logging out and logging in) and the same problem occurs again.

To replicate the issue:

1. Click on "My Profile" button
2. Attempt to click on "Let's do it!" or "Not Now" buttons in the "We can help you fill out your profile!" banner at the top
3. Not working / unclickable / buttons are not highlighted with a mouseover indicating that there is no further pathway

![20170520 we can help you fill out your profile functio not working](https://cloud.githubusercontent.com/assets/28573123/25901270/4221383c-3564-11e7-9b18-e3995a363c97.png)

**Comment by ToferC** [comment]
Approved for review.

**Comment by ethanWallace** [comment]
Was fixed as part of earlier onboarding changes
