### ISSUE TITLE
My Profile - "Work Experience" section formatting (Require HTML for a line break)

### ISSUE THREAD

**Issue by beckyjeong** [gctools-outilsgc/gcconnex#1076]
Unlike the "About Me" section, "Work Experience" requires < br > in between different bullet points and paragraphs in order to write on a new line. I am assuming it would be the same for GCcollab.

While some users may assume and use HTML, others may have difficulty as it is not explicitly obvious. Also, some users may not know how to write HTML.

![20170520 my profile html 1](https://cloud.githubusercontent.com/assets/28573123/25917334/a48a9726-3595-11e7-8825-46dc5f8a2e72.png)
![20170520 my profile html 2](https://cloud.githubusercontent.com/assets/28573123/25917335/a48b3172-3595-11e7-9485-8c15ea019f6d.png)
![20170520 my profile html 3](https://cloud.githubusercontent.com/assets/28573123/25917333/a48608fa-3595-11e7-902e-7ccefd5d3727.png)
![20170520 my profile html 4](https://cloud.githubusercontent.com/assets/28573123/25917332/a4813096-3595-11e7-956b-dcb8f46e2fc3.png)

Gen also found the following GCconnex post asking a similar question:

[https://gcconnex.gc.ca/discussion/view/26275996/how-do-i-make-my-profile-strength-100](url)

> if you could also tell me how to make sure my bullets start on a new line (instead of appearing as a paragraph chunk after hitting save)

**Comment by beckyjeong** [comment]
@LemieuxGen

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
