### ISSUE TITLE
Improve url sharing in the wire.

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#1083]
The long characters strings of GCconnex/GCcollab/GCpedia urls makes posting links to the wire difficult.  One url can consume most of the wire's 140 characters.

One possible solution, [the current (unofficial) GC link shortener](http://i.gc20.ca/) is not part of the GCTools and could go away at any time.

Options are to remove URLs from character limits on the wire or incorporate a GC link shortener into the GCTools and automatically shorten pasted links.

Note, as folks can use the hyperlink in the CKeditor in other post formats, this is only an issue for the wire.

Suggest we consider a broader re-design of the wire to incorporate feedback from GCcollab users and Wahida's assessment.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
