### ISSUE TITLE
Changes not saving when editing content using "Source" editing and when pasting content in Rich text editor

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1086]
As a user I need to be able to save Edits to content using "Source" mode and when pasting new content using the Rich text editor.
When I edit a page or discussion using the "Source" mode, the changes will not save.
If the change to the content is typed or is a copy/paste from a webpage, it will save in the Rich text editor however if it is copy/paste from Word or an e-mail, it will not save.

**Comment by KevinChagnon** [comment]
I tested this again today and it seems that copy/paste from Word or email to the Rich text editor does retain changes when saved BUT changes are still not saving when done using the "Source editor"

**Comment by ethanWallace** [comment]
@KevinChagnon Is this issue still occurring? I haven't been able to replicate it.

**Comment by KevinChagnon** [comment]
Looks like creating new content in Source Editing mode now work, however user gets an "Empty Post" Error when commenting/replying to a post in Source Edit mode;

![empty post](https://user-images.githubusercontent.com/23527358/30558167-86ea84ba-9c7e-11e7-9784-deb1ef22f75f.PNG)
