### ISSUE TITLE
Unable to Access Manage Group Operators Page in Group - 500 Error

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1087]
Unable to access "Manage group operators" page in the [Welcome to GCconnex group](https://gcconnex.gc.ca/groups/profile/19980634/welcome-to-gcconnex). Tried multiple times, without success. The group currently has 18055 members. 
![manage grou poperators welcome to gcconnex - 18055members](https://cloud.githubusercontent.com/assets/15378977/26105509/37c7bd74-3a10-11e7-9cb1-8d697dfe053a.JPG)

**Comment by LemieuxGen** [comment]
@Phanoix could this be linked with issue #796?

**Comment by Phanoix** [comment]
probably related to the fix for it, I'll take a look.
