### ISSUE TITLE
Can't update title of file unless new file is uploaded

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1095]
As a regular user I need to be able to update a file's title without having to upload the file again;
When I try to update the title of a file, I can't do so unless I reload the file itself. I used to be able to update the title after it was uploaded, but now it appears I can't make any changes unless the file gets replaced.
It is indicated that the field must be left blank if the file itself is not updated but when attempting to save the change to the tile I get the following error message under "Chose File"
![new file name](https://cloud.githubusercontent.com/assets/23527358/26163276/3201b8f8-3af7-11e7-88e0-174490ad0941.JPG)

**Comment by ethanWallace** [comment]
Fixed in pull request #1065
