### ISSUE TITLE
Can't add new Group operator

### ISSUE THREAD

**Issue by gabrielcossette-ca** [gctools-outilsgc/gcconnex#1096]
Settings->Manage group operators->Add another operator

We receive the following error message when clicking on "Make operator": **You do not have the permissions for this**

**Comment by LemieuxGen** [comment]
@Phanoix @Troy-Lawson Group owner and users are no longer able to add group operators.
![can not add group operator](https://cloud.githubusercontent.com/assets/15378977/26204455/ced39a92-3bac-11e7-98fc-c0d185973357.JPG)
