### ISSUE TITLE
Add time zone option to events

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gcconnex#1099]
Hi!

Someone just made me realize that there's no time zone option when we create an event in GCconnex.

I think it is essential that this option be added.

Thanks!

**Comment by joymosk** [comment]
+1 User Howard Jones asked in the GCTools https://gcconnex.gc.ca/discussion/view/31310218/engcconnex-event-time-zone-issuefr

**Comment by CalvinRodo** [comment]
It would be nice if this was automatically done. 

- Capture the time in the users timezone
- Store in UTC
- Render the time in the users timezone

You can use either geolocation to capture users timezone or allow the user to set it in their account settings.

**Comment by martydonofrio** [comment]
https://gccollab.gctools-outilsgc.ca/a/tickets/6522

**Comment by Menrika** [comment]
Freshdesk: 
https://gccollab.gctools-outilsgc.ca/a/tickets/5557
https://gccollab.gctools-outilsgc.ca/a/tickets/6773

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
