### ISSUE TITLE
Group management options only viewable from About page of the group

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1101]
As a group owner or operator, I need to be able to see all group management settings from any page of the group so that I can efficiently manage my group.

From group's about page, settings drop down menu shows: Edit group, Invite my colleagues, Manage group operators, Manage invitations, Email Members, Create a Sub-Group.
![group settings_about page](https://cloud.githubusercontent.com/assets/15378977/26250350/b9c1b910-3c77-11e7-9568-5a5fe9f55a62.JPG)

From any other page in the group (except the About page), settings options include: Edit group, Invite my colleagues, Manage invitations, Email Members.
![group settings_other page page](https://cloud.githubusercontent.com/assets/15378977/26250353/bd58b54c-3c77-11e7-85f2-d4c3d2fc5c55.JPG)

**Comment by LemieuxGen** [comment]
@ethanWallace I see this ticket is closed, but the group management options are still not viewable from the other sections of the group (ex: discussions). Was this pushed to prod?
![group mngt options](https://cloud.githubusercontent.com/assets/15378977/26783406/021e0b7c-49c6-11e7-9235-2f2aeca55b7b.JPG)

**Comment by ethanWallace** [comment]
@LemieuxGen No there was no push this past weekend so this fix has not been pushed to prod.
