### ISSUE TITLE
"Contact Us" form rejects valid e-mail address with unusual characters

### ISSUE THREAD

**Issue by gabriellehubert** [gctools-outilsgc/gcconnex#1105]
All users should have the ability to use the "Contact Us" form to report issues or get guidance from a GCTools Unit Support Officer. However, some users with valid GoC e-mail addresses which happen to have irregular characters (such as hyphens or apostrophes) are being rejected by the form, rendering them unable to use it as intended.  

The following two screenshots demonstrate an example of the form filled out using an e-mail address containing both an apostrophe and a hyphen, and the error message that follows.

![email rejection pt1](https://cloud.githubusercontent.com/assets/25649583/26261845/cb1d013c-3ca0-11e7-9253-47b4ec6d2837.png)

![email rejection pt2](https://cloud.githubusercontent.com/assets/25649583/26261865/d31d26be-3ca0-11e7-8613-824099c27cde.png)

**Comment by nschonni** [comment]
It appears to be the use of the custom email validator https://github.com/gctools-outilsgc/gcconnex/blob/266a6eef44ae6c854e98228393f8abac28e3fcce/mod/wet4/views/default/contactform/scripts/gen_validatorv31.js#L362
Reqular WET validation allows the address in the screenshot http://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-en.html
