### ISSUE TITLE
Ability for users to include emoticons in new Wire Posts

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1114]
As a GCconnex user and volunteer executive member of the Professional Development Network – Ontario Region Core team, I believe the option for users to include emoticons in new Wire Posts would benefit the federal public servants community.  This allow employees to express their ideas or thoughts with visuals.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
