### ISSUE TITLE
Expand the choices of emoticons in the Insert a Smiley menu.  

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1115]
As a GCconnex user and volunteer executive member of the Professional Development Network – Ontario Region Core team, .  I believe expanding the choices of emoticons in the Insert a Smiley menu would benefit the federal public servants community. This would allow employees to express their ideas or thoughts with a wider choice of visuals! 
![emoticon 1](https://cloud.githubusercontent.com/assets/23527358/26500316/79b642d2-4203-11e7-8354-f4a3c8297119.jpg)
![emoticon 2](https://cloud.githubusercontent.com/assets/23527358/26500334/80196ffa-4203-11e7-85ef-7afdb2b65db1.jpg)

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
