### ISSUE TITLE
Digest using French Subject line

### ISSUE THREAD

**Issue by nschonni** [gctools-outilsgc/gcconnex#1116]
The rest of the email is in English, but the subject line appears to be picking up the wrong language.
![image](https://cloud.githubusercontent.com/assets/1297909/26502935/c22b4b4e-420c-11e7-82a5-2b1811c75bb0.png)

**Comment by pandurx** [comment]
The patch for this may have already been applied to production. Please see the specified pull request.

**Comment by nschonni** [comment]
:+1: I can confirm that it was fixed probably a day or so after reporting the issue. I'll let the referenced issue close it once it's merged.

PS: It's a good idea to use the [close from the commit message](https://help.github.com/articles/closing-issues-via-commit-messages/), since then users can see what the resolution is
