### ISSUE TITLE
French characters don't display in Digest email

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gcconnex#1119]
I got the digest on Sunday: the French characters don't display in the email.
Here is the text of the email I received:

Votre résumé GCconnex : De nouvelles activités à signaler!
Ceci est un message généré par le système de GCconnex. Veuillez ne pas répondre à ce message
GCconnex 
Bonjour Philippe Andrecheck. Voici vos notifications pour le 2017/05/28
Notifications de la Plateforme de possibilités
•	14 Nouvels items ont été publiés
o	Jean-Su00e9bastien Saulnier a publié une opportunité (Mutation): Statistique Canada cherche u00e0 du00e9ployer des CS-02 | Statistics Canada is looking to deploy highly motivated CS-02u2019s - Date limite : 2017-07-28
o	Jean-Su00e9bastien Saulnier a publié une opportunité (Mutation): Statistique Canada cherche u00e0 du00e9ployer des CS-02 | Statistics Canada is looking to deploy highly motivated CS-02u2019s - Date limite : 2017-07-28
o	Jean-Su00e9bastien Saulnier a publié une opportunité (Mutation): Statistique Canada cherche u00e0 du00e9ployer des CS-03 hautement motivu00e9s | Statistics Canada is looking to deploy highly motivated CS-03u2019s - Date limite : 2017-07-28
o	Chantal Martel a publié une opportunité (Détachements / Affectations): Adjoint(e) exu00e9cutif(ve) - Executive Assistant - Date limite : 2017-06-01
o	Chantal Martel a publié une opportunité (Détachements / Affectations): Adjoint(e) exu00e9cutif(ve) - Executive Assistant - Date limite : 2017-06-01
o	Jean-Su00e9bastien Saulnier a publié une opportunité (Mutation): Statistique Canada cherche u00e0 du00e9ployer des CS-03 hautement motivu00e9s | Statistics Canada is looking to deploy highly motivated CS-03u2019s - Date limite : 2017-07-28
o	Jean-Su00e9bastien Saulnier a publié une opportunité (Mutation): Statistique Canada cherche u00e0 du00e9ployer des CS-03 hautement motivu00e9s | Statistics Canada is looking to deploy highly motivated CS-03u2019s - Date limite : 2017-07-28
o	Jean-Su00e9bastien Saulnier a publié une opportunité (Mutation): Statistique Canada cherche u00e0 du00e9ployer des CS-03 hautement motivu00e9s | Statistics Canada is looking to deploy highly motivated CS-03u2019s - Date limite : 2017-07-28
o	Joanne Bastille1 a publié une opportunité (Mutation): AS-02 Administrative Assistant / Adjointe administrative - Date limite : 2017-06-19
o	Jacques Denomme a publié une opportunité (Micro-mission): Adjoint(e) exu00e9cutif(ve) - Executive Assistant - AS-01 - Date limite : 2017-06-02
o	Jacques Denomme a publié une opportunité (Micro-mission): Adjoint(e) exu00e9cutif(ve) - Executive Assistant - AS-01 - Date limite : 2017-06-02
o	Cristina Bianchi a publié une opportunité (Détachements / Affectations): IS-04 (or equivalent) for one year // poste IS-04 (ou lu2019u00e9quivalent) pour un an - Date limite : 2017-06-02
o	Cristina Bianchi a publié une opportunité (Détachements / Affectations): IS-04 (or equivalent) for one year // poste IS-04 (ou lu2019u00e9quivalent) pour un an - Date limite : 2017-06-02
o	William Jeans a publié une opportunité (Détachements / Affectations): Casual AS-01 at ESDC- Looking for AS/CR/PM in the NCR- Casual/Term/Indeterminate - Date limite : 2017-07-12
Notifications de groupe
•	GCTools
o	5 Nouvels items ont été publiés
	Jenn Goudie Coates a publié une discussion : Finding regisitered users 
	Jenn Goudie Coates a publié une discussion : Finding regisitered users 
	Jenn Goudie Coates a publié une discussion : Finding regisitered users 
	Jenn Goudie Coates a publié une discussion : Finding regisitered users 
	u00c7hristinu00e9 Yu a publié un fichier : TwitterCode 
•	Digital Government
o	2 Nouvels items ont été publiés
	Aaron Rajesh a publié une page : 2017 5, Department of the Prime Minister and Cabinet | New look MyGov making life easier for 10 million Australians 
	Aaron Rajesh a publié une page : 2017 5, Xinhua Net | Unified data-sharing platform proposed for e-government 

Cordialement,
L'équipe des OutilsGC

**Comment by pandurx** [comment]
@PhilAndrecheck  is this still happening?

**Comment by PhilAndrecheck** [comment]
Thanks!
