### ISSUE TITLE
New pages not saving content, cannot delete page, duplicates not showing in list of editable pages

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1120]
When a new sub-page is created under the "Newsbytes" page (https://gcconnex.gc.ca/pages/view/19479736/newsbytes) in the Digital Government group (https://gcconnex.gc.ca/pages/group/18885366/all), the content does not save and when viewing the page as the creator (and as an admin) there is no option to edit, delete or share the page.  There are also no details as to who created the post.  As a user, I would need this content to be saved and displayed and also be able to delete/edit the duplicate sub-pages that were created when attempting to create a new page.
These pages are displayed as follows:
![no page no content](https://cloud.githubusercontent.com/assets/23527358/26556421/73770458-4468-11e7-8776-b5ca78b9e527.JPG)

The behaviour  is not constant in that it does not happen with every page that is created.

If the user tries to create the same page again, the user gets the same result - no content.  The page will show only once in the list of editable pages, but will show as many times as there were attempts to create it in the right hand page navigation list.

**Comment by KevinChagnon** [comment]
#1087

**Comment by ethanWallace** [comment]
@KevinChagnon Please inform the user that their affected pages should now display properly. If there are any more pages that are still affected that I missed, please forward them to me.

**Comment by KevinChagnon** [comment]
see this link: https://gcconnex.gc.ca/pages/group/24670219/all

There are many pages missing in the list of editable pages and there is no option to edit a page when selected from the list on the right.  User is trying to delete duplicates and of course add content to these pages.
