### ISSUE TITLE
Search results for groups shows name of the groups' related groups

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1123]
When searching for a group on GCconnex, the search results show the name of a related group instead of the name of the group being searched for. EX:
Search for "Data Science", gives as a first results "Enterprise Data Integration, Management & Analytics", which is a related group of the group "Data Science @ GoC". The results need to show the name of the group, not the related groups (related groups widget should be excluded from the search results.)
![group search_related groups](https://cloud.githubusercontent.com/assets/15378977/26584621/6e4cb95a-4517-11e7-95a0-6b81229a86c7.JPG)
![group search_related groups2](https://cloud.githubusercontent.com/assets/15378977/26584622/6e53b6d8-4517-11e7-972b-7619bd4f72a3.JPG)

**Comment by pandurx** [comment]
Duplicate issue gctools-outilsgc/gcconnex#1001
