### ISSUE TITLE
"Closed – users must request to join" option missing from group membership permissions

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1140]
As a group owner/operator, I need to be able to set group membership permissions to "Closed – users must request to join" which used to be an available option.
The are currently only 2 options "Open – Any user may join" and "Closed – Users must be invited". 
I would like for All Public Servants to see my group, however they would need to request permission to join.

**Comment by LemieuxGen** [comment]
Please chance wording to say "Closed - Users must request to join the group" FR: "Fermé - les utilisateurs doivent faire une demande pour joindre le groupe".
