### ISSUE TITLE
gcconnex: The ability to "follow" an individual's blog feed

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#1142]
New Feature Request
As a New User, I need The ability to "follow" an individual's blog feed because There are some people that regularly contribute to a personal blog on GCconnex, and if the content is good I would like to get updates when they post new material. 

 - 6/7/2017 9:21:40

**Comment by pandurx** [comment]
Isn't this the same as subscribe to blog?

**Comment by ToferC** [comment]
Or follow the person.

**Comment by pandurx** [comment]
There is subscribe to colleague functionality
