### ISSUE TITLE
Group members not receiving notifications (new file upload, new discussion, ect.)

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1146]
Members of some groups are not receiving notifications when new files are uploaded or new content is posted to the group.  I have verified group and member settings and can confirm that the users are subscribed to receive email notifications and that there has been recent activity in the group.
Examples of groups where this is happening:

https://gcconnex.gc.ca/groups/profile/24393400/the-public-service-employee-annual-survey-pseas-le-sondage-annuel-aupres-des-fonctionnaires-federaux-saaff

https://gcconnex.gc.ca/groups/profile/10451879/cfpconnex-parlons-en-pscconnex-lets-talk

https://gcconnex.gc.ca/groups/profile/7322003/gc-ea-working-group

https://gcconnex.gc.ca/groups/profile/12448299/cross-domain-solutions

https://gcconnex.gc.ca/groups/profile/6753922/it-security-tripartite-itst-technical-interchange-meetings-tims

https://gcconnex.gc.ca/groups/profile/18753716/government-of-canada-security-summit-sommet-sur-la-securite-du-gouvernement-du-Canada

https://gcconnex.gc.ca/groups/profile/2785549/gc-enterprise-security-architecture-gc-esa

**Comment by LemieuxGen** [comment]
@pandurx Would it be possible to look into this issue? We have others who reported the same issue. Some users are subscribed to the digest, and some not, but the same problem is happening, users are not receiving notifications about group postings.

**Comment by KevinChagnon** [comment]
Another group that creates no content yet no notification is sent to members:

https://gcconnex.gc.ca/groups/profile/20383838/cio-blog-blogue-dpi
