### ISSUE TITLE
To have consistant behaviour of green "confirmation bar"

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1153]
User: 
"This green "confirmation bar" shows up to confirm when you like something, when you post something, etc. When it shows up to confirm that you have liked something, you can just click anywhere on it and it disappears. When it confirms that you post something, or delete things (as in the screen clip attached), clicking anywhere on it doesn't close it. Instead, you have to enlarge your Internet Explorer (IE) window to be able to get to the "x" on the far right that will close it. There isn't even a scroll bar at the bottom to scroll over to get to the "x". Frequently, once I've deleted messages, I want to log out. But I can't log out because, in the case of deleting messages/notifications (see screen clip), I can't even access my account options because the bar covers me completely. So if I want to log out, I have to enlarge my IE window, click the "x" to close the bar, and THEN click on me, and log out. Needless to say, it's a bit frustrating, to say the least. Is it possible, then, to do one of the following options to avoid having to do these seemingly unnecessary steps? 1) Make the bar act like it does for likes: Simply click anywhere on it to make it disappear. 2) Make it responsive to the size of the IE window - ie: the entire green bar shows up in the IE window regardless of how big or small the IE window is. 3) Create a bar at the bottom of the IE window that allows you to scroll left and right. My preference would be idea 1 above - it exists for the green bar that appears when you like something.  Also from a user perspective, it's preferable to be able to just click anywhere than to have to click on one small x."
![green confirmation bar_2017-06-12](https://user-images.githubusercontent.com/23527358/27132958-9d9b999c-50de-11e7-9c04-6e89f96ffe50.GIF)

**Comment by ToferC** [comment]
Approved for review and work. Behavior should be consistent and accessible. Suggest disappear after 3-5 seconds and clicking anywhere on the screen dismisses it.
