### ISSUE TITLE
Hyperlink not detected in new Event

### ISSUE THREAD

**Issue by gabrielcossette** [gctools-outilsgc/gcconnex#1154]
Hi!

When we create a new Event and add an hyperlink in the description, the hyperlink is not clickable after the Event has been posted. We must manually create the hyperlink using the corresponding button in the toolbar.

Just like in Discussions, the hyperlink should be automatically detected.

Thanks!

**Comment by ToferC** [comment]
@KevinChagnon @klecuyer - please test and update issue. Thanks!

**Comment by ToferC** [comment]
Also - this should probably be addressed in the content refresh discussion.

**Comment by KevinChagnon** [comment]
Tested this issue and confirming that the hyperlink is not automatically detected as it is elsewhere on the platform.  You must use the toolbar button to insert the link as the user has described;

![no hypelink new event](https://user-images.githubusercontent.com/23527358/28214307-bef8a48a-6877-11e7-958f-34965a873114.JPG)

**Comment by KevinChagnon** [comment]
Looking at older pending tickets so tested this again - this now works.  Closing issue.
