### ISSUE TITLE
GCconnex - Files Tab -- allow option to see folders instead of last five uploads

### ISSUE THREAD

**Issue by IN-RIX** [gctools-outilsgc/gcconnex#1157]
Hello,
My team is using GCconnex to connect with team members that do not have consistent GCDOCS access. We have set up a sub-group in GCconnex so that we can share unprotected files. Currently, when a member selects the "FILES" tab within the group, they are brought to a page that only shows the last five uploaded files. We would rather be able to have our group members go straight to the file folders under which we have organized our files. Some users do not see the "VIEW ALL" link at the bottom.

**Comment by ToferC** [comment]
@beckyjeong - please consider in group review.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
