### ISSUE TITLE
gcconnex: I would like to see the option to sort bookmarks into folders.

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#1160]
Enhancement of existing feature
As a Regular User, I need I would like to see the option to sort bookmarks into folders. because Bookmarks would allow me to group them.  Also, I would like to be able to bookmark things by types (ie. I need to bookmark a number of directives, policies, etc.) but at the moment they get mixed up.

allison.perquin@canada.ca - 6/16/2017 10:06:35

**Comment by ToferC** [comment]
Similar/duplicate to gctools-outilsgc/gcconnex#1161 with focus on bookmarks. @beckyjeong for group milestone.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
