### ISSUE TITLE
gcconnex: I would like to be able to re-order file folders, posts, etc. in the various places on my GCconnex group (ie. in the files tab, bookmarks tab, etc.)

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#1161]
New Feature Request
As a Regular User, I need I would like to be able to re-order file folders, posts, etc. in the various places on my GCconnex group (ie. in the files tab, bookmarks tab, etc.) because I would like to be able to move certain posts/files/entries to the top of the list that are of higher importance to the group - it would also allow for better grouping of content

allison.perquin@canada.ca - 6/16/2017 10:22:38

**Comment by ToferC** [comment]
@beckyjeong - please consider this use case in your review of Groups. This is pretty significant functionality change, but funnily enough also reflects the original Elgg theme that used widgets for everything.

**Comment by klecuyer** [comment]
+1

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
