### ISSUE TITLE
gcconnex: a way to connect a full communication application such as Pidgin to the GCconnex system in order to have full notifications (like an alert in the Windows task bar)

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#1162]
New Feature Request
As a Regular User, I need a way to connect a full communication application such as Pidgin to the GCconnex system in order to have full notifications (like an alert in the Windows task bar) because The chat will not notify the user of a new message unless the web page is kept at the GCconnex web page. This will never be the case since most users need to move between different sites (Phoenix, GCDocs, Peoplesoft, etc).

The only notification is a short beep and that only works for people who have speakers attached to their workstations (and are not on teleconference).

Without notifications, the usefulness of GCconnex Chat is mostly limited to seeing who is online since message will go unnoticed for long periods of time.

Sylvain.lafeur@ssc-spc.gc.ca - 6/16/2017 10:24:41

**Comment by ToferC** [comment]
Closing as related to ongoing IM/Team Chat upgrade work on GCTools. @KevinChagnon - could you please respond to the user?  Thanks!

**Comment by KevinChagnon** [comment]
Contacted user.
