### ISSUE TITLE
Ability to add Favorites to Community Favorites widget + change name of widget

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1164]
It is currently not possible to add Favorite pages to the Community Favorites widget available in the GCconnex Dashboard.
The widget  instructs users to click on the star in the sidebar to add a favorite Community page to the widget however there is no start to be found on any GCconnex page.
![community favorites](https://user-images.githubusercontent.com/23527358/27232869-9364a7ae-5285-11e7-9ed3-1e83b67ed5d2.png)
Also, the French version of the widget does not seem to have been translated
![community favorites french](https://user-images.githubusercontent.com/23527358/27233083-4d5a5848-5286-11e7-8f6a-41a194bef49b.png)
The star in the sidebar was removed when the platform was updated with a new design.
![community favorites star](https://user-images.githubusercontent.com/23527358/27233021-159991b2-5286-11e7-87b7-ed1223f48b07.png)
This feature acts like favorites or bookmarks in a web browser.  A user can add a group pages, blog list, etc. as a favorite.  Favorites added by a user will only be displayed in their dashboard and will not be seen by other users.
I would be a good idea to rename the widget "My Favorites" as the current name "Community Favorites" could lead to confusion.

**Comment by ToferC** [comment]
@KevinChagnon - good catch with this one. @piet0024 @ethanWallace - not sure if removing the favourite "star" was an oversight or deliberate. @beckyjeong - please consider this in your group review.

**Comment by LemieuxGen** [comment]
@Troy-Lawson Can you ask someone from the tech team to look into the effort required into bringing back the star? @pandurx had you looked at this in the past? I vaguely remember a conversation about this. If it's easy to bring back, please do. If not, we need the remove the Community Favourite from the Widgets.
Thanks.

**Comment by LemieuxGen** [comment]
@markwooff this issue is the same on GCcollab.

**Comment by Steph4104** [comment]
We can add back the star with the clip and RSS feed when we remove the comment tag around the echo of extras menu in mod/wet4/views/default/page/elements/sidebar.php

But, i'm not sure if we want something different with the design or not.
