### ISSUE TITLE
List view for Opportunities platform

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1165]
As a regular user, I find that the card view in the Opportunities Platform takes a lot of the page real-estate leaving a lot of white space.  It would be nice to be able to see the Opportunities in a list view in order to have more items displayed on a single page.

**Comment by ToferC** [comment]
Approved for work. Toggle option between would be cool.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
