### ISSUE TITLE
Look for *secret* documents on GCconnex

### ISSUE THREAD

**Issue by pandurx** [gctools-outilsgc/gcconnex#1168]

**Comment by ToferC** [comment]
@cdegrass @pandurx - please update with status. I think this is active in sprint 16, no?

**Comment by pandurx** [comment]
i have everything set up, charles was supposed to give me the terms

**Comment by ToferC** [comment]
@cdegrass - I think you did this. Can we close?

**Comment by Troy-Lawson** [comment]
@pandurx @cdegrass is this finished or still ongoing?

**Comment by pandurx** [comment]
@Troy-Lawson  I don't know if there is still a need for this, never got the metadata from IM group. I also don't know who I need to follow up / contact for metadata.
