### ISSUE TITLE
Subsequent page of search results not displaying results

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1174]
When conducting a search in GCconnex, the subsequent pages return a white screen with a URL and not the next page of search results.
In the example below, a search was done for "government"
![search - government](https://user-images.githubusercontent.com/23527358/27300321-54d09406-54fd-11e7-8836-54cad7755060.JPG)

When the user clicks on "2" to go to the next page, the result is the following:

![serach - government - next page](https://user-images.githubusercontent.com/23527358/27300344-6dc52ed6-54fd-11e7-8cd6-416caf80a094.JPG)

**Comment by pandurx** [comment]
This has been resolved @KevinChagnon
