### ISSUE TITLE
Develop application architecture for Elgg 2 upgrade

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#1179]
Business team will develop and lead consultations with users to inform the upgrade to Elgg 2.

For consideration:

- Consolidation of content types
- Overall layout and UI / Navigation
- Core requirements for enterprise collaboration

**Comment by joesb** [comment]
Are there any plans to upgrade the Elgg core for GCconnex? Elgg is now on 3.x

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
