### ISSUE TITLE
Add supervisor relationship to work experience in user profiles

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#1180]
As part of the recommendation engine preparatory work, add a supervisor field to work experience and a new relationship, "supervisor" to the elgg relationship types.

This data will support the recommendation engine profile and allow the creation and visualization of organic org charts across the public service.

User Stories:

As an regular user, I need to be able to add my manager to my work experience as an optional field so that people can contact them for references.

As a regular user, I need to be able to understand my organization by being able to see an accurate organization chart.

**Comment by Troy-Lawson** [comment]
This functionality will be built into the profile / directory service, so this issue will be closed
