### ISSUE TITLE
Add group and level as hidden field in user profile

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#1181]
As part of the data required for the recommendation engine profile, add optional fields for occupational group and level as a private (hidden) field in the profile.

Users should receive information describing the benefit of adding their group & level in providing more accurate recommendations re: content, opportunities, groups and colleagues and a clear explanation that this information will not be visible to any other users and will only be used to improve the application and services to users.

We should ask users about their current group & level at the same time as we update the department.

There may be value in tracking each group & level separately as it will give data on employment and staffing trends.  Open for discussion.

**Comment by ToferC** [comment]
Build into Profile as-a-service.

**Comment by Troy-Lawson** [comment]
will be built into profile project
