### ISSUE TITLE
Contact Form resets the reason drop down when returning with a validation error

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1193]
The form resets the Reason drop-down when returning with a validation error - As a regular user, I do not want to have to re-enter my information - an indication of the field that should be corrected would be sufficient.

Not selecting a Reason also returns the "file type validation" when no file was attached; 

There is a number one ( 1 ) at the top of the Contact Form that should not be there;

![valid file type](https://user-images.githubusercontent.com/23527358/27596500-bbde341a-5b2d-11e7-9976-8e8c7884fcd9.jpg)

**Comment by ToferC** [comment]
Approved for work.
