### ISSUE TITLE
Tag Cloud Widget not displaying content

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1194]
User: Jeremiah.Stanghini
"I'm having a bit of trouble getting the "tag cloud" widget to function correctly in a GCconnex group. I have a bunch of content (with tags) and the "tag cloud" widget "on," but it remains empty."
As a user, I would like instructions to be able to configure the widget to display content based on tags I have used.

As per @Troy-Lawson some functions on the site were modified, preventing this widget from working properly; the widget may have to be removed from the list of available widgets.

**Comment by ToferC** [comment]
Recommend that this issue be closed as we deliberately turned off this functionality. @KevinChagnon - can you please inform the user.

I've removed the Tag Cloud widget from profiles, Dashboards & Groups.

**Comment by KevinChagnon** [comment]
Informed user that the widget has now been removed
