### ISSUE TITLE
Closed group pages in search results: If non-member user gets permission error but does not redirect to group to join (Edit: Redirecting user with no access to group to the Group profile)

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1195]
As a regular user, when clicking on a search result for a page within a group for which I am not a member, I would like to be redirected to the group's main page when I am presented with an access permission error.  This would allow me to know which group I should join to see the page I selected to view in my search result.
Currently I get an error and I am redirected to my dashboard.

![access error](https://user-images.githubusercontent.com/23527358/27638225-89e96962-5be0-11e7-8b6d-06ba26e0f7e2.JPG)

**Comment by ToferC** [comment]
Approved as part of content refresh.

**Comment by pandurx** [comment]
@ToferC @KevinChagnon I don't think this would be a search issue, this is an expected behaviour within the application; when you do not have permission for a particular content, GCconnex will redirect you to either the Newsfeed or Activity

**Comment by ToferC** [comment]
@pandurx - could we set it to jump to the About page of the group, the same as if a person did a search for and clicked on the group?

**Comment by pandurx** [comment]
@ToferC okay
