### ISSUE TITLE
Indication of a (one) post in Jobs Marketplace forum but no post displayed: Clerical and Secretarial section for British Columbia 

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1196]
@pandurx

The Clerical and Secretarial section for British Columbia shows there is a post in the Deployments, Secondments and Assignments / Mutations, détachements et affectations but there is none.
When you click on this section you see there is no post.

![jobs marketplace - image 1](https://user-images.githubusercontent.com/23527358/27644264-0b7bf1ce-5bf1-11e7-88ee-28b9d57b0a70.png)

![jobs marketplace - image 2](https://user-images.githubusercontent.com/23527358/27644273-101b2d76-5bf1-11e7-830a-ab1277506750.png)

**Comment by ToferC** [comment]
@KevinChagnon - quick question. Does this issue reflect a user problem? If not, it might not warrant an issue card. We need to carefully consider what we want our developers working on.  Each issue created and assignment takes developer attention away from other work.  Please consider and close the issue if it doesn't have any urgency. Thanks!
