### ISSUE TITLE
"Make Sticky" checkbox no longer available when editing post in Group Forum

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1197]
Below is a screen capture for a new topic that shows the “Sticky Topics” checkbox as expected.
Next is a screen showing the topic displayed as a Sticky Topic, again as expected.
Followed by editing of that topic where the Sticky Topics checkbox is not visible anymore.

![create forum topic](https://user-images.githubusercontent.com/23527358/27696019-8b6125c6-5cbe-11e7-8fa6-aa646ce837a4.jpg)

![shows as sticky](https://user-images.githubusercontent.com/23527358/27700657-3b63adb0-5ccc-11e7-9535-6b96c52ebccd.jpg)

![edit no sticky](https://user-images.githubusercontent.com/23527358/27700687-50fe790c-5ccc-11e7-94a1-2416aa2b4e64.jpg)

As per Workforce management's request we removed this option for users posting in the Jobs Market place, however the feature was being used within group forums elsewhere on the site and users are requesting the feature to return in order to post priority/important items as "sticky" (top of page)

**Comment by ToferC** [comment]
Suggest we review this issue as part of the content refresh. Q: do we keep forums? If so, what functionality do they need?  Are they part of GCconnex or a stand-alone modern forum application? (Yeah, yeah, I know.)

**Comment by pandurx** [comment]
I think this was not worded well, it's more of an issue with sticky being not displayed when user is editing.

**Comment by KevinChagnon** [comment]
I also tested this on my machine (again) and it is currently working as intended. I will inform the user.
