### ISSUE TITLE
Hamburger Menu Doesn't Work Properly on BB10

### ISSUE THREAD

**Issue by massierick** [gctools-outilsgc/gcconnex#1198]
I sometimes need to access GCConnex on my blackberry, and have a lot of trouble using GCConnex. The main nav menu, which gets collapsed into a hamburger on small mobile devices, seems to have touch control issues. 

The menu has many items, so when I open it, it ends up being a list that is more than one visible page long. When I try to scroll down it usually doesn't work, and ends up scrolling the background page (which is the main page I was on when I clicked the hamburger menu). Sometimes (not often) the menu will register the touch and will scroll a little, but it sometimes takes me up to a minute to get to the bottom of the menu since it keeps scrolling the background page. 

I wonder if expanding the menu to fill the screen (with an "x" to leave at any time) would help? Or perhaps having it append to an existing element on the page on click, so that it becomes a part of the page, not a new layer?

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
