### ISSUE TITLE
Notification Digest gettng mangled since week of July 4th

### ISSUE THREAD

**Issue by nschonni** [gctools-outilsgc/gcconnex#1219]
Attached is a sample recieved today
[Your Daily Digest.zip](https://github.com/gctools-outilsgc/gcconnex/files/1128336/Your.Daily.Digest.zip)

- [ ] Some headings are missing entirely
- [ ] Some headings appearing as JSON
- [x] Opportunities platform only showing a single character for title

**Comment by pandurx** [comment]
the patch has been tested and will be implemented over the coming weekend.

**Comment by nschonni** [comment]
Thanks!

**Comment by nschonni** [comment]
Not sure if this went out on the weekend, but it looks like the Digest is still broken

**Comment by klecuyer** [comment]
+1

**Comment by pandurx** [comment]
@nschonni still broken as in titles and groups are not showing up still?

**Comment by nschonni** [comment]
At least the JSON encoding issue. I've updated the original to a checklist to track the outstanding issues
[2017-07-16 and 17 - Your Daily Digest.zip](https://github.com/gctools-outilsgc/gcconnex/files/1153439/2017-07-16.and.17.-.Your.Daily.Digest.zip)
I can't confirm the missing categories is fixed but I did still see it for the Sunday 1AM email

**Comment by pandurx** [comment]
@nschonni I'd wait a day to see if the changes went through, I realized that the data (content that were posted) that is incorrect had been saved into the database and when the digest went out it displayed the incorrect data. It was done this way because there could be a potential performance issue that could happen.

**Comment by nschonni** [comment]
[JSON ERROR in title.zip](https://github.com/gctools-outilsgc/gcconnex/files/1153558/JSON.ERROR.in.title.zip)
Will do. I did just get this one now, but it was a group notification rather than the Digest. Should I open a separate issue?

**Comment by pandurx** [comment]
@nschonni The non-digest notifications are having issues, I know someone had brought it up last week but I'm not sure if they had created a ticket for it. Would be great if you can open a separate issue so that everyone can track it.
Thanks!

**Comment by pandurx** [comment]
@nschonni i've just received my daily digest and all the information seems to be displayed correctly, can you please validate

**Comment by pandurx** [comment]
That is weird.. cause I'm getting the titles displayed correctly (the group i could have maybe replicate the issue had a bilingual group name)

**Comment by nschonni** [comment]
It may be partially due to notifications that were supposed to get cleaned up. I've got 3 sections that deal with the Opportunities Platform/Group.
1. With JSON
1. With a file post (in French)
1. "Opportunities Platform notifications"

[Your Daily Digest.zip](https://github.com/gctools-outilsgc/gcconnex/files/1163531/Your.Daily.Digest.zip)

**Comment by pandurx** [comment]
It wouldn't quite make sense as the "clean-up" should just be a one time thing (unless you're doing a weekly digest, then that will be resolved over the weekend since it clears the records on Saturday morning). My guess would be those slashes that are saved in the group->name and maybe the encoded characters that are messing up the JSON format? (though, i validated the JSON via rando validation on the internet). All the other group seem fine (I had subscribed to a couple groups who have both the English and French name saved as JSON).

**Comment by pandurx** [comment]
The latest patch should have been resolved since the weekend, re-open if issue still persist

**Comment by nschonni** [comment]
This mornings looked good. I'll re-open if I notice any more this week

**Comment by nschonni** [comment]
[2017-08-03 - Your Daily Digest.zip](https://github.com/gctools-outilsgc/gcconnex/files/1197482/2017-08-03.-.Your.Daily.Digest.zip)
@pandurx I can't re-open, but I'm still seeing the JSON for one of the group headings

**Comment by nschonni** [comment]
[2017-08-06 Your Daily Digest.zip](https://github.com/gctools-outilsgc/gcconnex/files/1209074/2017-08-06.Your.Daily.Digest.zip)
- Still has bad encoding, but just for the Opportunities Posting Group
- Has missing headers

[2017-08-07 Your Daily Digest.zip](https://github.com/gctools-outilsgc/gcconnex/files/1209075/2017-08-07.Your.Daily.Digest.zip)
- Fixed encoding on Opportunities Posting Group

**Comment by nschonni** [comment]
@pandurx here is an interesting one. There is a record for the Opportunities Posting Group both correctly and incorrectly encoded in the same mail
[2017-08-09 Your Daily Digest.zip](https://github.com/gctools-outilsgc/gcconnex/files/1212272/2017-08-09.Your.Daily.Digest.zip)
Also a few that had the group title, but not the links

**Comment by LemieuxGen** [comment]
Group title includes JSON in daily digest - I'm re-opening this issue. @Troy-Lawson can someone look into this issue this sprint? Thanks.
![json_notification digest_aug 31-2017](https://user-images.githubusercontent.com/15378977/29923004-dfa02f40-8e25-11e7-8e84-8d4781359a69.JPG)

**Comment by pandurx** [comment]
@nschonni has there been other occurrences recently/lately in the digest besides the group notifications?

**Comment by nschonni** [comment]
[2017-08-31-Your Daily Digest.zip](https://github.com/gctools-outilsgc/gcconnex/files/1267756/2017-08-31-Your.Daily.Digest.zip)
I actually didn't get the JSON encoded title today (which I think is new). The only odd one I saw this morning was one group missing the hyperlink.

**Comment by nschonni** [comment]
[2017-09-01-Your Daily Digest.zip](https://github.com/gctools-outilsgc/gcconnex/files/1270855/2017-09-01-Your.Daily.Digest.zip)
OK, the JSON encoding issue is back for me today for that one group.

**Comment by LemieuxGen** [comment]
@pandurx the notification digest is still showing JSON encoding...
![json_notification digest_sept-06-2017](https://user-images.githubusercontent.com/15378977/30112077-0c63e4ce-92de-11e7-9fc1-b3fab264ea96.JPG)
If I look at the page of the group (Opportunities Posting Group), the content on the page appears correctly, without JSON encoding. 

Do we have a fix for this issue? 
Thanks!

**Comment by pandurx** [comment]
@LemieuxGen Can you tell if this happens on other entries in the digest?

**Comment by LemieuxGen** [comment]
For me, I only see it on the Opportunities Posting group. I had it again in my digest this morning.

**Comment by LemieuxGen** [comment]
@pandurx I'm still getting the daily digest with the JSON for the opportunities platform group. 
![json digest op](https://user-images.githubusercontent.com/15378977/31227744-fb2fe496-a9a8-11e7-8a76-e3f3bc3d3ebf.JPG), Was this supposed to be fixed during the last code push?
