### ISSUE TITLE
Group members and operators not receiving notifications

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1227]
sub-group: Engaging Indigenous Peoples https://gcconnex.gc.ca/groups/profile/16100881/enengaging-indigenous-peoples-mobilisation-des-peuples-autochtonesfr 
Problem: email notifications when new content is uploaded are not being sent to group members. Members are subscribed to group notifications; Group notification settings for email are allowed.
In addition to members, operators are not receiving email notifications. Problem is specific to this group; user Zaria.Channer (an operator) receives email notifications from the parent group, and other sub-groups.

**Comment by pandurx** [comment]
is it possible if i could have the affected user that is not able to receive the notification?

**Comment by KevinChagnon** [comment]
User reporting the issue is: julie.legault1

**Comment by KevinChagnon** [comment]
Affected user: Zaria.Channer

**Comment by KevinChagnon** [comment]
Another group where members are not receiving notifications when updates are made to a group page:

https://gcconnex.gc.ca/pages/view/24479284/occasions-demploi-job-opportunities

Reported by user: Julie.legault1

**Comment by KevinChagnon** [comment]
Another group where members are not receiving notifications:

https://gcconnex.gc.ca/groups/profile/25961968/enssc-recruitmentfrrecrutement-au-spc

Group owner: Kristen Pidduck  reports not receiving notifications for new blog posts or bookmarks and is subscribbed to email and site notifications (not the digest)

**Comment by KevinChagnon** [comment]
User and group operator tessa.starnaud reports that members are not receiving notifications for updates to Pages within the group https://gcconnex.gc.ca/group_operators/manage/28200249.
Only group operators seem to be receiving the notification.

**Comment by pandurx** [comment]
@KevinChagnon do they receive notification from other groups?

**Comment by joymosk** [comment]
From a Group Owner as posted in Group Owners' Group: "Group members seem to not receive notifications for certain functionalities in one of my groups. A group member started a discussion thread and I believe a notification did not go out. I did not receive one and I asked colleagues around me and they also did not receive one. I am the group owner and my colleagues are subscribed to notifications from this group. They received notification of a new event I posted a couple of days ago, but not of the discussion. I receive notifications of new discussions in other groups I'm a member of, so it doesn't seem to be generalized. "

**Comment by pandurx** [comment]
Aug  9 13:45:10 server-name sm-msp-queue[28274]: [    ]: [    ]: sender notify: Warning: could not send message for past 4 hours

**Comment by ErinChapman** [comment]
I have a similar issue. I created an event in my group but was never notified when people commented on the post

**Comment by pandurx** [comment]
Creating more specific notification issues/tickets rather than them all compiled into one

As a group operator, when I post a group blog, I want members to be notified so people see the content (to like, comment, share).

Group content is not consistently notifying group members when it is posted.

Link to blog: https://gcconnex.gc.ca/blog/view/32183962/enjust-say-yesfrdites-simplement-oui
Link to group: https://gcconnex.gc.ca/groups/profile/19651377/enexecutive-corner-carrefour-des-cadres-supu00e9rieursfr

I have checked three group members (with email and site notifications enabled for this group) and no one received the notification for the blog posted above.

**Comment by KevinChagnon** [comment]
@pandurx 

When this ticket was originally created there was mention of this group page being updated and group member not receiving the notification of the update:

Another group where members are not receiving notifications when updates are made to a group page:

https://gcconnex.gc.ca/pages/view/24479284/occasions-demploi-job-opportunities

Reported by user: Julie.legault1

This is still an issue for this user and other group members.  The user reporting the problem has access to the group owner login (its a generic account) so this has been tested over and over on her part an ours.

**Comment by pandurx** [comment]
Referencing the pull request: https://github.com/gctools-outilsgc/gcconnex/pull/1593

**Comment by KevinChagnon** [comment]
Julie.legault1 reporting this is still an issue with Pages. @Steph4104 also working on notifications and I assisted in testing. Issue cannot always be replicated

**Comment by Steph4104** [comment]
@KevinChagnon , for julie.legault1, is it possible she published (with the generic account) a first version as only me (type of draft) before let it show to everyone?

**Comment by pandurx** [comment]
@Steph4104 @KevinChagnon @klecuyer 
Pull Request #1758 should fix the page update notifications

Are notifications for new contents still an issue?

**Comment by klecuyer** [comment]
@pandurx I cannot seem to replicate this issue currently.
