### ISSUE TITLE
Discrepancy between number of Topics and posts in Opportunities Posting Group forum

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1231]
The Professional and Administrative forum displays 17 topics and 5 posts. ( https://gcconnex.gc.ca/gcforums/group/7617731/7803029 ) When you click on the hyperlink, the number change to 154 topics in the Deployments, Secondments and Assignments / Mutations, détachements et affectations ( https://gcconnex.gc.ca/gcforums/group/7617731/7803304 )  and 5 posts in the Casuals / Employés occasionnels ( https://gcconnex.gc.ca/gcforums/group/7617731/7803303 )

![topics and posts ncr](https://user-images.githubusercontent.com/23527358/27971586-391fb16a-6321-11e7-9c5a-796054bee7d2.png)

![topics and posts p a](https://user-images.githubusercontent.com/23527358/27971589-3e69f716-6321-11e7-90ac-aaf4357ec526.png)

I would be more accurate and informative if the proper count can be displayed.

**Comment by pandurx** [comment]
This might be due to some topics that are set to "Only me", so for this issue, i will make it display the access that are set to the topic.

**Comment by pandurx** [comment]
For some reason, the forums are filed under guid 0. Trying to replicate how this happened
