### ISSUE TITLE
Create Group auto-suggest of existing groups not working

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#1241]
We previously developed functionality so that when a user is creating a group, we would provide a list of similarly named groups and suggest that they may want to join an existing group rather than create a new one.

This functionality is no longer working and should be fixed as part of our summer upgrade.

User Story: As a regular users, I need to know if other groups are already meeting the need that I see so that I and other can contribute expertise and content in the most effective way possible.

As an administrator or regular user, I benefit from having content and discussions in themed areas rather than spread across the platform.

**Comment by LemieuxGen** [comment]
@Steph4104 Nous avons jeter un coup d'oeil ce matin à GCconnex, et l'option "Auto suggest" ne fonctionne pas. Est-ce que ça l'a été relâché sur GCconnex cette fin de semaine? Merci.
