### ISSUE TITLE
Call to undefined function gc_explode_translation() after fresh install

### ISSUE THREAD

**Issue by smellems** [gctools-outilsgc/gcconnex#1251]
After setting the environment for GCconnex (or collab), Apache returns the following error when you go to the application to complete the installation.

> Call to undefined function gc_explode_translation() in /var/www/html/engine/lib/views.php

This was added by gctools-outilsgc/gcconnex#679 

## Steps to reproduce
- Clone GCconnex
- Composer install/update
- Start Apache and MySQL
- Go to application URL (localhost or other)
- 500 Error

**Comment by markwooff** [comment]
I know that function is declared in the `wet4` module, was that module enabled when you tried loading the site?

**Comment by smellems** [comment]
No, the installation was not even started.  No config file and nothing in the database.

Core should not depend on the `WET4 ` mod.

**Comment by markwooff** [comment]
Looks like there was a modification to a core file that uses `wet4`'s function: https://github.com/gctools-outilsgc/gcconnex/blob/660955e8f1116ed719dbca85de4ff3e784aa6c20/engine/lib/views.php#L490
