### ISSUE TITLE
Group objects navigation error when Questions plugin enabled in group

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#1255]
When the group admin enables questions in a group, "Group Questions" appears in the objects nav-bar, but it's unclickable and the "More" navigation element disappears.

![questions error](https://user-images.githubusercontent.com/6226762/28270486-a3cdbf20-6ad3-11e7-9ea3-5457b64d89be.PNG)

**Comment by ethanWallace** [comment]
Issue was caused by incorrect location of plugin in plugin order. Has been moved to the correct location on production and now the menu item displays correctly.
