### ISSUE TITLE
profile nudge 500 error

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#1260]
works on gccollab errors on gcconnex

**Comment by markwooff** [comment]
@Phanoix were there any more details on the 500 error?

**Comment by Phanoix** [comment]
PHP Fatal error:  Unsupported operand types in .../gc_profile_nudge/start.php on line 29

**Comment by markwooff** [comment]
Sounds like the error is thrown after trying to perform the subtraction logic. I've added an `intval()` call so a proper number is used, possible to test on preprod?

**Comment by markwooff** [comment]
PR https://github.com/gctools-outilsgc/gcconnex/pull/1287 created to test out fix for 500 error.

@Steph4104 do you think you could test this out on GCconnex?
