### ISSUE TITLE
Drop down list of Departments on Registration form does not list all departments

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1278]
All new GCconnex users should be able to select the department they work for when creating a new profile.
Currently, employees of "Parliamentary Protective Service (PPS)" (@pps-spp.parl.gc.ca) are able to register a new profile however they are not able to select their department name as it is not found in the drop-down list. Instead they must chose “House of Commons” ; PPS brings together the former Senate and House of Commons Protection Services and the RCMP’s Parliament Hill Security Unit (PHSU) into a unified security service

**Comment by nschonni** [comment]
I would guess it may be because the department isn't part of the GCDirectory/GEDS https://gcdirectory-gcannuaire.ssc-spc.gc.ca/en/GCD/?pgid=012 either

**Comment by KevinChagnon** [comment]
https://github.com/Phanoix/gcconnex-help/issues/20

**Comment by klecuyer** [comment]
Also to be added: Canadian Forces Liaison Council

**Comment by klecuyer** [comment]
@LemieuxGen do you think these two organizations could be an easy add for next sprint? Or is it more complicated (ie GCdirectory)

**Comment by LemieuxGen** [comment]
@Troy-Lawson who is responsible for updating the domain manager on GCconnex and GCpedia?

**Comment by klecuyer** [comment]
@JOutram77 this is another one has been pending for a while, but we didn't yet have a clear path of workflow. Can you consider/research and get back to me?
Parliamentary Protective Service

**Comment by Troy-Lawson** [comment]
This list is pulled from GEDs. If the organisation isnt in teh drop down list then it must not be in GEDS either. Our options could include manually maintaining additional organisations in the list, or allowing a "other" category with a free form entry field, or continuing to ignore  the problem

**Comment by Addyvan** [comment]
I think this card is the byproduct of a bigger problem which is how we are generating the list of options and how we are maintaining user departments in the event of changes in this list.

I propose that rather than figure out how to add specific missing departments we reopen a discussion on how we can maintain up to date and correctly titled department and agency names in their entirety.
