### ISSUE TITLE
Invite to a group option for members

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gcconnex#1280]
As a regular member of a group, I would like an easy way or option (other than sending a link in an email) to invite my colleagues to the group.  It could really help grow membership of all groups that way.
 
Obviously this feature should only be available to open groups.

Suggested by Robert McLeary via the GCconnex Group Owners group. 

Could the "share" feature be enhanced for this purpose?

**Comment by joymosk** [comment]
[A new discussion was posted in group GCconnex Group Owners' and Operators' Corner  Une nouvelle discussion a été affichée dans le groupe Coin des propriétaires et des administrateurs de groupes sur GCconnex.txt](https://github.com/gctools-outilsgc/gcconnex/files/1162964/A.new.discussion.was.posted.in.group.GCconnex.Group.Owners.and.Operators.Corner.Une.nouvelle.discussion.a.ete.affichee.dans.le.groupe.Coin.des.proprietaires.et.des.administrateurs.de.groupes.sur.GCconnex.txt)

**Comment by klecuyer** [comment]
+1
