### ISSUE TITLE
Minor edit notifications still sending

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1290]
As a user, I check the box (below) when I don't want to notify group members of a file I've uploaded, discussion I've posted, or anything I have made a minor edit to and don't want to send notifications.

![image](https://user-images.githubusercontent.com/29754185/28574560-51602e2c-711c-11e7-9748-c4b87f854aa9.png)

A user and I have both tested this and it still sends notifications/emails to group members who receive notifications, even when selecting the check-box labeled, "Don't want to send a notification?"

Link to user's test group: https://gcconnex.gc.ca/groups/profile/28722515/endbbb-testfr

![image](https://user-images.githubusercontent.com/29754185/28574655-a1075f2c-711c-11e7-982f-5231df579329.png)

**Comment by ErinChapman** [comment]
I have this issue. I made a few minor edits to an event post on the Ambassador Network group and when I went to the news feed I saw a post for every time I edited the event even though I clicked the minor edit box

**Comment by pandurx** [comment]
https://github.com/gctools-outilsgc/gcconnex/pull/1342
