### ISSUE TITLE
Increase Find Members search to showing unlimited results per page

### ISSUE THREAD

**Issue by Eldoraaoun** [gctools-outilsgc/gcconnex#1303]
Opportunities Platform, Find Members, the maximum results per page currently caps at 100 - add a feature that enables showing "all results".

**Comment by ToferC** [comment]
We should also let users set their default #. 9 of anything isn't enough.
Maybe bump to 30?

**Comment by Eldoraaoun** [comment]
The Search Opportunities tab also caps at 100 results. The interface says there are 120 results per page, but there are only 100 posts that appear. 

If you set the max number of opportunities per page to 120, the platform says "This search has reached the maximum number of entities." with the oldest post being only 3 weeks old. The platform is not showing all the opportunities that have been posted (and that are active) instead, it is only showing the latest 100.

**Comment by Eldoraaoun** [comment]
@beckyjeong Should I create a separate ticket for this issue and link it?

**Comment by lucbelliveau** [comment]
I submitted a PR to allow "unlimited" search results as well as showing "all" candidate results on a single page.

@ToferC Did you want to bump up the minimum results per page for opportunities from 9 to 30?  What about the member search?

Regarding the whole 120 capping out at 100 thing - this is controlled by a plugin setting on the backend... Someone will have to visit /admin and change the setting for "micro-missions".  In the PR I added a "all" option, as well as some higher numbers like 400, 800, 1000, etc.  This value can be changed on the fly on production.  (There may be performance impacts)

**Comment by ToferC** [comment]
Minimum 30 sounds good. 9 is definitely too few. @phanoix - can you look
into config settings?

**Comment by lucbelliveau** [comment]
Changed to 30.

**Comment by LemieuxGen** [comment]
@Phanoix Can you confirm if this fix will be live on GCconnex and GCcollab following this weekend's code push?

**Comment by Phanoix** [comment]
Did a bit of testing, looks like the default for advanced member search is 30 and 9 for the simple search, if you change the results per page you can get the rest. I assume we want simple search to also default to 30?

**Comment by ToferC** [comment]
@phanoix - yes to increasing default search.

**Comment by LemieuxGen** [comment]
The issue is not resolved, unfortunately. Even with the results count increased, the search results are not all showing up. 
I asked Ryan to pull up the stats for the OP, and there's definitively an issue. the number of active  opportunities is 1456, but only 100 show up in the search results. 
See attached file with export of the posted opportunities. 
Can someone have a look at what's going on here? 
[elggentities_opp.xlsx](https://github.com/gctools-outilsgc/gcconnex/files/1668403/elggentities_opp.xlsx)

**Comment by lucbelliveau** [comment]
Was the max search results updated in the backend config?



Sent from my Samsung Galaxy smartphone.

**Comment by LemieuxGen** [comment]
@Troy-Lawson Can we add this back in this current sprint?

**Comment by Phanoix** [comment]
Haven't heard any issues with this since the config change, closing the issue.
