### ISSUE TITLE
Add ability to Find Members by group+level in Advanced Find.

### ISSUE THREAD

**Issue by Eldoraaoun** [gctools-outilsgc/gcconnex#1305]
In Find Members -> Advanced Find, add search filter field based on group and level

**Comment by LemieuxGen** [comment]
@Phanoix Communicated with OCHRO to confirm scope. We will go forward with adding the option in the advanced search, to find opportunities based on group and levels. This would allow people looking for opportunities to find some at their level, and would allow hiring managers to find people who posted opportunities as “seeking opportunities” to find people at a specific classification and level. 

No changes required in the "Find Members" advanced search. I changed the title to reflect the requirements.

**Comment by Phanoix** [comment]
Looked into this, should be quite doable next sprint in a few days. Shouldn't have a negative impact on overall mission search performance.

**Comment by LemieuxGen** [comment]
@Phanoix As discussed, I'm reopening this issue to action this within this sprint.

**Comment by LemieuxGen** [comment]
@Phanoix Thanks for working on this. I have a few required changes:
- When searching by classification, it makes sense for users to search by classification only, but not to search by level only. We should have a field for "Classification". Once the user selected that, they are shown value fields: 1) Group; 2) All levels, =, >=, <=; and 3) Level. This can be similar to how the "duration" field works (see image below). For the 2nd value, the user needs to be able to select an option that will look at all the levels. I suggest "All levels" or leaving it blank, which would mean that the 3rd value for Level would not be populated. 
![op duration search ex](https://user-images.githubusercontent.com/15378977/38026730-3e595154-325b-11e8-99da-1321aafcf223.PNG)

In French, the field should be "Classification" and the values should be: 1) Groupe; 2) Tous les niveaux, =, >=, <=; and 3) Niveau.

For the "Level" value, we should add the levels: 00 and 20 (also needs to be added to the options when creating an opportunity). 
FYI- There are also a few groups that have odd levels, like U1-U6. I will verify with OCHRO if we need to adjust the group and levels across the OP (when creating opportunities and searching for opportunities). This could be an other Github issue. 

Note: This is based on how the search by classification works on the [GC Jobs website](https://emploisfp-psjobs.cfp-psc.gc.ca/psrs-srfp/applicant/page2440?fromMenu=true&toggleLanguage=en).

**Comment by LemieuxGen** [comment]
@Phanoix I also added these comments in the pull request. 
Thanks for working on this. I have a few required changes:
- When searching by classification, it makes sense for users to search by classification only, but not to search by level only. We should have a field for "Classification". Once the user selected that, they are shown value fields: 1) Group; 2) All levels, =, >=, <=; and 3) Level. This can be similar to how the "duration" field works (see image below). For the 2nd value, the user needs to be able to select an option that will look at all the levels. I suggest "All levels" or leaving it blank, which would mean that the 3rd value for Level would not be populated. 
![op duration search ex](https://user-images.githubusercontent.com/15378977/38026730-3e595154-325b-11e8-99da-1321aafcf223.PNG)

In French, the field should be "Classification" and the values should be: 1) Groupe; 2) Tous les niveaux, =, >=, <=; and 3) Niveau.

For the "Level" value, we should add the levels: 00 and 20 (also needs to be added to the options when creating an opportunity). 
FYI- There are also a few groups that have odd levels, like U1-U6. I will verify with OCHRO if we need to adjust the group and levels across the OP (when creating opportunities and searching for opportunities). This could be an other Github issue. 

Note: This is based on how the search by classification works on the [GC Jobs website](https://emploisfp-psjobs.cfp-psc.gc.ca/psrs-srfp/applicant/page2440?fromMenu=true&toggleLanguage=en).
