### ISSUE TITLE
Group avatar displaying file name with "en": and "fr": as opposed to the image itself

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1308]
When viewing the following group page with a regular (non-admin) user profile, the group avatar is  displaying the file name with "en": and "fr": as opposed to the image itself;

https://gcconnex.gc.ca/groups/profile/26794819/eninac-albertafraanc-alberta

![group avatar](https://user-images.githubusercontent.com/23527358/28672216-1902b904-72ad-11e7-9a35-10ee2918616b.JPG)

When the group page is viewed using an admin profile, the image (avatar) is blank/white;

![group avatar blank](https://user-images.githubusercontent.com/23527358/28672279-518a3edc-72ad-11e7-89b4-0aece9d5af99.JPG)

**Comment by Steph4104** [comment]
@LemieuxGen , @KevinChagnon , is it still an issue? the group avatar on prod display correctly with an admin and none admin account.

**Comment by KevinChagnon** [comment]
Yes still an issue:

![enfr](https://user-images.githubusercontent.com/23527358/31547593-f19a7d12-aff5-11e7-8018-42f75e139504.PNG)

**Comment by Steph4104** [comment]
Fix in pull request #1539
