### ISSUE TITLE
Group name missing from some Join notifications on the Wire

### ISSUE THREAD

**Issue by nschonni** [gctools-outilsgc/gcconnex#1310]
Here is an example where one has a blank and another shows the details
![image](https://user-images.githubusercontent.com/1297909/28683790-ea70c0e0-72cf-11e7-91bd-ed03dd08db2b.png)

**Comment by RobJohnston** [comment]
Duplicate of https://github.com/gctools-outilsgc/gcconnex/issues/1246. ;-)

**Comment by nschonni** [comment]
Duplicate of #1246
