### ISSUE TITLE
Add <User Department> tab to main nav-bar

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#1311]
As part of the info. architecture redesign of the GCTools, add a new nav-bar element that pulls the department from a user's profile, so for Chris Allison it would say "Treasury Board Secretariat" or "TBS" and selecting it would bring me to a newsfeed-like page that would pull all content created by users from the same department in the feed and a wire that provides all posts by members from the same department.

User Stories: 

As a new user, I need a central place in which to find and understand what my departmental colleagues are working on.

As an experienced user, I can benefit from having a global view of what is happening in my department.

As a communications professional, I want to know that there is a central platform with which I can post content for my department's knowledge.

**Comment by ToferC** [comment]
@ethanWallace - just checked it out on pre-prod. Looks very good. We should add the ability to filter out colleague connections on both this and the communities newsfeed.

**Comment by LemieuxGen** [comment]
@ToferC Just spoke with @ethanWallace about the new department tab. Adding the name of the user's department in the main nav bar was causing too many issues. We looked at different options and came to the conclusion that having tabs in the newsfeed would work much better. Basically, no changes will be made to the main nav bar, but on the newsfeed page, the user will see 2 tabs, one for "groups and colleagues" and one for his/her department (similar to tabs you would find on a group page). Let us know if there are any major issues with this. Thanks!

**Comment by LemieuxGen** [comment]
@ethanWallace: just looked at it with Chris on preprod. Looks great! Would it be possible to do minor change to the text?
Title "Your News feed", please change to "My personal news feed" (French: "votre fil de nouvelles" change to "Mon fil de nouvelles personnel")
Title "Your department's activity feed" change to "My department's news feed" (French: Fil d'activités de votre ministère" change to "Fil de nouvelles de mon ministère")
Groups and colleagues tab, change to "My groups and colleagues". (French: Mes groupes et collègues)

Let me know if you have any questions, or if there are other places language may need to be adjusted based on those changes. Thanks!

**Comment by LemieuxGen** [comment]
@ethanWallace just saw there are 2 other places the text needs to be adjusted (changing "activity feed" to "news feed". Change is in bold below:
'dept:activity:do' => "Colleague connections will no longer display in your department’s **news** feed.",
'dept:activity:undo' => "Colleague connections will now display in your department’s **news** feed.",

FRENCH
'dept:activity:do' => " Les connexions de collègue ne seront plus affichées dans le **fil de nouvelles** de votre ministère.",
'dept:activity:undo' => " Les connexions de collègue s’afficheront maintenant dans le **fil de nouvelles** de votre ministère. ",

**Comment by LemieuxGen** [comment]
For the option to hide/show the colleague connexions, the alt text is different from one filter to the other. Could you make those consistent please?
