### ISSUE TITLE
User not receiving e-mail notifications for comments/likes made on blog he created

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1328]
User: Claude.Renaud

User is not receiving e-mail notifications for comments made on blog he created despite being subscribed to e-mail notifications for comments made on content he creates.

There are comments made on the following 2 blog posts for which the user did not receive an email notification;

https://gcconnex.gc.ca/blog/view/29058388/enhow-to-love-the-job-you-hatefr

https://gcconnex.gc.ca/blog/view/28066871/enwell-being-in-the-workplacefr

There are also Likes on the posts for which the user didnot receive notificaitons

**Comment by pandurx** [comment]
@KevinChagnon I don't see the blog anywhere in his subscribed list

**Comment by pandurx** [comment]
the issues with likes will be fixed in this pull request: #1358
