### ISSUE TITLE
Message Titles showing JSON for translation

### ISSUE THREAD

**Issue by CalvinRodo** [gctools-outilsgc/gcconnex#1330]
The title of groups are showing up as JSON objects when there is a translation available:
![jsontitle](https://user-images.githubusercontent.com/87738/29042895-efa4d564-7b86-11e7-87f6-ad33bfb4717d.png)

Looks to be related to #1313

**Comment by nschonni** [comment]
Duplicate of #1263, although that was supposed to be fixed

**Comment by pandurx** [comment]
Issue #1313 is strictly related to the Question/ Answer functionality

**Comment by pandurx** [comment]
Tested on production and the title seems to be alright. You can re-open if the issue still persist.
