### ISSUE TITLE
Text snippet for discussions showing up as JSON when translation available

### ISSUE THREAD

**Issue by CalvinRodo** [gctools-outilsgc/gcconnex#1331]
Seems to be related to gctools-outilsgc/gcconnex#1313 
![json description](https://user-images.githubusercontent.com/87738/29042994-4d2bf24e-7b87-11e7-9172-8e7a737c11b3.png)

**Comment by ToferC** [comment]
Thanks, @calvinrodo - approved for work. Please review the related cards and let's figure out why this issue is still occurring.

**Comment by LemieuxGen** [comment]
@Steph4104 , will the fix also address the JSON that appears in the notifications? 
![json_notification digest_aug 31-2017](https://user-images.githubusercontent.com/15378977/29922581-35e23eea-8e24-11e7-8dc2-3ec52a95931c.JPG)

**Comment by Steph4104** [comment]
@LemieuxGen  No, my fix is only for the view of the description of the discussion on the web site.

**Comment by LemieuxGen** [comment]
Thanks @Steph4104 . I'll open a new ticket for the JSON in notifications.

**Comment by CalvinRodo** [comment]
This is still occurring instead of JSON it's some other format: 
![bugpic1](https://user-images.githubusercontent.com/87738/30073595-570e0ec0-923c-11e7-8d0b-c103fabb005e.png)
![bugpic2](https://user-images.githubusercontent.com/87738/30073599-59cb2210-923c-11e7-928e-c1618a5fea24.png)

**Comment by CalvinRodo** [comment]
It's also still appearing in the Latest Discussion list:
![bugpic3](https://user-images.githubusercontent.com/87738/30073621-78de5b86-923c-11e7-833a-09d1c7f7f413.png)

**Comment by Steph4104** [comment]
The fix will be up on prod this week end
