### ISSUE TITLE
Questions function: multiple issues

### ISSUE THREAD

**Issue by joymosk** [gctools-outilsgc/gcconnex#1333]
RE: https://gcconnex.gc.ca/questions/view/29253439/enhow-does-the-questions-functionality-workfr#elgg-object-29269661#elgg-object-29269694 

1. Question doesn't indicate what group it was created in.
2. Drop-down menu doesn't include the group it was created in. 
3. Notifications -- see also issue 1313 and file https://gcconnex.gc.ca/file/view/29345527/enquestions-notification-capturefr (could not upload in GitHub
Title of notification is wrong. Person not identified. JSON coding as noted Also does not indicate the Group

**Comment by nschonni** [comment]
> Question doesn't indicate what group it was created in.

Questions can either be site-wide (from the global navigation menu) or to a specific group https://elgg.org/plugins/2472722. I think the question you linked to was a global one.

**Comment by ToferC** [comment]
Thanks @nschonni - @joymosk - can you please review and if so, please close the issue. Thanks!

**Comment by pandurx** [comment]
@joymosk Just did a quick test on my local for notifications...
1. Questions does indicate whether it was created in a group or site-wide [via colleague notification]
2. The questions listed will contain the group link [if applicable]
3. The question title seems to be parsed correctly and notification does include the group [if applicable]

If issue still persist, you can re-open this issue ticket.
