### ISSUE TITLE
Search results are not filtering correctly

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1343]
When performing a search, the results are not filtering correctly. 
For example, when searching GCconnex, and using the "Group" filter, the results are all forum content. (i.e., search for GCTools (apply group filter), only forum topics appear in the results - the GCTools groups don't show up.) Additionally, the content of the forum topics included in the search results do not include the search key word "GCTools" in the content. 

Also of note, when  for a keyword, results with no mention of the keyword appear in the results.  Ex: Search "GCTools", user profiles (ex: Roy Nader) show up, that have no mention of GCTools (except in the footer).

**Comment by LemieuxGen** [comment]
@pandurx remove avatar.

**Comment by pandurx** [comment]
Its been fixed
