### ISSUE TITLE
Search results showing language encoding (i.e., {"en":"","fr":""})

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1345]
Some search results are showing language encoding: {"en":"","fr":""}. This issue is still occurring, as of August 14, 2017.

See examples below: 

![search_language code2](https://user-images.githubusercontent.com/15378977/29282527-22248c2c-80f1-11e7-94ef-7e97baae6a46.JPG)

![search_language code](https://user-images.githubusercontent.com/15378977/29282493-055555fe-80f1-11e7-9631-b9de413fbaff.JPG)

**Comment by pandurx** [comment]
- [ ] place a noindex in group url that includes the title
