### ISSUE TITLE
upgrade mods to version elgg 2.3.x

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#1347]

**Comment by Phanoix** [comment]
Need manifest.xml updated:
* [ ] ideas
* [ ] toggle language

Crash on activate:
* [ ] Friend request
* [ ] gcforums
* [ ] Notification Email Messages Control Panel

**Comment by Phanoix** [comment]
next: update changed / deprecated function calls outside wet4:
* [ ] elgg_register_action($action, $filename = "", $access = 'logged_in')

**Comment by Phanoix** [comment]
still need to upgrade parts of:
* [ ] profile
