### ISSUE TITLE
Messages from group sending duplicates

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1352]
As a group operator, when I send a message to all group members, they get the notification 4x within minutes of each other, even though I only clicked Send once. 

I have not refreshed the page or clicked more than once. I can confirm that multiple group members have gotten this notification four times:
![image](https://user-images.githubusercontent.com/29754185/29323320-864a6f4c-81ae-11e7-9e8b-57d2a5ad8737.png)

**Comment by klecuyer** [comment]
I am using this as a workaround because group notifications are not sending. 

Link to Executive Corner group where this is consistently happening: https://gcconnex.gc.ca/groups/profile/19651377/enexecutive-corner-carrefour-des-cadres-supu00e9rieursfr

**Comment by ToferC** [comment]
Approved for work. Do we have a possible fix for this issue? If not, please leave an update on what has been done/tried in comments. Thanks!
