### ISSUE TITLE
Total Poll votes do not match distribution of votes in results

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1355]
As a user, when I create a poll, the total number of votes should equal the combined results of the answers.

I can see the total number of votes are 83, but the results only show me 52 (40+12). Either some of the vote results are not displaying, or the total number of votes is skewed.
![image](https://user-images.githubusercontent.com/29754185/29419893-67d402c6-833e-11e7-88d1-ba2ef6165cba.png)

Link to Poll where this is occurring: https://gcconnex.gc.ca/polls/view/29629880/enwhat-would-you-call-an-online-inventory-of-former-students-eligible-for-integration-in-the-federal-public-service-of-canadafrquel-nom-donneriez-vous-u00e0-un-ru00e9pertoire-en-ligne-danciens-u00e9tudiants-salariu00e9s-admissibles-u00e0-lu2019intu00e9gration-dans-la-fonction-publique-fu00e9du00e9rale-du-canada

**Comment by ToferC** [comment]
Approved for review and assignment. Medium priority.

**Comment by joymosk** [comment]
When corrected, we need to reply to 
https://gccollab.ca/discussion/view/116289/enpollsfr

**Comment by LemieuxGen** [comment]
Hi @Phanoix , we checked this fix this morning, but it doesn't seem to be fixed on GCconnex. Can you confirm if this was pushed over the weekend? Thanks!

**Comment by Phanoix** [comment]
it can't fix the polls that already had this issue, only future votes on those option. We can check the database and in most cases figure out the counts for the choices that had this issue but it's a manual process.

**Comment by markwooff** [comment]
Yeah had to go through the DB on GCcollab manually to fix this issue. Was just a matter of the strings for the vote option and user votes not matching.

**Comment by LemieuxGen** [comment]
@Phanoix can we look at fixing it for this poll?
https://gcconnex.gc.ca/polls/view/29629880/enwhat-would-you-call-an-online-inventory-of-former-students-eligible-for-integration-in-the-federal-public-service-of-canadafrquel-nom-donneriez-vous-u00e0-un-ru00e9pertoire-en-ligne-danciens-u00e9tudiants-salariu00e9s-admissibles-u00e0-lu2019intu00e9gration-dans-la-fonction-publique-fu00e9du00e9rale-du-canada

**Comment by Phanoix** [comment]
I have the numbers for A and D (the options that were broken):
A: 24
D: 14
If any new votes appear for either of those options I'll be able to easily fix the older ones to match the new/working one.
