### ISSUE TITLE
Embed Videos in Custom Widgets

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1360]
(not sure if this is a bug or enhancement)

As a user, I need to be able to easily upload videos, and embed them to play in GCconnex. I tested this on a new Blog post and, without going into Source, just pasting the URL in the blog post, the video embeds/plays nicely.
![image](https://user-images.githubusercontent.com/29754185/29565994-2d6ea9d4-8716-11e7-937f-604e19e20942.png)

I need this same kind of functionality in Custom Widgets, so I have select certain videos to appear front and centre on my page, or wherever I choose. Now, when I just paste the URL into my custom widget, it looks like this:

![image](https://user-images.githubusercontent.com/29754185/29566034-53ebc4d4-8716-11e7-90d5-f55c93248162.png)

**Comment by KevinChagnon** [comment]
Issued related to open ticket #1086 
https://github.com/gctools-outilsgc/gcconnex/issues/1086
