### ISSUE TITLE
Group is deleted when original group creator account is deleted, even if group ownership has transferred

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1378]
As a user, when I create a group and then transfer that group to another GCconnex user, if ever I delete my account, this group is also deleted, even if I have transferred group ownership to another user. 

Original group creator deletes account = group deleted. I have tested this with a user's duplicate profiles and on my own.

This could cause problems when users insist on deleting their accounts; even if they don't currently own any groups, there is no way to identify if they've created any groups in the past.

**Comment by LemieuxGen** [comment]
Approved for work.
