### ISSUE TITLE
Language change required for Message Widget (Dashboard)

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1380]
The name of the Message widget (available in the Dashboard widgets) needs to be changed. This widget was tested and the widget displays site notifications, not site messages. 

Widget name should be "Notifications" 
Description should be "Displays your latest site notifications"
![messages widget - language change to notifications](https://user-images.githubusercontent.com/15378977/29940366-fe13bdde-8e5c-11e7-93c9-d50b9b20b9ab.JPG)

FRENCH:
Widget name should be "Notifications" 
Description should be "Affiche vos dernières notifications"
![messages widget - language change to notifications_fr](https://user-images.githubusercontent.com/15378977/29940367-fe190410-8e5c-11e7-9c43-e3a95f48b826.JPG)

**Comment by Steph4104** [comment]
At the bottom of the widget, you can compose a message, should we remove it?

**Comment by LemieuxGen** [comment]
@Steph4104 where those the message get posted?

**Comment by Steph4104** [comment]
To the compose message page. Where you can compose and send a site message

**Comment by LemieuxGen** [comment]
Ah, that makes sense... I think we can keep the link to compose a message.
