### ISSUE TITLE
Forums deletion usability

### ISSUE THREAD

**Issue by pandurx** [gctools-outilsgc/gcconnex#1387]
@LemieuxGen @KevinChagnon 
Have a confirmation pop up to make sure user does not accidentally delete forum

**Comment by LemieuxGen** [comment]
@pandurx Awesome! can we try it on preprod?

**Comment by pandurx** [comment]
@LemieuxGen It's not implemented yet

**Comment by nschonni** [comment]
Maybe use the idea from GitHub, where you need to type in the name of the thing you're deleting as a confirmation
