### ISSUE TITLE
Invalid link from News feed

### ISSUE THREAD

**Issue by ErinChapman** [gctools-outilsgc/gcconnex#1392]
Krista made a post that showed up on my news feed. When I clicked the link to view the group and when I clicked the link to "view reply" button I got the same error message that the group could not be found.

![bug](https://user-images.githubusercontent.com/23339980/30213526-45eb7550-9477-11e7-9e90-38591cb491cf.JPG)
![bug 1](https://user-images.githubusercontent.com/23339980/30213530-495c5150-9477-11e7-84c6-d71d91571b3c.JPG)

**Comment by klecuyer** [comment]
Interesting. This is in a private group. Is there an existing ticket for this? Private groups showing up in news feeds?

**Comment by ErinChapman** [comment]
@klecuyer doing a search this is a closely related ticket but a slightly different issue because it won't even take me to the group or tell me that I need permission to view it: https://github.com/gctools-outilsgc/gcconnex/issues/544

**Comment by Phanoix** [comment]
Does this also happen in the My Colleagues tab in Activity?

**Comment by ErinChapman** [comment]
I only saw the item in the news feed

**Comment by Phanoix** [comment]
It seems like it's treated as a non-group post in this case, which is probably the reason it appeared. Haven't had any luck replicating this, maybe there's something different about the group or that discussion topic in particular.

**Comment by Phanoix** [comment]
I looked through the db, looks like there's no bug here and the reason it's showing up is because the discussion topic is set to public access. I tested the case where restricted access discussions are created in closed groups and none of the activity appeared on colleagues' newsfeeds.

**Comment by Phanoix** [comment]
I'm going to close this issue, if it turns out that there's a bug with setting / changing the access levels of some discussions that should be a different issue.
