### ISSUE TITLE
French Language code displaying in emails sent to users

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1394]
As a user, when I invite people to my group, the email they recieve shows code in the place of accented vowels.

For example, this user is writing 'réseau' and the email displays 'r\u00e9seau'.

Suspected link to existing coding/language bugs but no ticket found for this exact email issue.

**Comment by pandurx** [comment]
@klecuyer do you have an example of an email?
I tried the following and the accented characters seem to be encoded correctly:

- Invite colleagues to the group
- Invite GCconnex user to the group
- Invite non GCconnex user to the group via e-mail address

**Comment by KevinChagnon** [comment]
![language invitation email](https://user-images.githubusercontent.com/23527358/30395094-14312df0-9893-11e7-82b9-cf9a9a0f0931.PNG)

copy of the hyperlink: https://gcconnex.gc.ca/groups/profile/25235144/enmarine-litter-and-microplastics-networkfrru00e9seau-sur-les-du00e9chets-et-les-microplastiques-dans-le-milieu-marin?utm_source=notification&utm_medium=email
