### ISSUE TITLE
Digest Notification: file posting text in French

### ISSUE THREAD

**Issue by nschonni** [gctools-outilsgc/gcconnex#1395]
It looks like when a file is uploaded and marked as french, the Notification digest uses French translation for the action.
![image](https://user-images.githubusercontent.com/1297909/30226678-e7c66c18-94a4-11e7-8ed4-bc672440a569.png)

Here are the links if you want to look at the internal records:
- https://gcconnex.gc.ca/file/view/30364610/enstatement-of-merit-criteriafr?utm_source=notification_digest&utm_medium=email
- https://gcconnex.gc.ca/file/view/30364631/enfru00c9noncu00e9-de-critu00e8res-de-mu00e9rite?utm_source=notification_digest&utm_medium=email

**Comment by pandurx** [comment]
Are you able to set labels to issues? (it would be helpful if I can filter the issues by bugs)

**Comment by nschonni** [comment]
@pandurx no labeling is restricted to people with write access to a repo. The security model for that feature isn't that great.

**Comment by pandurx** [comment]
@nschonni 👎 well, i suppose that's alright. i'll try and make sure i'm up to date with the issues. thanks :)
