### ISSUE TITLE
"Page not Found" when logging out of GCConnex

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1399]
When logging out of GCConnex via the "Log Out" button users get a "Page not found" error;

![log out page not found error](https://user-images.githubusercontent.com/23527358/30289147-25e1715e-96f9-11e7-874f-0cb388f80a50.PNG)

the URL in address bar is:  https://gcconnex.gc.ca/simplesaml/saml2/idp/SingleLogoutService.php?ReturnTo=https://gcconnex.gc.ca/login

....it should return to the location indicated in the URL: https://gcconnex.gc.ca/login

**Comment by LemieuxGen** [comment]
This is also an issue on GCcollab, when logging in to collab (@markwooff)

**Comment by markwooff** [comment]
@LemieuxGen is this the issue with users logging in and being redirected somewhere else? Not quite the same as the GCconnex redirect but I know what you mean. It's being looked into.

**Comment by LemieuxGen** [comment]
@markwooff Sorry - you're right. on GCcollab, it's the redirect that brings you to a Page Not Found. Logging in from the login page works. Thanks!

**Comment by Troy-Lawson** [comment]
This is probably code related to the saml integration on connex. It's in the the wet 4 / actions / logout page

**Comment by LemieuxGen** [comment]
Similiar issue on GCcollab: https://github.com/gctools-outilsgc/gccollab/issues/225
Getting Page not Found after login.

**Comment by Troy-Lawson** [comment]
@LemieuxGen this is not related to any issue on collab as the simple signon is the cause and that does not exist on collab
