### ISSUE TITLE
User's posts to Jobs Marketplace not showing in user's Activity

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1404]
Users unable to find their posts to the Jobs Marketplace forums in under Activity - the posts are not listed.
This makes it very difficult for users to find/manage their posts.

Lawrie.Beamer posted an opportunity on Sept. 01 2017: https://gcconnex.gc.ca/gcforums/group/7617472/30242095/hjforumtopic

Its shows she is subscribed to the post;

![post not listed](https://user-images.githubusercontent.com/23527358/30387297-099eb326-987a-11e7-8d3b-7e4edc03bdca.PNG)

![post not listed activity](https://user-images.githubusercontent.com/23527358/30387353-2ea529d4-987a-11e7-8ab5-89ac209e9464.PNG)

There is no indication of the subscription in the users settings:

![post not listed notification settings](https://user-images.githubusercontent.com/23527358/30387402-5ff6337a-987a-11e7-887a-178a8e8a07e9.PNG)

The subscriptions do show in the notification troubleshooting tool:

![post not listed notification troubleshoot](https://user-images.githubusercontent.com/23527358/30387604-ff072898-987a-11e7-93e7-8863382101cb.PNG)

This user activity (posting in the forum) should show in under Activity.

This issue has also been reported by other users such as: Sylvie.Sibué

**Comment by KevinChagnon** [comment]
@LemieuxGen

**Comment by KevinChagnon** [comment]
links/URL to a subscription to a Forum Topic in Notification Settings simply brings you to the pages of regions for the group/subgroup.

See Lawrie Beamers subscriptions within Jobs Seekers and the Opportunities posting group in Jobs Marketplace;

https://gcconnex.gc.ca/settings/notifications/Lawrie.Beamer

(Within a chain of emails) we were discussing the this post:

https://gcconnex.gc.ca/gcforums/topic/view/30242095

but in her subscriptions the URL is:

https://gcconnex.gc.ca//gcforums/group/7617472/30242095/hjforumtopic

![lbeamer cs error](https://user-images.githubusercontent.com/23527358/32195104-b4f2390e-bd92-11e7-8c61-eeb3bd28c0ea.PNG)


Note that her posts do not show in her list of Activities while comments she made on files do.

**Comment by KevinChagnon** [comment]
https://github.com/Phanoix/gccollab-help/issues/13

**Comment by pandurx** [comment]
- Anything posted in the forum before the week of October 10th, will not show up in the user's Activity.
- I will fix the URL in her Notification Settings page
