### ISSUE TITLE
GCconnex Unvalidated accounts needs a search feature

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1413]
As an admin in GCconnex, I need a way to look through unvalidated accounts. Right now my only option is to click through 58 pages of unvalidated accounts, searching for one that was registered at some point in history.

The unvalidated accounts only show in these pages for the last few months. 

If a person registered before this period (shown in the 58 pages), is there registration still valid? I can see their username in php gcconnex but can't find the account and was never validated.

**Comment by markwooff** [comment]
@klecuyer this is actually something that I had started playing around with in GCcollab. If I can get it out soon enough, I'll put in a pull request for GCconnex as well 👍

**Comment by markwooff** [comment]
@klecuyer just a heads-up that this feature is now live on GCcollab, should be carried over to GCconnex as part of the code merge soon.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
