### ISSUE TITLE
Closed groups should still be land-able for users trying to join

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1424]
As a user, I receive an invitation to a closed group only visible to group members. However, I can't land on this page. Because I'm not yet a member I get booted back to my Newsfeed/Home page. 

Closed groups with the access settings 'only visible to group members' should still have a landing page. Or the access settings should change. There is no way for invited, but not-yet members to land on the page to accept.

**Comment by KevinChagnon** [comment]
Closed - see #620

**Comment by KevinChagnon** [comment]
This is when a user is invited to a group "by email" as opposed to using "My Colleagues"

The beginning of the text in the notification is as though it is assumed that the user is not already a member of GCconnex. It also provides a link to the group in the first line which makes the potential group member want to click it to see what group they are being invited to;

![group invitation](https://user-images.githubusercontent.com/23527358/30710330-30797ab2-9ed3-11e7-9346-6ec1a5a8c074.PNG)

**Comment by KevinChagnon** [comment]
The text would need to be modified to make it clear to existing GCconnex users as to where they should go/click to accept the invitation.

The last line of the Notification seems to indicate that the system verified if the potential member already has an existing account - but this does not seem to be a matter of fact as the Notification does get sent to existing members - Maybe this line should be removed or we should actually have the system make the verification and possibly send a different Notification to existing members.

**Comment by ToferC** [comment]
@KevinChagnon - is this closed?

**Comment by KevinChagnon** [comment]
Yes this is still an issue; when using the feature to invite by email , the system does not seem to verify if that email is already registered and tailor the outgoing email accordingly...

**Comment by klecuyer** [comment]
This is still an issue. Users are having to go to Groups, More, and Invitations to accept because they can't land on a group page until they are a member. It's a vicious circle - they can't view the page until they are a member... but can't accept it to become a member because they are not...yet

**Comment by LemieuxGen** [comment]
I updated the text for the notifications that users receive when they are invited to join a group on GCconnex and GCollab. This should be a quick fix for this issue as people will no longer be able to click on the group link from the email, thus eliminating the error when user attempt to access the group without being logged in or having an account. 
@pandurx @Steph4104 as discussed.

**Comment by Steph4104** [comment]
Fix with #1596
