### ISSUE TITLE
French title in Polls not changing when clicking 'Ce contenu est aussi disponible en français

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1425]
As a user, when I create a bilingual poll, I click 'Ce contenu est aussi disponible en français' and the poll results change to French but the title does not.

If I change my GCconnex user settings to French, the results and title display properly, but if I click within the poll to change the language, the French title displays in English.

French poll view:
![image](https://user-images.githubusercontent.com/29754185/30650479-fcf0291c-9df0-11e7-98e7-980c268da4a7.png)

Link to where I tested this https://gcconnex.gc.ca/polls/view/30848372/entesting-enfrfrfrancais-titre#

**Comment by Steph4104** [comment]
Related to #676 

This function only change the content, not the title. This is how its work.

**Comment by klecuyer** [comment]
Duplicate of #676

**Comment by Steph4104** [comment]
Fix in pull request #1498
