### ISSUE TITLE
Opportunities Platform > Find Members > Advance Find

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1431]
1. When ‘Field’ “Skill” is selected; the Value box does not offer the auto-suggest from the skills list anymore. [Connex & Collab]
2. When ‘Field’ “User department” is selected; the Value box does not offer the drop down list of departments used in profiles for consistent spelling. [Connex & Collab]
3. When ‘Field’ “Opt In” is selected; the Value box does not offer the drop down list of mechanisms offered via the Opportunities Platform anymore – it is a free text box. [Connex; resolved on Collab]
4. Searches still max out at 100 entries, but we need it to show the actual total number for depts using this feature to report how many employees in their departments are use it for various mechanisms. Also will be required for our own reporting, including for the Clerk’s Report.

**Comment by mbujold** [comment]
@LemieuxGen 
Tested issues:
- [ 1 ] GCConnex & GCCollab both showed auto-suggested options for skills - Can't reproduce.
- [ 4 ] Can you elaborate on this a bit more so I can truly test this?

**Comment by marcleblanc** [comment]
@LemieuxGen Please let us know feedback on what @mbujold mentioned about issues 1 and 4. Thanks!

**Comment by LemieuxGen** [comment]
Received an response back from OCHRO: 
**•[ 1 ] GCConnex & GCCollab both showed auto-suggested options for skills - Can't reproduce.**
This issue is ongoing on both GCcollab & GCconnex.  See the screen shot below. There should be an autosuggest list popping up with skills that begin with the letter “L”.  I have tried from a few computers and the issue is consistent.  Make sure when trying to reproduce that you go to Opportunities Platform > Find Members > Advance Find
![op advanced search 1](https://user-images.githubusercontent.com/15378977/31079144-9be27f24-a752-11e7-94b0-47072a420f45.png)

**•[ 4 ] Can you elaborate on this a bit more so I can truly test this?**
 Search for a term like “communication” or “project” and you will see a notification that the system has reached the maximum number of entries (which is 100). There should not be a maximum number, we need to know the actual number of users who have identified certain skills, or opted in for certain mechanisms. This is required for our reporting responsibilities.  In addition to showing the all the relevant profiles, it would be very helpful to have a count at the top of the page of how many entries were found (like on amazon, example: “there are 1,957 entries that match your search criteria”.

**Comment by marcleblanc** [comment]
Issue items 1 & 4 have been resolved. Please check the PR when you can. Thanks!

**Comment by LemieuxGen** [comment]
Would it be possible to get a status update on this issue? Please let me know items 1 to 4 will be part of this weekends release. Thanks.

**Comment by Phanoix** [comment]
There are a couple issues with the pull request right now.

**Comment by LemieuxGen** [comment]
@Phanoix Is this something our team needs to action? Can this be included in this sprint?
