### ISSUE TITLE
Opportunities Platform > Search Opportunities > Advance Search (department field)

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1433]
The field “Department” should be from the same drop down list of departments used to populate profiles (currently is a free text box) [GCconnex & GCcollab]

**Comment by mbujold** [comment]
@LemieuxGen do you have an example of what isn't working? I just tested on the live site and for instance when I search environmental I get a result where the Title is Environmental scan..
