### ISSUE TITLE
Unable to see icon in "Back" button of the Freshdesk widget (when using IE)

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1437]
As a user of the tools looking for help material, I need to know how to go back to the main category of the knowledge base when navigating the articles on the Contact Us page. On IE, the arrow icon for the "back" button doesn't display, therefore users don't know how to go back tot he previous category. If the user clicks on the back button of the browser (intuitive thing to do) he is brought to the previous GCcollab page he visited, and is taken away from the Contact Us page completely. 
Note: the icon is visible in Chrome... 

![back button for freshdesk widget](https://user-images.githubusercontent.com/15378977/30743977-f9e49716-9f6d-11e7-88d0-61223b490690.JPG)

**Comment by ToferC** [comment]
Fixed itself. It's a miracle!
