### ISSUE TITLE
Automatic link between Github private and public repositories 

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1439]
As a help desk agent using freshdesk, we need to have a functionality where freshdesk tickets can be "pushed" to Github automatically with a link to the closed and open repos, so that we don't need to duplicate efforts by creating github issues in both repos, and to ensure the loop is closed (meaning when the github ticket in the open repo is closed, the one in the closed repo is closed as well, which automatically closes the freshdesk ticket). 

When a freshdesk ticket is pushed to github, it creates an issue in a closed repo. We need to have an automatic script, where a ticket is also automatically created (duplicated) in the open repo, to avoid having to create and keep track of 2 different github issues for each ticket.  The loop back, closing the github issue and freshdesk ticket if crucial to the efficient use of Freshdesk.

**Comment by LemieuxGen** [comment]
linked to: https://github.com/Phanoix/gcconnex-help/issues/1

**Comment by LemieuxGen** [comment]
closes https://github.com/Phanoix/gcconnex-help/issues/1

**Comment by Troy-Lawson** [comment]
@Phanoix abandon in favour of issue repo?

**Comment by LemieuxGen** [comment]
Closing this issue as a solution is not possible. Help desk agent are now using a different workflow.
