### ISSUE TITLE
Group Forums default to 'All public servants'

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1444]
As a group owner, when I want to set the access level of a group forum, I get a notice that my access settings have been saved successfully.
![image](https://user-images.githubusercontent.com/29754185/30809937-681c976e-a1d1-11e7-9cc1-2f21892cc901.png)

However, when I return to my group forum, it has defaulted back to 'All public servants'. I can't seem to save my group forum to 'only me' or 'only members of this group'.

Link to group forum where this was initiallyt reported: https://gcconnex.gc.ca/gcforums/edit/30970840

**Comment by KevinChagnon** [comment]
@LemieuxGen @pandurx

**Comment by pandurx** [comment]
the setting is saved correctly, however, it is not displayed with the right access in the form when user goes to the edit page

**Comment by LemieuxGen** [comment]
@pandurx is this fixed so that the access level will display properly now?
