### ISSUE TITLE
Breadcrumbs within group forums either missing or are in the wrong order

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1445]
As a user, I need to be able to navigate quickly through my group, as well as go back without using my browser's back button. The breadcrumbs help me to know where I am and where I can click to next.

Currently, the breadcrumbs read something like: Home > Questions > CITS Directory Services > Who is this group for

But really, I should be able to see Questions within my group, without having to go to all questions on GCconnex. It should read more like Home > CITS Directory Services > Questions > Who is this group for

The navigation should read from the user's perspective and should be able to go back to features just within their own group.

Within the main page of the group's forums, the breadcrumbs seem to be missing entirely:
![image](https://user-images.githubusercontent.com/29754185/30811354-eff2305a-a1d5-11e7-8300-e01718cf00e4.png)

It should resemble something like this: 
![image](https://user-images.githubusercontent.com/29754185/30811376-007897d4-a1d6-11e7-979c-a61d871115f6.png)

**Comment by KingBain** [comment]
It looks lik someone is working on this issue as now a breadcrumb trail has appeared. Question though, why does the trail sometimes show the group name as {"en":"Your English Group Name","fr":"Your French group name"}

**Comment by KingBain** [comment]
added a screenshot

**Comment by KevinChagnon** [comment]
@LemieuxGen @pandurx

**Comment by klecuyer** [comment]
Adding: the "New Forum Topic" is visible on the wrong pages. Users are entering their post while not going "deep enough" into the forums.

For example, I click on the NCR region, and can post my resume right there. But I haven't selected my Classification and then the next level, which is "deployments, secondments and assignments OR casuals".

This is creating a lot of confusion for users. "New Forum Topic" should only be visible on the last, and very deepest page so that users are posting in the right place once they have selected all the appropriate settings.

**Comment by LemieuxGen** [comment]
@Troy-Lawson @pandurx Could we look at auctioning this as part of this sprint? (this week)
This issue came out of the last code push. Thanks.

**Comment by pandurx** [comment]
i am looking into all the Forums issue this week

**Comment by pandurx** [comment]
@KingBain referring to your screenshot, do you mean localization issue with the breadcrumb?

**Comment by KingBain** [comment]
@pandurx Yes  :)

**Comment by klecuyer** [comment]
@pandurx 
The layout of the forum displays like this:
![image](https://user-images.githubusercontent.com/29754185/31141870-99063ab2-a846-11e7-9453-d9bc62ef85ea.png)
And posts seem to either display in no chronological order, or from oldest-newest, meaning the most recent are at the bottom
Linked to (Private repo) https://github.com/Phanoix/gcconnex-help/issues/3
Public repo: https://github.com/gctools-outilsgc/gcconnex/issues/1462
