### ISSUE TITLE
Can't find users in GSA search

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1448]
As a user, searching for a GCconnex member, I need to be able to search and find GCconnex users through the GSA search. 

Users search for user, and their profile page doesn't show up, but the content associated to them will.

**Comment by pandurx** [comment]
Rajeev is investigating

**Comment by ToferC** [comment]
@LemieuxGen - linked cards pls.

**Comment by 4rsood** [comment]
Added the https://gcconnex.gc.ca/members files to the list of files to be indexed and modified the GSA configuration to index larger files.  GCconnex members are now searchable.  However, the GSA search is currently set up to be language specific.  So members' contents in French are searchable from the French search UI and the English contents from the English search UI.

**Comment by LemieuxGen** [comment]
@klecuyer I vaguely remember you talking about an other ticket related to search where ppl couldn't find other user profiles. If there's an other card about this, could you please reference it in this card?

**Comment by LemieuxGen** [comment]
> So members' contents in French are searchable from the French search UI and the English contents from the English search UI.
@4rsood if I understand correctly, this means that some users can only be found when searching on the English UI page, or French UI page? If that's the case, this is an issue... can we find a solution to ensure all user profiles can be found, regardless of the search UI? Thanks!

**Comment by 4rsood** [comment]
@LemieuxGen You are right - English & French contents are searchable based on the user interface's language.  The easy fix is to modify the search application to not pass the language parameter to the query.  That way the users will find what they are searching for regardless of the UI's language selected.  To be consistent, the change should be applied to all the GCTools sites.   Users may end up getting too many search results but it is better than not finding the information.
