### ISSUE TITLE
GCTools search page - GCconnex menu - wrong link to Contact Us page under More drop down

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1449]
On the GCTools common search page (GSA) need to update the link to Contact Us page of GCconnex under the More menu. Should link to the new page: https://gcconnex.gc.ca/help/knowledgebase

**Comment by pandurx** [comment]
Sent Rajeev an email to look into this

**Comment by ToferC** [comment]
Redirect added. Closing.

**Comment by 4rsood** [comment]
Link updated
