### ISSUE TITLE
Link to "Contact us" in Validation email point to old GCConnex Contact page

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1452]
The link to "Contact us" in the user account Validation email points to the old GCConnex Contact page in both the English and French text ( https://gcconnex.gc.ca/contactform/?utm_source=notification&utm_medium=email )

It should link to: https://gcconnex.gc.ca/help/knowledgebase

**Comment by ToferC** [comment]
Fixed by redirect. Closing.
