### ISSUE TITLE
Group owners/operators can not be edited - list doesn't auto-suggest and username not accepted

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1455]
As a group owner, I need to be able to set admin settings for my group owner and operators.

When I start typing in a group member's name, the drop-down list doesn't auto suggest names to select my new operator. I've tried pasting the username and this is not accepted. 

This blocks any group owners from making changes to admin settings. This has been reported by a number of users.

**Comment by Phanoix** [comment]
fixed in #1475

**Comment by KevinChagnon** [comment]
The group's avatar/image is not being retained when a new group owner is assigned.

**Comment by KevinChagnon** [comment]
@LemieuxGen

**Comment by LemieuxGen** [comment]
This is linked to the issue: #687
