### ISSUE TITLE
Group invitations don't send if user doesn't receive notifications

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1460]
As a user, it appears that my notification settings are affecting my ability to find and join groups.

When somebody invites me to a group, I am not receiving any message or notification. This could either be a notification bug or because of my notification settings:
![image](https://user-images.githubusercontent.com/29754185/30927637-1c6957dc-a387-11e7-85d9-a15230ee7d95.png)

Should there be a separate notification option for group invites to make it clearer to users? I can manage group-specific notifications once I am a member, but some users may not be realizing that they are getting invited to groups. Users already have a hard time finding Invitations under Groups, More, Invitations, if they even know where to look. There should be a notification pushed through for group invites, even if a user has already configured their settings otherwise, no?

**Comment by klecuyer** [comment]
Submitted on behalf of Rima/Heather. Rima was inviting Heather to our GCTools group & sub-group but Heather was never getting the notification or a clue to where to find them. I found them in her Invitations but suspected it could be her notification settings, it just isn't clear.

**Comment by klecuyer** [comment]
@LemieuxGen Heather asked me to flag this to you for tutorials.. She said she configured her notifications for groups and we should educate users to do the same, but from my understanding you can't configure group notifications until you're a member of the group. 
Which notification would you turn off that would cause you to not receive group invitations?
![image](https://user-images.githubusercontent.com/29754185/30975303-ffb41d34-a43f-11e7-8b38-1112b7b80dc7.png)

**Comment by LemieuxGen** [comment]
@klecuyer a user should receive group invitations, regardless of his/her settings for that group. invitations are treated separately. The user would receive them either instantly, or based on their digest's preferences (if enabled). Have you done any tests to see if this is a bug? thanks.
