### ISSUE TITLE
New resume postings not showing first in list - Jobs Marketplace

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1462]
When posting new resumes on the job seekers - national capital region - professional and administration & computer related - casual section, the new post is not showing first, but last. There seems to be an error with the sorting, not allowing hiring managers to see the newest resume when posted.

https://github.com/Phanoix/gcconnex-help/issues/3

**Comment by KevinChagnon** [comment]
@LemieuxGen @pandurx

**Comment by pandurx** [comment]
files sort should be configured in the edit page in group ( group > edit > admin options > Default folder sorting options )
