### ISSUE TITLE
"New Category" and "New Forum" buttons missing from Group Forums

### ISSUE THREAD

**Issue by KingBain** [gctools-outilsgc/gcconnex#1463]
The New category and New forum buttons are missing 

![forum header](https://user-images.githubusercontent.com/367922/30966448-e36261cc-a426-11e7-94b5-feef16314dc2.jpg)

**Comment by KevinChagnon** [comment]
## **https://github.com/Phanoix/gcconnex-help/issues/4**

**Comment by KevinChagnon** [comment]
@LemieuxGen @pandurx

**Comment by LemieuxGen** [comment]
@pandurx Could you look into this as part of this sprint? This seems to be linked to the updated made to the forums last print. Thanks!
