### ISSUE TITLE
GCDropbox Enhancement Suggestion

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1473]
With the roll out of the new policy on Personal Data Storage Device within departments and the requirement for many users to use GC information outside of the workplace (mainly presentations) I would like to propose that a GCDropbox tool be created for users.
 
This would allow:
GC info to remain in GC platform
Easier file transfer between departments (avoiding the cap and firewalls)
Provide a solution for employees to move important files when changing dept.
Reduce the security risk with the usage of Dropbox, Google drive, etc
Provide a back up option for presenters

Linked to https://github.com/Phanoix/gcconnex-help/issues/7

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
