### ISSUE TITLE
Problems with GCconnex links sent via e-mail (notifications)

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1474]
As a user, when I receive emails from GCconnex regarding **new** discussion topics, the link that is sent brings me to a Page not found GCconnex window.

I have tried this while already logged into GCconnex and even in my admin account, so I know I have access to the page.

The user believes this is only occurring in new discussion topics specifically.

Linked to https://github.com/Phanoix/gcconnex-help/issues/8

Posted by user:
I don't know when this problem has started but every time I receive a GCconnex notification via e-mail that someone has started a new discussion topic, when I click on the "View or reply" link embedded within the e-mail, I'm getting a "Page not found" error message from your website.  I'm unable to locate the discussion thread and therefore I'm unable to contribute to the subject at hand.  Can you please fix?
 
Here's an example of a link that doesn't work:
https://gcconnex.gc.ca/discussion/view/31135990/enrequestoffer-for-solutionsfr?utm_source=notification&utm_medium=email

**Comment by pandurx** [comment]
do all links not work? do they know whether or not the discussions were removed before hand?

**Comment by klecuyer** [comment]
Yes multiple users are reporting that the links sent in emails (and specifically Notifications Digest) lead to a Page not Found.

**Comment by klecuyer** [comment]
@pandurx are these changes live on GCconnex or will we see them in two weeks? The existing links (the ones reported) still return a Page not found error, will it only be for new emails/notifications moving forward?
