### ISSUE TITLE
Freshdesk reset password URL doesn't work (click or copy paste)

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1490]
URL: https://gcconnex.gctools-outilsgc.ca/admin/email_notifications/requester_template/2100034563/https:/gcconnex.gctools-outilsgc.ca/en/password_resets/TasvpjjxvIO8RT3CezyH/edit

Do we need to contact Freshdesk about this?
Two users have reported this.
![image](https://user-images.githubusercontent.com/29754185/31146110-8d30315e-a853-11e7-8fb2-fea406d1ba5f.png)
Linked to https://github.com/Phanoix/gcconnex-help/issues/12

**Comment by LemieuxGen** [comment]
Updated the link in the freshdesk email template. Issue should be fixed.
