### ISSUE TITLE
Redirect from old to new contact us page (GCconnex & GCcollab)

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1491]
Now that we have a new contact us page for the freshdesk knowledge base and ticket, we need to remove access to the old contact us form to avoid having any users send help desk enquiries to the generic mailboxes. 

**GCconnex:** 
Please created a redirect from "https://gcconnex.gc.ca/mod/contactform/" to "https://gcconnex.gc.ca/help/knowledgebase"

**GCcollab:**
Please created a redirect from "https://gccollab.ca/mod/contactform/" to 
"https://gccollab.ca/help/knowledgebase"

**Comment by Phanoix** [comment]
GCconnex redirect is up
