### ISSUE TITLE
JSON appearing in various GCconnex content

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1494]
there is still JSON encoding appearing in various pages on GCconnex:
- Opportunities Platform Forum (https://gcconnex.gc.ca/gcforums/group/7617731), in breadcrumb, title
![json in op group](https://user-images.githubusercontent.com/15378977/31227883-7501e396-a9a9-11e7-9343-f45ca57b8073.JPG)
- User profile, new skills
![json profile skills](https://user-images.githubusercontent.com/15378977/31228148-69fdf286-a9aa-11e7-9a12-ed686ccaef28.JPG)
- When adding a comment in a group you're not a member (this was identified on collab @markwooff).
![json comment non-member](https://user-images.githubusercontent.com/15378977/31228374-4ac82cf0-a9ab-11e7-9ccc-3a3045b201c0.JPG)

**Comment by s-duffey** [comment]
JSON still appearing for some groups on Groups Page of GCcollab

![json](https://user-images.githubusercontent.com/31668114/31228702-5f6b9916-a9ac-11e7-8c54-b12be27facc4.JPG)

**Comment by s-duffey** [comment]
And in Group titles

![json 2](https://user-images.githubusercontent.com/31668114/31228756-90c3e324-a9ac-11e7-82f8-aa58aba1432f.JPG)

**Comment by markwooff** [comment]
@LemieuxGen I've fixed the issue in the popup that appears when commenting on a group you're not a member of. Also noticed the text still references GCconnex in there, fixed that as well.

@s-duffey will look into the Group issues you mentioned here.

**Comment by markwooff** [comment]
@s-duffey the title for the **Government of Canada Organizational Culture and Change** group has been fixed. The issue with the **GCcollab - Student Ambassador Network** is that the group photo wasn't set. If there's an issue with the photo, that mangled text will appear instead. This is now fixed.

**Comment by LemieuxGen** [comment]
linked to issue #1308

**Comment by LemieuxGen** [comment]
@Steph4104 Although JSON doesn't appear anymore in Opportunities posting group title, there's still JSON in the title in the notification digest. 
![json digest op_oct13](https://user-images.githubusercontent.com/15378977/31547730-652065b2-aff6-11e7-8b82-32fa29a4885f.JPG)

**Comment by klecuyer** [comment]
Also appearing in Files/Folders
![image](https://user-images.githubusercontent.com/29754185/31723059-d268e7f4-b3eb-11e7-85a3-8df99a61a23e.png)

**Comment by Steph4104** [comment]
Issue related #1458

**Comment by klecuyer** [comment]
Not sure if sharing JSON on GCconnex is still helpful to you @Steph4104 but just in case, still displays in group names when editing content/access settings
![image](https://user-images.githubusercontent.com/29754185/31788093-a92f00d0-b4db-11e7-9800-6dde2c70fe6f.png)

**Comment by Steph4104** [comment]
Yes, is still helpful @klecuyer . If you have other JSON error, you can put it here

**Comment by LemieuxGen** [comment]
@Steph4104 unfortunitely, there's still some JSON appearing on GCconnex. ex: Group avatar on Newsfeed. 
FYI @klecuyer @s-duffey 
![json_group avatar](https://user-images.githubusercontent.com/15378977/31894956-e6ee4de0-b7dd-11e7-9f7c-724fbecdeed3.PNG)

**Comment by Steph4104** [comment]
@klecuyer , in which group the json error show in the widget?

**Comment by klecuyer** [comment]
Hey @Steph4104 
The group was User Experience Design in GCcollab. The ticket was submitted by Charles as the very first Freshdesk ticket on Sept 14th, I was just linking it to the open repo ticket trying to make sure everything's linked. I'll include his description and screenshot below. 
![image](https://user-images.githubusercontent.com/29754185/32014196-6637679a-b98b-11e7-9fbb-9ec364c99f6d.png)
Coding characters appear in Group Title within widget. 
 
See attached screen capture from user profile with widget enabled 

I don't see this in collab anymore in this group. The only place I still see JSON is in Connex where groups are missing an avatar and the JSON appears overlapping the page content:
![image](https://user-images.githubusercontent.com/29754185/32014385-ef5b6b2a-b98b-11e7-9edf-a2806c08962f.png)

**Comment by klecuyer** [comment]
@Steph4104 I don't know if this is related to JSON or a different issue, but I also notice within a group, the subgroups display the URL instead of the sub-group title. Let me know if you want me to create a different ticket for this issue in Github: 
![image](https://user-images.githubusercontent.com/29754185/32014472-31b94b2c-b98c-11e7-9abd-f52498711d25.png)
Link: https://gcconnex.gc.ca/groups/profile/3833837/ensandbox-do-your-testing-here-faites-vos-essais-icifr

**Comment by Steph4104** [comment]
@klecuyer , for the sub-group name, I look into the code, and it's look fine. It's not about the language. I suggest you create a ticket for it.

For the JSON error on broken image, I have a fix to remove the JSON code and only show the group name. It will be on prod on the next push.

**Comment by klecuyer** [comment]
JSON showing in group invitations page @Steph4104 
![image](https://user-images.githubusercontent.com/29754185/32066608-561e4d56-ba4e-11e7-9c12-e3c9f220acf6.png)

**Comment by KevinChagnon** [comment]
@Steph4104   more JSON errors found when viewing GCconnex in French or English:
This is in the photo Album section of a group:

https://gcconnex.gc.ca/photos/siteimagesgroup/31049185

![image](https://user-images.githubusercontent.com/23527358/33216116-89c62a7a-d100-11e7-8df3-7534111667fe.png)

**Comment by KevinChagnon** [comment]
Found some more JSON;

Logged in as Admin

Searched for group: IBSDB
Found: IBSDB's Collaboration Space ()

In "Managae Join Requests" ( https://gcconnex.gc.ca/groups/requests/33076183 )

![image](https://user-images.githubusercontent.com/23527358/33781713-a40d4f66-dc23-11e7-8027-cc6686e763e6.png)

**Comment by KevinChagnon** [comment]
Found another JSON issue:

![json - group event added to pers calendar](https://user-images.githubusercontent.com/23527358/34840349-9e97144c-f6fc-11e7-8ac2-2fb85b0488b5.PNG)

https://gcconnex.gc.ca/event_calendar/display_users/34226204

You get there by creating an Event in a group, viewing the event and clicking on "In # calendars" on the right hand side;

![additional info](https://user-images.githubusercontent.com/23527358/34840475-f735019a-f6fc-11e7-8759-220ce35b0bc8.PNG)

https://gcconnex.gc.ca/event_calendar/view/34226204/entestfr

**Comment by ethanWallace** [comment]
The JSON reappearing is from the new wire image plugin. Submitted a pull request(#1682) which should fix this issue.

**Comment by ethanWallace** [comment]
Pull request containing the fix for latest version of this issue has been merged and pushed to production. Closing this issue again.

**Comment by klecuyer** [comment]
When closed please also close: https://github.com/Phanoix/gcconnex-help/issues/53
