### ISSUE TITLE
Unsubscribe from Notifications (usually Group Forums) does not 'stick'

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1495]
As a user, I have unsubscribed from all possible content under my Account Settings. I continue to receive Job Seeker/Opportunities Group Forum notifications every time someone posts.

In many cases, I have already reached out to the Help Desk, been manually unsubscribed in the admin panel, only to continue receiving notifications every 15 minutes in some cases. 

Many users have reported this specifically starting again in the last few weeks, prior they had been unsubscribed for months with no problems. 

As an admin, sometimes I have gone into an account and unsubscribed in the admin panel, only to refresh the page and see the subscription back again. Some users are deactivating their accounts over this and I can remember this being an issue for a while now. It has just recently started being more prominent, specifically in Help Desk inquiries, and I suspect it may be linked to our existing issues with the group forums. 

@LemieuxGen

**Comment by klecuyer** [comment]
The view to the user may look like they have completely unsubscribed from all notifications, but when I log into the admin panel I can see something more like this:
![image](https://user-images.githubusercontent.com/29754185/31229992-87c66586-a9b0-11e7-8ece-b5a6bc23ced9.png)

**Comment by klecuyer** [comment]
I suspect this is linked to group forums. Will have to determine if the fixes we push through are linked to this in Group Forums:

More than usual amount of users reporting all of a sudden getting forum notifications and more than usual amount of users I'm trying to convince not to delete their accounts.

I think the Group Forums are:
1) showing en/fr coding
2) displaying weird for some users (I can show you screenshots in the Github tickets)
3) ordering oldest-newest or no order at all (putting the newest user's post on the very last page or lost somewhere)
4) re-subscribing users who have previously unsubscribed and I have to go in the back-end admin panel to unsubscribe. They can't see any subscriptions so it's causing a lot of confusion
5) enabling users to add 'New Forum Topic' and upload a resume on any page within the forums, without having to choose their region, classification, and deployment or casual

**Comment by pandurx** [comment]
See pull request for a list of updates that will go up live on production over the coming weekend: https://github.com/gctools-outilsgc/gcconnex/pull/1477

**Comment by pandurx** [comment]
@KevinChagnon @klecuyer @LemieuxGen 

displaying weird for some users
- i think they just need to clear their browser caches

admin troubleshoot tool
- i just did a quick test on production, i was able to unsubscribe myself from the forum

too much notifications sent out
- that might have been caused by the issue mentioning how users can post forum topics anywhere in the forums, so since she unsubscribed to a specific forum, the other users were posting topics in a higher level branch of the forum. Pull Request #1477 will fix that

**Comment by klecuyer** [comment]
Usernames with notifications sticking:
- Kirby.Scott

**Comment by LemieuxGen** [comment]
@pandurx The notification subscriptions are coming back, even if the admin uses the admin troubleshoot tool is used to manually unsubscribe the user from the notifications. The issue is that the subscriptions come back, automatically. Can we look into a fix to ensure this is fixed? There are many users asking to have their GCconnex accounts deleted because of this specific issue.

**Comment by LemieuxGen** [comment]
@pandurx Is this issue "blocked"?

**Comment by pandurx** [comment]
@LemieuxGen i unsubscribed my account (non-admin) through my notification settings/administrative tool, and i was successfully unsubscribed.
i need examples of users and the type of content they're subscribed to

**Comment by LemieuxGen** [comment]
An example is included in this ticket (user:Tammy.Charette). Krista manually unsubscribed her from all notifications. Her notifications settings were successfully saved. However, shortly after, the notifications reverted back to being subscribed and she was receiving notifications again (see screenshot above). Unfortunately, the user insisted in having her account deleted... @klecuyer are there other users you know of that had the same issue? or are there any other details to add? Note: This seems directly linked to forum notifications. Thanks!

**Comment by pandurx** [comment]
I tried to unsubscribe some of the things that Tammy was subscribed to, but only to realize her account was already purged. I just need to be able to replicate.

**Comment by klecuyer** [comment]
@pandurx @LemieuxGen I have an example.
Username: natalie.levesque

Her notification settings look completely blank - no notifications.
![image](https://user-images.githubusercontent.com/29754185/31548856-4e6c8a90-affa-11e7-9a90-2b0acf8fa991.png)

Admin panel shows a different story:
![image](https://user-images.githubusercontent.com/29754185/31548871-5ed90b24-affa-11e7-8975-abbc3aef50c3.png)

I'm not unsubscribing her from these just yet for you to be able to test if need be. @pandurx can you give me the green light when I can go in and unsubscribe her from all these in the admin panel?

**Comment by pandurx** [comment]
@LemieuxGen @klecuyer 
I have a script that I can run that could fix that issue (when a user subscribed to group topics but are not part of the group)

**Comment by klecuyer** [comment]
Here's another. Same thing, multiple subscriptions that she can't see on the front-end.

Username: Pamela.Massad

I have not yet unsubscribed her to leave time for testing @LemieuxGen @pandurx please let me know when I can unsubscribe this user

**Comment by LemieuxGen** [comment]
@pandurx Thanks for looking into this. Yes, please proceed with the script and the bug fix. Please let @klecuyer know once it's done so she can let the users know. 
Thanks!

**Comment by pandurx** [comment]
@klecuyer @LemieuxGen 
Ran the script over the weekend, all the users who were subscribed to forums from a group that they're not members of are all cleaned up.

**Comment by klecuyer** [comment]
This is still an issue @pandurx @LemieuxGen 
From looking at this user's notifications settings,everything was unsubscribed.

I manually unsubscribed her from these notifications sitting on the back end:
![image](https://user-images.githubusercontent.com/29754185/31728595-b32fdabe-b3fa-11e7-98cc-9e6ddfd3fa90.png)

**Comment by pandurx** [comment]
@klecuyer @LemieuxGen 
the weekend push should resolve with empty notification settings (via user's setting) and i will also run the script tonight to clear these
