### ISSUE TITLE
jobs.gc.ca link under Career tab leading to 404 error: appears site URL has changed

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/gcconnex#1500]
Posting this in here because not sure if the ticket was properly created via Freshdesk

The jobs.gc.ca link under the Career tab on GCconnex now leads to a 404 error page. It must have recently been changed because it appears that the site is now: https://www.jobbank.gc.ca/home-eng.do?lang=eng

**Comment by s-duffey** [comment]
Meme chose en français. Nouveau lien: https://www.guichetemplois.gc.ca/accueil-fra.do?lang=eng

**Comment by klecuyer** [comment]
Hey @s-duffey you're right. The Freshdesk Github link creates it in a closed repo, and we have to create a duplicate in our open GCconnex repo

You just paste the URL with Linked to https://github.com/Phanoix/gcconnex-help/issues/15

That way when this one is closed, they know to go close our private repo and we know to tell the user. I'm sorry I created a duplicate ticket but I've closed it now

**Comment by markwooff** [comment]
I think those links were fixed with 51671ad7814bbedccf1a0a9b2fa7331dcf53887a - right @piet0024?

**Comment by KevinChagnon** [comment]
Issue being resolved in #1427
