### ISSUE TITLE
UI changes to the GCTools Search 

### ISSUE THREAD

**Issue by 4rsood** [gctools-outilsgc/gcconnex#1507]
Following UI changes to the GCTools Search were requested:

•         Hide title of the page "Basic Search/Search Results"
•         Hide search label "Search For"
•         Make the search text box span across the page
•         Move the "Search now" button to the right of the text box 
•         On the "Search now" button, hide the text and show the search glyphicon
•         Remove the pagination from the top of the results, but keep it at the bottom
•         Update the look of the results to look more like Canada.ca
o    Bold the result link
o    Move the URL below the result link and remove the "URL: " text
o    Use the following format for the dates: "Sep 2, 2016", place before the description and remove the "Date: " text.
•         Update the layout of the Filter your results section:
o    "Filter your results" should be the heading in the gray bar
o    "By source" text should be moved above the list of checkboxes

**Comment by 4rsood** [comment]
The changes have now been applied to the GCTools search.

**Comment by LemieuxGen** [comment]
@4rsood, closing issue as this is now completed.
