### ISSUE TITLE
Creating an Opportunit - Opportunity Type field should be required and appear blank.

### ISSUE THREAD

**Issue by Eldoraaoun** [gctools-outilsgc/gcconnex#1536]
In Creating an Opportunity, _Opportunity Type_ should be a mandatory field and the first option should appear blank (currently shows Micro-Missions in GCconnex and Mentoring GCcollab) to force users to use the drop down menu and select the appropriate opportunity type.

**Comment by marcleblanc** [comment]
PR created.

https://github.com/gctools-outilsgc/gcconnex/pull/1580

**Comment by Eldoraaoun** [comment]
@LemieuxGen @Phanoix  Can we reopen this issue? The Opportunity Type field is now marked as required (great!), but Micro-Mission is still the default. Can we change it so that the first option is blank, so that users are forced to look at the drop-down menu and choose the appropriate mechanism. 

Thank you!

**Comment by LemieuxGen** [comment]
In Opportunities Platform on GCconnex and GCcollab, the opportunity type when creating a new opportunity currently defaults to "Mentoring" (collab) and "micro-mission" (connex). The drop down list needs to default to a blank option, as opposed to the first option of the drop down list. By having the filed pre-populated, users are likely to ignore changing the type, resulting in false information and skewed stats. 
![op type](https://user-images.githubusercontent.com/15378977/33952916-464b3334-e001-11e7-9d35-be90817aa261.PNG)

**Comment by Steph4104** [comment]
We just need to desactivate and reactivate the plugin

**Comment by LemieuxGen** [comment]
@markwooff @Troy-Lawson This is compelted on GCconnex, but not on GCcollab. On GCcollab the opportunity type is still not mandatory and default option still shows Mentoring (should be blank).

**Comment by Steph4104** [comment]
@markwooff , you only need to desactivate and reactivate the plugin. This code is in the activate.php page, so it's only need to be reload.

**Comment by LemieuxGen** [comment]
I need a confirmation once the plugin is reactivate so I can advise the client this is completed. Thanks!
