### ISSUE TITLE
Translating content to French also replaces content of comments with French blog text

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1553]
As a user, I post a blog. There are comments under it:
![image](https://user-images.githubusercontent.com/29754185/31828209-97fa2482-b587-11e7-9c14-fc37ff68c535.png)

If I use _this_ button to translate the blog post, it replaces my comments with the content of the blog... in French:
![image](https://user-images.githubusercontent.com/29754185/31828257-b8222796-b587-11e7-9c7a-b35ebbc0a5b9.png)
![image](https://user-images.githubusercontent.com/29754185/31828308-da6900ae-b587-11e7-97a9-34f9044c7d94.png)
![image](https://user-images.githubusercontent.com/29754185/31828316-e12560e0-b587-11e7-9616-52bdd83a3593.png)

If I translate back to English now, the comments are English, but still replaced with the content of the blog:
![image](https://user-images.githubusercontent.com/29754185/31828385-12d56842-b588-11e7-894e-78f4620fadcf.png)
![image](https://user-images.githubusercontent.com/29754185/31828393-1a670386-b588-11e7-84ae-03a86fc4e538.png)
![image](https://user-images.githubusercontent.com/29754185/31828417-271ecdd4-b588-11e7-84f4-8b98d3cec855.png)

If I refresh the page, everything goes back to normal.

Using my user settings (top nav bar), everything works fine.

Link to the group: https://gcconnex.gc.ca/blog/view/31810543/enfall-update-from-the-clerk-of-the-privy-councilfrmise-u00e0-jour-dautomne-du-greffier-du-conseil-privu00e9

**Comment by Steph4104** [comment]
@klecuyer , can you test again? I think it was fix with the update of the week-end.

**Comment by klecuyer** [comment]
@Steph4104 yes it works beautifully. Thank you

**Comment by klecuyer** [comment]
This bug has returned. Toggling to French replaces comments with French content of post.
Link to where this is reported. Be sure to toggle languages within the content, not the user settings.
https://gcconnex.gc.ca/pages/view/30805166/ensemaine-21-aout-week-of-august-21frsemaine-21-aout-week-of-august-21

Linked to https://github.com/Phanoix/gcconnex-help/issues/33

**Comment by LemieuxGen** [comment]
@Steph4104 can we look into this issue? This was fixxed last sprint, but came back with the latest release. Thanks!
