### ISSUE TITLE
Notification for new Wire message are missing the wire message...

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1554]
As a user receiving instant notification, I need the email message to be complete and include the wire message in the notification. 
As it is now, the notification text is missing the wire message and I have to click on the link to reply to the wire in order to see the wire message. 

In English and French text are missing words (missing text in bold): 
EN: Sebastien.Lemay posted a new wire **message** entitled 
FR: Sebastien.Lemay a ajouté un nouveau **message sur le fil** intitulé 

Please add wire message in notification and fix french language. 
![wire notifications](https://user-images.githubusercontent.com/15378977/31833066-5a4d58a6-b597-11e7-9c74-8a62f48b9629.PNG)

**Comment by Troy-Lawson** [comment]
mAKE WORK WITH IMAGES

**Comment by pandurx** [comment]
Originally, this issue was to put the Wire message in the Notifications. This seems to be on production now. For Wire Images, please see #1640 for updates.
