### ISSUE TITLE
Editing Poll title doesn't update poll

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1559]
As a user, if I need to edit my poll title/question, my edit saves but does not update the poll title:
![image](https://user-images.githubusercontent.com/29754185/31890156-272ec848-b7d0-11e7-816b-7da8213204ac.png)

I can see that my changes are saved (Poll question in English) but the poll title is not updated. 
For users who made a spelling mistake initially or want to rephrase, they can't.

Link to poll: https://gcconnex.gc.ca/polls/view/31833387/endo-you-like-cakefr

**Comment by LemieuxGen** [comment]
@klecuyer Just tried this, and the page just needs to be refreshed before the change appears in the title. Can you verify and ask the user to try refreshing his browser to see if the edit will work? If it does, please close the private repo issue and freshdesk ticket.

**Comment by klecuyer** [comment]
@LemieuxGen this is still an issue. The question should have a question mark on the end of it (my edit) and after refreshing still does not.

**Comment by klecuyer** [comment]
@LemieuxGen I saw your test poll: it doesn't appeared that the edit shows, no? https://gcconnex.gc.ca/polls/view/31913097/enenglish-title-with-typafrtitre-de-sondage-en-francais-avec-typa

**Comment by LemieuxGen** [comment]
@klecuyer You're right, it is a bug! 
If you go to edit a poll, and save the new content. The edited content doesn't appear right away. If you change the language using the language link (not top toggle), the edited content will appear. However, if you refresh the page, or leave that page and come back to the poll, the content still shows as the original content (not edited). 
See example: https://gcconnex.gc.ca/polls/view/31913097/enenglish-title-with-typafrtitre-de-sondage-en-francais-avec-typa# 
![poll_edit language link](https://user-images.githubusercontent.com/15378977/31907343-8e053daa-b801-11e7-823f-b752455e27f3.PNG)

**Comment by LemieuxGen** [comment]
@Steph4104 Let us know when it's ready to test on preprod. Thanks!

**Comment by Steph4104** [comment]
@LemieuxGen , it's on preprod.
