### ISSUE TITLE
Prominent typo 'Inviter les mes colleagues'

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1561]
Typo when inviting group members in French user settings:
![image](https://user-images.githubusercontent.com/29754185/31895188-82049514-b7de-11e7-8e5a-9bff9e458c40.png)

**Comment by LemieuxGen** [comment]
The text should be updated in English and French as the function here is for the group owner or operator to invite others to the group (as opposed of inviting only "my colleagues" to the group). 
Please fix. Text should say:
EN: Invite users to the group
FR: Invitez des utilisateurs au groupe

**Comment by maazsq** [comment]
#1564

**Comment by maazsq** [comment]
#1566
