### ISSUE TITLE
Access set to 'Only Me' still sends notification to group

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1563]
This may be a broader access setting or closed content issue to address, but here's the isolated incident.

As a user, Gen posts a poll, Access set to 'Only Me': 
![image](https://user-images.githubusercontent.com/29754185/31908328-6fb44e10-b804-11e7-800b-9b2a4de5712b.png)
Link to poll: https://gcconnex.gc.ca/polls/view/31913097/enenglish-title-with-typafrtitre-de-sondage-en-francais-avec-typa

I can't see the poll in my non-admin account, but I still got an email notification when she posted it:
![image](https://user-images.githubusercontent.com/29754185/31908432-d7f261e2-b804-11e7-920f-3156d0e1908f.png)

Is this because of my admin account? It's hard to determine because both my personal and admin GCconnex accounts are registered to my same email.

**Comment by pandurx** [comment]
- you are receiving the notification because administrative accounts can see all post despite being set as "Only Me"

**Comment by klecuyer** [comment]
@pandurx that's what we were trying to determine - if the email was sent because of my admin/personal account. You might be right we just weren't sure why I got that email. Both are registered to the same email address so it was difficult to tell

**Comment by pandurx** [comment]
@klecuyer i'll have it patched, since this shouldn't happen
