### ISSUE TITLE
Add English / Français tabs to the invitations page

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1573]
Currently, when sending a group invite, the email is sent in FR/EN but the message is simply duplicated in both sections:
![image](https://user-images.githubusercontent.com/29754185/32068661-cac3347c-ba54-11e7-932b-54adf7f87fd8.png)

As a user, I'd like the option to have FR/EN tabs on my group invite so I can send a bilingual message, and avoid this unnecessary duplication.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
