### ISSUE TITLE
Ability to search by classification and level in Opportunities Platform

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1574]
As a user searching for opportunities (advanced search in the opportunities platform), I want to be able to filter opportunities by group classification and level so that I can find the ones that are relevant to me without having to scroll through all the postings. 
The filter for the group and classification would **only apply to specific types** of opportunities, such as: 
- Job swap
- Assignment / Secondment
- Deployment 
- Job rotation

**Comment by LemieuxGen** [comment]
linked to issue https://github.com/Phanoix/gccollab-help/issues/12

**Comment by KevinChagnon** [comment]
ticket created in closed collab repo should have been made in closed connex repo.
this issue was resolved as part of the 2 following tickets:
https://github.com/gctools-outilsgc/gcconnex/issues/1305
https://github.com/gctools-outilsgc/gcconnex/pull/1782
