### ISSUE TITLE
Notification not sending to group members for new group content (blog)

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1587]
Creating more specific notification issues/tickets rather than them all compiled into one

As a group operator, when I post a group blog, I want members to be notified so people see the content (to like, comment, share).

Group content is not consistently notifying group members when it is posted.

Link to blog: https://gcconnex.gc.ca/blog/view/32183962/enjust-say-yesfrdites-simplement-oui
Link to group: https://gcconnex.gc.ca/groups/profile/19651377/enexecutive-corner-carrefour-des-cadres-supu00e9rieursfr

I have checked three group members (with email and site notifications enabled for this group) and no one received the notification for the blog posted above.

**Comment by pandurx** [comment]
Relates to issue #1227

**Comment by LemieuxGen** [comment]
Duplicate issue. Adding a link to this ticket in main issue ([1668](https://github.com/gctools-outilsgc/gcconnex/issues/1668))
