### ISSUE TITLE
Faute de grammaire - Mes collègues

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1598]
![ajouter des mes collegues](https://user-images.githubusercontent.com/23527358/32668293-21c9d836-c60b-11e7-880c-5ed41b3d72ea.jpg)

Grammar in the message "Cet utilisatuer n'a pas encore ajouter de mes collègues à ce jour" should read:

Cet utilisatuer n'a pas encore **ajouté des collègues** à ce jour"

**Comment by KevinChagnon** [comment]
https://github.com/Phanoix/gcconnex-help/issues/30

**Comment by Steph4104** [comment]
@KevinChagnon  des collègues ou de collègues?

**Comment by KevinChagnon** [comment]
@LemieuxGen @CPoulin1 

Thoughts?

"des collègues"  or  "de collègues" ?

"Cet utilisatuer n'a pas encore ajouter ______________________ à ce jour"

**Comment by KevinChagnon** [comment]
@Steph4104 : as per @CPoulin1 is should be: "Cet utilisateur n’a pas encore ajouté **de collègues**."

**Comment by Steph4104** [comment]
@KevinChagnon , le titre de la page ne devrait pas être "Collègues de Username" ?

**Comment by KevinChagnon** [comment]
@Steph4104 - oui "Collègues de Username"

"Demandes de collègue" devrais aussi être "Demandes de collègue**s**"

**Comment by KevinChagnon** [comment]
Closed ticket in error - re-opened ticket
