### ISSUE TITLE
Cannot edit 'Pages' within a group, though 'Write access' is set to group members

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1604]
As a group owner, I have group members editing 'Pages' collectively within a group. I have set my 'Write access' to group members, but as of this week, they no longer have the option to edit Pages:

Link to page in group: https://gcconnex.gc.ca/pages/view/31668994/enfrsalle-su00e9curisu00e9e-quu00e9bec-semaine-du-13-novembre-2017

![image](https://user-images.githubusercontent.com/29754185/32856080-c054dece-ca11-11e7-925e-937465b268a6.png)

![image](https://user-images.githubusercontent.com/29754185/32856142-f3c364ba-ca11-11e7-956e-c1ada7a0cbde.png)

This access appears to have changed after the last sprint (users were able to edit last Friday but can't anymore). They use this feature weekly for scheduling because all group members can edit the page.

**Comment by klecuyer** [comment]
Linked to https://github.com/Phanoix/gcconnex-help/issues/32

**Comment by klecuyer** [comment]
Reported by another user. I can see the edit icon in my admin account, but cannot see it in my personal, despite being a group member and write access for group members being enabled:
![image](https://user-images.githubusercontent.com/29754185/32857985-cf0629fe-ca17-11e7-9305-19e652692c3e.png)
![image](https://user-images.githubusercontent.com/29754185/32857989-dc3d74e2-ca17-11e7-958e-8f85afe97862.png)
![image](https://user-images.githubusercontent.com/29754185/32858087-39a271aa-ca18-11e7-9ba0-fd20559361b7.png)

**Comment by KevinChagnon** [comment]
Here is a link to a page where the group owner/creator of the page no longer sees the option to Edit the page: https://gcconnex.gc.ca/pages/view/9652881/a-la-carte-precedents

![image](https://user-images.githubusercontent.com/23527358/33028160-16de1362-cde3-11e7-9da9-1048acb84a7e.png)

The page could be Edited by changing "View" in the address bar to "Edit" - put this does not make the Edit button show up after changes were saved.

**Comment by LemieuxGen** [comment]
@klecuyer Now that this is puched on production, can you confirm if the group members have access to edit pages (based on the access level set)? thanks!

**Comment by klecuyer** [comment]
@LemieuxGen yes I can confirm this is working. Tested yesterday and again just now to be sure. Freshdesk tickets have been resolved, notifying users.
