### ISSUE TITLE
Invite users by email (to a group) not working

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1605]
Within a group I own, I go to invite users using their email address:
![image](https://user-images.githubusercontent.com/29754185/32858311-172fd0bc-ca19-11e7-85ba-f9ffbc226dd2.png)

I am immediately brought to this blue error page full of code upon clicking Invite:
![image](https://user-images.githubusercontent.com/29754185/32858345-3750a132-ca19-11e7-8a8d-7ae23d28e4c9.png)

**Comment by klecuyer** [comment]
This can be replicated @Gen still an issue. Get error when inviting someone new by email or resending to someone already invited.
If you use an email already invited butdon't check the resend box you get this error instead (not the blue screen)
![image](https://user-images.githubusercontent.com/29754185/32905860-35f1df3a-cac9-11e7-954f-e1251d45f431.png)

**Comment by KevinChagnon** [comment]
+1

It is important to know that the invited email address is added to the listed of Invited email addresses regardless of the Oops error.

We would need to verify the mail log to see if the email actually went through - as per my testing (screenshots below) the email does not send.

![image](https://user-images.githubusercontent.com/23527358/33077832-ded7bd80-ce9e-11e7-840e-1f4580c7979e.png)

![image](https://user-images.githubusercontent.com/23527358/33077848-e805a0a2-ce9e-11e7-9156-8a068efde2ec.png)

**Comment by markwooff** [comment]
I think this may be related to an issue I fixed yesterday on GCcollab. Email invitation weren't being sent out because of the way notifications were set up. Will push the fix for this on GCconnex as well.

**Comment by markwooff** [comment]
PR created at https://github.com/gctools-outilsgc/gcconnex/pull/1615

**Comment by LemieuxGen** [comment]
@markwooff will this be pushed over the weekend? and is there a way we can test to see if this will in fact fix the issue?

**Comment by markwooff** [comment]
It's live on GCcollab and has been proven to fix the issue by the fact that users are actually receiving group invitations now. Could ask one of the devs to test on GCconnex?

**Comment by Troy-Lawson** [comment]
@Steph4104 can you take a look at this from the gcconnex side?

**Comment by Steph4104** [comment]
I test on Prod and I was able to invite user by email and reinvite the same by email with the resend box check.
