### ISSUE TITLE
Unable to view photo album posted in group when logged out #35

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1608]
Users  get an "Oops error" when trying to view an photo album in a group when they are not logged in;

Example:
https://gcconnex.gc.ca/photos/album/32151992/enbn-infographicfr?utm_source=notification&utm_medium=email

![image](https://user-images.githubusercontent.com/23527358/32901129-1f2680a0-cabd-11e7-92ec-9e810eac2628.png)

![image](https://user-images.githubusercontent.com/23527358/32901143-27dfe8da-cabd-11e7-8d18-b8e4ea8ec8f2.png)

When the user is logged in - the album can be viewed.

**Comment by KevinChagnon** [comment]
## **https://github.com/Phanoix/gcconnex-help/issues/35**

**Comment by piet0024** [comment]
@KevinChagnon do we know if this is still an issue? I just visited this album not logged in and the page displayed. Perhaps the network was slow that day and it timed out?

**Comment by KevinChagnon** [comment]
Yep..still an issue.

https://gcconnex.gc.ca/photos/siteimagesgroup/31049185

If I open this link and am not logged in. I get the Oops msg.

![image](https://user-images.githubusercontent.com/23527358/33451407-fd1d8cee-d5dc-11e7-8495-78e2193fa636.png)

Once i click on a picture:

![image](https://user-images.githubusercontent.com/23527358/33451454-1a1c0564-d5dd-11e7-9224-5a2eb5170c1b.png)

I selected the highlighted image, but get an error on all of them;

![image](https://user-images.githubusercontent.com/23527358/33451527-4cd164b8-d5dd-11e7-8cb0-5fae42d4f834.png)
