### ISSUE TITLE
Remove extra space on GCTools Search page

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1610]
Following interface updates to the Search page, there is extra space between the search bar and the search results. As a user, I would like like to maximize the space on the page and see more results without scrolling. Please move the search results up closer to the search bar. 
![extra space on search page](https://user-images.githubusercontent.com/15378977/32955482-1a2e50ec-cb84-11e7-8726-f833952bac3a.PNG)

FYI: @4rsood as discussed.

**Comment by 4rsood** [comment]
The extra space has been removed.
