### ISSUE TITLE
Opportunities Platform ->Search members, Advanced find, Opt-In field should be a drop down menu of all types of opportunities

### ISSUE THREAD

**Issue by Eldoraaoun** [gctools-outilsgc/gcconnex#1614]
In “Search members”-> “Advanced find” -> Opt-In field should be a drop down menu of all mechanisms (Micro-Mission,  Mentoring,  Job Swap,  Job Shadowing,  Assignment/ Secondment,  Deployment,  Job Rotation,  Job Sharing, Skill Sharing  Peer Coaching). Currently it is a free text box.

Bug! @LemieuxGen

**Comment by markwooff** [comment]
This issue should be fixed with my latest commit. Had already been set to a dropdown on GCcollab.
