### ISSUE TITLE
Users receiving notifications for group content they do not have access to

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1626]
User reports receiving email notification for 'closed' content set to 'only me' for both read/write access.
As a user, I don't want to receive notifications for content I don't have access to.
As a content creator, I don't want other group members to receive notifications for content I have not yet published.

Link to content: https://gcconnex.gc.ca/pages/view/32818667/enjosu00e9phine-bacon-poetfrjosu00e9phine-bacon-pou00e8te?utm_source=notification&utm_medium=site

Link to user's notification: https://gcconnex.gc.ca/messages/read/32818736

Read/write access to only me:
![image](https://user-images.githubusercontent.com/29754185/33221869-f8d2aae0-d120-11e7-8859-29165263b8e2.png)

I have tested creating a group page set to only me and did not receive a notification on my personal account. Haven't yet been able to replicate myself. Perhaps linked to changes on read/write access for Pages

**Comment by klecuyer** [comment]
Linked to https://github.com/Phanoix/gcconnex-help/issues/38

**Comment by pandurx** [comment]
The notifications seems to be working fine with the access level. I created a page with access set to Only Me, I did not receive anything.

**Comment by pandurx** [comment]
@klecuyer  is this still an issue?

**Comment by klecuyer** [comment]
@pandurx I haven't been able to recreate this issue myself. I just know it did happen. It looks like the user has deleted the notification since
