### ISSUE TITLE
Broken URL - Jobs Marketplace

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1627]
Some links in Jobs Marketplace are giving an Error 500;

![image](https://user-images.githubusercontent.com/23527358/33222977-8f0ce040-d129-11e7-96d0-3fe1681dbdf0.png)

DEPLOYMENT/Assignment/Secondment EC‑03 or EC 04 Opportunity at the Treasury Board Secretariat / MUTATION/Affectation/Détachement EC 03 ou EC 04 Possibilité au Secrétariat du Conseil du Trésor

https://gcconnex.gc.ca/gcforums/topic/view/32424750

**Comment by KevinChagnon** [comment]
## **https://github.com/Phanoix/gcconnex-help/issues/39**

**Comment by LemieuxGen** [comment]
@KevinChagnon Can you provide the link to the page where the broken link is located?

**Comment by pandurx** [comment]
@KevinChagnon 
I'm trying to find out where this opportunity would be listed but I cannot seem to be able to find it. I looked up the id of the forum topic, but it doesn't seem to exist in the database.
Perhaps the poster had deleted the topic?

**Comment by KevinChagnon** [comment]
I am waiting for a reply from the client as to how she found the link.
If you do a search for it by keyword.... EC‑03 or EC 04 Opportunity at the Treasury.... it does come up in search results.

trying to upload the screenshot, but it's not working

**Comment by pandurx** [comment]
I'm not sure when the post started giving out the HTTP500 error, but another example is https://gcconnex.gc.ca/profile/Erik.Tremblay1 (I know this profile does not exist because I just had his username changed yesterday morning)

**Comment by pandurx** [comment]
This issue is closely related to the Search index and not the Forums, but I've updated the code so that it will display "Page not found" instead of HTTP500 Error

**Comment by LemieuxGen** [comment]
@pandurx Will you be looking into it? or do you want us to assign it to @4rsood?

**Comment by pandurx** [comment]
@LemieuxGen 
This has to do with the GSA's indexing capability, for some reason the old index are not being removed correctly (@4rsood has those page results removed and it doesn't come up anymore)
