### ISSUE TITLE
Merge users

### ISSUE THREAD

**Issue by ethanWallace** [gctools-outilsgc/gcconnex#1629]
Some entity types do not transfer properly.

**Comment by ethanWallace** [comment]
@KevinChagnon Please add more details to this issue.

**Comment by KevinChagnon** [comment]
**Unable to upload screenshots at this time.  will try later (they go between all this text)**

Profiles used:

https://gcconnex.gc.ca/profile/user1
https://gcconnex.gc.ca/profile/user2

Selected Merge from Admin panel



Selections: I did not select to delete a profile.


 
Clicked Merge – then OK



 **Confirmation message: Seems incomplete** – **no details as to status of User 1**



**OBSERVATIONS** (after cache was flushed)

https://gcconnex.gc.ca/profile/user1                                     
 

https://gcconnex.gc.ca/profile/user2


Personal info:                    Personal info/avatar did not overwrite
About Me:                         Did not copy over
Education:                         Transferred to user 2 – deleted from user 1
Work Experience:              Transferred to user 2 – deleted from user 1
Skills:                                  Did not copy over and deleted skills from user 1 and 2
SLE:                                     ok
Files:                                   Transferred to user 2 – deleted from user 1
Blogs:                                 Transferred to user 2 – deleted from user 1
Photo Album:                     Transferred to user 2 but image within did not


...transfered/replaced with this (& deleted from user 1):

Events:                                 Did not transfer/copy
Pages:                                  Transferred to user 2 – deleted from user 1
Bookmarks:                          Transferred to user 2 – deleted from user 1
Questions:                            Transferred to user 2 – deleted from user 1
Polls:                                     Transferred to user 2 – deleted from user 1
Colleagues:                           ok
Groups:                                 ok

**Comment by KevinChagnon** [comment]
@ethanWallace  @LemieuxGen - all notes and screenshots from testing the Merge plugin have been added above.

**Comment by LemieuxGen** [comment]
@ethanWallace Is this on preprod for testing?
@KevinChagnon can you test again now that we have the new fixes?

**Comment by ethanWallace** [comment]
@LemieuxGen Yes it is up on preprod right now.

**Comment by KevinChagnon** [comment]
Test Results:

Profiles used:
https://gcconnex.gc.ca/profile/user1
https://gcconnex.gc.ca/profile/user2

Selected Merge from Admin panel
Selections: all besides delete profile
Clicked Merge
Prompt to confirm: clicked OK
Confirmation message: fix in message ok

**OBSERVATIONS** (after cache was flushed)
Personal info: Personal info/avatar did not overwrite
Note: email address should not be overwritten as it is usually the users new email address
About Me: Did not copy over
Education: Transferred to user 2 – deleted from user 1
Work Experience: Transferred to user 2 – deleted from user 1
Skills: Did not copy over and deleted skills from user 1
SLE: ok
Blogs: Transferred to user 2 – deleted from user 1
Events: Did not transfer/copy - Deleted from User 1 and User2 (new behaviour)
Pages: Transferred to user 2 – deleted from user 1
Bookmarks: Transferred to user 2 – deleted from user 1
Questions: Transferred to user 2 – deleted from user 1
Polls: Transferred to user 2 – deleted from user 1
Colleagues: ok
Groups: ok
Files: This feature was not worked on / decision made not to transfer files
Photo Album: This feature was not worked on / decision made not to transfer files

Behavior is pretty much the same except for Event which simply deleted events in both accounts

**Comment by KevinChagnon** [comment]
@LemieuxGen  FYI
