### ISSUE TITLE
Digest including file updates under wrong/blank group

### ISSUE THREAD

**Issue by nschonni** [gctools-outilsgc/gcconnex#1637]
[2017-11-30-Your Daily Digest.zip](https://github.com/gctools-outilsgc/gcconnex/files/1519555/2017-11-30-Your.Daily.Digest.zip)
Full email attached, but you can see in the screenshot, there is notifications for another group inbetween the Discussion and File updates
![image](https://user-images.githubusercontent.com/1297909/33456164-8cc147c8-d5ec-11e7-9d80-a2897675fc86.png)

**Comment by marc-donofrio** [comment]
No longer an issue.
