### ISSUE TITLE
Wire Images (notification)

### ISSUE THREAD

**Issue by pandurx** [gctools-outilsgc/gcconnex#1640]
@LemieuxGen 
The notification (both site and email) now displays the image that the user uploads and posts on the Wire.
Digest should also have the image and message displayed, for consistency.

@markwooff @ethanWallace 
**confirmed that the wire-message works for share and reply**
When I attempt to do a share to the wire or reply on the wire, it doesn't seem to invoke the action file. No PHP error, just a bunch of Ajax error on the console.

**Comment by pandurx** [comment]
@LemieuxGen  @Steph4104 
For single notifications, both the wire message and wire image will be displayed and linked to the wire post.

For the digest, the section will be displaying the wire message and the "image text" and both are linked to the wire post. 

Both text will be provided by @LemieuxGen

**Comment by LemieuxGen** [comment]
@pandurx @Steph4104  As discussed, here's the text for all options of the single and digest notifications when someone post a wire message (text only, image only, or image and text). 

Single notification with text message only: 
EN: USER posted a new Wire message: hyperlinked message here
FR : USER a affiché un nouveau message sur le Fil : hyperlinked message here
Single notification with image only: 
EN: USER posted a new message on the Wire: 
<image thumbnail hyperlinked to wire post - image to appear below the text>
FR : USER a affiché un nouveau message sur le Fil : 
<image thumbnail hyperlinked to wire post - image to appear below the text>
Single notification with image AND Text: 
EN: USER posted a new message on the Wire: hyperlinked message here
<image thumbnail hyperlinked to wire post - image to appear below the text>
FR : USER a affiché un nouveau message sur le Fil : hyperlinked message here
<image thumbnail hyperlinked to wire post - image to appear below the text>

Digest notification with text message only: 
EN: USER posted a new message on the Wire: hyperlinked message here
FR : USER a affiché un nouveau message sur le Fil : hyperlinked message here
Digest notification with image only: 
EN: USER posted a new message on the Wire: See Wire post image on the Wire
FR : USER a affiché un nouveau message sur le Fil : Voir l’image du message sur le Fil
Digest notification with image AND Text: 
EN: USER posted a new message on the Wire: hyperlinked message here (See the Wire post to view the image) 
FR : USER a affiché un nouveau message sur le Fil : hyperlinked message here (Voir le message sur le Fil pour visionner l’image)

**Comment by pandurx** [comment]
I think this is resolved, it should have been pushed Jan 20th
