### ISSUE TITLE
Department tab in newsfeed gives 500 error

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1642]
User reports this is hit or miss. Sometimes clicking on his department tab in the Newsfeed brings a 500 error.

User: sas120
Department: National Defense

Linked to https://github.com/Phanoix/gcconnex-help/issues/41

Was unable to replicate.

**Comment by klecuyer** [comment]
From user, just now: 
Good day,
 
I did some testing and it looks like it might be related to a specific post within the set. If I try to look historically, there seems to be a certain entry (now in the 30’s in recent history) that seems to cause the access issue. Maybe a special character or something?
 
Scott

**Comment by klecuyer** [comment]
Another user getting a 500 error. I tested logged in as him and got this:
![image](https://user-images.githubusercontent.com/29754185/33850939-77d78382-de83-11e7-8b04-7125fb4fd128.png)

User: tarek.akhtar
Department: Global Affairs

**Comment by klecuyer** [comment]
Another user: https://gcconnex.gc.ca/profile/steven.dorey
Department: Canadian Nuclear Safety Commission

**Comment by Troy-Lawson** [comment]
here is what i believe to be the error log error: PHP Fatal error:  Call to a member function canEdit() on a non-object in /sites/gcconnex/htdocs/elgg/engine/lib/navigation.php on line 481
