### ISSUE TITLE
500 error when trying to access a group while not logged in

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1643]
As a user, if I click a link to a group (or anything I can't access), but I'm not logged in, I should be brought to the login page with a notice that I have to be logged in to view this page.

I tested this twice with two different results. The user reports getting a 500 error when accessing a group while not logged in that is only visible to logged in GCconnex users.

The first time, everything worked fine. This should happen every time:
image
![image](https://user-images.githubusercontent.com/29754185/33678899-39402ce2-da8b-11e7-826d-ae16356967f0.png)

The second test, still not logged in, I got the 500 error:
![image](https://user-images.githubusercontent.com/29754185/33678923-49189348-da8b-11e7-8d3e-0ed030ec9b01.png)

Linked to: https://github.com/Phanoix/gcconnex-help/issues/42

**Comment by KevinChagnon** [comment]
+1
Confirming this is still an issue, but after many attempts still cannot not land a desirable page like Krista's second example. I always get the 500 error when trying to access a closed group page when not logged in both in Chrome and IE;
![image](https://user-images.githubusercontent.com/23527358/36691613-d640e74e-1b03-11e8-851f-5a69c903eb96.png)
![image](https://user-images.githubusercontent.com/23527358/36691626-e1846ee6-1b03-11e8-95dc-66589c17bf7c.png)
