### ISSUE TITLE
Add to GCconnex inquiry: Office of the Parliamentary Budget

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1644]
https://support.gctools-outilsgc.ca/helpdesk/tickets/1383

PBO is now an independent agency- we are no longer part of the Library of Parliament
@parl.gc.ca

@JOutram77 @KevinChagnon

**Comment by klecuyer** [comment]
Since Sep 21, PBO is now independent
http://www.pbo-dpb.gc.ca/en/

**Comment by KevinChagnon** [comment]
@Troy-Lawson @LemieuxGen

**Comment by klecuyer** [comment]
@JOutram77 @LemieuxGen @CPoulin1 can we close this? It could have been discussed in an email but this ticket and the Freshdesk ticket are still open. Waiting on a decision and justification to share with the user.

**Comment by JOutram77** [comment]
The Office of the Parliamentary Budget Officer has been added to the GCcollab registration. It is covered in the domain manager by *.gc.ca.

**Comment by klecuyer** [comment]
This one is for GCconnex. @JOutram77 sorry if tagging you was the wrong move, just looking for a response.

**Comment by klecuyer** [comment]
@LemieuxGen this is our only pending registration for GCconnex. It's from 4 months ago. Who would be the best person to make this call for GCconnex specifically so I can give the user a definitive answer?

**Comment by klecuyer** [comment]
Pulls from GCdirectory.

**Comment by LemieuxGen** [comment]
@klecuyer was PArliamentary Budget added to GCconnex? and if not, can you confirm that the resolution of using GCcollab ok with the client? thanks!

**Comment by klecuyer** [comment]
@LemieuxGen the client was able to register initially using his govt email. He just wanted to have this sub-section or division added as an option in GCconnex. The explanation I gave him was that GCconnex pulls information from GCdirectory and that once it is in GCdirectory we can add it in GCconnex

**Comment by LemieuxGen** [comment]
Great, thanks for clarifying @klecuyer
