### ISSUE TITLE
Group Admin Options not working

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1649]
Some of the Group Admin Options are not working;

Limit Owner Block: Does not work - no change on Group home page
Hide the Join Group/Request Membership button:  Does not work - no change on Group home page
Hide Sidebar items:  Does not work - no change on Group home page
Hide Search in Groups:  There is no Search in group

![image](https://user-images.githubusercontent.com/23527358/33726686-bb4a0498-db43-11e7-973d-35503b721b96.png)

Default Sorting Options: Does not work - Selection is saved but folders not sorted according to selection - its displays folders with the default settings

![image](https://user-images.githubusercontent.com/23527358/33726805-12a5c236-db44-11e7-8843-23b09324cc5f.png)

![image](https://user-images.githubusercontent.com/23527358/33726821-2606cf82-db44-11e7-9c50-0918b5ae77f1.png)

**Comment by KevinChagnon** [comment]
https://github.com/Phanoix/gcconnex-help/issues/43

**Comment by Steph4104** [comment]
@KevinChagnon  The default folder sorting option is for file, not folder. Do we want keep it that way and change the language?

**Comment by KevinChagnon** [comment]
As the function is made to sort files and not folders, we will change the language to match the function.

The text should be changed to:

"Default **file** sorting options" for English

"Option de tri de **fichiers** par défaut" for French

Both for the header and title of drop down.
