### ISSUE TITLE
Deactivated user still receiving email notifications for Opportunities he's Opted-in to 

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1652]
User: Scott.Biggin

As a user, I should stop receiving all notifications from GCconnex once my account is deactivated, regardless of my notification settings.

Linked to https://github.com/Phanoix/gcconnex-help/issues/45

This user forwarded me an email received on his deactivated GCconnex account. It is for an Opportunity created that he had opted-in to.
![image](https://user-images.githubusercontent.com/29754185/33781632-65f32dd6-dc23-11e7-907f-0a37eb969cc8.png)

 I can't sign in as a deactivated user, and can't seem to make changes to his notification settings while he is deactivated. I have already reactivated him and had him re-deactivate once. I cannot deactivate him as an admin, only reactivate. Deactivating requires his password and the 'toggle state' button in the admin panel only works to reactivate.

Unchecked Opportunities email notifications:
![image](https://user-images.githubusercontent.com/29754185/33781771-d5ce3330-dc23-11e7-8b6e-da94560c38f1.png)

Get the message that it has been saved, but no changes:
![image](https://user-images.githubusercontent.com/29754185/33781793-eb7db8fe-dc23-11e7-8386-19492f9d45d1.png)

**Comment by pandurx** [comment]
@klecuyer if their account still exist in the system, then logically, they would receive the notifications.

**Comment by klecuyer** [comment]
@pandurx one of the reasons we suggest for deactivating their account is 'I am receiving too many notifications'

**Comment by pandurx** [comment]
@piet0024 how does the deactivation plugin work?

**Comment by piet0024** [comment]
https://github.com/gctools-outilsgc/gcconnex/blob/gcconnex/mod/member_selfdelete/actions/delete.php#L68-L70
		
```
//remove notification 
remove_entity_relationships($user->guid,'cp_subscribed_to_email');
remove_entity_relationships($user->guid,'cp_subscribed_to_site_mail');
```
When a user deactivates I do this. What else would I have to do to remove all notifications?

**Comment by Steph4104** [comment]
Set opportunity platform notification to off when user have a suspend account

**Comment by sabrinatbs** [comment]
![notification emails](https://user-images.githubusercontent.com/35535700/35818402-ddc7b9ec-0a97-11e8-95f4-8621c5935e11.PNG)

Testing this issue, I deactivated my account. Becky helped me by sending messages, adding me as a colleagues and adding me to a group. I received an email notification for all of these. I reactivated my account and none of my "Personal Notifications" are checked. This issue still seems to be occurring @Troy-Lawson

**Comment by Steph4104** [comment]
@sabrinatbs , this issue is related to notification from opportunity platform. I think, your issue is related to #1674

**Comment by pandurx** [comment]
@sabrinatbs  @Steph4104  is this issue still relevant to the main issue description?

**Comment by Steph4104** [comment]
@pandurx , As I say in my previous comment, this issue is about notification from the oportunity platform, the one of @sabrinatbs is related to #1674

**Comment by pandurx** [comment]
okay, i will close this and work on issue #1674 instead
