### ISSUE TITLE
Oops Error when posting to The Wire

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1653]
Posting new content or sharing content on The Wire causes an Oops error:

![image](https://user-images.githubusercontent.com/29754185/33844362-202de4b0-de6e-11e7-8bc7-3a5aa687e954.png)

...BUT the content still posts:
![image](https://user-images.githubusercontent.com/29754185/33844405-3b5bc946-de6e-11e7-8ff0-935d73660026.png)

**Comment by klecuyer** [comment]
Linked to https://github.com/Phanoix/gcconnex-help/issues/46

**Comment by s-duffey** [comment]
Only an issue on Connex and not Collab

**Comment by LemieuxGen** [comment]
@Troy-Lawson Can we assign this to some to look at ASAP?

**Comment by Troy-Lawson** [comment]
@Phanoix and @pandurx, can you take a look and find out what is the issue here. 
Thanks
