### ISSUE TITLE
Allow opting out of empty digest email

### ISSUE THREAD

**Issue by nschonni** [gctools-outilsgc/gcconnex#1672]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."

As a regular user, I do not want to receive the empty notification digest emails every day if my groups happen to be quiet.

## Details on issue or enhancement

I understand you're trying to get people to come back or search for new groups if they've haven't visited in awhile. The currently nightly digest with an empty "It seems it was quiet in your network on ..." message is similar to the login message you see everyday when you log into your work PC. You see that message everyday but ignore it because it doesn't help or act as a call to action when it is done every day.
If opting out isn't an option, I'd suggest tying these messages to a combination that includes an activity period. EX: If I haven't logged in for a month, trying to re-engage might be appreciated, but If I logged on in the current week I probably don't need a reminder.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

/cc @sdkibb @markwooff from out conversation of GCChat

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
