### ISSUE TITLE
Bookmarks sending duplicate notifications (in excess, 15+)

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1678]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."

Multiple users reporting getting excessive duplicate notifications for bookmarks:
https://gcconnex.gc.ca/messages/notifications/Robert.Muma1 (8 notifications)
https://gcconnex.gc.ca/messages/notifications/Anja.Bilandzic (16 notifications) **this user has also recieved 3 duplicate notifications for another bookmark since
https://gcconnex.gc.ca/messages/notifications/Lydia.Bonard (17 notifications)

In 2/3 cases the bookmark has since been deleted, likely because of the excess of notifications. 

## Details on issue or enhancement
None of the bookmarks are from the same group.
None of these users are from the same department

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

@KevinChagnon @LemieuxGen

**Comment by klecuyer** [comment]
https://github.com/Phanoix/gcconnex-help/issues/51

**Comment by KevinChagnon** [comment]
Stacey.ileleji posted a (one) Bookmark Friday Jan 26 which resulted in multiple posts. The 1st instance was around 12:22 pm, the last 12:36 pm.  A total of 7 notifications were sent and reported by user Val.loudfoot

As per user Stacey.ileleji she experience no system errors when creating her post.

![image](https://user-images.githubusercontent.com/23527358/35513950-ab4cbda2-04d2-11e8-9541-64a141b5ddbc.png)

![image](https://user-images.githubusercontent.com/23527358/35513955-b1708510-04d2-11e8-9011-c5032d1fc5b6.png)

![image](https://user-images.githubusercontent.com/23527358/35513960-b9268c64-04d2-11e8-8b02-1b542721a287.png)

![image](https://user-images.githubusercontent.com/23527358/35513970-bf8b37ee-04d2-11e8-8a6f-eb0717f8fb25.png)

![image](https://user-images.githubusercontent.com/23527358/35513976-c4ac4268-04d2-11e8-9f14-2706ba6bb511.png)

**Comment by KevinChagnon** [comment]
This is also happening for events at times.  Can Events also be added to subtype to db duplicate checking ?

Mon 2018-02-12 10:05 AM - "(User) Theriaultc posted a new event entitled Equipping Managers for a Culture of Change"

This was sent out a few time and received by Eric.fleck

**Comment by pandurx** [comment]
@Phanoix 
i may be wrong, but didn't you already added bookmarks and events to the database?

**Comment by pandurx** [comment]
Related to Issue #1414
