### ISSUE TITLE
Remove 'Make Translator' ability for admins

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1679]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."

As an admin, I can easily accidentally click 'Make translator' when editing user settings. Can we remove this option if it does not serve a purpose?

## Details on issue or enhancement

![image](https://user-images.githubusercontent.com/29754185/35156135-de9a9170-fcfd-11e7-9578-43763f63df4b.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by bmrgould** [comment]
I don't know if it has a purpose, but to get rid of it:

gccollab/mod/translation_editor/classes/ColdTrick/TranslationEditor/UserHoverMenu.php

On Line 24 add - `return $return; //remove this if you want Make/Remove Translator in hover menu`

That file adds the Translator option to the hover menu, so just return before it reaches the part where it adds it. Putting the fix here means it goes into the file without needing to, but it's a one line fix that can easily be removed.

Works on my local gcconnex 
![gcc_remove_translator](https://user-images.githubusercontent.com/34379222/35939429-1c5e3f72-0c1a-11e8-9c73-0913b4e988a5.PNG)


Ill make a branch/pull but someone will have to review and decide if it has a purpose.

_________

Is removing it the best option? If you misclick it while going to "login as" on users, the new misclick may be "make admin" which is worse.

**Comment by markwooff** [comment]
@klecuyer looks like Brandon found a quick fix for this 👍 are there any use cases for this menu item? Just wondering if we can go ahead and remove it without breaking something else.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
