### ISSUE TITLE
Missing button on Departmental News feed: Create a Wire post

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1680]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a regular user, I need to be able to create a new wire post message directly from the Wire widget of my departmental News feed page so that I don't need to change pages and waste valuable time. 

## Details on issue or enhancement
Following the release of new departmental tab on the GCconnex News feed, the Wire widget on the departmental News feed page does not include the button to "Create a Wire post". Please add button the the Wire Widget. 

**News feed page - My groups and colleagues**
![create a wire post button my newsvfeed](https://user-images.githubusercontent.com/15378977/35163291-3600ec64-fd14-11e7-8c2f-c0da2ccb8d95.PNG)

**News feed page - department**
![create a wire post button dept news feed](https://user-images.githubusercontent.com/15378977/35163289-35a77788-fd14-11e7-96b9-80829e5b0c0e.PNG)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by LemieuxGen** [comment]
@piet0024 as discussed, I created a ticket for adding the "Create a Wire Post" button on the departmental News feed, as mentioned by @ToferC on the Wire.
![create a wire post button dept news feed _wire message ca](https://user-images.githubusercontent.com/15378977/35163528-14c8d826-fd15-11e7-9e6c-d3cec344efb6.PNG)

**Comment by piet0024** [comment]
I have added the button with PR #1677
