### ISSUE TITLE
Add mp3 and .mid file formats to GCconnex for Elgg migration

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1687]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
Linked to https://github.com/Phanoix/gcconnex-help/issues/54

As part of Global Affairs Canada pilot to migrate our Elgg instance to GCconnex, we need to upload .mp3 **and** .MID files. Grateful if you could add this extension to your list of allowed files as soon as possible so that we can proceed with file transfer in the group: https://gcconnex.gc.ca/groups/profile/34520708/englobal-affairs-canada-choir-without-bordersfrchorale-sans-frontiu00e8res-daffaires-mondiales-Canada

## Details on issue or enhancement

Add file format: mp3 and .MID

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by klecuyer** [comment]
@LemieuxGen this is requested by Georgina Collins. I remember she's met with Charles and we're supporting her in migrating Global Affairs Elgg instance to GCconnex. Is there any way we can add this filetype before February 1st? I think it's a simple add in the admin panel. @cdegrass @Phanoix @KevinChagnon

**Comment by LemieuxGen** [comment]
Yes, we should do what we can to support GAC's migration of Agora on GCconnex. If there are no issue on the technical side, we should look at adding the file type. Did they mention how they use mp3 on their site?  It would be useful to know. thanks.

**Comment by KevinChagnon** [comment]
https://github.com/Phanoix/gcconnex-help/issues/54

**Comment by klecuyer** [comment]
Added .mid files also, if possible. The group, Choir Without Borders, publishes lyrics and small original MP3s, like the attached, so that the members of the Global Affairs Choir can practice the songs for performances.  The director records the different voice tones and then people can download them for practice.

**Comment by LemieuxGen** [comment]
@Troy-Lawson Can we look at adding these file types within this current sprint (if there are no technical issues in doing so)? This is in support of GAC migrating Agora to GCconnex. There official launch is tomorrow, Feb 1, 2018. Thanks!
