### ISSUE TITLE
Remove ability to enter HTML in Wire post

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1689]
As a site admin (and regular user), I need the ability for users to enter HTML code in Wire posts removed / have HTML stripped from created content so that site members are not able to force pop-ups/redirects/post extra large images ect.

This is also an issue on GCcollab.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [x] Issue closed

**Comment by KevinChagnon** [comment]
@LemieuxGen @ToferC

@smellems did various tests today confirming that various things can be done using HTML in the wire such as those mentioned above.

**Comment by ToferC** [comment]
Thanks. Approved to strip html.

**Comment by bmrgould** [comment]
Added strip tags for adding to the wire. Live on GCCollab. Merged on GCConnex github.
