### ISSUE TITLE
Closed Groupsstill visible to non-members should still be searchable

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1696]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user searching for groups, if a group is closed, but visible to non-members, it should appear in searches. Remove noindex tag from closed groups that are not 'invisible'.

Solution: remove following meta tag from group pages:
<meta name="robots" content="noindex, follow">

## Details on issue or enhancement

This is what the group settings appear as in the scenario described above:

![image](https://user-images.githubusercontent.com/29754185/35522115-85b57eb4-04e9-11e8-9e3a-c8e73d40d8db.png)

## For the development team
- [x] Issue user story documented
- [x] UX input received
- [x] Design completed
- [x] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by klecuyer** [comment]
@pandurx

**Comment by pandurx** [comment]
see referenced pull request for more information

**Comment by pandurx** [comment]
@klecuyer @4rsood  as discussed, we are looking into this issue. the robot meta tag for noindex has been removed, the gsa should be able to pick up the group profile page

**Comment by klecuyer** [comment]
@pandurx @4rsood thank you. Please keep me posted so I can inform the user.

**Comment by pandurx** [comment]
@klecuyer
@4rsood  has restarted the crawl for all the groups, with the new patch that was implemented on Monday. Confirmed that the group RCMP Policy Community now shows up in the results.
