### ISSUE TITLE
Username with "@" causing issue (e.g. referencing)

### ISSUE THREAD

**Issue by gabrielcossette** [gctools-outilsgc/gcconnex#1700]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."

I wanted to reference someone using "@..." in a reply

## Details on issue or enhancement

I tried to reference a GCconnex user using "@..." in a post reply. However, it didn't work because the username had an "@" in it. Here's an example: https://gcconnex.gc.ca/profile/greg.linton@ec.gc.ca

Trying to reference this user in a post using "@greg.linton@ec.gc.ca" doesn't work.

Maybe we shouldn't allow users to have an "@" in their username in the first place ;)

Thanks!

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by LemieuxGen** [comment]
@KevinChagnon Can you reach the user (Greg Linton) to change his username?

**Comment by KevinChagnon** [comment]
Will do today

**Comment by KevinChagnon** [comment]
Contacted user to propose change of username

**Comment by KevinChagnon** [comment]
User agreed to change username.
Request submitted to @pandurx to modify username

**Comment by KevinChagnon** [comment]
Username has been updated to **greg.linton**
https://gcconnex.gc.ca/profile/greg.linton
