### ISSUE TITLE
Opportunities Platform search results are not showing all entries

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#1707]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user looking for an opportunity, and as a business owner monitoring the OP, I need to be able to see all entries (still active opportunities) available when searching for opportunities, so that I can see all the opportunities available without being limited to only approx 100 results regardless.

## Details on issue or enhancement
Even with the results count increased, the search results are not all showing up.
I asked Ryan Lacroix to pull up the stats for the OP, and there's definitively an issue. the number of active opportunities is 1456, but only 100 show up in the search results.
See attached file with export of the posted opportunities.
Can someone have a look at what's going on here?
[elggentities_opp.xlsx](https://github.com/gctools-outilsgc/gcconnex/files/1690757/elggentities_opp.xlsx)

this ticket is linked to: https://github.com/gctools-outilsgc/gcconnex/issues/1303. As requested, I'm splitting up the issue in 2 tickets. 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by LemieuxGen** [comment]
Please see Ryan Lacroix for more info, if needed. He did a lot of testing. Thanks!

**Comment by LemieuxGen** [comment]
@Eldoraaoun FYI

**Comment by Phanoix** [comment]
Should be fixed now with some config changes on prod.
