### ISSUE TITLE
Uploading zip or multiple files gives 500 error

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1708]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
When uploading zip or multiple files, the user reports getting a 500 error. The files are still uploaded but the 500 error occurs regardless.

## Details on issue or enhancement
Linked to https://github.com/Phanoix/gcconnex-help/issues/58

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by pandurx** [comment]
This should have been resolved since the weekend push.
