### ISSUE TITLE
User unable to unsubscribe to notifications for Opportunities

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1714]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user, I need to be able to opt-in to Opportunities on the Opportunities Platform, but don't necessarily want to be notified for every Opportunity posted matching my settings.

I have to opt-in to see what's posted in the Opportunities Platform, but I can't unsubscribe myself from receiving the emails.

## Details on issue or enhancement

User's notification settings: https://gcconnex.gc.ca/settings/notifications/Gemma.Mattioli

I deselect the Email tab for these notifications:

![image](https://user-images.githubusercontent.com/29754185/35938360-d4fd7af6-0c16-11e8-9adc-16b837367234.png)

Click Save.
![image](https://user-images.githubusercontent.com/29754185/35938379-e47359b0-0c16-11e8-8d66-420e86f64004.png)

And the box is checked again and I continue to receive emails I do not want.
![image](https://user-images.githubusercontent.com/29754185/35938408-febc3f94-0c16-11e8-9420-2b5cefd42a44.png)

The only solution for now is to opt-out of Opportunities but then I can't browse. As a user, I want to opt-in but be able to choose how I'm notified, if at all.

@KevinChagnon  @LemieuxGen 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by klecuyer** [comment]
https://support.gctools-outilsgc.ca/helpdesk/tickets/2074

**Comment by klecuyer** [comment]
Update: this is not specific to Opportunities, but any group subscription.

I have unchecked these 4 boxes:
![image](https://user-images.githubusercontent.com/29754185/35990578-73c6cbcc-0cd2-11e8-8ad7-9340adfea783.png)

Click Save. Get a confirmation. And they aren't unsubscribed.
![image](https://user-images.githubusercontent.com/29754185/35990633-a5088860-0cd2-11e8-9965-dfe4af35374d.png)

Note: I can unsubscribe from group content (forums) but not from the group itself.

If I go into the backend, the subscriptions are still there:
![image](https://user-images.githubusercontent.com/29754185/35990692-d8e5a2c6-0cd2-11e8-98af-93923e53de3b.png)

**Comment by klecuyer** [comment]
This is also present on GCcollab. Tested on this profile: https://gccollab.ca/settings/notifications/Jean.Murray

**Comment by Steph4104** [comment]
For Gemma.Mattioli, I uncheck the notify me when a new oppotunity... and after I save, it was still uncheck. 

For Jean.Philippe.Bouchard1, when I look at his notification setting, everything was uncheck.

@klecuyer can you double check with the user if it still an issue?
I try to replicate the issue on my local, preprod and prod, and I was not able.

**Comment by klecuyer** [comment]
@Steph4104 I was able to opt-in Gemma to the Opportunities Platform but keep her unsubscribed from the emails.
If I try to test this on my own profile, I still have the same error: https://gcconnex.gc.ca/settings/notifications/Krista.Lecuyer

Start:
![image](https://user-images.githubusercontent.com/29754185/37047022-d282e820-2137-11e8-92db-969029da882c.png)
Change:
![image](https://user-images.githubusercontent.com/29754185/37047045-dd5bc3b6-2137-11e8-8a00-85da28c16fad.png)
Save:
![image](https://user-images.githubusercontent.com/29754185/37047069-ebb27a0e-2137-11e8-8f3a-bdb6b8be9dee.png)
Even after refreshing the page, my preferences haven't changed. Is there a delay perhaps?
I also tested this on the GCcollab profile mentioned above and still cannot unsubscribe: https://gccollab.ca/settings/notifications/Jean.Murray

**Comment by Steph4104** [comment]
@klecuyer , I just log in as you on GCconnex, and I unchecked some checkbox and it save without problem. So I'm not sure if it's about a server problem and it's happening some time or not.

Can you test this again with your account?

**Comment by klecuyer** [comment]
@Steph4104 still the same as the screenshots above. Let me know if you need me to test something else

**Comment by Steph4104** [comment]
@klecuyer , hum... can you try to log as me (stephanie.lefebvre) and see if you can change my access?

Cause, I have no problem to change your access or mine.

**Comment by klecuyer** [comment]
@Steph4104 it worked for me logged in as you, but not as an admin trying to make the changes

**Comment by klecuyer** [comment]
@Steph4104 also works for me on my own profile logged in as me, just not if I'm an admin trying to save changes
