### ISSUE TITLE
Changes to Opportunities Platform Email Notification

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1715]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user, I get confused when **all** Opportunities are titled as a 'micromission' in the email notification I receive. The title doesn't make sense in French either: "New Opportunities Platform"

In the below example, this is an opportunity for an assignment/secondment. Regardless of the opportunity type, the email labels it as a micromission.

![image](https://user-images.githubusercontent.com/29754185/35938731-106905dc-0c18-11e8-8ef8-0a8000115f13.png)

## Details on issue or enhancement

@LemieuxGen From a user experience perspective, ideally it would be nice to have the type of Opportunity in the email subject line and title.

As a quick fix, we could change the word micromission to Opportunity. In French, "Nouvelle notification d'opportunité"? @KevinChagnon thoughts?

If the details of these Opportunity notifications are already addressed in another ticket, please reference that ticket here and close this issue.

## For the development team
- [x] Issue user story documented
- [x] UX input received
- [x] Design completed
- [x] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by KevinChagnon** [comment]
@LemieuxGen  I would go with "Notification d'une nouvelle opportunité"

Also, the text in the French portion of the notification says "_Username_ a ajouté un nouveau intitulé ..." followed by the title of the post.  It should read "_Username_ a affiché une nouvelle opportunité intitulé ..."

**Comment by LemieuxGen** [comment]
The text is confusion. I don't think we need to say in the subject that this is a notification. To be consistent with the other notifications, the title should read:
EN: A new opportunity was posted on the Opportunities Platform 
FR: Une nouvelle possibilité a été affichée sur la Plateforme de possibilités

French body text should be corrected to say:
USER a affiché une nouvelle possibilité intitulée LINK TO OPPORTUNITY

**Comment by Troy-Lawson** [comment]
I created a pull request with the subject line change, but changing the body is another matter as that follows a template for all notifications not specific emails for each type of notification

**Comment by LemieuxGen** [comment]
@Troy-Lawson The body text in French doesn't make any sense as is. How can we get it modified?

**Comment by LemieuxGen** [comment]
@Troy-Lawson I see this is closed now. Were you able to make any changes to the body text?

**Comment by KevinChagnon** [comment]
I can see from a notification received today that the body has not yet been modified;
![image](https://user-images.githubusercontent.com/23527358/36979992-19afe70c-2057-11e8-9bd0-3621d4b8135d.png)

**Comment by LemieuxGen** [comment]
@Troy-Lawson We still need to fix the French body text. As per above comment, the French body text should be corrected to say:
USER a affiché une nouvelle possibilité intitulée LINK TO OPPORTUNITY

**Comment by KevinChagnon** [comment]
This is still an outstanding issue (missing some French language); do we have room to work on this during this sprint?
![image](https://user-images.githubusercontent.com/23527358/39538282-4b23dd8a-4e0a-11e8-8aba-c4290398a627.png)
 @LemieuxGen  @Troy-Lawson

**Comment by nschonni** [comment]
Related more to the Digest version, but https://github.com/gctools-outilsgc/gcconnex/issues/1744

**Comment by pandurx** [comment]
The body now displays 
![image](https://user-images.githubusercontent.com/5798645/39705417-59eaea22-51dc-11e8-8ba5-e2c7a4adbba2.png)
