### ISSUE TITLE
Personalized message not being added to group invitation

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1726]
As a group owner, I need my personalized message to be included in my group invitation (by email) so that I can deliver a specific message to potential group members.

Currently, the personalized message is not included in my invitation email.

![image](https://user-images.githubusercontent.com/23527358/36392565-de0e1062-1579-11e8-8a2c-96c214b2eb7f.png)

Included message was "JOIN JOIN JOIN"

NOTE: Issue also present in GCcollab

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by KevinChagnon** [comment]
https://github.com/Phanoix/gcconnex-help/issues/61

**Comment by klecuyer** [comment]
This is specific to inviting through a group. In GCcollab, if you invite using the egneric Invite button in the header, the personalized message is included. In group invitations on both collab and connex, personalized messages are not included.

**Comment by klecuyer** [comment]
This is also specific to inviting a user by email. If I invite a user using Find User it includes the personal message
