### ISSUE TITLE
Landing on user's profile gives Geocode error

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1731]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
Landing on this user's profile (for her as a logged in user or me as an admin) gives the following error message: Geocode was not successful for the following reason: ZERO_RESULTS

![image](https://user-images.githubusercontent.com/29754185/36563540-6da4de84-17e8-11e8-8d92-7b4a75f2a64e.png)

## Details on issue or enhancement
Link: https://gcconnex.gc.ca/profile/lori.bilecki1

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by klecuyer** [comment]
@smellems just looking at this, do you have any idea what this Geocode error is?

**Comment by klecuyer** [comment]
This was due to her account being synced with GCdirectory and it not pulling up her correct location on a map. I did a quick fix by unsyncing her account, but the map feature/sync doesn't seem to work.

**Comment by klecuyer** [comment]
Same error: https://gcconnex.gc.ca/profile/Michel.charron?language=en

Unsyncing from GCdirectory resolves this issue

**Comment by marc-donofrio** [comment]
No longer an issue.
