### ISSUE TITLE
Fatal error in exception handler

### ISSUE THREAD

**Issue by rleir** [gctools-outilsgc/gcconnex#1745]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
Sorry, I broke something again. 
"Fatal error in exception handler. Check log for Exception at time 1520015630"

![image](https://user-images.githubusercontent.com/2079763/36923064-1276283c-1e38-11e8-9743-66cb6416986f.png)

## Details on issue or enhancement
I was on my profile page, then left it open while I worked on other tabs. When I returned to this tab this error occurred.
Chrome on Windows 7, in the Statcan network (accessing the web via the Stcweb proxy)
There was a similar problem a few months ago.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by rleir** [comment]
Related to #904 
Would someone be so kind to look in the logs please and tell me the messages? Then I can look into my gcconnex home installation and maybe suss this out.
thanks
Rick

**Comment by marc-donofrio** [comment]
No longer an issue.
