### ISSUE TITLE
Changes to GCconnex Registration Page

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1746]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user, I need to know the best way to get user help. Currently we're directing them to the GCconnex email inbox, then about a day later myself or Kevin creates a ticket in Freshdesk for this, creating a lot of redundancy and longer wait for the user. 

We'll need to update these with simple instructions on how to request a reset password and where to submit a ticket.
![image](https://user-images.githubusercontent.com/29754185/36981543-6e6670dc-205b-11e8-95dc-3815cf7259fd.png)

## Details on issue or enhancement
https://gcconnex.gc.ca/register

## For the development team
- [x] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by klecuyer** [comment]
Also, as soon as the user emails this inbox, they get an auto-reply that this email inbox is no longer in service and asks them to submit a ticket. Generally confusing for the user and a lot of redirects.

My suggestion is a quick explanation that GCconnex accounts must be registered to a GoC email address, a link to the forgot password page, and a link to where they can submit a ticket.

@LemieuxGen

**Comment by Troy-Lawson** [comment]
@klecuyer @LemieuxGen let me know as soon as the language is decided upon and i will implement
Thanks!

**Comment by LemieuxGen** [comment]
@Troy-Lawson  - @klecuyer has the text ready in English and will share it with you as soon as we have it back from translation. thanks!

**Comment by klecuyer** [comment]
@Troy-Lawson just emailed you the text. Thanks!

**Comment by Troy-Lawson** [comment]
Thank you @klecuyer!

**Comment by klecuyer** [comment]
French registration text is still old text. Not sure if it was never changed, or somehow reverted back after an update.
![image](https://user-images.githubusercontent.com/29754185/41786400-629ccd10-7613-11e8-87d1-98cb9151d6e3.png)

The text was sent in an email on March 9th, 2018. @Troy-Lawson I can resend if needed.

@LemieuxGen

**Comment by LemieuxGen** [comment]
@klecuyer Can you add the updated text here?

**Comment by klecuyer** [comment]
@LemieuxGen 

1.	Votre compte GCconnex doit être lié à une **adresse de courriel valide du gouvernement du Canada** se terminant par gc.ca ou Canada.ca. 
2.	Vous devez **valider** votre nouveau compte avant de pouvoir ouvrir une séance pour la première fois. Un courriel de validation sera envoyé à votre adresse de courriel. Cliquez sur le lien figurant dans le courriel (ou copiez-collez-le dans votre navigateur) pour valider votre compte. Si vous ne recevez pas de courriel de validation, soumettez un billet au [bureau d’aide](https://gcconnex.gc.ca/help/knowledgebase). 
(Remarque : Il faudra peut-être plusieurs minutes avant que vous receviez le courriel de validation en raison de votre pare-feu ministériel. Assurez-vous de vérifier votre dossier de pourriels.) 
3.	**Vous avez déjà un compte?** [Demandez la réinitialisation du mot de passe.](https://gcconnex.gc.ca/forgotpassword) Si vous ne recevez pas le courriel de réinitialisation du mot de passe, soumettez un billet au [bureau d’aide](https://gcconnex.gc.ca/help/knowledgebase). 
(Remarque : Il faudra peut-être plusieurs minutes avant que vous receviez le courriel de mot de passe oublié en raison de votre pare-feu ministériel. Assurez-vous de vérifier votre dossier de pourriels.)
4.	**Vous avez changé de ministère ou d’adresse de courriel? Pas besoin de créer un nouveau compte.** Veuillez soumettre un billet au [bureau d’aide](https://gcconnex.gc.ca/help/knowledgebase). Nous apporterons les changements nécessaires à votre compte existant et nous vous aiderons à y accéder de nouveau. Assurez-vous d’inclure votre ancienne adresse de courriel ainsi que la nouvelle.
5.	**Vous éprouvez encore de la difficulté à créer un compte?** Soumettez un billet au [bureau d’aide](https://gcconnex.gc.ca/help/knowledgebase), et nous nous ferons un plaisir de vous aider.

**Comment by piet0024** [comment]
The language is in master, and works on my dev instance. It may be a plugin order issue, or the site caches may need to be flushed.

**Comment by Troy-Lawson** [comment]
This is fixed once again. The issue was the translation editor was overriding the language file. closing this issue
