### ISSUE TITLE
GCconnex and GCcollab Language File Change – “Jobs Marketplace” or “Opportunities Platform” to “Career Marketplace” 

### ISSUE THREAD

**Issue by Eldoraaoun** [gctools-outilsgc/gcconnex#1763]
### We are changing the name of the **Jobs Marketplace/Opportunities Platform** to **Career Marketplace**. 

**Deadline - April 9th, 2018**

_Request:_ Change language file **Jobs Marketplace** (FRA: Carrefour d'emploi) and **Opportunities Platform** (FRA: Platforme de possibilité) to **Career Marketplace** (FRA: Carrefour de carrière) on GCconnex and GCcollab, for the following pages: 

### GCconnex

- In the main grey navigation bar, drop down menu > Careers > 
o	Where it currently reads **Jobs Marketplace**, change to: **Career Marketplace Group** (in FRA: **Carrefour de carrière group**) _Note that links stays the same_.
o	Also, where it currently reads **Opportunities Platform**, change to:  **Career Marketplace** (in FRA: **Carrefour de carrière**) _Note that links stays the same_.

- When users are on the Opportunities Platform main page, there is a button asking users to "Opt in to Opportunities" > Once the button is clicked, a pop-up box appears. In the pop-up box, change button/ language file, **Continue to Opportunities Platform**, to **Continue to the Career Marketplace** (in FRA: **Continuer vers le Carrefour de carrière**)

- From the Opportunities Platform main page, the following sub-pages need language file changes > anywhere it reads J**obs Marketplace/Opportunities Platform** change to **Career Marketplace** (FRA: **Carrefour de carrière**)
o	Search opportunities page: https://gcconnex.gc.ca/missions/main/find 
o	Find members page: https://gcconnex.gc.ca/missions/main/members 
o	My opportunities page: https://gcconnex.gc.ca/missions/main/mine 
o	Archive page: https://gcconnex.gc.ca/missions/main/archive 
o	Analytics page: https://gcconnex.gc.ca/missions/main/analytics 

- After creating an opportunity on the Opportunities Platform, the system generates a list of potential candidates. Next to users who have _not_ opted-in to the platform, there is an “**Invite to opt in to Career ConneXions Opportunities**” button. Change language file/button to “**Invite to opt in to the Career Marketplace**” (in FRA: Inviter à s’inscrire au Carrefour de carrière)

- In user profile (only available on the ENG interface) there is a box that says “**Completed Career ConneXions Opportunities**” – change language file to “**Completed Career Marketplace Opportunities**” 

- In Fresh Desk, any mention of the **Jobs Marketplace** or **Opportunities Platform** should be changed to **Career Marketplace** (in FRA: **Carrefour de carrière**)

### GCcollab 

- Main grey navigation bar, drop down menu > Careers > 
o	Where it currently says **Jobs Marketplace**, change to : **Career Marketplace Group** (in FRA: **Carrefour de carrière group**) _Note that links stays the same._
o	Also, where it currently says **Opportunities Platform**, change to :  **Career Marketplace** (FRA: **Carrefour de carrière**) _Note that links stays the same_.

- When users are on the Opportunities Platform main page, there is a button asking users to "Opt in to Opportunities" > Once the button is clicked, a pop-up box appears. In the pop-up box, change button/ language file, **Continue to Opportunities Platform**, to **Continue to the Career Marketplace** (in FRA: **Continuer vers le Carrefour de carrière**)

- From the Opportunities Platform main page, the following subpages need language file changes  > anywhere it reads **Jobs Marketplace/Opportunities Platform** change to **Career Marketplace** (FRA: **Carrefour de carrière**)
o	[Search opportunities page](https://gcconnex.gc.ca/missions/main/find )
o	[Find members page ](https://gcconnex.gc.ca/missions/main/members) 
o	[My opportunities page](https://gcconnex.gc.ca/missions/main/mine) 
o	[Archive page](https://gcconnex.gc.ca/missions/main/archive )
o	[Analytics page ](https://gcconnex.gc.ca/missions/main/analytics )

- After creating an opportunity on the Opportunities Platform, the system generates a list of potential candidates. Next to users who have _not_ opted-in to the platform, there is an “**Invite to opt in to Career ConneXions Opportunities**” button. Change language file/button to “**Invite to opt in to the Career Marketplace**” (in FRA: Inviter à s’inscrire aux Carrefour de carrière)

**Note:** If you notice anywhere else on either GCconnex or GCcollab where the words **Jobs Marketplace** (FRA: Carrefour d’emploi) and **Opportunities Platform** (FRA: Platforme de possibilité) appear beyond the pages listed above, please feel free to change language file to **Career Marketplace** (FRA: Carrefour de carrière). 

Thank you!!

**Comment by Troy-Lawson** [comment]
@klecuyer @LemieuxGen in the main site navigation under the career drop down we have both jobs marketplace and opportunities platform listed. Wont it be even more confusing than it already is if they both say Career Marketplace?

**Comment by Eldoraaoun** [comment]
@Troy-Lawson In the Career drop down menu, where it currently reads Jobs Marketplace, change to "Career Marketplace **Group**" (in FRA: Carrefour de carrière group) _Note that links stays the same._ This link will drive users to our GCconnex and Gccollab group for the Career Marketplace, where they can find more information and guidance material. It will function as an information resource. The button below it will (only) be called Career Marketplace, and will link users to the actual platform/tool.

**Comment by LemieuxGen** [comment]
@Eldoraaoun thanks for clarifying the links for the menu. 
Also, the launch date is April 3rd, correct?

**Comment by Eldoraaoun** [comment]
@LemieuxGen Yes, April 3rd!

**Comment by Troy-Lawson** [comment]
@Eldoraaoun @LemieuxGen I understand that there is a lot of user confusion about the career drop down. Users aren't sure if they should be using the jobs marketplace or opportunity platform links in the drop down menu and what each one if for. I worry that if we name one career marketplace, and the other career marketplace group its only going to increase confusion around our users. We are trying to design things with a user first approach and I have to ask if this drop down will be less confusing for users or make the career marketplace easier to use and navigate. I would instead propose that we get rid of the drop down list entirely, and place the links to the group and the external jobs site within the front page of the career marketplace itself. Consider from a perspective of a user that has never been on the site before, will they know what the career marketplace group is for? Will they know which one to click to find a new job?

**Comment by Eldoraaoun** [comment]
@Troy-Lawson @LemieuxGen Totally agree with where you're coming from. However, the Career Marketplace is a completely separate tool from GCjobs, so having the GCJobs link within the Career Marketplace front page would be odd. With that being said, perhaps we can keep the Career drop down menu with only the GCJobs and Career Marketplace links, and remove the group. Instead, we can have just the group linked onto the main page of the Career Marketplace, with a message saying "Join the Career Marketplace Group for updates, guidelines and tutorials!". Thinking in a user perspective, it makes sense having only career tools in the Career drop-down menu - we can remove the group and promote it on the actual platform. Thoughts?

**Comment by LemieuxGen** [comment]
Thanks @Troy-Lawson for the comment - you're right that the group link should not be in the drop down. 
@Eldoraaoun yes! I agree. I was going to suggest the same thing. So the menu would include only jobs.gc.ca and Career Marketplace. 
Can you confirm the text you want to use on the Career Marketplace main page (https://gcconnex.gc.ca/missions/main) in both languages? I assume you'll be include that int he main paragraph that appears at the top of the page?

**Comment by Eldoraaoun** [comment]
@LemieuxGen @Troy-Lawson 

Additional text to Career Marketplace main page:
**Join our group** 
Join the [Career Marketplace group](https://gcconnex.gc.ca/groups/profile/7617072) for guidelines, definitions, tutorials and updates!

**Joignez-vous au groupe**
Joignez le groupe du [Carrefour de carrière](https://gcconnex.gc.ca/groups/profile/7617072) pour avoir accès aux lignes directrices, définitions, tutoriels et mises à jour!

Note: Add new text between the **Welcome to the Career Marketplace** message and **Get started by opting in** text (on the main page https://gcconnex.gc.ca/missions/main )

**Comment by LemieuxGen** [comment]
@Troy-Lawson Can you let me know once this is on preprod and ready to review? and please let me know if you need any other info to finalize this. thanks!

**Comment by LemieuxGen** [comment]
@Troy-Lawson New deadline is adjusted to match the extended sprint. This issue to be completed by April 9th.

**Comment by Eldoraaoun** [comment]
Hi all, noticed two small inconsistencies. On GCcollab, the Career Marketplace interface, in the dialogue box, can we add a line break before the sentence 'Join the Career Marketplace group.." (similar to how it appears on GCconnex). Also, in the [Help/Contact Us page](https://gccollab.ca/help/knowledgebase) on GCcollab, under the **GCcollab - Help Content** section, the last tab/hyperlink writes"Opportunities Platform" instead of "Career Marketplace" - note that in the FRA interface, the hyperlink/tab isn't there...

**Comment by markwooff** [comment]
Hi @Eldoraaoun - I've just made the change on the Career Marketplace main page for GCcollab so that there's a break before the last sentence.

The Help page on GCcollab is an embedded version of our FreshDesk help page so we'll need to edit the content within FreshDesk to reflect these changes. Could you help with this @klecuyer @LemieuxGen ?

**Comment by klecuyer** [comment]
@markwooff I looked into this and the folder is empty. Once an article is created in both EN/FR the folder will be also visible in French. I suspect Marianne has been making changes to the Help Content for Career Marketplace in GCcollab. @LemieuxGen thoughts?

**Comment by LemieuxGen** [comment]
@klecuyer As discussed yesterday, we don't currently have content for the Career Marketplace on GCcollab. We'll need to work with OCHRO to take the content we have for GCconnex and modify it for GCcollab. @Eldoraaoun Krista and @marianneaubrey15 will be in touch to coordinate. Thanks!
