### ISSUE TITLE
WIKI: Case sensitive email allows users to create multiple accounts

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/gcconnex#1786]
## Details on issue or enhancement
When registering onto the wiki, the email section is case sensitive. It allows you to register multiple times using the same email but changing letters (Uppercase or lowercase). It creates a new account in the account services but just updates the users information on collab. Uses same username.

Example: If you registers using this email: testing@gmail.com with name: Sabrina Rowland-Cote , and then register again using this email with the uppercase T: Testing@gmail.com and name Sabrina Testing, it would create a new account in account services and just change the name from Sabrina Rowland-Cote to Sabrina Testing. 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by markwooff** [comment]
This issue has also been fixed and is live on production. Thanks!
