### ISSUE TITLE
WIKI: Page not found after clicking chosen language on GCCollabs initial pannel

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/gcconnex#1787]
## Details on issue or enhancement
After registering the website leads you to GCCollab's lanugage pannel, after clicking chosen language, it leads you to a page not found

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by markwooff** [comment]
This issue should now be fixed and is live on production. Thanks @sabrinatbs
