### ISSUE TITLE
WIKI: New account services does not create usernames following the standard

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/gcconnex#1788]
## Details on issue or enhancement
The old standard format for usernames is Firstname.Lastname, now the usernames are listed as FirstnameLastname without the period. (Shown at the end of the link)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by markwooff** [comment]
Usernames are no longer used in the Account service as a user's email address will be their unique identifier. The standard username formatting will still be applied on GCcollab however.

**Comment by LemieuxGen** [comment]
@marianneaubrey15 for reference when updating the "[How to create an account?](https://support.gctools-outilsgc.ca/solution/articles/2100028324-how-do-i-create-an-account-)" help article.
