### ISSUE TITLE
WIKI: New emails received after trying to reset password after account services breaking it

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/gcconnex#1789]
## Details on issue or enhancement
Issue following issue #1785 .  After the admin broke the account while trying to reset password, user tries to reset password but never receives email for password reset. 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by markwooff** [comment]
Shouldn't be an issue anymore now that admins can change a user's password. Thanks

**Comment by LemieuxGen** [comment]
@KevinChagnon can you confirm if this is still an issue?

**Comment by LemieuxGen** [comment]
@KevinChagnon or @sabrinatbs Could you confirm if this is still an issue? thanks!

**Comment by klecuyer** [comment]
@LemieuxGen we have a manual workaround to reset a user's email if they create a ticket and contact us, but anyone who has not logged into GCcollab since we launched the account service won't be able to get a password reset email. It's a temporary fix but not necessarily sustainable.

**Comment by markwooff** [comment]
Original issue here has been resolved, as well as secondary issue discussed here. Closing!
