### ISSUE TITLE
WIKI: Account breaks but allows you to log on using same email but with different characters

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/gcconnex#1790]
## Details on issue or enhancement
After conducting a few tests the account finally breaks, it will not allow you to log back in using that exact email but it will allow you to log back in using that same email but using different characters (uppercase and lowercase)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by markwooff** [comment]
This has now been fixed and is live on production. Thanks!
