### ISSUE TITLE
WIKI: Remove all other languages except English and French and making language notification "dismiss-able"

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/gcconnex#1791]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user I only want English and French to be the language options. Also, when I have chosen my language I wish the notification would be "dismiss-able" or disappear when clicking elsewhere on the screen. 

## Details on issue or enhancement
Make English and French the only language choices, remove all other languages. Allow for the language change notification to be dismissed, and changing the location of the notification so it is not hiding everything else.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by sabrinatbs** [comment]
![image](https://user-images.githubusercontent.com/35535700/37869540-6eca424a-2f8f-11e8-812d-03a4fd86a9b6.png)

**Comment by sabrinatbs** [comment]
![image](https://user-images.githubusercontent.com/35535700/37869543-841327fc-2f8f-11e8-8d1c-101fdb3ba91d.png)

**Comment by LemieuxGen** [comment]
Closing this issue and transferring in the GCpedia repo, tagging it with GCwiki. 
https://github.com/gctools-outilsgc/gcpedia/issues/89
