### ISSUE TITLE
WIKI: "Statistics" on the sidebar does not lead users to another page

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/gcconnex#1793]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user, I need to be led to statistics when clicking Statistics

## Details on issue or enhancement
When you click "Statistics" in the sidebar the page simply refreshes but does not bring you to another page. 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by markwooff** [comment]
@Phanoix can confirm, but I believe we were going to remove this link from the sidebar for now.

**Comment by LemieuxGen** [comment]
Closing and transferring to the GCpedia repo, tagging it with GCwiki. 
https://github.com/gctools-outilsgc/gcpedia/issues/90
