### ISSUE TITLE
WIKI: French: Content outside of it's box on the Aide page, causing scrolling

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/gcconnex#1794]
## Details on issue or enhancement
On the French help/aide page there is content outside of it's box, it is also causing scrolling.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by sabrinatbs** [comment]
![image](https://user-images.githubusercontent.com/35535700/37869557-b98e5a28-2f8f-11e8-88ac-eb1d9a6ccf0d.png)

**Comment by ethanWallace** [comment]
Has been addressed in pull request #1773 Just waiting for changes to go live.

**Comment by LemieuxGen** [comment]
Thanks @ethanWallace! Will this issue be closed once it's live, or should I close it now?

**Comment by ethanWallace** [comment]
I was going to close it when the code changes go live.

**Comment by LemieuxGen** [comment]
great, thanks!

**Comment by ethanWallace** [comment]
Changes are now live
