### ISSUE TITLE
WIKI: Create splash page for GCCollab Wiki

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/gcconnex#1796]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user, I need a splash page when I get onto the Wiki

## Details on issue or enhancement
A splash page needs to be created for the Wiki, it can be the same one as the GCCollab, where you get the chance to choose English or French

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by LemieuxGen** [comment]
Closing the issue and transferring it to the GCpedia repo, tagging with GCwiki. 
https://github.com/gctools-outilsgc/gcpedia/issues/91
