### ISSUE TITLE
Certain users/content do not appear in search results

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1841]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user, when I search for the exact name of another existing user, I hope that their name would appear in a list of results. 

## Details on issue or enhancement
Currently, a number of users do not appear in search results, although filters are correct and their name is spelled correctly. Below is a list of accounts I was able to find, who do not currently appear in search results.
https://gcconnex.gc.ca/profile/Francisco.Couto?language=en
https://gcconnex.gc.ca/profile/Daryell.Nowlan?language=en
https://gcconnex.gc.ca/profile/Cheryl.Baraniecki?language=en

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by pandurx** [comment]
Rajeev said he included the users listed in the Solr index.

**Comment by klecuyer** [comment]
@4rsood could you manually add this group to to the Solr index, making this group searchable?
Link: https://gcconnex.gc.ca/groups/profile/39784216/e-div-prime-purge-epurge?language=en
Group name (keywords): E Div PRIME Purge (ePurge)

Currently typing in the group name gives 0 results.
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4122

**Comment by klecuyer** [comment]
Another page wants to appear in Search GCTools results and doesn't: CFIA Mobility Information Hub
http://www.gcpedia.gc.ca/wiki/CFIA_Mobility_Information_Hub
![image](https://user-images.githubusercontent.com/29754185/42389246-0eb813cc-8116-11e8-9392-638f8e8c90ab.png)

**Comment by Troy-Lawson** [comment]
related to gccollab gctools-outilsgc/gccollab#336

**Comment by klecuyer** [comment]
@4rsood could you make this group searchable: E Div PRIME Purge (ePurge): https://gcconnex.gc.ca/groups/profile/39784216/e-div-prime-purge-epurge

https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4122

**Comment by klecuyer** [comment]
Ticket: https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5065

@4rsood Question for you: Tagging in GCconnex uses the search function, correct? So this content, he has added some tags yesterday and is wondering why for some of them (NAO Biometrics), some irrelevant content shows up and for another (NAOBiometrics) nothing appears in search results when he clicks the tag: https://gcconnex.gc.ca/file/view/41936719/guide-des-utilisateurs-du-portail-des-crdv-balayage-de-la-numero-de-la-biometrie-su-guide-des-utilisateurs-dun-crdv-dircc-guide-des-utilisateurs-dun-crdv-dircc-pdf?language=en
Is it possible that this was affected by us turning off the search crawler last night and this is why nothing appears in results for the tag 'NAOBiometrics'?

**Comment by 4rsood** [comment]
@klecuyer, I will get back to you soon.  Yes it uses the search function.  it will not appear in search results only if the document was posted yesterday or today.

**Comment by martydonofrio** [comment]
Is it possible to add the following users to the search:
https://gcconnex.gc.ca/profile/Sally.hasan
https://gcconnex.gc.ca/profile/abby.savoie

They don't seem to appear.

**Comment by 4rsood** [comment]
@martydonofrio  The following users are now searchable
https://gcconnex.gc.ca/profile/Sally.hasan
https://gcconnex.gc.ca/profile/abby.savoie

**Comment by klecuyer** [comment]
@4rsood for the ePurge group, it's not a sub-group and it's an open group. Specific group content is only viewable by members, but does this mean that the group itself still can't be searched, even if it's open? https://gcconnex.gc.ca/groups/profile/39784216/e-div-prime-purge-epurge?language=en

**Comment by 4rsood** [comment]
@klecuyer You are right that the group should be searchable.  After further investigating, I am seeing a pattern where the URLs like https://gcconnex.gc.ca/groups/profile/39784216/e-div-prime-purge-epurge?language=en are not being indexed while others like  https://gcconnex.gc.ca/groups/profile/42175343?language=en are being indexed with no problem.  I will speak to the dev team and figure out if the two URL patterns are rendered differently to the Solr web crawler and get back to you.

**Comment by 4rsood** [comment]
The following accounts are now searchable:
https://gcconnex.gc.ca/profile/Francisco.Couto?language=en
https://gcconnex.gc.ca/profile/Daryell.Nowlan?language=en
https://gcconnex.gc.ca/profile/Cheryl.Baraniecki?language=en

**Comment by 4rsood** [comment]
@klecuyer I have opened a ticket for the dev team to investigate a possible bug in gcconnex that is preventing Solr crawler to read some of web pages' contents and therefore, such pages are not searchable.
