### ISSUE TITLE
Remove link to GCconnex Tutorials in GCConnex footer

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1847]
It points to a (now) blank GCPedia page / Tutorials are found in Knowledge base.

![image](https://user-images.githubusercontent.com/23527358/39538069-8559ef54-4e09-11e8-9a16-d703f10f293d.png)

**Comment by Steph4104** [comment]
On the register page, we have a link to Gcconnex tutorial, is it still good? 

This is the link http://www.gcpedia.gc.ca/wiki/Tutorials_on_GC2.0_Tools_/_Tutoriels_sur_les_outils_GC2.0/GCconnex

**Comment by KevinChagnon** [comment]
yes please.
