### ISSUE TITLE
GCconnex does not switch to French in Chrome. 

### ISSUE THREAD

**Issue by marianneaubrey15** [gctools-outilsgc/gcconnex#1850]
## Details on issue or enhancement
GCconnex on Chrome does not switch to French after clicking "Français" in the top bar. Appears to be the case on every page. 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by klecuyer** [comment]
Can confirm the language toggle is not working. Tested in groups and Career Marketplace in both Chrome and IE
@LemieuxGen @KevinChagnon
