### ISSUE TITLE
French language corrections

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#1863]
"Veuillez voir svp à soigner davantage votre français sur votre site et dans vos correspondances ! C'est gênant, honteux et irrespectueux envers les francophones et envers les 2 langues officielles du pays ! Merci !
 
On ne dit jamais en français « Soumettre un billet »  Ce n'est pas un billet de spectacle ou de concours !! C'est une demande, une requête, une question, un commentaire, un point, ...."

(Help/Contact us -> Submit a ticket page)

![image](https://user-images.githubusercontent.com/23527358/40384801-a0f6e040-5dd2-11e8-8f9a-971ae0d1bd34.png)

(Group invitation - missing "e" in word "group" at end of text)

![image](https://user-images.githubusercontent.com/23527358/40384903-ee9f5214-5dd2-11e8-9b5f-f9be02082717.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Steph4104** [comment]
Quelle serait la bonne traduction de ticket?

**Comment by KevinChagnon** [comment]
I would recommend "une requête"

@LemieuxGen - Thoughts?

**Comment by LemieuxGen** [comment]
@KevinChagnon @Steph4104 the tranlsation for ticket is "Billet". It's an approved translation in Termium (http://www.btb.termiumplus.gc.ca). Please keep it "billet". Thanks!
