### ISSUE TITLE
Missing titles (group name, blog titles, author name) both GCconnex and GCcollab

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1881]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
Certain fields are missing titles: group names, profile names and in breadcrumbs.
This was initially reported in GCcollab on IE11 but can confirm this is also happening in GCconnex and on Chrome.

The below example is a **sub-group of a sub-group** missing the parent group's names in the breadcrumbs. There is no way to know what the parent groups are and users cannot join the sub-group until they join each parent group in subsequent order. (GCconnex, Chrome, reporting this one myself) https://gcconnex.gc.ca/groups/profile/12833384/my-gchr-production-clients-clients-de-lenvironment-de-production-de-mes-rhgc?language=en
![image](https://user-images.githubusercontent.com/29754185/42467396-c9972c58-837f-11e8-93b8-6834a85aa728.png)

The below example is missing both the group name and titles on blogs. (Reported on IE11, GCcollab, haven't been able to replicate) https://gccollab.ca/groups/profile/109491/creative-writers
![image](https://user-images.githubusercontent.com/29754185/42467419-dc153172-837f-11e8-9e1d-4aef1cd86f11.png)

Below example is missing user names and the group name. (Reported on IE11, GCcollab, haven't been able to replicate) https://gccollab.ca/groups/profile/904923/ssc-jabber-instant-messaging-video-presence-spc-jabber-messagerie-instantanee-video-presence-riche
![image](https://user-images.githubusercontent.com/29754185/42467534-2ffab622-8380-11e8-9138-b71389b66d59.png)

## Details on issue or enhancement
@bryan-robitaille @LemieuxGen @Troy-Lawson 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by marc-donofrio** [comment]
Language toggle fixes this issue.
