### ISSUE TITLE
Can't add a badge to my avatar

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1889]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user, I want to add a badge to my avatar. I did have this badge on my avatar, then updated the photo, now when I add the badge and save, it doesn't appear.

## Details on issue or enhancement
I'm editing my avatar: https://gcconnex.gc.ca/avatar/edit/Rebecca.Hanssen
I'm a member of the associated group with this badge: https://gcconnex.gc.ca/groups/profile/20934966/centre-of-expertise-on-mental-health-in-the-workplace-centre-dexpertise-pour-la-sante-mentale-en-milieu-de-travail?language=en
After I select this badge from the drop down (JSON showing) and click Create your avatar, the badge is not added to my avatar.
![image](https://user-images.githubusercontent.com/29754185/42898988-b59c45ca-8a92-11e8-9309-190e6edc8953.png)

Freshdesk: https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4361

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
