### ISSUE TITLE
Users getting IP address password resets - didn't request one

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1893]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
Multiple users have reported getting mysterious password reset emails from their IP address, although they didn't request one.
![image](https://user-images.githubusercontent.com/29754185/43221023-91b9e91e-9019-11e8-8b4b-781ba95101f7.png)

Another: Une demande de réinitialisation du mot de passe a été faite à partir de cette adresse IP : 198.103.61.2 Une demande de réinitialisation du mot de passe a été faite pour l'adresse IP: 198.103.61.2 Cliquez sur le lien suivant afin de réinitialiser le mot de passe pour le compte de Lucie : https://gcconnex.gc.ca/changepassword?u=101051&c=hlrrk4nvdvz9

Users: lucie.fortin@tpsgc-pwgsc.gc.ca, monique.campeau@canada.ca

## Details on issue or enhancement
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/3853
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4452

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by marc-donofrio** [comment]
No longer an issue.
