### ISSUE TITLE
Identical text appearing in multiple widgets.

### ISSUE THREAD

**Issue by marianneaubrey15** [gctools-outilsgc/gcconnex#1894]
When clicking on "Ce contenu est aussi disponible en Francais" the text appears in other widgets.

![widgetbug](https://user-images.githubusercontent.com/35609738/43266726-1c94ec64-90ba-11e8-8925-60d51e415e7c.PNG)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4402

**Comment by klecuyer** [comment]
@Steph4104 is this resolved?
