### ISSUE TITLE
Department issue - bad request/AJAX error/verify department

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1895]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
A user reports having frequent trouble accessing GCconnex. She says often on her newsfeed or The Wire she gets the following error.
![image](https://user-images.githubusercontent.com/29754185/43284260-3c6a54c8-90e9-11e8-90d2-a920428abef3.png)

I can see from the URL something about verifying her department. She is with CRA.

When I log in as the user, and click on Canada Revenue Agency filter in my Newsfeed, I get a 500 error:
![image](https://user-images.githubusercontent.com/29754185/43284296-5e5c5874-90e9-11e8-8f76-e905e39e5be8.png)

## Details on issue or enhancement

I suspect this might be department or user-specific. 

User profile: https://gcconnex.gc.ca/profile/andrea.lepiane?language=en

https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4462

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by marc-donofrio** [comment]
No longer an issue.
