### ISSUE TITLE
Help/Documentation: Creating and Editing Tables

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1903]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
@marianneaubrey15 

Freshdesk: https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4001

Tables don't appear by default in GCconnex Pages. It must be edited manually in Source.

Article needed around creating and editing tables for Pages in GCconnex and Docs in GCcollab (if applicable). The table must be coded and cannot be done in the WYSIWYG editor. 

Having this information with a link to external help would help our users who can't understand why the simple editor doesn't work. Some research is needed as to how to code this. 

It has to do with the system that GCconnex is built (WET) on removing these tables from being visible. You can custom code it so that it'll show them but it's less user-friendly than the Word-format and you have to do the changes in the Source. 

![image](https://user-images.githubusercontent.com/29754185/44160206-b86d4c80-a087-11e8-8088-8eeaddbaac97.png)

This is much easier if you have a good understanding of HTML (which I don't) and we don't offer typical coding support, but I'll include the instructions provided by one of our developers in a recent ticket I had about this. I hope it helps.

The relevant part of this  issue has to do with WET styles removing borders from tables... and allowing users to override that (among others).
 
There are a couple things that can be done, first would be to add the table class, another would be to add the border as a css style and for a visible (ex. solid) border
<table … class=”table”  style=”border: 1px solid;”>
 
More options: add table-striped and/or table-hover classes after table (class=”table table-striped table-hover”) to make rows in the table easier to distinguish from one another.

Here is a link to a closed Github ticket where this issue is discussed; it may provide you (other someone more familiar with coding) with additional/valuable information. https://github.com/gctools-outilsgc/gcconnex/issues/365

Seeing as the issue has to do with WET styles, it was not determined to be bug simply how the current system works.

Folder in Freshdesk : Content Management 

## Details on issue or enhancement

References:
https://github.com/gctools-outilsgc/gcconnex/issues/365

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by MGoodberry** [comment]
@LemieuxGen 

Draft in Freshdesk under GCcollab Help Content > Content Management

**Comment by MGoodberry** [comment]
French screenshots taken. Just waiting for translation to publish.
