### ISSUE TITLE
Search filter does not stick after 1st page of results

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1904]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user, I need to filter my search results on GCconnex (GCintranet).

Let's say I want to filter only by groups. This works on the first page, but once I get to the second page of results my filter is lost. If I re-click on the Groups filter I'm brought back to page 1 again as a new session.

## Details on issue or enhancement
First page, successfully filter by groups.
![image](https://user-images.githubusercontent.com/29754185/44413965-a33a6700-a53a-11e8-8df8-f80a45b7d058.png)

Navigate to page 2 of results.
![image](https://user-images.githubusercontent.com/29754185/44413995-b2211980-a53a-11e8-82fd-6fe42b394c27.png)

I've lost my filter.
![image](https://user-images.githubusercontent.com/29754185/44414023-c107cc00-a53a-11e8-9ef1-f517db5a72e3.png)

Filtering by groups on Page 2 brings me back to page 1 and starts a new session, thus the problem repeats itself.

@4rsood 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by klecuyer** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4809

**Comment by 4rsood** [comment]
@klecuyer The search filter issue is resolved now

**Comment by klecuyer** [comment]
@4rsood amazing. Thank you!
