### ISSUE TITLE
Bullets in lists don't display in IE

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1908]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user, I need to be able to read long bulletes lists, which don't currently format in IE. Many departments only have access to IE as a browser and it displays like this:
![image](https://user-images.githubusercontent.com/29754185/44787635-a69aa780-ab65-11e8-9cd3-e410c6ae2382.png)

Instead of this (Chrome):
![image](https://user-images.githubusercontent.com/29754185/44787651-b2866980-ab65-11e8-936a-b69a0974291f.png)

## Details on issue or enhancement
Hoping this might be an easy fix.
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/4900

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
