### ISSUE TITLE
Can't access the admin panel (Legacy tools)

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#1913]
As a help desk officer and admin of GCconnex, I need access to the admin panel to assist users with their issues.

When I click on the Admin button, the page times out:

Step 1:
![image](https://user-images.githubusercontent.com/42844328/45503660-794d1c80-b755-11e8-98b4-d5cf838d86e0.png)
Result:
![image](https://user-images.githubusercontent.com/42844328/45503753-dcd74a00-b755-11e8-9f4c-68344a37743b.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by LemieuxGen** [comment]
This issue has surfaced in the past, and the issue was linked to the widgets on the page that take too long to load. perhaps there'S a way to remove the unnecessary widgets by default...

**Comment by marc-donofrio** [comment]
No longer an issue.
