### ISSUE TITLE
Can't access members page for a group

### ISSUE THREAD

**Issue by martydonofrio** [gctools-outilsgc/gcconnex#1915]
A group owner can't access the members page. I am also not able to access the page:

Groups affected:
https://gcconnex.gc.ca/groups/profile/24271235/cfia-ontario-inclusiveness-and-diversity-committee?language=en **FIXED**
https://gcconnex.gc.ca/groups/profile/38314698/passport-operational-training-coachs-corner?language=en **FIXED**
https://gcconnex.gc.ca/groups/profile/22203269?language=en
https://gcconnex.gc.ca/groups/profile/28754517?language=en
https://gcconnex.gc.ca/groups/profile/20336628/health-canada-dg-planning-sante-canada-dg-planification?language=en **FIXED**
Page 4 of the members list: https://gcconnex.gc.ca/groups/members/24775859#customTable
Page 3: https://gcconnex.gc.ca/groups/profile/39784216/e-div-prime-purge-epurge?language=en **FIXED**

![image](https://user-images.githubusercontent.com/42844328/45754743-71c0c400-bbea-11e8-899f-18df42d6ca7d.png)
Result:
![image](https://user-images.githubusercontent.com/42844328/45754763-81400d00-bbea-11e8-8a13-7289eefe7662.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by martydonofrio** [comment]
Another group is having this issue:
https://gcconnex.gc.ca/groups/profile/24271235/cfia-ontario-inclusiveness-and-diversity-committee?language=en

**Comment by klecuyer** [comment]
Thanks @martydonofrio 

Can you include the links to these 2 Freshdesk tickets also?

**Comment by martydonofrio** [comment]
Tickets:
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5192
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5139

**Comment by martydonofrio** [comment]
Another group: https://gcconnex.gc.ca/groups/profile/22203269?language=en

**Comment by martydonofrio** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5533

**Comment by martydonofrio** [comment]
Page 4 of the members list: https://gcconnex.gc.ca/groups/members/24775859#customTable

**Comment by martydonofrio** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5830

**Comment by martydonofrio** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/6044

**Comment by Steph4104** [comment]
Send information about user with broken account. Those users need to be delete to solve this issue.

**Comment by Steph4104** [comment]
Delete user with unvalided / desactivate broken account.
