### ISSUE TITLE
Emails from GCconnex/GCpedia not being sent

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1921]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
Outgoing emails for GCconnex not being sent for:
- newly registered accounts
- password resets
- group notifications

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by nschonni** [comment]
I didn't see the Digest this morning either from GCConnex (but did for Collab)

**Comment by Troy-Lawson** [comment]
i believe this is fixed
