### ISSUE TITLE
User can't post new work experience

### ISSUE THREAD

**Issue by martydonofrio** [gctools-outilsgc/gcconnex#1928]
As a user posting work experience, I should be able to post more than 13 posts under the Work Experience section.

## Details on issue or enhancement
Here is the error message, no box is highlighted red in the whole section and I could reproduce this issue every time.
![image](https://user-images.githubusercontent.com/42844328/46826282-99c3c300-cd63-11e8-8546-5c841948f176.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by martydonofrio** [comment]
https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/5472

**Comment by Troy-Lawson** [comment]
will not be fixing.
