### ISSUE TITLE
Text error in GCcollab's password reset window.

### ISSUE THREAD

**Issue by martydonofrio** [gctools-outilsgc/gcconnex#1940]
As a user, when I reset my password, the message saying the email is sent is worded in a confusing way.

The text in the message states that the email will be sent when the password is registered:
![image](https://user-images.githubusercontent.com/42844328/48788452-d961c100-ecb8-11e8-8d06-a113e5612b75.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by martydonofrio** [comment]
Suggested text to be approved and translated: 

You will receive an email with a link to set a new password in the next 20 minutes. Please check your junk folder.

**Comment by MGoodberry** [comment]
French translation: Au sein de 20 minutes, vous allez recevoir un courriel avec un lien pour créer un nouveau mot de passe. Veuillez vérifier votre dossier de courrier indésirable.

**Comment by Steph4104** [comment]
@MGoodberry Maybe it's just me but "Au sein de 20 minutes" does not make a lot of sense for me. My suggestion will be ' En l'espace de 20 minutes' or 'Au courant des 20 prochaines minutes'.
What do you think?

**Comment by MGoodberry** [comment]
@Steph4104 That could work. I had Sierra translate it for me because translation won't accept text under 50 words. I'll have Gen take a look.

**Comment by MGoodberry** [comment]
@Steph4104 Vous recevrez un courriel avec un lien vous permettant de définir un nouveau mot de passe dans les 20 prochaines minutes. Veuillez vérifier votre dossier de courriel indésirable.
