### ISSUE TITLE
Add widget button not working in dashboard

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#1944]
As a user, I need to be able to add widgets to my GCconnex personal dashboard.

After clicking the Add widget button, the user gets a blank pop-up:
![image](https://user-images.githubusercontent.com/42844328/49233802-c9d32e00-f3c4-11e8-92bd-9cddf80df933.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by martydonofrio** [comment]
https://gccollab.gctools-outilsgc.ca/a/tickets/6236

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
