### ISSUE TITLE
French Language Correction on GCconnex -- closed groups

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#1945]
As a user as navigating GCconnex, the text in french should be as accurate as the text in english with impeccable spelling  to showcase the tool's professionalism.

Current text with spelling error:
Ceci est un groupe fermé. Le contenu de **se groupe** est accessible uniquement à ses membres." Pour y devenir membres, cliquez sur le lien **"Demande d'ahdesion**
 
 
Suggested text by user : 
Ceci est un groupe fermé. Seuls les membres ont accès au contenu de ce groupe.

Suggested 2nd part : 

Pour y devenir membres, cliquez sur le lien "Demande d'ahdesion".
 

![image](https://user-images.githubusercontent.com/45214337/49234374-f20f5c80-f3c5-11e8-8d7c-aad538ca3c3d.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed
****

**Comment by martydonofrio** [comment]
I do agree they should match.

**Comment by Menrika** [comment]
@martydonofrio @Steph4104 Good job Stephanie catching that one, I did not notice at all and when I did I got completely confused
