### ISSUE TITLE
Can't see all GCconnex groups in a list

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#1947]
As a user, I need to be able to see an alphabetical list of all groups in GCconnex.

Our help article shows how the option should appear:
![image](https://user-images.githubusercontent.com/42844328/49397493-c4018380-f709-11e8-91aa-f9d80c9aa0a1.png)
Source: https://gccollab.gctools-outilsgc.ca/a/solutions/articles/2100027146

Here is what we currently see:
![image](https://user-images.githubusercontent.com/42844328/49397575-fdd28a00-f709-11e8-818e-472d4901d1b6.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by martydonofrio** [comment]
https://gccollab.gctools-outilsgc.ca/a/tickets/6280

**Comment by Steph4104** [comment]
I don't know why and when it was remove but we we want it back, you just need to access the admin panel / settings / group tools -> Under **Available group listing tabs** you check **Alphabetical** and you click **save**.

**Comment by marc-donofrio** [comment]
No longer an issue.
