### ISSUE TITLE
GCMessage log in bug --- Blank Screen / IE

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#1950]
Some users gets directed to a blank or grey screen whenever they try to log in to **GCcollab's GCmesage** portal on their desktop using **Internet Explorer** even when it worked before it stops working. I don't know yet if its a IT issue. 

So far the **departments** affected are : Shared Service, Employment and Social Development , National Defense and Service Canada. But not for everyone just a few people. 

**Person 1** : I can't seem to open the login page for GCmessage.
I get to purple login screen, but when I press **LOGIN, it takes me to a blank grey** screen and nothing happens. 

**[Person 2](https://gccollab.gctools-outilsgc.ca/a/tickets/6435%C3%A0)** : I have been using GCcollab message for several months.  Unfortunately, for the last week, each time I go to access it, I get a screen asking me to click, Login, which I do.  And then I get a **blank screen!**.  I am logged into GCcollab each time and am still unable to access.   Any guidance would be appreciated as our team does use this forum as a means of internal, informal communication.  _I seem to be the only one on my team with this issue._

**Person 3**: I used to open my gc collab right to my chats - we use this often in our work. Now it takes me to the main login page, and when I go to log in.. it takes me to a blank white screen.

[**Person 4**](https://gccollab.gctools-outilsgc.ca/public/tickets/30787a4169ff668f1996e3ce424ba43be9bb2eb89808aa7268c64eee6b16b646): Can get to the login in screen for GC Message but after click login I get a white screen and can't access the site.  It was working for me up to Friday, 

**Person 5** :  If I click on anything other than profile or security, it brings me to the screen below.   If I click on Login, it just keeps bringing me back to this screen. : 

![image](https://user-images.githubusercontent.com/45214337/49876579-aa3efb00-fdf1-11e8-8dac-92db0df94002.png)

![image](https://user-images.githubusercontent.com/45214337/49876600-b1660900-fdf1-11e8-972c-8acb0231f79e.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by martydonofrio** [comment]
https://gccollab.gctools-outilsgc.ca/a/tickets/6435

**Comment by martydonofrio** [comment]
juliana.tow@cbsa-asfc.gc.ca
tahira.khan@pptc.gc.ca
jillian.hooper@forces.gc.ca
