### ISSUE TITLE
Can't access members list

### ISSUE THREAD

**Issue by martydonofrio** [gctools-outilsgc/gcconnex#1952]
A user is causing the members list to give a HTTP ERROR 500. Can the user be identified for deletion?

Group: https://gcconnex.gc.ca/discussion/owner/26434475

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Steph4104** [comment]
@martydonofrio , User is Alice.Lau

If you need more info, let me know.

**Comment by martydonofrio** [comment]
I can't find that user. Can you deleted it from your end?

**Comment by Steph4104** [comment]
User deleted

**Comment by martydonofrio** [comment]
The user reported that the 3rd page now doesn't load.

**Comment by Steph4104** [comment]
@martydonofrio , user is Myrian.Bouchard.
Let me know if you can't find the user.

**Comment by martydonofrio** [comment]
Sorry, I can't find that user. Can you delete them?

**Comment by martydonofrio** [comment]
The page 3 of the members list still doesn't load.

**Comment by Steph4104** [comment]
@martydonofrio User deleted. All page works fine now
