### ISSUE TITLE
Validation email not received post-registration/SPAM detection -- CRA & others

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#1954]
## Emails from gctools blocked by spam detection in certain departments. 

It was noticed that registration **validation emails were not received.** It was mostly observed with **Canada Revenue Agency employees** which were tracked.

Other department that we received complaints : **Transportation Safety Board of Canada**

**CRA** manually validated account count thus far : **26**

According to my comparison with other departments, CRA's unvalidated account count is higher. https://account.gccollab.ca/admin/core/user/?q=cra-arc.gc.ca

We might want to be in contact with their IT service to make sure that the GCtools email are white-listed from the server since we are unable to change domain at the moment. . 

--------

**Person TSBC :** Hi, what is the status of issues with email servers used by GCcollab being blacklisted as spam?  (Ticket 6424) 
 
Users are still not receiving email for account invitations, validations, help desk emails, etc.  This renders GCcollab useless to us as we cannot invite users to join, they are unable to validate their accounts, and they do not receive replies from the help desk.
 
- Our IT dept has whitelisted some of the emails as suggested, however it remains a security risk.  Whitelisting open-relay mail servers that are blacklisted for spam greatly increases our exposure to harmful content.  Also we can’t recommend to our many international partners that they all whitelist those servers just so they can access the group.  It would appear unsafe (which it is) and would not reflect professionally upon the Govt of Canada.

**Ticket #6424** : Hi GCCollab,
 
GCCollab emails are being blocked due to spam detection. Your email service provider (Sendgrid) has been identified as a source of spam. Could you contact your provider and request they action the removal from the known spam database?
## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Menrika** [comment]
email : 
kyle.jackson@tsb-bst.gc.ca

**Comment by Troy-Lawson** [comment]
look for TBS SMTP server

**Comment by Troy-Lawson** [comment]
COLLAB issue

**Comment by nschonni** [comment]
@bryan-robitaille  was something done today, because as of yesterday this is still an issue

**Comment by bryan-robitaille** [comment]
@nschonni I am closing this issue as the research has been completed and the source of the problem found.  This is not an issue on the GCollab end but rather the various departments blocking the GCTools current email provider.  The much more global issue will be tracked on issue #1975
