### ISSUE TITLE
Content missing from GCcollab groups

### ISSUE THREAD

**Issue by martydonofrio** [gctools-outilsgc/gcconnex#1958]
Users are missing content from their group blogs or discussions.

The affected groups have reported that content is missing, in some cases content from the last 2-3 months is missing. One user reported that a user with the name SolCrawler was added to the group right before missing content.

Affected groups:
- https://gccollab.ca/groups/profile/1042029/envoilu00c0frvoilu00c0
- https://gccollab.ca/groups/profile/19750/entalent-cloud-nuage-de-talentsfrnuage-de-talents-talent-cloud 
- https://gccollab.ca/groups/profile/868173/enprocurement-real-property-and-materiel-management-functional-communitiesfrcollectivitu00e9s-fonctionnelles-de-lapprovisionnement-des-biens-immobiliers-et-de-la-gestion-du-matu00e9riel
- https://gccollab.ca/groups/profile/1268187/engovernment-of-canada-innovation-hubs-and-labshubs-et-labos-dinnovation-du-gouvernement-du-canadafr
- https://gccollab.ca/groups/profile/177679/eninformation-management-common-core-imcc-renewal-working-groupfrrenouvellement-de-la-base-commune-des-sgedd-bcsgedd 
- https://gccollab.ca/groups/profile/1503270/ensciencefridayfr
- https://gccollab.ca/groups/profile/418980/entrendingfrla-tendance

New user reported posts missing from their person page: https://gccollab.ca/profile/etienne.laliberte

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by JOutram77** [comment]
Blogs are also missing from the Policy Community at: https://gccollab.ca/groups/profile/85014/enthe-policy-communityfrla-communautu00e9-des-politiques
