### ISSUE TITLE
Users can't login to support portal

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#1959]
As a user of GCcollab, I need to be able to login to the support portal with my GCcollab account.

The following users can login to GCcollab but the support portal gives them the error message that their password is incorrect.
mohammed.elmachkour1@cic.gc.ca
kyle.jackson@tsb-bst.gc.ca
patrick.coghlan@canada.ca
howard.jones@canada.ca
jean.richer@cic.gc.ca

 can login to GCcollab but the support portal gives them the error message that their password is incorrect.
![image](https://user-images.githubusercontent.com/42844328/57486979-5986dd80-727d-11e9-9143-c9d2e2a3d4be.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Menrika** [comment]
@martydonofrio Was this one fixed?

**Comment by Menrika** [comment]
Can't Login to Support Panel : 

https://gccollab.gctools-outilsgc.ca/a/tickets/8681 
Email : Brenda.lovett@canada.ca (CEAA)

**Comment by marc-donofrio** [comment]
No longer an issue.
