### ISSUE TITLE
Minor edit in GCconnex blog still sends notifications

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#1964]
As a user of GCconnex, I need the blog minor edit function to not send notifications.

The following group is reporting that the minor edit function is still sending notifications:
https://gcconnex.gc.ca/groups/profile/5822608?language=en

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Menrika** [comment]
https://gccollab.gctools-outilsgc.ca/a/tickets/5872 (From November)

**Comment by marc-donofrio** [comment]
No longer an issue.
