### ISSUE TITLE
Deleted account still appearing on search index -- GCconnex

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#1967]
## Ticket : https://gccollab.gctools-outilsgc.ca/a/tickets/6743

![image](https://user-images.githubusercontent.com/45214337/51707713-e4560c00-1fef-11e9-8beb-f3cf0d86a1d5.png)

Email of user : **kabitha.thiruvarangan@cra-arc.gc.ca** 
Username : **Kabitha.Thiruvarangan** 
## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
Pretty sure this should get fixed when gcconnex gets fully re-indexed @4rsood ?

**Comment by Phanoix** [comment]
If this was gccollab then I could understand some outdated results right now. but I'm pretty sure gcconnex should have been fully re-indexed recently.
