### ISSUE TITLE
GCpedia link for Collectivités leads to the english page

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#1968]
As a user of GCpedia, I need the language to be the same when clicking on a link.

While navigating in french on the main page(http://www.gcpedia.gc.ca/wiki/Main_Page), the link on the left hand menu for Collectivités leads to the english page:
![image](https://user-images.githubusercontent.com/42844328/51748822-98e93f80-207b-11e9-9128-387d9ad7f94f.png)
Result:
![image](https://user-images.githubusercontent.com/42844328/51748877-bb7b5880-207b-11e9-84b7-7b3c4c9cea79.png)
The link should be: http://www.gcpedia.gc.ca/wiki/Category:Collectivités

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
This page already toggles between English and French versions based on interface language. The convention so far for bilingual pages like this is to either have a bilingual title or have it hidden like on the main page, so that is something that is missing here.

**Comment by marc-donofrio** [comment]
Fixed.
