### ISSUE TITLE
GCcollab group fatal error in IE

### ISSUE THREAD

**Issue by martydonofrio** [gctools-outilsgc/gcconnex#1976]
As a user of GCcollab groups, I need to access a page that shows a fatal error.

This group shows a fatal error in IE:
https://gccollab.ca/groups/profile/1227749/enpublic-service-renewal-beyond-2020-renouvellement-de-la-fonction-publique-u2013-au-delu00e0-de-2020frrenouvellement-de-la-fonction-publique-u2013-au-delu00e0-de-2020-public-service-renewal-beyond-2020

This one also: https://gccollab.ca/file/view/1637836/enbeyond2020-guide-for-championsfrbeyond2020-guide-for-champions

The issue was reproduced once and now it loads but the images on the main page don't.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
Looks like it's actually some general connectivity issues, should be fixed now.
