### ISSUE TITLE
Tagging images in GCconnex not working

### ISSUE THREAD

**Issue by martydonofrio** [gctools-outilsgc/gcconnex#1978]
As a user of GCconnex, I need to be able to tag usernames on images in my group.

Example group that cannot tag users: https://gcconnex.gc.ca/photos/album/46405175/rencontre-superviseur-2019

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by martydonofrio** [comment]
https://gccollab.gctools-outilsgc.ca/a/tickets/7237

**Comment by Troy-Lawson** [comment]
will fix by removing tag feature.

**Comment by Troy-Lawson** [comment]
since it never worked and we will never build it

**Comment by Steph4104** [comment]
Tag option remove. I only uncheck the option in the plugin.
Admin panel / Settings / TydiPics / Primary setting : Enable image tagging.
