### ISSUE TITLE
GCcollab onsite search brings up nothing

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#1979]
## Search in members or general searches don't bring up any results.  

Ticket : https://gccollab.gctools-outilsgc.ca/a/tickets/7288 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by martydonofrio** [comment]
Ilia restarted it and it now works.
