### ISSUE TITLE
Fatal Error on Career Market Place --- GCcollab 

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#1981]
## Fatal error on career marketplace on GCcollab while trying to find members

 " I am consistently getting a 'fatal error' (see attachment) when trying to search 'find members' within the Career Marketplace.  I have logged out/in and rebooted my computer multiple times.  I have no outstanding updates for my workstation. "

User email : alec.judt@forces.gc.ca
Username : alecjudt

**( On Internet Explorer )**
![image](https://user-images.githubusercontent.com/45214337/53179898-99192400-35c2-11e9-8e89-b5a8b4f92320.png)

Ticket : https://gccollab.gctools-outilsgc.ca/a/tickets/7350

I have also tested it out and this is what I receive **( On Chrome)**

![image](https://user-images.githubusercontent.com/45214337/53180199-22305b00-35c3-11e9-83c8-7d127a67bb0f.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
Looks like this needs a fulltext index over metastrings.string. I'll add it.

**Comment by Phanoix** [comment]
Also needed over objects_entity.title, didn't like the one that also included the description. It works now.
