### ISSUE TITLE
Research Fresh-desk login issue

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#2002]
This card is for research only of the related issue.

**Comment by ethanWallace** [comment]
Maybe the issue?

https://support.freshdesk.com/support/solutions/articles/236807-sso-is-not-working-and-getting-the-message-session-expired-please-login-again-

We use the UTC timestamp to generate the hash for validation. Before we were allowing the hash to be valid for 30 minutes, but now we have updated it to be valid for 30 seconds alone. Please check if your SSO server is in sync with the UTC time.


If your server is in sync, and you're still getting the session expired error, please drop an email to support@freshdesk.com.

**Comment by ethanWallace** [comment]
Potential different way to format freshdesk_sso view. 

https://gist.github.com/jasonhildebrand/43520463d17bddce4576ab712cc5d857

**Comment by ethanWallace** [comment]
Research hasn't yielded a definitive answer as to why this issue is happening. The best I could come up with is in the first comment above. If that fails to work we can contact freshdesk directly through the email provided in the same comment.
