### ISSUE TITLE
GCcollab group docs content not loading

### ISSUE THREAD

**Issue by martydonofrio** [gctools-outilsgc/gcconnex#2010]
As a user of group docs, I get the following error message when accessing the content of the docs:

Cannot GET /p/?userName=admin+-+marc&showControls=true&useMonospaceFont=false&showChat=false&showLineNumbers=false

https://gccollab.ca/docs/view/2172983/design-jam-task-list
https://gccollab.ca/docs/view/2167605/key-messages-data-as-an-asset-workshop-draft
https://gccollab.ca/docs/view/2172346/notes-from-april-8th-meet-up-digital-note-de-la-rencontre-du-8-avril-le-numerique
https://gccollab.ca/docs/group/1268187/all

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by bryan-robitaille** [comment]
Doc's cannot be recovered.  I have now enabled database backups on the Etherpad server.
