### ISSUE TITLE
GCcollab digest email not being received

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2011]
As a user of GCcollab, I need to get digest emails weekly.

User konstantinmanyakin@cmail.carleton.ca is getting password reset emails and location logins but no digest emails.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by martydonofrio** [comment]
For helpdesk: https://gccollab.gctools-outilsgc.ca/a/tickets/8260

**Comment by nschonni** [comment]
Duplicate of #1975?

**Comment by Troy-Lawson** [comment]
8 points for Investigation only

**Comment by marc-donofrio** [comment]
duplicate.
