### ISSUE TITLE
GCconnex group files deleted

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2018]
The user's group files were all deleted. The user wishes to know what happened and can a list of files or the files themselves be retrieved?

Group link:
https://gcconnex.gc.ca/groups/profile/32553148/iseds-hr-transformation-open-house-journees-portes-ouvertes-sur-la-transformation-des-ressources-humaines-disdes-ouvertes-lean?language=en%C2%A0

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
Doesn't look like a bug but a side effect of a user being deleted.
