### ISSUE TITLE
GCmessage password reset page

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2035]
## 

je peux maintenant accéder à gcmessage, mais j'ai toujours cette fenêtre qui apparaît :
( Every time user tries to log into GCmessage they are directed to a page asking them to reset their emails since their emails is apparently not validated but I have already validated the email)

![image](https://user-images.githubusercontent.com/45214337/61795828-430b0f80-adf2-11e9-9112-2a5f51584d5d.png)

Étrangement, j'entre toujours le même mot de passe et ça fonctionne.  Serait-ce possible de faire en sorte que je n'ai plus ce message?  merci à l'avance.

Ticket: https://gccollab.gctools-outilsgc.ca/a/tickets/9369

Email : josee.morneau@canada.ca 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by PhilAndrecheck** [comment]
@ethanWallace, is this resolved?

**Comment by ethanWallace** [comment]
@PhilAndrecheck We have reached out the the user experiencing this problem and have yet to hear back. So at this time it is unknown.

**Comment by PhilAndrecheck** [comment]
@ethanWallace thanks.
Should this be moved to blocked then?

**Comment by ethanWallace** [comment]
If we don't hear back by the end of the sprint, it will be moved into blocked.

**Comment by Menrika** [comment]
@ethanWallace They replied and they are still having the issue.

**Comment by ethanWallace** [comment]
It seems the issue was caused by a disconnect between GCaccount and GCmessage. GCmessage had the email field starting with a capital letter while GCaccount did not. 

This didn't prevent the user from still using GCmessage they just needed to enter their password again but that extra step is annoying so by changing the GCmessage email to match the GCaccount email this will let the user continue normally.
