### ISSUE TITLE
 Preview Blog Post function broken

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2036]
## As a GCcollab user
I want a preview function
so that I can preview my post before submitting.
 
Issue:
Currently, using Firefox when I select the preview button it actually publishes the article.
 
Hack:
The current hack is to publish the article as a draft to preview it before posting.
 
 Ticket : https://gccollab.gctools-outilsgc.ca/a/tickets/9590

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by PhilAndrecheck** [comment]
@Steph4104 qui fait la revue ?

**Comment by Steph4104** [comment]
@PhilAndrecheck , c'était Ethan, je ferme l'issue car la pull request a été merger
