### ISSUE TITLE
Missing department in drop-down

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2037]
## Would it be possible top add the Parliamentary Protective Service as an organization in the drop down menu. The organization is described in the Parliament of Canada Act https://laws-lois.justice.gc.ca/eng/acts/p-1/page-16.html. In french the name should be Service de protection parlementaire. 
 
Thank you as this will allow me to change my profile. 
 

Ticket : https://gccollab.gctools-outilsgc.ca/a/tickets/9601 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by PhilAndrecheck** [comment]
@Troy-Lawson who's reviewing?
