### ISSUE TITLE
Gateway error/JSON Error when creating -Pages- on GCcollab

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2038]
##  I recreated the page today and when I clicked published I got an error (something about a Gateway error?). So I refreshed, but got the error message again. Giving up, I then returned back to our “pages” page on our Group’s site and found two recently uploaded pages by me! In other words, despite the error message, the page did get published. Weird.

Ticket : https://gccollab.gctools-outilsgc.ca/a/tickets/9591 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Menrika** [comment]
https://gccollab.gctools-outilsgc.ca/a/tickets/9241
https://gccollab.gctools-outilsgc.ca/a/tickets/9198
https://gccollab.gctools-outilsgc.ca/a/tickets/9583

**Comment by Menrika** [comment]
@piet0024 @Phanoix 
Okay so the JSON error in the related card seems to be with the whole Group Docs on GCcollab from what what I could investigate and not just a group-centric issue

**Comment by PhilAndrecheck** [comment]
@Phanoix has this been resolved?

**Comment by Phanoix** [comment]
The JSON error should be, the other one I haven't been able to replicate.

**Comment by piet0024** [comment]
I also haven't been able to replicate this issue, do we know in what group this user was trying to create a page? Is this error still happening?

**Comment by Menrika** [comment]
@piet0024 
This is the group : https://gccollab.ca/groups/profile/2168792/enseb-digital-commonsfrdirection-gu00e9nu00e9rale-des-compu00e9tences-et-de-lemploi-dgce
