### ISSUE TITLE
Add CIRNAC and remove INAC from list of departments

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/gcconnex#2039]
## Details on issue or enhancement
Submitted from a user on July 25:

The INAC Department got split in 2 other Departments back in November last year or tso
 
Your site when selecting where you work currently has
 
ISC - Indigenous Services Canada,
but seems to be missing
CIRNAC - Crown-Indigenous Relations and Northern Affairs Canada
 
THe acronym INAC still shows... but doesn't exist anymore

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by PhilAndrecheck** [comment]
@Troy-Lawson who's reviewing this one?
