### ISSUE TITLE
Restoration of group file /// GCcolab

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2048]
## Unfortunately this group is still missing some documents.
It was recently brought to our attention that this document is blank when opened: https://gccollab.ca/file/view/307205/enterms-of-reference-imcc-renewal-working-groupfrmandat-groupe-de-travail-pour-le-ru00e9nouvellement-du-bcgi#elgg-object-2698779
 
Is there any way that it can be restored? This document was created before I joined the group, and worked in a different department. She’s since left, and we can’t seem to locate the original document.
Thanks,
 
Group : https://gccollab.ca/groups/profile/177679/eninformation-management-common-core-imcc-renewal-working-groupfrgroupe-de-travail-pour-le-renouvellement-de-la-base-commune-de-gestion-de-linformation-bcgi

Ticket : https://gccollab.gctools-outilsgc.ca/a/tickets/7496

Issue from a ticket from 5 months ago : https://gccollab.gctools-outilsgc.ca/a/tickets/7496

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Troy-Lawson** [comment]
ask @Phanoix
