### ISSUE TITLE
Time adjustment 

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2053]
## Hi there,
 
It seems that the time zone on GCcollab is pacific.  Any way in changing it to our time zone?
 
Thanks!

Ticket : https://gccollab.gctools-outilsgc.ca/a/tickets/10312 
## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
The default is actually universal time (UTC) now, and while that can be changed there isn't a way for users to set their own time zone, outside of the event calendar which is better off rebuilt completely I don't see much justification for building in time zones into elgg when most of the times where times might matter most (recent activity) are displayed as "4 minutes ago" or "2 days ago", etc.

**Comment by piet0024** [comment]
Is this issue related to time stamps on the site in general or is this related to the time on events?

**Comment by marc-donofrio** [comment]
I have seen this issue with login stats and upload stats as well. For example, this user logged in the future(Last logged in:	Wed, 04 Dec 2019 17:12:40 +0000): https://gcconnex.gc.ca/settings/statistics/Manon.Mclellan

**Comment by Phanoix** [comment]
Yeah, that's the default time zone being UTC. Since collab is globally available and there's no way for users to set their own time zone (which sounds like the real issue here) some people are always going to have the wrong time. We can add a feature request for per-user time zones but that might be a considerable undertaking to implement.
