### ISSUE TITLE
GCpedia paged cannot be edited

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2059]
When clicking on the Edit button on a page, the following error appears:

## Details on issue or enhancement
![image](https://user-images.githubusercontent.com/42844328/64782706-e09dd800-d533-11e9-94e6-02dfbd6b019b.png)

Example: https://www.gcpedia.gc.ca/wiki/Immigration,_Refugees_and_Citizenship_Canada_(IRCC)/Knowledge_Management/New_titles-Nouveaux_titres

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by marc-donofrio** [comment]
A user is still having issues and got the following error:
![image](https://user-images.githubusercontent.com/42844328/65156257-c3b64880-d9fc-11e9-825a-8bddb33bdbe8.png)

Is this related or should it be a different ticket?

**Comment by bryan-robitaille** [comment]
> A user is still having issues and got the following error:
> ![image](https://user-images.githubusercontent.com/42844328/65156257-c3b64880-d9fc-11e9-825a-8bddb33bdbe8.png)
> 
> Is this related or should it be a different ticket?

This should be a different ticket.  It's not related to the original issue.
