### ISSUE TITLE
GCpedia file upload limit is now 2MB

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2060]
![image](https://user-images.githubusercontent.com/42844328/64783610-425f4180-d536-11e9-8bdd-804e6fb44d40.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
It's probably the new apache configuration, I'll have a look.
