### ISSUE TITLE
GCconnex links in emails appear blocked

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2063]
When a user receives a notification email, the links inside the email appear to be blocked but the user can access gcconnex.gc.ca

This issue cannot be replicated from our end.

Example: 
https://u12122282.ct.sendgrid.net/wf/click?upn=ZCzkC2BRv-2BnSzBZtlLzlT0GOcclD1-2FEUVfJfwT3bt2DhUD1txj5ZWSkcJ6jv5i1MID98uPViI0grGFt-2BN-2B-2BVX53U0qkQLMqw7ieqhEEM0RuZndYfOD9X91rzxDn2XgUE_V-2FUUiW5KvBPNV-2FItFYsbuM5bawSldrXRqFBpAzlPi0RWQJMUTE5O68qipbp73-2B-2FM6g0QVtuKXq64wzbv3m1L3TAGehzZYVxzxySVaUGMyH4p0XKSxrIAXQBXCQEy6JY5GIiT568t-2FdABpsBN6y-2FZQTDetrg-2B6arUdDJ5YY60c1bpKWE6ral0NObP2fs8tAvzVSMmBhzUwAgWOinrit-2BYM0Q9Oko1xdvFFf2z-2FWZuc24-3D

----- Original message -----
From:"GCconnex (TBS/SCT)" <tbs.DoNotReply-NePasRepondre.sct@canada.ca>
To:Michelle Joljart <michelle.joljart@rcmp-grc.gc.ca>
CC:null
Date:Fri, 13 Sep 2019 20:47:33 +0000 (UTC)
Subject:A new opportunity was posted on the Career Marketplace | Une nouvelle possibilité a été affichée sur le Carrefour de carrière

This is a system-generated message from GCconnex. Please do not reply to this message. | Ceci est un message généré par le système de GCconnex. Veuillez ne pas répondre à ce message
GCconnex
(Le français suit)
Maggie.Graham posted a new opportunity titled Storytellers and Writing Aficionados EC-02, EC-03, EC-04 or equivalent / Narrateurs et passionnés de rédaction EC-02, EC-03, EC-04 ou l’équivalent
View or reply
You can like, share or subscribe to this content directly in GCconnex
Need help? Contact us.
To unsubscribe from these notifications, login to GCconnex and edit your notifications' settings.
***************************************
Maggie.Graham a affiché une nouvelle possibilité intitulée Storytellers and Writing Aficionados EC-02, EC-03, EC-04 or equivalent / Narrateurs et passionnés de rédaction EC-02, EC-03, EC-04 ou l’équivalent
Visualiser ou répondre
Vous pouvez aimer, partager et vous abonner à ce contenu dans GCconnex.
Besoin d’aide? Contactez-nous.
Pour vous désabonner de ces notifications, connectez-vous à GCconnex et modifiez vos paramètres de notifications.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
The links in my daily digests are now back to being regular gcconnex links.
