### ISSUE TITLE
GCconnex user's profile won't load

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2067]
The following user cannot access his profile:

https://gcconnex.gc.ca/profile/Thomas.Carnegie

The page only loads if the viewer is not logged in.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by marc-donofrio** [comment]
Another user seems to be getting the same error: https://gcconnex.gc.ca/profile/frances.palaschuk

**Comment by marc-donofrio** [comment]
This user on GCcollab reported an issue similar and I could replicate it: pd@museumsontario.ca

**Comment by Phanoix** [comment]
Looks like the culprit is the 'Group News' widget settings view trying to load a list of all group names, I'd recommend limiting it to the groups the user / widget owner is a member of.

**Comment by marc-donofrio** [comment]
This widget is no longer supported. | Ce widget n'est plus supporté.
