### ISSUE TITLE
Error on 'Colleagues' page-- GCconnex

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2069]
## 
It happens when I click on "My colleagues" or 'view all my colleagues'

the issue is across the tool so it shows on every colleagues page from any user. 

![image](https://user-images.githubusercontent.com/45214337/65449359-d370cb00-de08-11e9-8460-555235843a57.png)

## Details on issue or enhancement

Ticket : https://gccollab.gctools-outilsgc.ca/a/tickets/10715

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Steph4104** [comment]
Error causing by suggesting friends. Add back the procedure to the database.
