### ISSUE TITLE
GCpedia page T&C links need updating

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2074]
Section: Requirements of the Communications Policy and the Copyright Act
T&C: https://www.gcpedia.gc.ca/wiki/GCpedia:Terms_and_conditions_of_use

Current text:
Requirements of the Communications Policy and the Copyright Act
Any information that you post is subject to the Communications Policy,the Federal Identify Program Policy , and the Copyright Act.

Change to:
Requirements of the Policy on Communications and Federal Identity and the Copyright Act
Any information that you post is subject to the Policy on Communications and Federal Identity(https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=30683) and the Copyright Act (https://laws-lois.justice.gc.ca/eng/acts/C-42/index.html).

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Emily-Kokkoros** [comment]
updated text links & marc added it to page
