### ISSUE TITLE
Should language settings be remove?

### ISSUE THREAD

**Issue by Steph4104** [gctools-outilsgc/gcconnex#2102]
This is more a question but language settings in user settings is it necessary? 

![image](https://user-images.githubusercontent.com/15112568/66339877-0be8cc80-e912-11e9-86a3-a121ff560a0c.png)

**Comment by Troy-Lawson** [comment]
test and make decision

**Comment by Troy-Lawson** [comment]
Language setting is not on GCcollab and appears to only be on GCconnex. It does function nearly as intended, With language being set to the selected language on your next login.
