### ISSUE TITLE
GCPedia site blocked

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2110]
Canadian Museum of Nature users are unable to access the GCPedia site. Their IT team stated that traffic is being blocked by GCpedia.

## Details on issue or enhancement
![image](https://user-images.githubusercontent.com/42844328/66651006-f9b3aa80-ebff-11e9-9d4f-26fcaaf7e980.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
We'll need the IPs / ranges they use.

**Comment by marc-donofrio** [comment]
All users are under: 205.192.176.6

**Comment by marc-donofrio** [comment]
The 19 Crown Organizations listed below require access to GCpedia.
 
1.       Atomic Energy of Canada Limited
2.       Bank of Canada (we understand that they have been able to gain access to GCpedia)
3.       Business Development Bank of Canada
4.       Canada Deposit Insurance Corporation
5.       Canada Mortgage and Housing Corporation*
6.       Canada Post* 
7.       Canada Science and Technology Museum
8.       Canadian Air Transport Security Authority
9.       Canadian Broadcasting Corporation (CBC)
10.   Canadian Commercial Corporation
11.   Canadian Museum for Human Rights*
12.   Canadian Museum of History
13.   Canadian Museum of Nature
14.   Export Development Canada
15.   Farm Credit Canada*
16.   International Development Research Centre
17.   National Arts Centre
18.   National Gallery of Canada
19.   Royal Canadian Mint*
 
*Departments who have specifically requested access

**Comment by marc-donofrio** [comment]
New IP address from the nature museum using google's ip search: 104.156.64.122

**Comment by marc-donofrio** [comment]
IP address for the nature museum using the google search: 104.156.64.122

**Comment by marc-donofrio** [comment]
Update for the nature museum:
We tested it out at our 2 locations and had different results.

From 104.156.64.122 location, we were able to access the site (see attached)

However, when we tried at our site, we were getting time out results. The IP address there was IP 172.17.220.13  
![image](https://user-images.githubusercontent.com/42844328/73472244-b9b43700-4358-11ea-87d5-5591ee159c19.png)

**Comment by Phanoix** [comment]
The non-private IPs have access now.

**Comment by marc-donofrio** [comment]
![image](https://user-images.githubusercontent.com/42844328/74945871-70d72780-53c6-11ea-96c4-1f9b989cd471.png)
 Can you try this iP address?
