### ISSUE TITLE
Investigate feasibility of some missions mod back-end optimizations

### ISSUE THREAD

**Issue by Phanoix** [gctools-outilsgc/gcconnex#2115]
Look into the ones listed and potentially add some new ones:
1 Split missions off into a separate elgg site
  * using elgg sites feature
  * as a separate instance / db dedicated to the mod
    * Easy enough to set up with .../missions  being served from another directory using apache config
    * Will still need to one way or another have access to some entities in the main db and vice-versa
     * kinda hacky way - just query the other db for whatever is needed

*If we still want missions objects appearing in the newsfeed, activity feeds, etc. this would involve a fair number of changes to core and other mods to include. Would only suggest this for consideration if the plan is to not keep those connections. 
Note: this would still require access to the users, their skills, etc. from the main site in some way.*

2 Split missions data into missions-only tables - similar to how groups have a separate table in elgg.

*Data would need to be duplicated to these tables for a seamless transition or override query builder / fetching data for missions. Either way would require rewriting all queries for the mod.*

3 One of the worst parts of the feature is its search, so one option is to maintain a live-updated instance of elastic / solr, etc. or some search / metadata friendly db for use in those parts of the feature and maybe for even the lists, etc.
  * could work as a side / microservice that handles this or directly managed by the missions mod

*Duplicating data in something like redis for more efficient search queries would likely be the easiest here, Similar to gctools-outilsgc/gcconnex#2 but would include any data that can be searched, can be used as a cache layer, and likely to be more effective because of that.*

4 Custom query builder functions / queries for slowest / most commonly visited parts missions mod

*Simplest, probably the way to start until we know what's happening with this.*

And combinations of the above.
  * 3 and 4, if the db used in 3 isn't used for every query that might need to be re-written

**_This would be my recommendation if building it as a separate app isn't an option. Start with 4 - optimize some of the slower non-search queries and then 3 - add a (for example) redis cach-like layer for search queries in especially and any others that would see a benefit_**

**Comment by Troy-Lawson** [comment]
do research towards producing a documented recommendation for optimizing Micro Missions

**Comment by Phanoix** [comment]
Easiest thing to do would be to replicate the rewrite of the archive page data fetch / generation on the main / active opportunities pages which would at the least remove the arbitrary limit on the number of items that can be listed.
