### ISSUE TITLE
Error 502 + Time out-- GCconnex

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2124]
##

My GCconnex is giving me errors – this is the third time I create in GCconnext and I receive the following error – also another error I receive is a time-out error – not sure why because I complete the request in less than no time.
 
Please look into this at the earliest.

I have been encountering problems with GCconnex – for example this morning, I can’t open it and yesterday, when I filled in the fields to post my resume – less than a few minutes after, the system displayed a message “time out” causing me to loose all the work that I’ve done.  After trying this a few times, again I encountered the same problem.
 
Also, last week, I put my resume in “Career Marketplace”  is this where I should be posting my resume seeking work.
 
Please advise and fix the problem a.s.a.p.

## 
![image](https://user-images.githubusercontent.com/45214337/67518733-563cae00-f673-11e9-99c0-6c344de703f4.png)

Ticket: https://gccollab.gctools-outilsgc.ca/a/tickets/11448 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
Do we have anything more specific like the pages that are getting this error?

**Comment by Menrika** [comment]
> Do we have anything more specific like the pages that are getting this error?

They might have been using the wrong link.They just messaged me a d said that after doing a  search on google they found this : https://gcconnex.gc.ca/

**Comment by Phanoix** [comment]
Sounds good, going to close this issue then and if they get back to us still having problems we can always reopen it.
