### ISSUE TITLE
GCconnex file permissions error

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2126]
Access to the file is giving a permission error to admins and the file owner:

https://gcconnex.gc.ca/file/view/54308879/online-payments-in-sps-document-in-english-only-online-payments-in-sps?language=en

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
related to #2075

**Comment by Phanoix** [comment]
duplicate of #2075 and will be fixed when it is, closing.
