### ISSUE TITLE
Email Notification Digest

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#215]
Combine all system notifications into one email.

**Comment by Troy-Lawson** [comment]
@pandurx can you please help @piet0024 and @ethanWallace get up to speed on this? Share with them your code along with work remaining.
Thanks!

**Comment by pandurx** [comment]
@piet0024 @ethanWallace  use branch notification_digest

**Comment by pandurx** [comment]
I will provide documentation

**Comment by pandurx** [comment]
how to enable functionality:
- use branch notification digest (updated code)
- to enable digest, go to admin interface and enable the digest option
- go to your user notifications settings and then enable digest option

what is left to do:
- testing: make sure the users who opt in for digest receives all content update/new creation
- ui: email templates matches the template in the requirements
- text: all messages and email contents are bilingual
- code: clean up for better management/maintaining
