### ISSUE TITLE
Error when logging into GCcollab

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2208]
Some users are encountering an error page when attempting to login. Example user:
jm@publicsectorcompany.com

## Details on issue or enhancement
![image](https://user-images.githubusercontent.com/42844328/70806711-eea90200-1d89-11ea-92ce-c8223baebb3f.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
Can they still log into other services like the wiki or message?

**Comment by marc-donofrio** [comment]
I have requested this info and will let you know ASAP.

**Comment by Phanoix** [comment]
The problem is that their username in gccollab would be 2 characters long and the minimum is currently 3.
