### ISSUE TITLE
Group members list

### ISSUE THREAD

**Issue by EtienneLaliberte** [gctools-outilsgc/gcconnex#2213]
As a group owner, I need to see the date at which new members join my group and display all members by more than 20 at a time (as it use to be the case).

One little piece of information I found very useful prior to the changes was the display of the date at which new members joined my group (which has almost 1500 members). The fact that I could display the members 100 at a time meant I could do the monitoring in 15 clicks. This allowed me to manage a mailing list I maintain to keep my followers engaged, even if their use of GCcollab is sporadic. With this piece of info now gone, and the group members being displayed only 20 at a time (which would now mean 58 clicks!), I have lost the ability to track the membership of my group. Potential solution: have a "new member" feature, or allow to sort members chronologically by "join date", or display the join date again. And most definitely, bring back the ability to display a large number of members, or groups, in the search results.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by nschonni** [comment]
As an alternate, maybe having an "Export as CSV" for group administrators to dump the member lists.

**Comment by Troy-Lawson** [comment]
> As an alternate, maybe having an "Export as CSV" for group administrators to dump the member lists.

That would be amazing if you built that. Thanks!

**Comment by Troy-Lawson** [comment]
for this issue we will tackle re-adding the date joined. Other issues or ideas will be spun off.
