### ISSUE TITLE
GCcollab - Source Code Button

### ISSUE THREAD

**Issue by jquinn-cdn** [gctools-outilsgc/gcconnex#2215]
As a user of GCcollab, I need access to view the source code of pages when I create or edit to ensure that the features I want to include are captured and fix any errors in the html directly.

The source code view was an option available before the last GCcollab enhancement.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by marc-donofrio** [comment]
Enhancements were put on hold as we wait for the next version of the GCtools.
