### ISSUE TITLE
Group event blank -- GCcollab

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2219]
## Details on issue or enhancement

![image](https://user-images.githubusercontent.com/45214337/71843608-4a696100-3092-11ea-832c-b61637e6f54e.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
I think this is an admin only thing, if I remember correctly it tries to load up an absurdly sized drop-down element or something.
