### ISSUE TITLE
GCtools search not bringing up specific page

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2222]
When searching with an exact title:
Trousse promotionnelle du Carrefour des langues officielles

The page does appear in the GCpedia search but not in the global GCtools search with GCpedia filtered.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
Is this a relatively recent file? Maybe it just hasn't been crawled / indexed yet.
