### ISSUE TITLE
Group gives error 403 message -- GCconnex

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2227]
## User : I’ve tried logging out and logging back in but no dice. I can see the group but I can’t access anything, or I’ll get the error message. Yes, I am only getting this error message from this specific group. Here’s the link https://gcconnex.gc.ca/groups/profile/15644682/ontario-federal-council-conseil-federal-de-lontario?language=en

**Error 403 Forbidden** (click on a content of the group to get it)

## Details on issue or enhancement

![image](https://user-images.githubusercontent.com/45214337/72353352-f1ad5000-36b1-11ea-814c-ee0ed4e8f4aa.png)

Ticket : https://gccollab.gctools-outilsgc.ca/a/tickets/12957 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
group name starts with 'on', so it's most likely #2075.

**Comment by Menrika** [comment]
@Phanoix Discussions and group members page also have an error message

**Comment by Phanoix** [comment]
Go to the address bar and hit enter and it'll load, it's an odd bug in a firewall that's outside our control but should be changing soon. If it's still an issue then we can reopen it and I'll find who I need to bug about it again.
