### ISSUE TITLE
ClientID and ClientSecret request

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2234]
Please take a look at ticket #13240 raised by Jean-Philippe Tissot (jean-philippe.tissot@canada.ca).

On Mon, 27 Jan at 4:07 PM , Jean-Philippe Tissot <jean-philippe.tissot@canada.ca> wrote:
Hi, we are currently using https://account.gccollab.ca/openid/ to authenticate our radar.statcan.gc.ca application. 
 
We are currently building another integration and would like to get a ClientID and ClientSecret for our developpers to test a new integration. The Callback URL should be https://localhost:5001/signin-gccollab to allow us to test. 
 
Thanks

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by ethanWallace** [comment]
Client ID and secret have been sent
