### ISSUE TITLE
Drop down change request in Career Marketplace GCcollab & GCconnex.

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2240]
The Biologics and Genetic Therapies Directorate (BGTD) of the Health Products and Food Branch (HPFB) in Health Canada, recently changed its name to the Biologic and Radiopharmaceutical Drug Directorate (BRDD). 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by marc-donofrio** [comment]
French needed. I will contact the client.

**Comment by Phanoix** [comment]
Do we have this in both languages yet?

**Comment by Phanoix** [comment]
canada.ca still has the old name https://www.canada.ca/en/health-canada/corporate/about-health-canada/branches-agencies/health-products-food-branch/biologics-genetic-therapies-directorate.html

**Comment by marc-donofrio** [comment]
From the client:
Biologic and Radiopharmaceutical Drugs Directorate (BRDD)
Direction des médicaments biologiques et radiopharmaceutiques (DMBR)
