### ISSUE TITLE
GCpedia/GCconnex --- simplified sign in 

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2255]
## Petite suggestion afin d’éviter de faire perdre du temps, soit d’ajouter un message afin d’aviser les utilisateurs ou encore cacher la fonctionnalité temporairement.

User suggesting that we write a message on GCpedia to notify users that the simplified sign in with Connex and Pedia is malfunctioning. Also suggesting if we can hide the feature. 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Troy-Lawson** [comment]
@Menrika should be fixed with next server update
