### ISSUE TITLE
Event Calendar date -- GCcollab

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2257]
## Details on issue or enhancement
Ticket : https://support.gccollab.ca/a/tickets/13860

Group : https://gccollab.ca/event_calendar/group/4060793

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by marc-donofrio** [comment]
In my testing, this does not seem to occur in GCconnex.

**Comment by piet0024** [comment]
Break down of my findings:

Here is an example of the issue on prod
![event_cal_prod.jpg](https://zube.io/files/tbs-sct/dd0b6031ce2c1a9e565b6287003f4f1d-event_cal_prod.jpg)
Both of those events have start times that are not 12am.

The wet4 and wet4_collab mods both have different versions of the calendar view as well as the fullcalendar.js files.

wet4:
View: https://github.com/gctools-outilsgc/gcconnex/blob/master/mod/wet4/views/default/event_calendar/full_calendar_view.php
JS that renders calendar: https://github.com/gctools-outilsgc/gcconnex/blob/master/mod/wet4/views/default/js/event_calendar/fullcalendar.min.js

wet4_collab:
View: https://github.com/gctools-outilsgc/gcconnex/tree/master/mod/wet4_collab/views/default/event_calendar
JS that renders calendar: https://github.com/gctools-outilsgc/gcconnex/tree/master/mod/wet4_collab/views/default/js/event_calendar

For some reason the collab calendar has different functions to render the calendar than connex (I can't see why this was done).

When I try to unregister or replace the wet4_collab views and JS with the connex ones I get this:
![event_cal_local.jpg](https://zube.io/files/tbs-sct/a87aa6447c52da97b9cc7b6e3dfde562-event_cal_local.jpg)

Here you can see that replacing the views and js files with the connex ones cause the correct time to show up but then it breaks the layout and CSS of the calendar as well as our localisation strings.
Another mention of this event calendar feature is in the start.php of wet4_collab:
https://github.com/gctools-outilsgc/gcconnex/blob/master/mod/wet4_collab/start.php#L26

Perhaps fully unregistering everything from wet4_collab will fix this issue, but I don't know if that will break other things, as I can't find any commits for why these different views and JS files are there in the first place.
