### ISSUE TITLE
GCcollab intro page has outdated Help / Contact us link

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2262]
https://account.gccollab.ca/login/

## Details on issue or enhancement
![image](https://user-images.githubusercontent.com/42844328/78067447-be02cd80-7364-11ea-9d2b-1843589daf69.png)

From:
https://gccollab.ca/help/knowledgebase/
to:
https://support.gccollab.ca/

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by ethanWallace** [comment]
@marc-donofrio Help link has been updated.
