### ISSUE TITLE
Group Docs error - JSON Response could not be decoded // GCcollab

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2273]
## Details on issue or enhancement

Ticket : https://support.gccollab.ca/a/tickets/14267

In addition. When creating a group docs this error appears : 
![image](https://user-images.githubusercontent.com/45214337/80737917-35ea2200-8ae2-11ea-9ba7-53b6cd1788ec.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by marc-donofrio** [comment]
Docs feature turned off.
