### ISSUE TITLE
GCcollab generic email // French concerns

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2277]
## GCcollab email notice text inaccurate in french.  **("account x2", "on" Windows).**

Furthermore, the email said 'donotreply' written in french.

 En ouvrant une session sur gccollab, j'ai reçu ce courriel d'avertissement.  Je tiens à signaler qu'il y a du texte qui n'est en français dans celui-ci **("account x2", "on" Windows).**

Le courriel duquel est arrivé ce message est aussi en anglais seulement "donotreply".

## Details on issue or enhancement

![image](https://user-images.githubusercontent.com/45214337/81443833-299a4080-9144-11ea-83e6-6b0543ed067a.png)

Ticket : https://support.gccollab.ca/a/tickets/14374

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
The GCaccount parts seem to be part of a base / wrapper template which may also be used for bilingual emails, so maybe the way to go with those is to make them bilingual too (GCaccount - GCcompte) if that doesn't cause any formatting issues

**Comment by piet0024** [comment]
Yes, it looks like it's pulling in the app title from a setting and trying to translate but the emails only go out in english. 
Header: https://github.com/gctools-outilsgc/concierge/blob/master/core/templates/emails/base.html#L214
Footer: https://github.com/gctools-outilsgc/concierge/blob/master/core/templates/emails/base.html#L269
We can change this setting on prod like you suggested.

**Comment by Phanoix** [comment]
I think that setting's also used in some other places where it gets translated depending on your language, so changing it would probably break that.

**Comment by piet0024** [comment]
A quick fix would be to hard code the app title in the header and footer. I know we built the template to be customizable. Maybe we can create a new "email app title" setting. This may require a db migration though.

**Comment by piet0024** [comment]
This issue may have actually been addressed with this commit: https://github.com/gctools-outilsgc/concierge/commit/347d2d209646119c50397f74328ab951a70a1067
