### ISSUE TITLE
GCcollab suspicious emails text change request

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2286]
A user noticed that the text for the suspicious email security feature might be misleading and they would like it to be updated before launching a campaign.

Suggested text:

Voici comment je vous recommande de l’écrire :  
 
q   Je souhaite être informé de toute tentative de connexion suspecte à mon compte.
 
In English:
 
q   I wish to be informed of any suspicious login attempt to my account.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Troy-Lawson** [comment]
What is the current text?

**Comment by marc-donofrio** [comment]
Receive Suspicious Sign In Emails

**Comment by JoyMosk** [comment]
I wish to be informed of any suspicious login **attempts** to my account.

**Comment by JoyMosk** [comment]
In French: Je souhaite être informé(e) de toute tentative suspecte d’accès à mon compte.
