### ISSUE TITLE
GCcollab files are with extension as “.sas7bdat” and “.dta”

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2289]
A user would like us to support uploading files are with extension as “.sas7bdat” and “.dta” to share unclassified scientific data.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Troy-Lawson** [comment]
@marc-donofrio in the admin panel under plugin settings, pick file tools and you should be able to add the file extensions there
