### ISSUE TITLE
event_calendar showing instead of label in Activity view in GCconnex and GCcollab groups

### ISSUE THREAD

**Issue by nschonni** [gctools-outilsgc/gcconnex#2303]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
When an event is shown on a group's Activity page, the label for event isn't rendered 

## Details on issue or enhancement

![GCcollab missing label](https://user-images.githubusercontent.com/1297909/90922755-80a5e780-e3ba-11ea-8de1-ca2e09048a76.png)

![GCconnex missing label](https://user-images.githubusercontent.com/1297909/90922798-95827b00-e3ba-11ea-9a51-3bbd44353118.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
Had a quick look and it does look like it's just missing language variables to map event_calendar to (for both languages)
