### ISSUE TITLE
GCconnex not loading in IE

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2306]
Users are reporting that they cannot access GCconnex.gc.ca in IE but it works in Chrome.

IE 11.0.9600.19431

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
Tested this using all the browsers and environments I have available:
Works in IE11  (11.1016.18362.0)
Works in edge
