### ISSUE TITLE
Auto-Suggest for Meta-data (tags)

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#232]
More analysis required to provide proper time estimate.

**Comment by CalvinRodo** [comment]
Without auto completion of tags they aren't really providing much benefit, small typos render them worthless.

**Comment by ToferC** [comment]
Not entirely, but good point. We have auto tagging that we could add here
or we could auto-suggest based on a curated set of tags. Worth a discussion.

**Comment by Troy-Lawson** [comment]
closing as not likely to be addressed before rebuild
