### ISSUE TITLE
Error when publishing -- GCconnex

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2322]
## Details on issue or enhancement

![image](https://user-images.githubusercontent.com/45214337/95232075-05fe2380-07d2-11eb-87aa-d875b675e30e.png)

https://gcconnex.gc.ca/action/file/upload / https://gcconnex.gc.ca/file/edit/69618678 

https://gcconnex.gc.ca/event_calendar/view/69672400/gcwellnessinmotion-challenge-defi-mieuxetreenaction?language=fr

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by marc-donofrio** [comment]
https://gcconnex.gc.ca/groups/about/54143633

**Comment by Phanoix** [comment]
This should be fixed as of a while ago, if not go ahead and re-open.
