### ISSUE TITLE
Error 500 when reseting password --- GCcollab

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2327]
## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by ethanWallace** [comment]
Was fixed in https://github.com/gctools-outilsgc/concierge/pull/183
