### ISSUE TITLE
Add retired / suspended user functionality

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#233]
Create better understanding of which users are active on the tools

**Comment by ToferC** [comment]
Additional details:
* Allow users to retire or suspend their account
* Have visual indicator for other users to show that the user is retired (in profile, user card, user avatar)
* Turn off notifications while user is retired or suspended
* Allow user to re-activate their account

**Comment by LemieuxGen** [comment]
@Troy-Lawson Can we add this to the next sprint?

**Comment by ToferC** [comment]
Good idea. Thanks @lemieuxgen

**Comment by LemieuxGen** [comment]
This issue will solve issue: #1378. Please add to next sprint.
