### ISSUE TITLE
Error when publishing -- GCconnex

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2333]
## Error when publishing and using the description box and in calendar when putting a text in French.

**Issue seems to be fixed and I am not able to replicate the error to get the Support ID.** 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
Assuming it's related to other firewall issues that have been fixed.
