### ISSUE TITLE
GCcollab add file type

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2348]
A user request to add the OFT file type to GCcollab. The admin panel allows the update but it does not get saved and sent to the front end.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Troy-Lawson** [comment]
@marc-donofrio well i flushed the cache. I dont even see anywhere where it displays file types anyway? is this fixed for you?
