### ISSUE TITLE
Investigate issue - GCwiki: Visual editor breaks links

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2350]
When using the Edit button and adding any text or space, the link to the PDF becomes broken:

https://wiki.gccollab.ca/PFAN_-_Foire_aux_questions_(FAQ)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
using File: instead of Media: works as expected, pretty sure Media is intended for embeddable content like images which is probably why the visual editor changes it to a more direct link.
