### ISSUE TITLE
GCcollab user unwanted notifications

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2353]
The following user is no longer part of this group but is still getting the notifications:

From: GCcollab <admin@gccollab.ca> 
Sent: Tuesday, February 16, 2021 8:11 PM
To: Drouin, Jean-Rock (SSC/SPC) <jean-rock.drouin@canada.ca>
Subject: A new file was posted in group NRCan/RNCan | Un nouveau fichier a été affiché dans le groupe NRCan/RNCan

This is a system-generated message from GCcollab. Please do not reply to this message | Ceci est un message généré par le système de GCcollab. Veuillez ne pas répondre à ce message 
GCcollab 
(Le français suit)
ericajryan posted a new file titled Weekly BR Summary - NRCAN February 14, 2021 
View or reply 
You can like, share or subscribe to this content directly in GCcollab 
Need help? Contact us.
To unsubscribe from these notifications, login to GCcollab and edit your notifications' settings.
ericajryan a affiché un nouveau fichier intitulé Weekly BR Summary - NRCAN February 14, 2021 
Visualiser ou répondre 
Vous pouvez aimer, partager et vous abonner à ce contenu dans GCcollab. 
Besoin d’aide? Contactez-nous.
Pour vous désabonner de ces notifications, connectez-vous à GCcollab et modifiez vos paramètres de notifications.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
Looks like the user's subscription to the group remained after they had left.
