### ISSUE TITLE
GCmessage - refresh

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2374]
## Details on issue or enhancement

Messages not loading

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Menrika** [comment]
https://support.gccollab.ca/a/tickets/19223

**Comment by Phanoix** [comment]
should be fixed now
