### ISSUE TITLE
group activity indicators

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#238]
In groups it would be super useful if there could be some indication of activity beside the right hand group functions like bookmarks, discussion, files, etc. ideally a number indicating how many objects are there, but even just an indicator that there is something or nothing would be useful.

To save users time and highlight the areas within a group where there is content. I find myself surfing through empty sections when trying to assess a group.

**Comment by ToferC** [comment]
Related to #861

**Comment by Troy-Lawson** [comment]
closed as system will be rebuilt
