### ISSUE TITLE
GCcollab Profile - Rename colleague sidebar to [Page owner entity]'s colleagues

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/gcconnex#2434]
**Consistency and standards**
When viewing another user’s profile, their colleague show up as “My colleagues” which is confusing to the user. Change to “[Name]’s Colleagues” so as to be clear which user it relates to.

The code for this should be in the `b_extend_profile_collab` mod.

![Image](https://user-images.githubusercontent.com/7603237/181575788-0eaf8aa7-0edd-4d34-bcce-0cf11fec1d07.PNG)

**Comment by LecCory** [comment]
Component reads title from language EN and FR files, added conditions to output the header with the profile owners username in both languages if the title == Colleagues || collegues. 

Language files located in `wet4_collab` mod
component rendered  via `wet4` mod component file: `views\default\page\components\modules.php`

![Image](https://user-images.githubusercontent.com/17506947/186201212-98439171-0eb9-443b-8089-a33931c6ee67.png)

**Comment by LecCory** [comment]
#2450  merged into main
