### ISSUE TITLE
Error 403 submit a ticket -- GCconnex/GCpedia

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2465]
## Error when submitting a ticket on Connex and Pedia

Was able to replicate issue.

## Details on issue or enhancement
![image](https://user-images.githubusercontent.com/45214337/199807532-1ce73560-a023-412e-a37b-8bbb143426ce.png)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
should be working now
