### ISSUE TITLE
GC Collab - Database Discussion

### ISSUE THREAD

**Issue by LecCory** [gctools-outilsgc/gcconnex#2468]
# Notes from November 22, 2022 meeting

## GC Collab

Database Engines
 - CosmosDB 
    - Microsoft solution
    - IMTD Approved  ( @LecCory can follow-up with Marco/IMTD)

Schema design
 - Redesign an optimized schema
 - Remove Elgg database bloat
 - What features of current GC Collab are worth keeping

Retention
- Plan for what to do with old collab data
- Policy for how much data is kept vs. deleted

Migration
- Migration plan
   - Facebook-like profile download
   - parallel migration
   - Start fresh on new GC collab, or migrate all data
   
Graph Database Models
- Discuss Graph Databases with @vid
- CosmosDB per Microsofts official documentation is a [fully managed graph database](https://learn.microsoft.com/en-us/azure/cosmos-db/gremlin/introduction)

## GC Wiki

media wiki staying with MySQL 
 - Lift and shift the data onto GCX tenant
 

## GC Message

GC Messages data stream
 - Message queuing 
 - Consider other Instant Messaging solutions

**Next Meeting is scheduled for November 28th, 2022**

**Comment by vid** [comment]
In theory, targetting Gremlin for graph features looks like a good option to not get too locked in. It is supported by a number of other databases. https://en.wikipedia.org/wiki/Gremlin_(query_language)#Vendor_integration
Further to that, two areas of exploration would be the user and permissions models. User seems simple-ish, target OIDC. I will try to explore portability for data permissions 
Another area is cost. Is there a cost overhead to use the Gremlin API for CosmosDB?
I also want to explore any differences, deficiencies, and lock-in.
Finally, we would want to find interoperability, at least, with standards like Linked Data and other portable schema approaches, so we are not living in another silo.

**Comment by LecCory** [comment]
# GC Collab

Topics discussed during 11/28/2022 meeting

- Consider the complexity and ease of setting up a development environment independent of the cloud host
- Maintain a cloud vendor agnostic approach to keep the project truly open source
   - contributors should be able to run their own solution on the cloud of their choosing 
- Meeting with GCX tenant admin to determine the policies with regards to Gremlin API
- Research into Gremlin API
- Review the GC Collab analytics to determine features worth keeping and/or giving priority to
- Tackle the larger features that are required/missing from the legacy platform first
- Create back end testing environment in Cypher
- Get data for front end testing
