### ISSUE TITLE
Ongoing and consistent bug in the GCcollab platform

### ISSUE THREAD

**Issue by Elvis-Besingi** [gctools-outilsgc/gcconnex#2486]
User reporting - All email addresses using the @ised-isde.gc.ca domain are being automatically replaced with a link to an account from 2017 belonging to Chris Murray since that account GCcollab's handle is literally @ISED.

![Bug - Chris Murray at ISED](https://user-images.githubusercontent.com/123134358/213600112-5cebe304-08bc-41c9-98b8-d95e6f73289c.png)

This should be from the GCconnex side of things based on the image attached. I have requested a link to the particular page from the user in the meantime.

**Comment by piet0024** [comment]
After doing some testing, this user is correct there is another user with the username ised. A way around this would be to ignore the @ mention prompt. The user should be able to put a plain text email without the @ mention like this example here: 

![Image](https://user-images.githubusercontent.com/7603237/220138165-9e05ab47-7cf0-44fe-befe-44a39a6804b4.png)
