### ISSUE TITLE
GCconnex submitting form 

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2488]
## 
![image](https://user-images.githubusercontent.com/45214337/214638063-c6b8d9d8-c352-49d2-b345-4f319c121c6d.png)

## Details on issue or enhancement

https://support.gccollab.ca/a/tickets/27288

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by piet0024** [comment]
Are we still getting reports of issues with the form? Are we also still getting tickets from other users from other departments? Unfortunately, we can’t replicate this issue. This may be an issue with their department blocking access to the Freshdesk API or it may be a caching issue. We can suggest to users that they try clearing their browser cache and try to submit again.
