### ISSUE TITLE
Research getting GCCollab DB into Managed MariaDB

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/gcconnex#2505]
Goal is to create tasks.

**Comment by LecCory** [comment]
New repo created pointing to Cypher. It's a near identical clone of the repo pointing to the current GCCollab tenant, with the exception that the service connection is switched to point to Cypher. Note that this is only the IaC and not the core app, or data itself.

Before running we need to look at deleting old resources used to test Elgg POCs in Cypher. Multiple app service plans and database resources while not being used still incur charges. 

Once the deployment is complete we can begin testing out a mock migration and documenting the issues and outcomes that arise from this exercise, this way when we move GCCollab into production managed services we are prepared for a seamless (as possible) cut over.
