### ISSUE TITLE
look into gccollab object caching (memcached) for managed web app environment

### ISSUE THREAD

**Issue by Phanoix** [gctools-outilsgc/gcconnex#2527]
look into any web app - inherent caching too

**Comment by LecCory** [comment]
From what I've been able to find, it looks like we'd need a separate resource running redis or memcached. Unfortunately, neither of those as individual resources are approved in Cypher. We'd have to build a separate VM running either or to test it. That's partially why I wanted to do load testing on the site in Cypher to see what our response rates would be without memcache. I am also testing out getting memcache running in our container, off of #2550

**Comment by Phanoix** [comment]
That's why I decided to build it into the container as a local cache, since that's really the only option we have in an azure web app environment, and I agree that it would be good to test with vs. without memcached.

**Comment by Phanoix** [comment]
I'll need to finish #2409 before we can test out the memcached built in version in azure web apps since config files are a no-go there, but I think this can be called done for the context of this issue.
