### ISSUE TITLE
GCCollab - Managed Service - Restore Collab backup into new MariaDB instance

### ISSUE THREAD

**Issue by LecCory** [gctools-outilsgc/gcconnex#2534]
~~Depends on : #2533~~
~~Depends on: #2538~~

**Comment by LecCory** [comment]
Copy of schema and data from dev has been moved into the cypher instance of collab. Will need to write scripts to change all instances of gcconnex.local in the DB to the new web app url

**Comment by LecCory** [comment]
Had to make 1 update to the URL column in: elgg_sites_entity. The site is now accessible, but using dev data. 
@Phanoix @piet0024 we will need a dump of the prod db 
I have a Storage account named devdatastorageacc with a container called sqlbkp where the dump can be uploaded, @Phanoix you're an owner on the resource, but I went ahead and gave you blob contributor to avoid any issues. 

in the same SA I have a fileshare called data where we can point the copy task that's being worked on to. When we're ready I can generate SAS keys and relay that privately.

**Comment by Phanoix** [comment]
besides the main sites_entity one, there are probably a bunch of incidental URLs in private_settings that are things like mod config that were generated based on the original site url

**Comment by LecCory** [comment]
I'm not sure if we want to move the prod data into the cypher instance, or if we'd prefer to move it into the current production instance on the current cloud tenant once the resources have been deployed. My preference would be to move the data to the prod instance and keep Cypher running the basic development data and simply use the development instance for load tests and such. With that said, if we agree on where the data should be migrated to then we'll be able to complete the migration after [#56](https://github.com/gctools-outilsgc/Issues/issues/56) is resolved

**Comment by LecCory** [comment]
Infra has been deployed to seankibbee tenant.  [#56](https://github.com/gctools-outilsgc/Issues/issues/56)

Because there's no data, the site is currently non responsive. We can work on copying over the data.

**Comment by LecCory** [comment]
Cleaned up the *_old tables by importing the data into a temp server and exporting a clean backup. Re-running the import into cypher. Should be complete before EoD

**Comment by LecCory** [comment]
Import completed.
