### ISSUE TITLE
GCCollab - Managed Service - Deploy Infrastructure

### ISSUE THREAD

**Issue by LecCory** [gctools-outilsgc/gcconnex#2538]

**Comment by LecCory** [comment]
Infrastructure has been deployed based on the following design


![Image](https://user-images.githubusercontent.com/17506947/236282025-295ccc7b-17cf-4e7a-aaa9-fdb782261f56.png)


Resources are contained within rg-gctools-managedServices-dev

Anyone needing a maria database add the following to your IaC resource deployment. Feel free to also use the app service plan as well, it's a Basic plan we can have 16 apps off of it and vnet integration is supported.

```
resource dbVnet 'Microsoft.Network/virtualNetworks@2022-07-01' existing = {
    name:  'dev-gctools-vnet'
}

resource mariaInstance 'Microsoft.DBforMariaDB/servers@2018-06-01' existing = {
    name: 'dev-gctools-mariadb'
}

resource appPlan 'Microsoft.Web/serverfarms@2022-03-01' existing = {
    name: 'gctools-app-svc-dev'
}

resource appSvcSubnet 'Microsoft.Network/virtualNetworks/subnets@2022-07-01'  existing= {
    name: 'AppSvcSubnet'
}
resource yourApp resource gctools_web_app 'Microsoft.Web/sites@2022-03-01' = {
    name: string
    location: string
    properties: {
        [refer to documentation for additional properties]
        serverFarmId:   appPlan.id
        virtualNetworkSubnetId: appSvcSubnet.id
    }
}

resource yourWebAppConfig 'Microsoft.Web/sites/config@2022-03-01' ={
    [add the property below to your existing web config template properties]
    properties: {
        vnetName: dbVnet.name    
    }
}

resource gctools_database 'Microsoft.DBforMariaDB/servers/databases@2018-06-01' = {
    name: 'dbName'
    parent: mariaInstance

}
```


Note that public access to MariaDB is disabled unless you're in the Vnet. I'm working on a solution for that to push SQL commands from the pipeline.

**Comment by LecCory** [comment]
One last update that I'm working on. For some reason my mounted storage for the Collab app is not mounting in the web app. All resources are creating but this one is giving me a hard time.

**Comment by LecCory** [comment]
Fixed storage mounting issue. collab infra deploys successfully into the Cypher tenant. I will make updates to the non-GC tenant templates to include the updates I made

**Comment by LecCory** [comment]
Moving back to in progress. 

If we're lifting and shifting the current Elgg platform, we will need to run it in a docker container due do legacy requirements
![Image](https://github.com/gctools-outilsgc/gcconnex/assets/17506947/22c936c1-8961-4728-bb36-7a1a9308d03f)

Azure currently has support for PHP 8 and its current minor versions. The version of Elgg we're running requires PHP5.4 so breaking it out of docker and moving it to a proper web app will not be possible in its current state. The bicep templates will need to be revised

**Comment by Phanoix** [comment]
that's exactly what I ended up doing for the PR review instances https://github.com/gctools-outilsgc/gcconnex/blob/master/.bicep/PR/collab-test-instance.bicep  though it's a slightly different architecture for connecting to the db, not sure how well private links would work when the DB instance and vnet / subnet are common to all test instances which get spun up and down as PRs are opened and closed.

**Comment by LecCory** [comment]
Web app module changed to a container, pointing to @Phanoix's docker hub repo. 
Deploys successfully, but DB configuration is required to complete. Those are being tracked in #2534
