### ISSUE TITLE
Remove Stats Link from GCpedia Sidebar

### ISSUE THREAD

**Issue by Elvis-Besingi** [gctools-outilsgc/gcconnex#2558]
Hello Team,

The user flagged this to our attention. 

The link to the stats page is: [http://stats.gctools-outilsgc.ca/gcpedia?URL-search=Help](https://can01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fstats.gctools-outilsgc.ca%2Fgcpedia%3FURL-search%3DHelp&data=05%7C01%7C%7C78b633b9247b4819261f08db6b41f85e%7Cf6a7234dbc9b4520ad5f70669c2c7a9c%7C0%7C0%7C638221703309039218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8sQ9RihyKNMrkDGpWmrYLexe%2BLwLOpHdrLowGsfV%2BLE%3D&reserved=0).

They also wondered - if there is a plan to restore this function – the statistics link remains in the GCpedia menu bar, so I imagine deactivating it was not intentional.
 
Also, as noted above, the ticket submit features for the GCtools also do not appear to be working. This makes it very difficult to reach out when support is required.

Thanks in advance for investigating.

**Comment by Phanoix** [comment]
that's an old self-service GA stats app that's been on its last legs for a while and at this point combined with the GA changes over the last decade since it was thrown together will need to be rebuilt of we want to keep this kind of functionality. The link is added to the side menu through here https://github.com/gctools-outilsgc/gcpedia/blob/gcpedia-composer/includes/skins/BaseTemplate.php#L64

Is the ticket submit being confused for that or is it a separate thing?

**Comment by vid** [comment]
For http://www.gcpedia.gc.ca/wiki/Help, the help is an embedded page (iframe). Maybe it would be worth it to make that a regular wiki page, importing the content, so we don't have to maintain a unique section on gccollab. It does have a search box the wiki doesn't provide, but if there isn't too much content it could be organized into sections, using expand/hide elements.

**Comment by Phanoix** [comment]
We'll have to figure that out eventually for when the gcconnex page won't be available to iframe anyways. the external tools use a common https://support.gccollab.ca that's part of freshdesk, so that's also an option.

**Comment by Phanoix** [comment]
To help with the investigation - is this only affecting a handful of users or a couple departments? The latest helpdesk stats don't seem to show much of a drop if any in connex or pedia tickets.
