### ISSUE TITLE
GCCollab Career Marketplace - Create opportunity - Make application date not required

### ISSUE THREAD

**Issue by AdiMakkar** [gctools-outilsgc/gcconnex#2559]

**Comment by Phanoix** [comment]
Just to clarify, this is referring to the "Application deadline" field, correct? Or is it something else?

**Comment by AdiMakkar** [comment]
Yes, referring to the "Application deadline" field.

**Comment by Phanoix** [comment]
Looking at the [related code](https://github.com/gctools-outilsgc/gcconnex/blob/master/mod/missions/lib/missions-errors.php#L237) it would be a good chance to add some unit tests to particular part of missions error checking, and wouldn't be a bad idea to refactor it a bit at least.

**Comment by AdiMakkar** [comment]
Fixed by #2563.
