### ISSUE TITLE
Issue Editing on GCPEDIA --

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2562]
## User get error message when they edit these pages.
 
GCdocs How-to Videos
English: [https://www.gcpedia.gc.ca/wiki/GCdocs_How-to-Videos?setlang=en&uselang=en](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gcpedia.gc.ca%2Fwiki%2FGCdocs_How-to-Videos%3Fsetlang%3Den%26uselang%3Den&data=05%7C01%7Cmenrika.christian%40tbs-sct.gc.ca%7C552d891bdf544eaac2a808db7181f5ab%7C6397df10459540479c4f03311282152b%7C0%7C0%7C638228575320055845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TnYRjZLSVLP0go9OxONvpWem9ro%2FHvT%2F6%2BygaNYXLtE%3D&reserved=0)
CODE ERROR: Your support ID is: 8952924827316177713
ERROR on “Edit source”:
French: [https://www.gcpedia.gc.ca/wiki/GCdocs_How-to-Videos?setlang=fr&uselang=fr](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gcpedia.gc.ca%2Fwiki%2FGCdocs_How-to-Videos%3Fsetlang%3Dfr%26uselang%3Dfr&data=05%7C01%7Cmenrika.christian%40tbs-sct.gc.ca%7C552d891bdf544eaac2a808db7181f5ab%7C6397df10459540479c4f03311282152b%7C0%7C0%7C638228575320055845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=r1KOpWbsPF1N2F8aMjpyYV5JIiqZxKiyY9XRajGzlwQ%3D&reserved=0)
CODE ERROR: Your support ID is: 8952924827322637347
ERROR on “Edit source”:
 
FAQ de GCdocs
English: [https://www.gcpedia.gc.ca/wiki/GCdocs_FAQs?setlang=en&uselang=en](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gcpedia.gc.ca%2Fwiki%2FGCdocs_FAQs%3Fsetlang%3Den%26uselang%3Den%2520&data=05%7C01%7Cmenrika.christian%40tbs-sct.gc.ca%7C552d891bdf544eaac2a808db7181f5ab%7C6397df10459540479c4f03311282152b%7C0%7C0%7C638228575320055845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HiVY4s9ouKcTAebv7G%2FJ%2F4WQNlMcbfNCN8OJRNYEe%2BI%3D&reserved=0)
CODE ERROR: Your support ID is: 8952924827321533168
ERROR on “Edit source”:
French: [https://www.gcpedia.gc.ca/wiki/GCdocs_FAQs?setlang=fr&uselang=fr](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gcpedia.gc.ca%2Fwiki%2FGCdocs_FAQs%3Fsetlang%3Dfr%26uselang%3Dfr&data=05%7C01%7Cmenrika.christian%40tbs-sct.gc.ca%7C552d891bdf544eaac2a808db7181f5ab%7C6397df10459540479c4f03311282152b%7C0%7C0%7C638228575320055845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=88vlnluzRvfl9WBnOG%2FkVvMwZm5NcicefaiB8f0gb9Y%3D&reserved=0)
CODE ERROR: Your support ID is: 8952924827322635139
ERROR on “Edit source”:
 
GCdocs Quick Reference Guides and Leaflets
·        English: [https://www.gcpedia.gc.ca/wiki/GCdocs_Quick_Reference_Guide?setlang=en&uselang=en](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gcpedia.gc.ca%2Fwiki%2FGCdocs_Quick_Reference_Guide%3Fsetlang%3Den%26uselang%3Den&data=05%7C01%7Cmenrika.christian%40tbs-sct.gc.ca%7C552d891bdf544eaac2a808db7181f5ab%7C6397df10459540479c4f03311282152b%7C0%7C0%7C638228575320055845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=39Sp90U0yAVqFmaZF5560LAmNGjQKmtwo8SI5%2FOq9sU%3D&reserved=0)
CODE ERROR: Your support ID is: 8952924827316219041
ERROR on “Edit source”:
·        French: [https://www.gcpedia.gc.ca/wiki/GCdocs_Quick_Reference_Guide?setlang=fr&uselang=fr](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gcpedia.gc.ca%2Fwiki%2FGCdocs_Quick_Reference_Guide%3Fsetlang%3Dfr%26uselang%3Dfr&data=05%7C01%7Cmenrika.christian%40tbs-sct.gc.ca%7C552d891bdf544eaac2a808db7181f5ab%7C6397df10459540479c4f03311282152b%7C0%7C0%7C638228575320055845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=L3T1K1B5rm0kujqQ2H909Dm3u2LyljFFtmqULQgjcEs%3D&reserved=0)
CODE ERROR: Your support ID is: 8952924827315301303
ERROR on “Edit source”:
 
GCdocs Training at HC/PHAC
English: [https://www.gcpedia.gc.ca/wiki/GCdocs_Training?setlang=en&uselang=en](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gcpedia.gc.ca%2Fwiki%2FGCdocs_Training%3Fsetlang%3Den%26uselang%3Den&data=05%7C01%7Cmenrika.christian%40tbs-sct.gc.ca%7C552d891bdf544eaac2a808db7181f5ab%7C6397df10459540479c4f03311282152b%7C0%7C0%7C638228575320055845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aok%2FGu1hQVIWYYAyr2xSi3eQcvlkV3RfOpAM3HgOBQI%3D&reserved=0)
CODE ERROR: Your support ID is: 8952924827322605843
ERROR on “Edit source”:
French: [https://www.gcpedia.gc.ca/wiki/GCdocs_Training?setlang=fr&uselang=fr](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.gcpedia.gc.ca%2Fwiki%2FGCdocs_Training%3Fsetlang%3Dfr%26uselang%3Dfr&data=05%7C01%7Cmenrika.christian%40tbs-sct.gc.ca%7C552d891bdf544eaac2a808db7181f5ab%7C6397df10459540479c4f03311282152b%7C0%7C0%7C638228575320055845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZN7Ejs556T0s6BcuIq3GqVtgvIE2wNIwEsM%2FbcWO5cc%3D&reserved=0)
CODE ERROR:  
ERROR on “Edit source”: 8952924827322610179
 
The following error still appears:

![image](https://github.com/gctools-outilsgc/gcconnex/assets/45214337/96546e2d-b7a3-45c3-9393-97c6200c7e72)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
This is a firewall false-positive, will have it taken care of soon.
