### ISSUE TITLE
Clone GCPedia page 

### ISSUE THREAD

**Issue by Elvis-Besingi** [gctools-outilsgc/gcconnex#2646]
Hi Team, a user brought to our attention that edits made in a clone GCpedia page affects the original page.

Any suggestions for a fix?

Below is a link to the original and clone pages.

https://www.gcpedia.gc.ca/wiki/Portail_de_service_des_biens_immobiliers_(PSBI)
Page clone : https://www.gcpedia.gc.ca/wiki/Josee_landry_sandbox

**Comment by Phanoix** [comment]
This is because they hard-coded the edit link in their own custom menu and then copy / pasted it to a new page without updating where their menu links point, they should update their menu links to fix this.
