### ISSUE TITLE
Integration with GC Bus

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#265]
Exploratory analysis  & input into design.

**Comment by smellems** [comment]
The Interoperability team wants to use the justice HRMS as the “source of truth” for employee information.  We want to enable up to date information to be updated in GCconnex profile through the GCIP (GC Interoperbility Platform).

All exchanges of information would happen through the GCIP.  A change in Justice HRMS would trigger an update in the GCIP, that would then update GCconnex (and GEDS) by using their APIs.  This should also handle account creation and deactivation.

This requires new APIs for GCConnex to allow an authenticated push to update profile information or create/deactivate accounts.

Moving forward all employee information would only be updated by GCIP when changes are made to the “Source of Truth”.  The employee (at Justice only for the pilot) would no longer be able to update information manually in GEDS or GCconnex.  We would need to remove the sync with GEDS for those users.
