### ISSUE TITLE
Organizations hover -- GCPEDIA

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2658]
## Acronym error in spelling. I though this was an error with the code but after trying it out it seems that there might be an error

Should be **Public Services and Procurement Canada** ( services with an s)

## 
![image](https://github.com/gctools-outilsgc/gcconnex/assets/45214337/6bc2e134-e8f7-4c71-b4c5-167542e4f56f)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
This would be functionality from the [Lingo](https://www.mediawiki.org/wiki/Extension:Lingo) extension and can be fixed on the Terminology page.

**Comment by Menrika** [comment]
Terminology page : https://www.gcpedia.gc.ca/wiki/Terminology
