### ISSUE TITLE
GCcollab URL still displays the user's old name

### ISSUE THREAD

**Issue by massan35** [gctools-outilsgc/gcconnex#2667]
## User  want her URL name to go from  Marion to Mulcahey
Email: darlene.mulcahey@cbsa-asfc.gc.ca

## I updated my profile but when people receive a notification, it still says Darlene Marion instead of Darlene Mulcahey as per this screenshot
![image](https://github.com/user-attachments/assets/5371a1ab-6910-4cea-9e67-b7755104e917)

![image](https://github.com/user-attachments/assets/2a444a32-51af-447d-ba12-0f853c2c8713)

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment]
should be properly updated now.
