### ISSUE TITLE
Derek.Jackson@canada.ca not able to update the info in GCconnex that is retreived directly from geds which is updated

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#304]
GCCON-258
Here is the scenario. 
 user already synched his info with geds - all is good 
 user move to another department, his info in geds were updated. 
 user try to sync again with geds to have his info updated in Gcconnex but receive the message no info for Derek.jackson in geds.although his account in geds clearly exists. 
 email attached for reference.

**Comment by ToferC** [comment]
Closing issue as last activity more than 8mos ago. Will resolve in upcoming directory work.
