### ISSUE TITLE
Rick.Massie@aandc-aadnc can't add a colleague from the work experience tab

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#306]
GCCON-257
In my profile, under "work experience" the "Colleagues" form field does not work for me. It seems like it is meant to auto-populate when you start typing, however, it doesn't do that for me. If I type in the full name of the colleague and then save, it gets erased (I assume this is since it wants to use the autopopulated named, not just typed text.) I am using Firefox 45.3.0

**Comment by Troy-Lawson** [comment]
Im not even able to load this guys profile.

**Comment by Troy-Lawson** [comment]
profile doesnt load when logged in. Loads empty when not logged in

**Comment by ToferC** [comment]
@Troy-Lawson - is this still an issue? Please close if not. Thanks!

**Comment by ToferC** [comment]
Closing as old issue. Pls. re-open if still ongoing or let's just build our new system a bit better.
