### ISSUE TITLE
Problem not seeing colleagues in chat

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#310]
GCCON-244
Stil having issue not seeing colleagues in my chat bar 
 for example 
 Even though they are online, I can never see Steven, Erin or Christina. 
 
 Although, they can see my name, but not on my end. 
 
 -- 
 
 ! I have been experiencing a bug with the GCconnex chat function. I cannot see everyone I'm connected with in the chat list (I tested this multiple times with colleagues). Colleagues will see me but I will not see them, so I can't connect with them (they have to reach out to me first). In addition, I created a public chatroom today (not password protected, not invite-only) for a chat session with colleagues from a few departments and no one could see this chatroom except me (I ended up having someone else create the chatroom so we could have the scheduled chat). Thanks in advance for looking into this. I did have the same issue while working in tbs. We tested it out with Gen and Mylène a few times (we would delete and re-add each other as colleagues to see if it fixed it, but it did not). I remember at the time Christine or maybe Ilia had said the April update should take care of it but it did not get fixed in my case. 
 
 I’m not normally bothered by it (other than when I want to talk to someone who is online but I can’t contact), but creating chatrooms that no one else can see is definitely a problem – I’m trying to organize more interdepartmental regular chats so that’s kind of important.

**Comment by Phanoix** [comment]
Part if this (seeing who's online and available to chat) is likely made problematic with the use of memcached to get the last activity time stamp, which does not get invalidated in gcconnex/elgg when a user performs an action (we tried changing that, servers were not very happy with the increased load).

The other part (chat rooms) sounds like it could be department/network-related since the server-side part clearly works when another user created it and will need more investigation / testing.

**Comment by Troy-Lawson** [comment]
Should be noted that an update to cometchat is currently being investigated by @cdegrass

**Comment by Phanoix** [comment]
Waiting to see if update helps.

**Comment by cdegrass** [comment]
Perhaps I should put in a crony job that reloads the memcached

**Comment by ToferC** [comment]
Closing as we're currently investigating IM upgrades and alternatives that should resolve this issue.
