### ISSUE TITLE
Issues with deleting a user

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#317]
GCCON-224
I think it times out when you try to delete a user.

**Comment by pandurx** [comment]
No PHP Error, the action times out and the page gives a 500 Error.

**Comment by pandurx** [comment]
Claire.Mcclymont1 has a phantom folder with GUID 266644 with 6 widgets

**Comment by pandurx** [comment]
Claire owns a folder, in that folder, Aaron created a subfolder. I am assuming we can't delete Claire is due to the fact that she does not have access to Aaron's subfolder, which creates an infinite recursion and the PHP thread runs out of memory (Segmentation fault)
