### ISSUE TITLE
Profile Editing

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#334]
GCCON-66
Hi! Great job on the new site. I can't edit anything in my profile right now. When I click on the Edit buttons, nothing happens. For my main profile info, the info appears and is mostly out of the margin of my page - no matter how I change the settings by zooming in or out, I cannot see it. I'm not sure if this is an issue due to my firewall or version of IE. We are using IE 11. Thank you! 
 ________________________________________________ 
 I can edit information boxes in my profile, but I don't see any save button. 
 I use Firefox 43.0.4 (my main browser) and IE 11.0.9600

**Comment by ethanWallace** [comment]
Asked for more information from the user, never received any feedback from them. Moving to blocked until feedback is received.

**Comment by ethanWallace** [comment]
@KevinChagnon Is the user still experiencing this issue or are we able to close this issue?

**Comment by ToferC** [comment]
Good to close this.  Thanks!
