### ISSUE TITLE
Suggested colleagues needs to be reworked

### ISSUE THREAD

**Issue by Phanoix** [gctools-outilsgc/gcconnex#418]
Suggested colleagues functionality is should be a separate independent module that can be added to pages. It should accept a few parameters such as number of suggestions to return to allow for some customization for each page it's displayed on. The method of fetching the suggestions and error checking needs to be looked at.

**Comment by piet0024** [comment]
Quick Idea on this. We also create a page in this mod where users can go to search for colleagues as well as see suggested colleagues.

**Comment by ToferC** [comment]
Please review as part of summer content refresh and upgrade to Elgg 2.3.

**Comment by Troy-Lawson** [comment]
wont fix
