### ISSUE TITLE
Update plugins to the current latest "official" releases

### ISSUE THREAD

**Issue by smellems** [gctools-outilsgc/gcconnex#425]
Some of the 3rd party plugins we use have newer versions available.

**Comment by smellems** [comment]
List of plugins with original repos:
http://www.gcpedia.gc.ca/wiki/GCconnex_Development/List_of_Plugins

**Comment by Phanoix** [comment]
progress:
* [ ] analytics  https://github.com/ColdTrick/analytics
* [ ] friend request  https://github.com/ColdTrick/friend_request
* [ ] blog tools   https://github.com/ColdTrick/blog_tools
* [ ] File Tools  https://github.com/ColdTrick/file_tools
* [ ] Polls  https://github.com/iionly/poll
* [ ] simplesaml  https://github.com/ColdTrick/simplesaml
* [ ] ...
* [ ] ...
* [x] event calendar
* [ ] ...
* [ ] ...
* [ ] ...
* [ ] ...
* [ ] ...
