### ISSUE TITLE
Use Composer for the installation of Elgg and all the third party plugins

### ISSUE THREAD

**Issue by smellems** [gctools-outilsgc/gcconnex#426]
This removes the burden of maintaining the code in our Repo.

Suggestion from Elgg team:
Separate your custom development into separate repos. Just treat them like a third party plugin. This way there is 1 master repo (your distribution), that is the repo you use to install/update (take a look at https://github.com/Elgg/starter-project. Plugin maintenance should be taken place in all the different plugin repos.

https://elgg.org/discussion/view/2570541/elgg-and-gcconnex-collaboration

**Comment by nschonni** [comment]
This would probably be a good project for the hackathon

**Comment by smellems** [comment]
I started something a few months ago to show how it would look: https://github.com/smellems/gcconnex-starter

If you look at the composer.json file, you can see most of the third party plugins used on GCconnex and the packages under smellems are ones created by the GCTools team or not available on Packagist

**Comment by nschonni** [comment]
OK, so the ones under your account are ones you've manually pulled out from this repo? 
If so, could they get transferred to the org and published to Packagist, or is there a permission issue there?

**Comment by nschonni** [comment]
@smellems actually it looks like filter branches could be used to extract the history of those mods out to their own repos https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by smellems** [comment]
Yes they should all be under the gctools-outilsgc org.  I just did it in mine to test it out and show it.  Those repos are not up to date with the mods from gcconnex.  And keeping the history would be great!

For permissions, your right somebody from the GCTools would need to create all the repos and publish / sync them with Packagist.

**Comment by nschonni** [comment]
Just tested it out with one and it seems to work well https://github.com/nschonni/GC_profileStrength
1. Checkout the gcconnex branch
1. Create a new branch with PLUGIN_NAME
1. Create the filter branch (this will wipe out the current branch and replace it) `git filter-branch --prune-empty --subdirectory-filter mod/PLUGIN_NAME/ PLUGIN_NAME`
1. Create a new empty GH repo with no license or README
1. Add the new remote `git remote add PLUGIN_NAME https://github.com/nschonni/PLUGIN_NAME.git`
1. Push the filtered branch to the empty repo `git push PLUGIN_NAME HEAD:master`

@smellems I guess then you can do what you you did with the composer file and add the new entry even without the Packagist publish

**Comment by nschonni** [comment]
The IRCC team is working on this. We can discuss the PR and migration of the repos at the end of the Hackathon

**Comment by nschonni** [comment]
FYI, our internal fork PR https://github.com/gctools-hackathon-ircc/gcconnex/pull/13
We're looking to see about anything that has landed in the last day our so

**Comment by nschonni** [comment]
During the Hackathon @Abutu @chown-your-poptarts did the manual split of the plug-ins prior to the hackathon:
- [x] b_extended_profile
- [x] gc_api
- [x] gc_group_deletion
- [x] GC_profileStrength
- [x] GoC_dev_banner
- [x] ideas
- [x] missions
- [x] missions_organization
- [x] missions_profile_extend
- [x] toggle_language
- [x] unvalidated_user_cleanup
- [x] wet4
- [x] achievement_badges
- [x] cp_notifications
- [x] custom_error_page
- [x] c_email_extensions
- [x] c_members_byDepartment
- [x] c_module_dump
- [x] gcforums
- [x] gcProfilePictureBadges
- [x] gcRegistration 
- [x] widget_manager_accessibility 
- [x] gc_fedsearch_gsa
- [x] gc_group_layout
- [x] gc_newsfeed
- [x] gc_official_groups
- [x] gc_onboard
- [x] gc_splash_page
- [x] gc_streaming_content
- [x] gccollab_stats
- [x] geds_sync

We'll PR this to track the progress, but we think creating a script to redo this when the GCConnex/GCollab developers are ready to move to this approach might be easier.

**Comment by ToferC** [comment]
@smellems @Phanoix - has this pull request been merged? If not, please update. If yes, please close issue. Thanks!

**Comment by smellems** [comment]
#956 was merged, but only removed the vendor folder that now gets installed using Composer.

I think we can close this since we now have an issues for splitting up the mods #1150
