### ISSUE TITLE
Upgrade to Elgg 2.x or 3.x

### ISSUE THREAD

**Issue by smellems** [gctools-outilsgc/gcconnex#427]
Elgg 2.x is the latest Stable version, however, depending on our schedule, we could skip 2.x, because the plan is to release Elgg 3.0 in Q1 of 2017.

**Comment by Phanoix** [comment]
It'll be the latest version of 2.x most likely.

**Comment by ToferC** [comment]
This is now a milestone that will incorporate smaller issues. Closing.
