### ISSUE TITLE
Source of deleted files (404 page not found)

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gcconnex#448]
Apologies if this is already being looked at, but when a user deletes a file, the link sends you to a generic 404 page.

e.g. [A look at the impact of Onboarding and Career Connexions on GCconnex User Registrations](https://gcconnex.gc.ca/file/view/24110274/a-look-at-the-impact-of-onboarding-and-career-connexions-on-gcconnex-user-registrations) 

Can we not show the user in which group/profile/discussion etc...this element existed before it was deleted?
For example, the above file was posted to [files section of the GC2.0 Tools group](https://gcconnex.gc.ca/groups/profile/7108318/gc20-tools-team).

**Comment by Steph4104** [comment]
Need to talk with Phil and Gen

**Comment by ToferC** [comment]
@Steph4104 - did you talk with @LemieuxGen - if not, please come see me next week.

Thanks!
