### ISSUE TITLE
access level for images

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#481]
We need to be able to add access levels (private, public, etc.) to images. Currently, the images don't have an access level, the access level is based on the access level of the photo album. 
Suggestion: by default, the image should take the access level of the photo album. The users should be able to see the Access Level drop down option, and be able to modify it (same as for group content).
If no,
add a note/text in the image that tells users that the access level of the image is based on the access level of the photo album. 
Thanks!

**Comment by Troy-Lawson** [comment]
closed as enhancement to legacy system
