### ISSUE TITLE
Find Members Search Query needs to be optimized

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#495]
Searching from Find Candidates / Find Members takes 12+ seconds to resolve.  This needs to be faster for a good user experience.  Require heavy optimization of search or reduce scope to only search for skills and update search box text.

**Comment by Phanoix** [comment]
There doesn't seem to be any problem with the way it's constructed in the missions mod, in mm_simple_search_database_for_candidates(), however looking closely at / playing around with the query generated I found that it's at least an order of magnitude faster if a LEFT JOIN was used (allowing the query to only run the text search on the relevant objects) and/or if the DISTINCT was removed (which I don't think actually does much here)

**Comment by ToferC** [comment]
Did you update this on prod? Seems way faster this morning.

**Comment by lucbelliveau** [comment]
Not me; @Phanoix ?

**Comment by Phanoix** [comment]
Not the simple search, execution time does vary somewhat depending on the search string and some might have been cached, and there likely was less load on the server in the morning.

**Comment by lucbelliveau** [comment]
@cdegrass Any ETA on a dataset I can use to reproduce this?

**Comment by lucbelliveau** [comment]
I am still waiting on a dataset so properly implement this...

**Comment by ToferC** [comment]
@phanoix- can you pls. Confirm w/ Charles. I know he was working on this on Monday. Thanks!

**Comment by ToferC** [comment]
Just spoke with Charles. Should be up by end of day. Had an issue with server set up.

**Comment by lucbelliveau** [comment]
Any update on the data @cdegrass @ToferC ?

**Comment by ToferC** [comment]
Sorry @lucbelliveau - didn't even see Charles today. Will follow up
tomorrow ASAP.

**Comment by lucbelliveau** [comment]
Searches are running rather fast on my machine... instantly in fact...  configured with 10GB of memory for innodb.. (same as on the dev server) - Are you still having speed issues with this?

**Comment by ToferC** [comment]
I think this is now live on production.  Still fairly slow (10-12 sec), though. @cdegrass @Phanoix - can you please confirm config and memory on prod?

**Comment by lucbelliveau** [comment]
As long as there is enough RAM to load the keys in memory, the query should return in less than a second... as it does on mine... (unless there are other differences on the server)... 

I don't have access to the server, could someone send me the result of this query on the production database server:

`EXPLAIN SELECT SQL_CALC_FOUND_ROWS user_guid, GROUP_CONCAT(DISTINCT field SEPARATOR '!!!!!') as reason, SUM(relevance) as relevance FROM ( SELECT a.guid as user_guid, CONCAT('name:::::', a.name) as field, ((MATCH(a.name) AGAINST("management*" IN BOOLEAN MODE)) + 0) as relevance FROM elggusers_entity a WHERE ((MATCH(a.name) AGAINST("management*" IN BOOLEAN MODE))) UNION SELECT c.guid AS user_guid, CONCAT(d.string, ':::::', a.string) AS field, ((MATCH(a.string) AGAINST("management*" IN BOOLEAN MODE)) + 0) as relevance FROM elggmetastrings a LEFT JOIN elggmetadata b ON a.id = b.value_id LEFT JOIN elggusers_entity c ON c.guid = b.owner_guid LEFT JOIN elggmetastrings d ON b.name_id = d.id WHERE c.guid IS NOT null AND d.string IN ('contactemail') AND ((MATCH(a.string) AGAINST("management*" IN BOOLEAN MODE))) UNION SELECT eue.guid as user_guid, CONCAT(es.subtype, ':::::', eoe.title) as field, ((MATCH(eoe.title) AGAINST("management*" IN BOOLEAN MODE))) as relevance FROM elggmetastrings ems LEFT JOIN elggmetadata em ON ems.id = em.value_id LEFT JOIN elggusers_entity eue ON eue.guid = em.owner_guid LEFT JOIN elggentities ee ON CAST(ee.guid as char(10)) = ems.string LEFT JOIN elggentity_subtypes es ON es.id = ee.subtype LEFT JOIN elggobjects_entity eoe ON ee.guid = eoe.guid WHERE eue.guid IS NOT NULL AND ee.subtype IN (SELECT id FROM elggentity_subtypes WHERE subtype IN ('MySkill', 'education', 'experience', 'portfolio')) AND ((MATCH(eoe.title) AGAINST("management*" IN BOOLEAN MODE))) ) matches GROUP BY user_guid ORDER BY relevance DESC, reason LIMIT 10;`

Also try to run the query without explain and see how long it takes... (run it twice in a row to compare index loading)

Thanks

**Comment by ToferC** [comment]
@lucbelliveau @cdegrass @Phanoix 

Results from EXPLAIN:
Your SQL query has been executed successfully.
1	PRIMARY	<derived2>	ALL					7318128492024	Using temporary; Using filesort	
2	DERIVED	a	fulltext	name	name	0		1	Using where	
3	UNION	d	ref	PRIMARY,string_2,string	string_2	767	const	1	Using where	
3	UNION	a	fulltext	PRIMARY,string	string	0		1	Using where	
3	UNION	b	ref	name_id,value_id,owner_guid,elggmetapairs	elggmetapairs	8	elgg.a.id,elgg.d.id	26	Using where	
3	UNION	c	eq_ref	PRIMARY	PRIMARY	8	elgg.b.owner_guid	1	Using index	
4	UNION	eue	index	PRIMARY	admin	1		109106	Using where; Using index	
4	UNION	em	ref	value_id,owner_guid,elggmetapairs	owner_guid	8	elgg.eue.guid	161	Using where	
4	UNION	ems	eq_ref	PRIMARY	PRIMARY	4	elgg.em.value_id	1		
4	UNION	elggentity_subtypes	index	PRIMARY	type	153		67	Using where; Using index	
4	UNION	ee	ref	subtype	subtype	5	elgg.elggentity_subtypes.id	6218	Using where; Using index	
4	UNION	es	eq_ref	PRIMARY	PRIMARY	4	elgg.elggentity_subtypes.id	1		
4	UNION	eoe	eq_ref	PRIMARY	PRIMARY	8	elgg.ee.guid	1	Using where	
	UNION RESULT	<union2,3,4>	ALL						Using temporary	

Results from running the query: 504 timed out error.  I killed the process following the error at 120 seconds.  I ran it again and got the same error at 60 seconds.

**Comment by lucbelliveau** [comment]
Oh wow.. .the production database is significantly larger than what I am using...  line 1 explains why it is so slow... over 7 trillion rows...  which occurs because it's not enough to find all the results, the system wants to know what matched and has to group them... I think in this case, splitting the query in 2 will result in less rows being examined... and overall be much quicker.  I will work on that ASAP.

**Comment by ToferC** [comment]
Hi @lucbelliveau - @Phanoix or @lucbelliveau should be getting back to you shortly.  Just to note, another option for this issue is to scope back that search field to skills only and update the language fields.  If we can't get the full query to perform while still maintaining the core Elgg scheme, this might be the way to go.

**Comment by Phanoix** [comment]
Explain:

+----+--------------+--------------+----------+--------------------------------+----------------+---------+---------------------+------+------------------------------------+
| id | select_type  | table        | type     | possible_keys                  | key            | key_len | ref                 | rows | Extra                              |
+----+--------------+--------------+----------+--------------------------------+----------------+---------+---------------------+------+------------------------------------+
|  1 | PRIMARY      | <derived2>   | ALL      | NULL                           | NULL           | NULL    | NULL                |  110 | Using temporary; Using filesort    |
|  1 | PRIMARY      | b            | eq_ref   | PRIMARY                        | PRIMARY        | 8       | der.user_guid       |    1 | NULL                               |
|  2 | DERIVED      | a            | ref      | PRIMARY,string_2,string        | string_2       | 767     | const               |    1 | Using index condition; Using where |
|  2 | DERIVED      | c            | fulltext | PRIMARY,string                 | string         | 0       | NULL                |    1 | Using where                        |
|  2 | DERIVED      | b            | ref      | name_id,value_id,elggmetapairs | elggmetapairs  | 8       | elgg.c.id,elgg.a.id |   26 | NULL                               |
|  3 | UNION        | a            | fulltext | name                           | name           | 0       | NULL                |    1 | Using where                        |
|  4 | UNION        | a            | fulltext | fulltext_title                 | fulltext_title | 0       | NULL                |    1 | Using where                        |
|  4 | UNION        | b            | ref      | PRIMARY,string_2,string        | string_2       | 767     | func                |    2 | Using where                        |
|  4 | UNION        | c            | ref      | name_id,value_id,elggmetapairs | elggmetapairs  | 4       | elgg.b.id           |   41 | NULL                               |
|  4 | UNION        | d            | eq_ref   | PRIMARY                        | PRIMARY        | 4       | elgg.c.name_id      |    1 | NULL                               |
| NULL | UNION RESULT | <union2,3,4> | ALL      | NULL                           | NULL           | NULL    | NULL                | NULL | Using temporary                    |
+----+--------------+--------------+----------+--------------------------------+----------------+---------+---------------------+------+------------------------------------+
11 rows in set (5.79 sec)

**Comment by lucbelliveau** [comment]
@Phanoix is that the results for the create table query I sent via email?

**Comment by cdegrass** [comment]
We have 32GB ram on the SQL box,  mostly all dedicated to SQL

**Comment by lucbelliveau** [comment]
@ToferC The skill fields are actually the problem and main source of problems...  Another option would be to offload search to something like SOLR ...  I could set that up easily enough; but do you have the infrastructure agility to deploy new services?  

I can still prepare the refined view; even though it adds a new database table to the schema, I can wrap it up into a plugin, so upgrading the schema would be built in.  (Same as things like cometchat)

I can do the view as step #1, and we can examine SOLR or some other full text indexer later?

Please advise.
