### ISSUE TITLE
Opportunities Platform Analytics - Additional Data Required

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#498]
Currently tracking Posted, Cancelled, Completed.

Should also track:

- Offered (when offers made)
- Declined  (when offers declined)
- In Process (when offers accepted)

**Comment by lucbelliveau** [comment]
@ToferC , Just to clarify, are you asking for an additional option for stacked graph's "Separate opportunities by" labelled "Offered/Declined/In Process" - or a combination of the existing "Posted/Cancelled/Completed"?  (Becoming "Posted / Cancelled / Completed / Offered / Declined / In Process") ... ?  If the latter we may want to choose a new field name... maybe "Status"?

**Comment by ToferC** [comment]
I was thinking of a single continuum showing status: Posted  / Offered / Declined / Accepted or In Process  / Completed / Cancelled. This could be a new field name if that makes sense for the rest of the application. 

Optimally I'd also like to show this status visually on the cards as well. 

The use cases are: as an employee seeking opportunities I want to know which are actually open vs. Filled without having to look at the opportunity.

As an opportunity creator I want people to be able to find my opportunity quickly, but I also don't want new people to continue to apply to my opportunity once I have filled it. 

As a business analyst, I want an easy way to track the overall metrics and success of activities on the opportunities platform. Relevant to status, this includes how many opportunities are posted, accepted, declined, are currently in process as well as those that are completed or cancelled.

**Comment by lucbelliveau** [comment]
The data mentioned in the issue (Offered, Declined, In Process) is already being collected in the database - so this is just a matter of leveraging that data.  Adding the information to the analytics tab, using the stacked graph, should be simple enough.  (That would cover the third use case above correct?)

For the first and second uses cases; I would suggest adding a filter to the Filter and Sort button; maybe even with filled opportunities filtered out by default?  (I imagine users don't want to see opportunities they can't apply for?)  Adding a filter makes it possible to see all if the user wishes... thoughts?  As far as a visual indicator, do you already have a design in mind?  I can ask the product designer on our team here about it if it helps?

**Comment by ToferC** [comment]
@luc-belliveau - Sounds good for use case 3.

I like the idea of the default filter & sort as you suggest.  For visual indicators, I'm totally open to suggestions and your designer's input would be great.  I was just thinking of something simple like slightly greying out the card (as the user can't apply to it when filled).

**Comment by lucbelliveau** [comment]
@ToferC I took a closer look at the data; and although all the data is being tracked, only "declined" is being stored in a way we can produce analytics.

The problem is "accepted" and "offered" are transient relationships that can be altered by users; for example if a user declines an offer, the record of that offer is also removed.

I can modify the system to store this information for analytics; however the data would only be available from future events.  (Declined on the other hand can be added for the entire history of the application).

**Comment by ToferC** [comment]
Hi @lucbelliveau - better now than never. I'm good with a day forward
approach. Thanks for digging into this.

**Comment by lucbelliveau** [comment]
@ToferC the type "In Process" - would it be safe to say "In Progress" or is it not the same?  (I am trying to find a suitable french translation and "In Process" is a bit ambiguous...  Or should it simply say "Accepted" ?

**Comment by ToferC** [comment]
In progress works great. Thanks, Luc. The problem with accepted is that
it's an instantaneous kind of thing. We're looking for a period of time
between accepted and complete.

**Comment by lucbelliveau** [comment]
@ToferC Are those uses cases in your comment captured in their own issue?  I think they are separate enough to this one...
