### ISSUE TITLE
More intuitive pagination / browsing / navigation / search for activity list

### ISSUE THREAD

**Issue by Phanoix** [gctools-outilsgc/gcconnex#5]
- Consider changing the bottom menu of the activity list (widget, page). Participants suggested using a calendar or a drop-down menu with the events of the last week or last month. 
- Add a sort or search function.
- Add a scroll menu to the activity feed so that scrolling down the menu automatically adds more posts (similar to Facebook and Twitter).

**Comment by Troy-Lawson** [comment]
@Phanoix @ethanWallace @piet0024 addressed in WET?

**Comment by piet0024** [comment]
Streaming news feed / additional filters have been added to the base elgg activity page
