### ISSUE TITLE
Invite to chatrooms option has mixed up results

### ISSUE THREAD

**Issue by TK1975** [gctools-outilsgc/gcconnex#509]
The search is alphabetical, however, seems to be broken up and mixed. A group of users names that begin with "A" appears at the beginning and then aggain, after Z. In this case, the individuals I was looking for had user names that begin with A, but I found them after the "Z's".

![chatroom](https://cloud.githubusercontent.com/assets/12700318/20575061/a6b51bbe-b185-11e6-9cd9-6ecd8c1be505.PNG)

**Comment by Troy-Lawson** [comment]
may be updating cometchat anyway

**Comment by ToferC** [comment]
Closing as this should be resolved through IM upgrade.
