### ISSUE TITLE
Folders are not sorted alphabetically

### ISSUE THREAD

**Issue by gabrielcossette** [gctools-outilsgc/gcconnex#514]
Folders are not sorted alphabetically, rather by "time created". I believe alphabetical sorting would be much better.

To reproduce:
1. Create a "bb" folder
2. Create a "aa" folder
3. The "aa" folder is after the "bb" one

I tried to change the "Default folder sorting options" in the group settings but it only affects the files, not the folders it seem.

Thanks!

**Comment by KevinChagnon** [comment]
There is an option for Group administrators; **Edit Group** -> **Admin Option** -> **Default folder sorting options**
Options are: Time created, Title, Description, Type  /  Ascending or Descending

Default seems to be:  Type / Ascending

These setting are not available for individual users.

**Comment by gabrielcossette** [comment]
As I mentioned in my bug, this seems to only affects files inside the folder.

**Comment by gabrielcossette** [comment]
This bug is still present. Also I just tested again and it seems the **Default folder sorting options** doesn't work for files either now.

You can look at this test group where I selected the **Title** sorting option: https://gcconnex.gc.ca/file/group/15779765/all#

**Comment by Troy-Lawson** [comment]
We will try to address is possible future files rework however in an effort to organize backlog I am closing this issue
