### ISSUE TITLE
Breaking Barriers Profile Badge

### ISSUE THREAD

**Issue by csclaunchpad** [gctools-outilsgc/gcconnex#519]
We are looking to create a new profile badge for the Breaking Barriers event.
For design details please contact Alison Rumsey (alison.rumsey@canada.ca)

#enhancment #newbadge

**Comment by Phanoix** [comment]
@ToferC @LemieuxGen

**Comment by LemieuxGen** [comment]
@ToferC I'm following up on this request. Do you have more information? was a decision made on if we're going forward with this?

**Comment by LemieuxGen** [comment]
@ethanWallace, as discussed previously, we need to add a new avatar badge in GCconnex for the breaking barriers challenge. Please find the information required for the new badge provided by the client. Please note that the badge needs to be available any time before end of day March 30th, in time for the testing on March 31st.
 
Colour: Any purple colour would be great! Something like colour code: a208e6
Visual Element: Star (see attached document).
![wbbc_badge_star](https://cloud.githubusercontent.com/assets/15378977/24297960/f0e3cf06-107a-11e7-918c-b1d33a0371e5.jpg)

Tag: Building diversity, inclusion and accessibility in the workplace / Bâtir la diversité, l'inclusion et l'accessibilité au travail
Group URL and Name: https://gcconnex.gc.ca/groups/profile/24229563/workplace-breaking-barriers-challenge-defi-%E2%80%93-mettre-un-frein-aux-obstacles-en-milieu-de-travail 
the group is currently closed but we will be opening it in May.
