### ISSUE TITLE
Invisible bulleted/numbered list in comments

### ISSUE THREAD

**Issue by gabrielcossette** [gctools-outilsgc/gcconnex#536]
Hi,

When we insert either a bulleted or numbered list in a comment, we don't see the actual bullets or numbers after we saved it. The visibility seems to have been overriden in CSS.

To reproduce:
1. Add a new comment
2. Insert either a bulleted or numbered list
3. Save and see

Thanks!

**Comment by joshcampbell191** [comment]
Hackathon: Claimed by team NOP

**Comment by gabrielcossette** [comment]
Please reopen, the bug is still there.
