### ISSUE TITLE
Hyperlink tags to search

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#537]
When clicking on any site "tags", the user is brought to the old search page which yields no results.  Clicking a tag should bring the user to a GSA search of that tag, or (even better) to a list of content that also has that tag.

**Comment by pandurx** [comment]
https://www.google.com/support/enterprise/static/gsa/docs/admin/72/gsa_doc_set/xml_reference/request_format.html#1089494

GSA should be able to pick up the meta name="keywords"

**Comment by KevinChagnon** [comment]
When clicking on any site "tags", the user is brought to the old search page which yields no results.
