### ISSUE TITLE
Add "Like" button to Groups' main page

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#552]
The "like" button for groups only appears in 2 areas:

1- In the list of groups a user is a member of which is displayed on the right hand side of a user's profile page.
2- In the list of Featured groups if a user clicks on the Groups Tab

Request to Add "Like" button to Groups' main page and/or by the Group's statistics when groups are viewed in a list

**Comment by ToferC** [comment]
Re-opening as "like" button not added to groups cards in list on https://gcconnex.gc.ca/groups
