### ISSUE TITLE
No access to type in the larger text boxes - E-Reader sends an error noise

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#558]
When attempting to create a discussion, the E-Reader will read off all the labels regarding the editing features (i.e. bold, italic, underline, left, center, right, etc.) but when she goes to type a message using her keyboard, the E-Reader sends an error noise and nothing occurs. However, for other sections such as "Title" or "Tags", she is able to successfully insert text. This same issue occurred when she tried to reply to another users topic discussion

**Comment by piet0024** [comment]
I have tested the CK editor (the rich text editor for comments and discussion text) with my screen reader (NVDA). If the user hits space on their keyboard when they are selected on that area or when they cycle through the editing features it should enter the text area and let them know they can type. It should also tell them they can press alt-0 for more help. 

So I can replicate the error noices happening when the screen reader reads the labels, but hitting space then enters the typing area.

**Comment by ToferC** [comment]
@piet0024 - how can we let our users who use screen readers know this?  Can we use alt-text or another way?  Hitting space doesn't seem intuitive to me (unless this is standard screen reader practice to enter text fields) and letting users know one by one isn't an answer.  Thanks!

**Comment by LemieuxGen** [comment]
@piet0024 we're preparing a response for the user. Did you find anything other solution for this issue? (e.g. alt-text instructions). Thanks!
CC: @KevinChagnon

**Comment by piet0024** [comment]
I would like to add some alternative instruction to the text editor saying "hit space to activate" because I can understand how it would not be clear. I haven't had the chance to develop this though. I would like to know if hitting space will allow this user to enter the text area.

**Comment by LemieuxGen** [comment]
@piet0024 thanks! @KevinChagnon will respond to the user and we'll let you know if the space bar worked.

**Comment by ToferC** [comment]
Closing.  Will track work in #807.
