### ISSUE TITLE
Allow for declining to add a Dates under Education in user profile

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#564]
As participation is voluntary and users are free to enter as much or as little information as they want (name and email at a minimum);
Please allow for users to decline to add Dates under "Education" in their user profile.
(allowing users to save their Education information without entering Start and End dates.

**Comment by KevinChagnon** [comment]
+1

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
