### ISSUE TITLE
Group owner/operator looking for audit trail

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#565]
User within Group "**PMRA Operations Sub-Committee**"
( https://gcconnex.gc.ca/groups/profile/19257985/pmra-operations-sub-committee )
Reports having "lost" a File folder they have been using for months to upload meeting minutes.
Name of folder: "**Meetings by Date**"
Folder seemed to have been deleted some 3-4 weeks ago without owners knowledge/consent.
User would like to know if it is possible to find out how/when the folder was deleted through an audit trail...?

**Comment by Troy-Lawson** [comment]
this is not possible for something so far in the past.
