### ISSUE TITLE
10000 unread notifications made pages very slow to load

### ISSUE THREAD

**Issue by smellems** [gctools-outilsgc/gcconnex#568]
I had been collecting notifications for the last 2-3 years and I was up to 10000+ unread site notifications.  Deleting them, has really made a big difference in the time it takes to load a page.  I noticed the site was a lot more responsive if I was not logged in..

I know this was discussed before but there should be a maximum number of notifications and the rest should just be deleted.

500?

**Comment by ToferC** [comment]
Support 500 notifications max.

**Comment by Phanoix** [comment]
The delay from having a lot of notifications most likely comes from it counting them every page load to get the number that appears in the menu.

**Comment by Phanoix** [comment]
Cleaned up notifications removing those older than 90 days.
