### ISSUE TITLE
External links to open in a new tab or window

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#569]
Could we change the code so that external links open in a new tab or window (?)

**Comment by piet0024** [comment]
In the output/url view we can test if the link string contains the site url and add target="_blank" if it does not.

**Comment by CPoulin1** [comment]
+1

**Comment by KevinChagnon** [comment]
+1

**Comment by nschonni** [comment]
https://css-tricks.com/use-target_blank/
