### ISSUE TITLE
Add minor edit option to discussions

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#572]
Please add the option for "minor edits" to all GCconnex group content: 
- discussion topics 
- files
- pages
- bookmarks
- Polls
- Ideas
Note: Blogs and Events already have this functionality.

This will avoid sending multiple and unnecessary notifications to users when making minor edits. This will also help with the issue where users believe they are receiving duplicate notifications, when in fact, they are receiving a second notification because someone made a modification to the content.

**Comment by piet0024** [comment]
I did some quick testing on production with discussions and I was not able to replicate getting a notification for editing the discussion. I had someone create a discussion, I commented, subscribed, was a member of the group and my settings were checked to get notifications. I asked them to edit the discussion and no notification was sent. 

However when we edited blogs, events and pages I did get notified of the edit if the minor edit option was not checked. 

I'll keep looking into this, but if the other content types do not create notifications when they are edited how should I proceed with this issue?

**Comment by LemieuxGen** [comment]
@piet0024 weird, I thought for sure discussions notifications where sent out when a discussion was edited. Can we still implement this on the other content items?

**Comment by piet0024** [comment]
I have tested all the content types on production. The content that gives notifications for edits are:
-blogs
-pages
-events

These content types also currently have the minor edit options when you edit them. Editing the other content types do not send a notification to users of the group or users subscribed to the content.

**Comment by LemieuxGen** [comment]
Weird, I could swear that option was only available for blogs before... thanks for looking into this. seems like this can be closed then...
