### ISSUE TITLE
Group widget for Discussion bring to a different discussion page (Discussion Topic vs Discussion)

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#588]
As user recently pointed that the default Discussion link that appears in in a group widget for discussions, brings users to the "Discussion Topic" page. This differs from the Discussion page that users land on when selecting the group's Discussion tab.
Why do we have 2 difference pages for discussions? Should we remove one? or default that the widget points to the same place as the discussion tab?
Additional detail and screen shot available on GCconnex: https://gcconnex.gc.ca/file/view/24313148/two-paths-to-group-discussions

**Comment by ToferC** [comment]
@beckyjeong - please review as part of your work.
