### ISSUE TITLE
Closed Group Members unable to see Uploaded files / notifications not received

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#589]
User Hejung.Kim uploaded 7 individual files to a closed Group : https://gcconnex.gc.ca/groups/profile/13250599/dsorc-cpasm

Files are located here: https://gcconnex.gc.ca/file/group/13250599/all#24276860

Documents are not visible to members of the group regardless of proper settings.
Posts do show in group activity tracking but members did not receive a notification.

**Comment by Troy-Lawson** [comment]
@KevinChagnon was this the issue we spoke about?

**Comment by KevinChagnon** [comment]
No...I do not believe we had discussed this particular issue.

I'm waiting for reply from the user to find out if this is still an issue.

**Comment by KevinChagnon** [comment]
Not receiving replies from user.
