### ISSUE TITLE
HTML table in email alert displays incorrectly

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gcconnex#599]
Table HTML coding seems to interfere with proper display of email description:
![connexemail](https://cloud.githubusercontent.com/assets/22220521/21108818/77c2fb8a-c064-11e6-98f6-5ab7864cf90f.PNG)

**Comment by pandurx** [comment]
@LemieuxGen maybe we should discuss on how to mitigate this, preferably not display the content itself in the notification.

**Comment by LemieuxGen** [comment]
@pandurx , is there any way we can keep the content of the page in the notification? The content is somewhat important for the notification... is there a way we can strip the HTML from the content for the notifications?

**Comment by pandurx** [comment]
It is possible to strip the HTML from the content, however, it may not be viewable/not a nice notification.

**Comment by pandurx** [comment]
@LemieuxGen can we further discuss on this issue?
Thanks.

**Comment by LemieuxGen** [comment]
@pandurx Absolutely, come by to see me when you're in the office.

**Comment by ToferC** [comment]
In our notification digest discussion, we decided to remove the table and replace with text "This content contains a table. Please select the link to view the content."

**Comment by pandurx** [comment]
Ok

**Comment by pandurx** [comment]
// 915 cyu - client wants the html tags stripped from the notifications
			$object_description = ($object->description != strip_tags($object->description)) ? "" : $object->description;


			$message = array(
				'cp_topic' => $object, 
				'cp_msg_type' => 'cp_new_type',
				'cp_topic_description' => $object_description,
			);

Disregard this comment

**Comment by pandurx** [comment]
Please review pull request
https://github.com/gctools-outilsgc/gcconnex/pull/837
