### ISSUE TITLE
Update onboarding module (profile+)

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#602]
In testing a new user, a) the onboarding module didn't trigger after sign-in and selecting department - I was just brought to the newsfeed screen.  The welcome module triggered the second time I went to Newsfeed.  B) There was no guidance in the Welcome module about completing a profile or even that a thing like a profile existed.

We should re-visit the onboarding module side-by-side with the GCcollab onboarding.

The onboarding welcome module should:
* Highlight the user profile
* Let users know what a profile is and that by creating a profile, it will encourage others to connect and work with them
* Offer to help users create their profile

The onboarding profile module should:
* Automatically launch when a user without a complete profile goes to their profile
* Add a profile walkthrough
* At minimum have an option for users to continue to the profile completion walkthrough.

**Comment by LemieuxGen** [comment]
@ethanWallace, just reviewed the new profile step of the welcome onboarding module on preprod. Looks great, just a few changes required in French.
- Buttons appear in English in the French window. Buttons should say: "Bâtir mon profil" ou "Visitez ma page de profil". the word "or" that appears between the buttons also needs to be changed to "ou".
![weolcome module_step6_fr change](https://cloud.githubusercontent.com/assets/15378977/26202480/93c91e10-3ba5-11e7-8e73-bae9f167123f.JPG)

- Other minor change required in the French language of step 5. Please change "Chercher" to "Recherche".
![weolcome module_step5_fr change](https://cloud.githubusercontent.com/assets/15378977/26202484/99e66258-3ba5-11e7-86c0-9dcb82e73d76.JPG)
