### ISSUE TITLE
strange characters instead of text on top next to profile pic (mobile)

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gcconnex#603]
While viewing GCconnex from a BlackBerry Q10, unusual characters appear instead o "notificatins" etc. text on top right next to profile pic.
![img_20161213_073725_edit](https://cloud.githubusercontent.com/assets/22220521/21140794/e674f4e0-c107-11e6-9cec-901b34340eed.png)

**Comment by pandurx** [comment]
BlackberryQ10
10.3.3.2163 (current release)

**Comment by pandurx** [comment]
I cannot replicate this error. This only seems to affect Phil's blackberry.
