### ISSUE TITLE
Name of Sub-group displayed in English while display preferences set to French

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#606]
The name of the Sub-group, when viewing list of members, is being displayed in English while preferences are set to be viewed in French.

Group: https://gcconnex.gc.ca/groups/profile/24199553/sft-functional-forum

![title_error_gcconnex](https://cloud.githubusercontent.com/assets/23527358/21155219/4b378c58-c13f-11e6-9088-fb093d1df607.jpg)

**Comment by KevinChagnon** [comment]
Another instance of this problem:

![french error pulling](https://cloud.githubusercontent.com/assets/23527358/21314812/03522a60-c5c7-11e6-8ccd-9d0e92b71688.jpg)

**Comment by Steph4104** [comment]
Will be fix in the rework of en/fr content
