### ISSUE TITLE
typo in the french notification of a page

### ISSUE THREAD

**Issue by RimaSakr** [gctools-outilsgc/gcconnex#610]
For the notification of  a page or a discussion we should add an e to the verbe mis , but if the notification is for a blog post there will be no need for the e.  

![notifications typo in french](https://cloud.githubusercontent.com/assets/23101205/21184394/4c42e6ba-c1da-11e6-980a-ac4340decf4e.jpg)

thanks,

**Comment by smellems** [comment]
Already fixed! Tested with @KevinChagnon
