### ISSUE TITLE
Opportunities Platform > Find Members > Searches do not reveal all users who match the queries

### ISSUE THREAD

**Issue by MichelleSegger** [gctools-outilsgc/gcconnex#615]
When doing a simple search or an advanced search, not all GCconnex user accounts that match the search parameters appear in the results.  Example : in the simple search if you search the word "project" only 9 results appear. I know for a fact that this account (https://gcconnex.gc.ca/profile/Joymosk) has the word "Project" in her skills but she does not appear in the results.

**Comment by lucbelliveau** [comment]
I've updated the query and now over 900 users are found by the search "project" (although the system has a setting which limits results to 100)  I also took the liberty to optimize the query so this should also fix #495 .  I'll be posting the pull request soon.

**Comment by ToferC** [comment]
Thanks @lucbelliveau- looking forward to seeing the fix!

**Comment by lucbelliveau** [comment]
ready for testing.  Let me know how it performs on your staging server...

**Comment by ToferC** [comment]
Thanks, @lucbelliveau ! @phanoix- can we push to pre-production for testing?

**Comment by Troy-Lawson** [comment]
@toferc this should already in preprod.  Test away

**Comment by Troy-Lawson** [comment]
Hi Luc, I was passed the following information via email, and am sharing here so everyone can be in the loop:
Hi guys,
When I tried to test in the simple find, this is what happened:

 ![fatal](https://cloud.githubusercontent.com/assets/1971552/22997361/0d9f444c-f3a0-11e6-9ba3-8dfa28105388.png)


The fuller results seems to work in the advanced find search for the same keyword (leadership as a skill in the advance find).

Merci!

Michelle

**Comment by Troy-Lawson** [comment]
I am able to replicate but got a bit more details:
![fatal2](https://cloud.githubusercontent.com/assets/1971552/22997425/531c498e-f3a0-11e6-9b01-55844068f37b.png)

**Comment by lucbelliveau** [comment]
Looks like an index is missing... I will double check and send the command over.

**Comment by lucbelliveau** [comment]
A new index has to be added... this query needs to be executed (and added to whatever script you use to seed the database ... )

`alter table elggobjects_entity add fulltext fulltext_title(title);`

where "elgg" is the database prefix (could be elgg_)

**Comment by lucbelliveau** [comment]
I just pushed a update file that should do it when you click "Upgrade" from the admin; however the query is likely to take a very long time to run... so the update process may timeout (it might be best to run it directly in mysql anyway - the update will be most useful for new installations)
