### ISSUE TITLE
User profile will not load for user - all other links work fine

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#619]
User : Brigid.Prince

" when she clicks on any link to her profile on GCconnex, the profile won’t load at all. (Everything else loads fine.) At first, she had 2000+ notifications so we deleted those to see if it would help; no change. "

User profile does load for me - unable to duplicate user's problem.

**Comment by Troy-Lawson** [comment]
Do you have an administrator account you are using?

**Comment by KevinChagnon** [comment]
I do have an admin account...

**Comment by Phanoix** [comment]
Does it fail to load and displays an error message of some sort or does it simply take a very long time / time out?

**Comment by KevinChagnon** [comment]
as per user: "doesn’t take me anywhere – nothing happens, just spins for a while until I click something else"

**Comment by Phanoix** [comment]
thanks, that at least points in in a direction to starting investigating this.

**Comment by Phanoix** [comment]
can't replicate this even on production.

**Comment by Phanoix** [comment]
Is this still happening, and have they tried clearing all browser cache or tested this on another machine?

**Comment by KevinChagnon** [comment]
I am waiting for an answer form the user who reported this issue.

**Comment by ToferC** [comment]
Please close. We can re-open if necessary.
