### ISSUE TITLE
Simplified Sign-on - update to login link on GCpedia page

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#622]
The **_Log in_** link at the top right corner of the GCpedia page should be changed so that it automatically logs in the user using simplified sign-on (for those who have it and are logged in with GCconnex), instead of having to go on the login page and selecting the "simplified sign-on" button. This eliminates unnecessary steps for the users.

**Comment by piet0024** [comment]
related to gctools-outilsgc/gcpedia#28
