### ISSUE TITLE
User gets Geocode error everytime porofile loads

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#636]
user: Eric.Archambault

Message from Webpage:
Geocode was not successful for the following reason: ZERO_RESULTS

see attached.

Could not replicate error

![geocode](https://cloud.githubusercontent.com/assets/23527358/21404660/4bfe6b50-c790-11e6-82b6-faffd7da4c38.PNG)

**Comment by Phanoix** [comment]
This functionality has been updated a few times since this was created, so this is most likely fixed by now. If the issue persists go ahead and reopen this.

**Comment by KevinChagnon** [comment]
This is still an issue:

User: martin.pinard

![martin pinard geo](https://cloud.githubusercontent.com/assets/23527358/24754779/c5a73f00-1aa5-11e7-9a50-18a4db878b0b.JPG)

**Comment by KevinChagnon** [comment]
👍 

User: BLonergan

**Comment by nschonni** [comment]
Just saw this now
![image](https://user-images.githubusercontent.com/1297909/28729763-950e19e6-739b-11e7-81d2-c622efb241c1.png)

**Comment by LemieuxGen** [comment]
Other users have reported getting this issue when searching/accessing a user profile. 
![profile_geocode issue](https://user-images.githubusercontent.com/15378977/29519242-9bef04fc-864a-11e7-9aff-1f6d4eb735fe.png)
