### ISSUE TITLE
Split language content for "Adress of the bookmark"

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#637]
Users should have the ability to enter bookmarks in both language. Same as the language split for the content title, description, etc. the field entitled "Address of the bookmark" (bookmark feature) should be split so that users can enter the English URL and the French URLs separately, and show only the URL of the language of choice (when both are available). 
![bookmark language split enhancement_dec22-2016](https://cloud.githubusercontent.com/assets/15378977/21426452/f75932dc-c81c-11e6-829d-8d83aff031ee.JPG)

**Comment by KevinChagnon** [comment]
+1

**Comment by KevinChagnon** [comment]
**#https://github.com/Phanoix/gccollab-help/issues/2**

**Comment by KevinChagnon** [comment]
@ToferC  @LemieuxGen does this warrant dev. work or will it be left for the redesign ?

**Comment by ToferC** [comment]
Suggest redesign.

**Comment by KevinChagnon** [comment]
https://github.com/Phanoix/gcconnex-help/issues/36

**Comment by KevinChagnon** [comment]
Closing as per notes from Oct. 31st

Contacted client to inform issue will be considered for redesign.
