### ISSUE TITLE
switching language when creating new content

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#639]
When creating new content (ex new bookmark in group), I enter the English content first, then click on the French link above the title field to switch to French to enter the French content. When clicking on the French link (this also applies to the English), it always brings me back to the top of the page, were I need to scroll back down to enter the content in the French fields. Although this is very minor, it is an unnecessary irritant for users. Perhaps there's a simple fix for this that would allow users to stay in the same section of the page when switching from one language to the other?
![bookmark language link_bug](https://cloud.githubusercontent.com/assets/15378977/21426937/af1f7456-c81f-11e6-94c3-f9ddb1eda3f3.JPG)

**Comment by Troy-Lawson** [comment]
closing as we will no likely work on this before rebuild
