### ISSUE TITLE
Request: Pop-up box asking how user wishes to receive group notifications

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#652]
"Group Notifications When joining a group; it would be helpful to have a popup box immediately after clicking the Join button, asking how the user wishes to receive the group notifications, and allowing them to quickly select email or site or both. Similarly, on the Notifications page, it would be helpful to have a "Turn off all site notifications" or Turn off all site notifications for groups"

**Comment by joymosk** [comment]
Why was this closed? It doesn't exist each time you join a group.
