### ISSUE TITLE
Comments box has overflowed onto blog text

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#655]
Comments box has overflowed onto blog text.

As seen here:
https://gcconnex.gc.ca/blog/view/24400026/is-it-possible-to-be-stressed-and-happy-in-a-job-est-il-possible-d%E2%80%99etre-a-la-fois-stresse-et-heureux-au-travail

**Comment by Phanoix** [comment]
It looks like the width is forced within the blog post, so I don't think there are any system-related issues left now. If I'm missing something please provide more details and reopen the issue.
