### ISSUE TITLE
System does not recognize the apostrophe when you select "Share to GCconnex" from GCintranet

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#664]
When you select "Share to GCconnex" from GCintranet, the system does not recognize the apostrophe. For example, I'm displays on the wire as "I & # 0 3 9 ; m" (without spaces - GitHub changes it to "I'm" if I don't put spaces)
see pic and link

https://gcconnex.gc.ca/thewire/owner/dmarion

![gcintranet apostrophe](https://cloud.githubusercontent.com/assets/23527358/21810626/8c4426e8-d71a-11e6-996e-5231ec4c9071.JPG)

**Comment by piet0024** [comment]
Have recently noticed this is also a problem with spaces (%20) on a wire post that was shared from GCIntranet.
