### ISSUE TITLE
Make user activity viewable to all users

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#667]
Currently, in GCconnex, only admin users have the ability to view users' activities on GCconnex. Make the user activity information available and viewable by all users. User activity should be added in the following places: 
-  in the User Profile page, under "More", add link to "Activity" (French should read: "Activités") ![auser activity](https://cloud.githubusercontent.com/assets/15378977/21820073/40708d02-d73c-11e6-942f-52f1ec2c11a1.png)
- in the user card (available when clicking on the arrow option in the user's avatar - i.e. from the newsfeed) add a link to "View activity" (French should say "Afficher les activités".  ![user activity user card](https://cloud.githubusercontent.com/assets/15378977/21820151/9ce74832-d73c-11e6-849d-ad1a36b33167.JPG) 
Note: this already exists when you have admin rights, we just need to make it available to all users. 
![user activity user card _admin view](https://cloud.githubusercontent.com/assets/15378977/21820444/a43b17e8-d73d-11e6-96b0-4ab7fe6e98b9.JPG)

**Comment by Phanoix** [comment]
The link just needs to be added, users should already have access to it if they know how to get to it (which currently is not quite so simple).
