### ISSUE TITLE
User to be automatically signed-up to the official groups

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#672]
As a super user, I need to encourage users to use groups and we'd like to have them see activity as soon as they login to GCconnex for the first time, to make it easier to participate on the platform, rather than having them figure out right away what groups to join.
The hope is that this will encourage them to join other groups, participate in the groups they've been signed up in, and by seein activity just by signing up, continue to use the platform rather than sign up and never come back.in order to / because New Feature Request

Super User - GCconnex

**Comment by ToferC** [comment]
Related to #584 #462 - @LemieuxGen @PhilAndrecheck to scope official group implementation before we implement this.
