### ISSUE TITLE
gcconnex: Badges and skill endorsements to be shown in activity feed and notifications

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#673]
As a Regular User, I need Badges and skill endorsements to be shown in activity feed and notificationsin order to / because Everyone should know how awesome I am.  Even me!

christopher.allison@tbs-sct.gc.ca - 1/12/2017 10:01:42

**Comment by Troy-Lawson** [comment]
may not be relevant after rebuild
