### ISSUE TITLE
Title of blog not changing to language selected by user when content available in both languages

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#676]
The language in which the title of a blog is displayed is dependent on the language setting of the page as opposed to that of the language selection within the blog post when content is available in both official languages.

Image 1: Page setting "English", Blog setting "English"
![english page - english blog](https://cloud.githubusercontent.com/assets/23527358/21903222/0555a3b4-d8cd-11e6-8071-4c92d8dfa6fd.JPG)

Image 2: Page setting "English", Blog setting "French".  Content of blog changed to French, tittle did not.
![english page - french blog](https://cloud.githubusercontent.com/assets/23527358/21903262/31c0af5c-d8cd-11e6-82d5-93d5b7f95310.JPG)

Image 3: Page setting "French", Blog setting "French". Page, blog content and *blog tittle* displays in French
![french page - french blog](https://cloud.githubusercontent.com/assets/23527358/21903340/7a392cf0-d8cd-11e6-9b03-320d2111ab69.JPG)

link to blog: https://gcconnex.gc.ca/blog/view/24429187/please-share-celebrate-success-%E2%80%93-cioc-community-awards-2017

Request: Title of Blog posts be dependent of the language setting chosen within the blog post.

**Comment by ToferC** [comment]
Approved for work as low priority as relates to OL and usability.

**Comment by klecuyer** [comment]
This is true for all posts: discussions, blogs, polls. +2

**Comment by Steph4104** [comment]
This is how I build it, it change only the content, not the title. 
Do we want to change the title and the content or use this function to change the language of the site. (Same as the language function in the top right of the page)

![image](https://user-images.githubusercontent.com/15112568/30758528-c1a391a8-9fa0-11e7-8d49-b8a28764049a.png)

**Comment by LemieuxGen** [comment]
@Steph4104 What was the fix applied for this? I just tried to change the language of a page using the link in "Ce contenu est aussi disponible en français" and the title didn't change... but I was sure that's what we decided on.  Can you confirm? thanks!

**Comment by Steph4104** [comment]
It's merge now, should be on prod next week-end.
