### ISSUE TITLE
Polls: Ability to Close polls to retain and display results after poll periode has ended

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#677]
Users only have the option to delete a poll once their desired poll period has ended preventing them from retaining the poll results for other users to view.

Request: Allow users to close polls in order to be able to share the results once the poll period has ended. while retaining the ability to delete the poll once its use has expired.
In addition to this, it would be beneficial to have the ability to not only select “All”, “Mine” or “Colleagues” when searching for polls, but also the ability to choose “Open”, “Closed” or “All” as a sub-selection to each of the aforementioned selection options.

this will provide more flexibility in the use of the Poll feature.

**Comment by klecuyer** [comment]
+1
