### ISSUE TITLE
Language change required - English wording for "Activity" appears appears in the French

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#686]
when navigating GCconnex in French, in the group page's menu (tabs), the English word "Activity" is used instead of "Activité". Change to "Activité".
![group activity](https://cloud.githubusercontent.com/assets/15378977/21987556/0ea80094-dbd2-11e6-9cd2-8da76eea08ad.JPG)

**Comment by ToferC** [comment]
Approved for language change.  Please action.
