### ISSUE TITLE
Loss of images on Group page when changing Group owner

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#687]
When a new Group owner is assigned, Group banner image and avatar is lost.
If previous Group owner is made owner again, images come back.

**Comment by klecuyer** [comment]
This is a current issue on GCconnex. Just tested with Kevin. When transferring group ownership the cover photo gets deleted.
![image](https://user-images.githubusercontent.com/29754185/28584000-2a902596-7139-11e7-94d1-68840203c3bb.png)

Link to test group: https://gcconnex.gc.ca/groups/profile/24287816/enmy-closed-groupfr

**Comment by LemieuxGen** [comment]
This issue is still ongoing. May have resurfaced because of fixe related to: #1455

**Comment by LemieuxGen** [comment]
FYI - @KevinChagnon @klecuyer
