### ISSUE TITLE
Add search to Opportunity Platform Archives

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#688]
User story:

As a user, I need to be able to search archives to find specific or general opportunities so that I can a) duplicate them, thereby saving time and energy or b) see what opportunities others have created.

Please add regular opportunity search functionality to allow searching of archives.

**Comment by lucbelliveau** [comment]
@ToferC Does the functionality to duplicate opportunities already exist, or is that required here as well?

**Comment by ToferC** [comment]
Duplicate functionality already exists.
