### ISSUE TITLE
When selecting "Find" from opportunity, return users with skills and opportunity type

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#690]
Current functionality: selecting Find from an opportunity returns users with matching skills from users who have opted in for ALL opportunity types.

Required functionality: search should return and prioritize
1) Users who have opted in to the opportunity type who have all skills
2) Users who have opted in to the opportunity type who have some skills (descending)
3) Users who have not opted in to the opportunity who have all skills
4) Users who have not opted in to the opportunity who have some skills (descending)

**Comment by ToferC** [comment]
@Phanoix - did we merge a pull request on this?  Thanks!

**Comment by Phanoix** [comment]
I think this is very similar to some MM search work I did a while back, and that would have been in production for a while, not sure if it met all those requirements as needed but at most it should just need some tweaking to get the ordering right.
