### ISSUE TITLE
Send notifications to opportunity users when opportunity filled

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#692]
Desired functionality: when an opportunity is filled, (offered, accepted), a notification is sent to unsuccessful applicants letting them know that the opportunity has been filled and thanking them for applying.

Suggested language: "Thank you for applying to this opportunity.  Unfortunately, the opportunity was offered to another applicant, but we look forward to seeing you apply for other opportunities."

User stories:

As a user, I want to know when an opportunity is filled (even if I didn't get it) so that I am not left hanging.

As an opportunity creator, when I fill an opportunity, I want everyone who has applied to the opportunity to be notified automatically so I don't need to do it manually and/or I don't forget to do it.

**Comment by ycharron** [comment]
In regards to the suggested language:
* Are you satisfied with the above for the en?
* For title, what would you like? (e.g. The opportunity <oppurtunity name> has been filled.)
* French translations?

Thanks,
Yves

**Comment by ToferC** [comment]
@LemieuxGen - can you please confirm translation. I'm good with EN and
title.

**Comment by LemieuxGen** [comment]
@ycharron @ToferC 
Here's the French text: 
FR Title: Cette opportunité à été comblée
FR Body Text: 
Nous vous remercions de votre candidature. Malheureusement, cette opportunité a été offerte à un(e) autre candidat(e), mais nous avons hâte de vous voir postuler pour d'autres opportunités.

Thanks!
Gen
