### ISSUE TITLE
Additional filters required for opportunity platform analytics

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#695]
Allow analytics filtering by:
* Department
* Opportunity Type
* Opportunity Status

M. Segger to outline specific business requirements.

**Comment by lucbelliveau** [comment]
Will the specific business requirements be added to this issue?

**Comment by ToferC** [comment]
Hello Luc,

The requirements are to add filters allowing users to drill down more into specific opportunities.  

We already have filters by department, but here are some illustrative examples:

- Analytics on the location for completed <opportunity status> micro-missions <opportunity type> in TBS <department>
- Analytics on program areas for posted <opportunity status> secondments <opportunity type> in NRC <department>
- Analytics on virtual opportunities areas for active <opportunity status> mentoring <opportunity type> in HC<department>

Does this make sense?

**Comment by Eldoraaoun** [comment]
Here are a few filters Michelle S. and I have drafted : 

- Opportunity status (ex: completed)+ Department (ex: Treasury Board) + Opportunity type (ex: micro-missions) 
- Reason to Decline + Department + Opportunity type
- Virtual Opportunity  + Department + Opportunity type
