### ISSUE TITLE
Group Forums: Q&A style forum environment - voting on best answers, categorizable questions etc

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#701]
"The Phoenix community could really benefit from a true Q&A style forum environment where much needed knowledge could quickly be shared. For collaboration, I would very much like to see additional functionality that would bring a searchable Q&A style forum environment. Posted Questions should be categorizable; this would enhance search capabilities. Users should be able to vote on best answers. Admins should have the ability to moderate questions and answers. For an idea of what is required, see http://stackoverflow.com/ "

**Comment by ToferC** [comment]
Great idea for a new GCTool.  This might be a potential partner work item for next FY.

**Comment by ToferC** [comment]
Closing as dealt with through gctools-outilsgc/gcconnex#1109 .
