### ISSUE TITLE
gcconnex: The ability to designate a group as a project and close it down when I'm done while keeping the information

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#705]
New Feature Request
As a Super User, I need The ability to designate a group as a project and close it down when I'm done while keeping the information because Current group functions don't work well for limited duration projects.

 - 1/17/2017 16:29:39

**Comment by ToferC** [comment]
Related to future work on broader issues/project layer on GCconnex. Approved for scoping in 2017-18FY and possible inclusion in work plan.

**Comment by Troy-Lawson** [comment]
will look to include as feature in rebuild. information architecture should be considered. closed for current work
