### ISSUE TITLE
Ability to change banner as group admin but not owner

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gcconnex#708]
Related to #687, if you are a group administrator (but not the owner), you cannot change the banner image. Even though the functionality is available to non-owner admins, if an admin tries to change the banner image, it only removes the current image.

**Comment by ToferC** [comment]
@ethanWallace - can you confirm if this issue should be closed re: #687 - Thanks!

**Comment by ethanWallace** [comment]
@ToferC - I don't believe this issue has been looked at yet.
