### ISSUE TITLE
"Like" notification should include link to item liked

### ISSUE THREAD

**Issue by PhilAndrecheck** [gctools-outilsgc/gcconnex#714]
When a user receives a notification of a "like", there is no link back to what the person liked e.g.:
Here's the link to the "Suggestion box?" discussion: https://gcconnex.gc.ca/discussion/view/24479423/suggestion-box

Here's the text of the email (there was no hyperlink to the reply in the discussion):

(Le français suit)
Chris Allison liked your reply to 'Suggestion box?' 
Your reply to 'Suggestion box?' was liked by Chris Allison 
Learn more about GCconnex notifications. Need help? Contact us.
To unsubscribe from these notifications, login to GCconnex and edit your notifications' settings.
Chris Allison a aimé votre réponse à 'Suggestion box?' 
Votre réponse à 'Suggestion box?' a eu une mention j'aime par Chris Allison 
Apprenez davantage au sujet des notifications de GCconnex. Besoin d’aide? Contactez-nous.
Pour vous désabonner de ces notifications, connectez-vous à GCconnex et modifiez vos paramètres de notifications.
-

**Comment by ToferC** [comment]
Approved for enhancement.  Low priority, but let's not forget about this.  It should be a quick fix.

**Comment by Troy-Lawson** [comment]
closed as enhancement to legacy system
