### ISSUE TITLE
Selection of language proficiency for the job opportunity not displaying saved settings

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#715]
From the drop down list, CBC was selected for English and CBC was selected for French, but the poster is showing CCC for the French

Was is displayed: 
![langauge poster](https://cloud.githubusercontent.com/assets/23527358/22120887/a23d2b16-de4f-11e6-8933-58b46e373597.jpg)

Actual settings:
![language settings](https://cloud.githubusercontent.com/assets/23527358/22120891/aa148a96-de4f-11e6-92d0-f8f62b561863.jpg)

link to opportunity: https://gcconnex.gc.ca/missions/view/24465030

**Comment by ToferC** [comment]
Approved for fix and given medium priority re: language requirements on opportunity platform.
