### ISSUE TITLE
Posts/comments from users replaced with Discussion topic when selecting to view content in other language

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#723]
Posts/comments from users replaced with Discussion topic when selecting to view content in other language. This behaviours continues when switching languages.  If you return to list of Discussion then go back to the Discussion in question, then posts/comments are displayed as normal.

![original discussion](https://cloud.githubusercontent.com/assets/23527358/22211158/2f57fdde-e15a-11e6-8833-6d71e81d2527.JPG)

After selecting "Ce contenu est aussi disponible en français":

Could not upload second image due to network issues. will try later

**Comment by ToferC** [comment]
Same issue as #769

**Comment by LemieuxGen** [comment]
Closed issue #769 and added the content here: 

When you look at a discussion, and use the link "This content is also available in English" OR "Ce contenu est aussi disponible en français", the comments in the discussion change to show the initial discussion post. (This happens in both English and French).
Example: https://gcconnex.gc.ca/discussion/view/24574031/have-your-say-help-us-improve-gcintranet

Initial post with discussion (BEFORE using the language split link.
![language split link_1](https://cloud.githubusercontent.com/assets/15378977/22553806/05bae64c-e92c-11e6-9e67-684338e01099.JPG)

AFTER clicking on the language split link to see the FRENCH content "Cette discussion est aussi disponible en Francais"
![language split link_2](https://cloud.githubusercontent.com/assets/15378977/22554122/0aa2efa0-e92d-11e6-962a-d432d74e009e.JPG)

AFTER clicking on the language split link to see the ENGLISH content "This content is also available in English"
![language split link_3](https://cloud.githubusercontent.com/assets/15378977/22554131/122a5c2c-e92d-11e6-8b93-45ef5ee46197.JPG)
