### ISSUE TITLE
Events automatically being removed from group calendar

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#724]
"When we create a new event and add it to our group we are only able to add 15 events. Once a 16th event is added, the 1st event is removed from the groups calendar. Moreover once it has been removed via this bumping it can no longer reappear on the calendar even if we remove it and re-add it. The only way to get events to appear is to create new ones which bumps the old ones.

This is happening in this group calendar: https://gcconnex.gc.ca/event_calendar/group/24234607

Is there any way to increase the number of events we can add to the group calendar?

**Comment by Troy-Lawson** [comment]
@markwooff

**Comment by pandurx** [comment]
i can't seem to be able to create event calendar on my localhost (displays error regarding not filling required fields, but i have all the fields filled in)

**Comment by Troy-Lawson** [comment]
update may fix.
