### ISSUE TITLE
gcconnex: As a GCconnex Group Owner, provide an option whereby I can capture the Discussion feedback into an "Export to Excel" format, for example.

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#725]
Enhancement of existing feature
As a Super User, I need As a GCconnex Group Owner, provide an option whereby I can capture the Discussion feedback into an "Export to Excel" format, for example. because As a GCconnex Group Owner, I can start (create) a "Discussion", yet the current GCconnex "Discussion" layout/template does not offer me (as owner) the ability to export the 'feedback' received into a format that I can prepare an analysis report (e.g.  have an "Export to Excel" format).

By doing this, I can capture feedback and derive metrics from similar comments and/or votes to the feedback.

Linda.Arsenault@cra-arc.gc.ca - 1/23/2017 15:02:40

**Comment by ToferC** [comment]
Approved for scoping.  More and more consultations are happening on the GCTools and this will also be handy when a user needs to respond to an access to information request.

**Comment by Troy-Lawson** [comment]
export to .csv

**Comment by ToferC** [comment]
[User discussion](https://gcconnex.gc.ca/discussion/view/25806786/can-i-download-blogs-discussion-posts-files-etc-from-a-gcconnex-group) on GCconnex.
