### ISSUE TITLE
Reset Password link received by email not opening reset password page

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#742]
The received links in both English and French when users request a password reset does not link to the "Reset/change Password" page

Email user received:

(Le français suit)
There was a password reset request from this IP address: 192.197.71.189 
There was a request to have a password reset from this user's IP address: 192.197.71.189 
Please click on this link to have the password reset for **David.Brown1's** account:

**https://gcconnex.gc.ca/changepassword?u=13184589&c=s22hnncvpv78** 

Learn more about GCconnex notifications. Need help? Contact us.
To unsubscribe from these notifications, login to GCconnex and edit your notifications' settings.

Une demande de réinitialisation du mot de passe a été faite à partir de cette adresse IP : 192.197.71.189 
Une demande de réinitialisation du mot de passe a été faite pour l'adresse IP: 192.197.71.189 
Cliquez sur le lien suivant afin de réinitialiser le mot de passe pour le compte de **David.Brown1** : 

**https://gcconnex.gc.ca/changepassword?u=13184589&c=s22hnncvpv78**

Apprenez davantage au sujet des notifications de GCconnex. Besoin d’aide? Contactez-nous.
Pour vous désabonner de ces notifications, connectez-vous à GCconnex et modifiez vos paramètres de notifications.

Username: **david.brown1**

**Comment by ToferC** [comment]
@KevinChagnon - can you please confirm that the link isn't accessible from the user's account?  Testing the reset password link and it is working here.  Maybe the user selected it more than once?

Suggest you have the user click reset password again.  If it works for them, then please close issue.  Thanks!
