### ISSUE TITLE
Files Sections - Reposition "Tags" and "functions" buttons for files for better user experience

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#743]
A user was unsure as to how to go about "Editing" a file - he could not find the "Edit" button.

_Comment from user:_
Looking at why I didn’t notice the Edit button. A couple of points:
•	Those icons appear as if they are grayed out
•	The File name is followed by metadata, tags, then functions.

![files - now](https://cloud.githubusercontent.com/assets/23527358/22436899/ec9281a0-e6f3-11e6-80ea-dfbae2317153.jpg)

Possible improvements:
•	Move the function buttons to just below the file name (see below)
•	Coloured the function buttons black for users with edit rights, **so they appear like active objects**

![files - mod](https://cloud.githubusercontent.com/assets/23527358/22436977/2e8e33ce-e6f4-11e6-919f-64219f7b1c71.jpg)

**Comment by ToferC** [comment]
@KevinChagnon - I think this might be a personal preference issue vs. usability, but let's build this into th e usability testing to happen early next FY.  Mousing over the icons also provides info on functions.  Closing issue, but will continue to assess usability across the platform. @piet0024 @ethanWallace @Steph4104
