### ISSUE TITLE
Search results not working when including accents - French search limiting results

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#759]
When doing a Search for "Café Jen" (page set to English) - the group is not displayed in Search Results:

![cafe jen](https://cloud.githubusercontent.com/assets/23527358/22467559/1ff2ec84-e793-11e6-951c-e337781bc44b.png)

However, when doing a search for "Café Jen" (page set to English) - the group shows in Search Results:

![cafe jen](https://cloud.githubusercontent.com/assets/23527358/22467608/4e6fad86-e793-11e6-9bb5-cf1844dafceb.png)

The name of the Group is "Café Jen" and so should show when doing a search with the same spelling.

When page is set to French, Search Results do not display the Group page regardless of the spelling:

"Café Jen" (page set to French):

![cafe jen f](https://cloud.githubusercontent.com/assets/23527358/22467846/36c306dc-e794-11e6-89cd-b20c87a34784.JPG)

"Cafe Jen" (page set to French):

![cafe jen f](https://cloud.githubusercontent.com/assets/23527358/22467859/4936c664-e794-11e6-970e-e709c6a0ed16.JPG)

**Comment by ToferC** [comment]
Approved as high priority item re: official languages requirement.  Please include in next sprint.

**Comment by pandurx** [comment]
Need to devise a plan with Rajeev about this

**Comment by pandurx** [comment]
Re-opened:
Searching from GCconnex to the *Fake* GCconnex search page will result with no set, but all the results will display when you click on "Search" in the *Fake* GCconnex result page.

**Comment by pandurx** [comment]
Please see for more info or progress: #1021
