### ISSUE TITLE
Automated email notifying users of removal from opportunity has a subject line but no text in body.

### ISSUE THREAD

**Issue by Eldoraaoun** [gctools-outilsgc/gcconnex#762]

**Comment by Phanoix** [comment]
@LemieuxGen @PhilAndrecheck There is no body text language for users being removed or a user removing themselves / withdrawing from an opportunity. It will be easy to add once I have something to put there.

**Comment by LemieuxGen** [comment]
@Phanoix : Here's the text to use in the notifications (English and French). 
**_Notification – when a candidate’s application is not retained._**
Thank you for your interest in this opportunity. Unfortunately, your application was not retained. Keep an eye out for another great opportunity! 
Merci de votre intérêt pour cette opportunité. Malheureusement, votre application n’a pas été retenue. Gardez l’œil ouvert pour une autre bonne opportunité! 

**_Notification – when a candidate’s withdraws from an opportunity._**
Please note that _%username_ has withdrawn from your opportunity. Select another participant or repost your opportunity to get other applicants.
Veuillez noter que _%username_ s'est retiré de votre opportunité. Sélectionnez un autre participant ou afficher votre opportunité à nouveau pour obtenir d’autres candidats.

@PhilAndrecheck - let us know if you see any issues with this text, this is supposed to go up this weekend.
