### ISSUE TITLE
Multiple Posts following system lag

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#763]
When a user attempts to post something like a Discussion and there is a system lag, clicking the submit button doesn't always trigger an immediate action.  When there is a lag, the user is tempted to try to click the button to submit the post again, but in reality it has already been clicked once.  At times a user may click it many times before the system actions the first click.
I am wondering if this could be a cause of multiple posts and if there is a way to prevent this from happening should a user click the same button many times before the system responds?
The following was sent to me as an example of a duplicate post, but it has since been removed:
https://gcconnex.gc.ca/discussion/view/24541002/deleting-discussion-on-gcconnex
Discussion continued in post that was kept (but on a separate topic):
https://gcconnex.gc.ca/discussion/view/24541235/deleting-discussion-on-gcconnex#elgg-object-24542213

**Comment by ToferC** [comment]
This is a system performance issue and will be resolved as part of server or cloud migration.  Closing issue, but should be considered ongoing. @KevinChagnon - please advise any users of cause and that we are working on a fix asap.  Thanks.
