### ISSUE TITLE
Ability to login as user

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#765]
As a GCconnex administrator (and for help desk purposes) I need to be able to login as a user (or view as user) to be able to see what the user is experiencing and better understand the user's issues without having to ask for multiple screen shots through a series of email exchanges. This will allow us to quickly identify the source of the users' issues and hopefully reduce number of unnecessary tickets inputted in GitHub.

**Comment by ToferC** [comment]
Approved as high priority due to opportunity to improve client service through helpdesk.
