### ISSUE TITLE
Adjust layout and text file from "Specific Time Requirements" table

### ISSUE THREAD

**Issue by Eldoraaoun** [gctools-outilsgc/gcconnex#766]
In creating an opportunity, the "Specific Time Requirements" table doesn't have the words "Start time" and "Duration" aligned with the columns. Also change text file "Duration" to "End time", and remove the example text since it no longer will be accurate.

**Comment by ToferC** [comment]
Approved.

**Comment by ToferC** [comment]
This is completed.
