### ISSUE TITLE
gcconnex: YouTube videos to start at specified times indicated in the URL (i.e. use the t=XmYs parameter from the URL to set the start time)

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#771]
Enhancement of existing feature
As a Regular User, I need YouTube videos to start at specified times indicated in the URL (i.e. use the t=XmYs parameter from the URL to set the start time) because Videos may be long and the PM may only start speaking in the video after 30 minutes.

richard.akerman@canada.ca - 2/2/2017 11:02:23

**Comment by ToferC** [comment]
User should be able to set this from choosing the start-time and then choosing share from YouTube.  Investigate to see if this works on GCconnex.

**Comment by Phanoix** [comment]
Doesn't look like the mod picks up start times in the url currently, maybe there's a more recent version that does?
