### ISSUE TITLE
gcconnex: I need to be able to re-order my work experience (and education) in my GCconnex profile

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#774]
Enhancement of existing feature
As a Super User, I need I need to be able to re-order my work experience (and education) in my GCconnex profile because because I don't have a way to easier change the order of the experience entered in my profile and it's not an efficient use of employees time to have to re-enter everything manually to fix the order.

 - 2/3/2017 13:10:04

**Comment by ToferC** [comment]
Suggest sort by date - most recent at top.
