### ISSUE TITLE
Search (GSA) showing "... GSA. christine.yu@tbs-sct3.gc.ca. " at beginning of search result description

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#776]
When searching for content on GCconnex using the GSA, the search results show "... GSA. christine.yu@tbs-sct3.gc.ca. " for a lot of the results (not all). For example, search for a specific user (Christina Metcalfe), shows me results with that text at the beginning of the description. Searching for other type of content (ex GCTools) shows me some results with that text "... GSA. christine.yu@tbs-sct3.gc.ca. ", others are ok. 

![search results with gsa chrsitine you tbs-sct3](https://cloud.githubusercontent.com/assets/15378977/22700715/8b7a19aa-ed29-11e6-859b-492e8acc4f8e.JPG)

**Comment by LemieuxGen** [comment]
@pandurx - see screen shot, not sure if this is related to a new change made tot he GSA.

**Comment by pandurx** [comment]
i don't know what changes were made, but i will need to strip that out.

**Comment by pandurx** [comment]
https://github.com/gctools-outilsgc/gcconnex/pull/806
