### ISSUE TITLE
gcconnex: A change to the email subscription model as it applies to users commenting on blog posts who have not joined the blog group. Currently users are auto-subscribed to emails for every new comment on the blog post without opting in, and are unable to opt out without first joining the group.

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#777]
Enhancement of existing feature
As a New User, I need A change to the email subscription model as it applies to users commenting on blog posts who have not joined the blog group. Currently users are auto-subscribed to emails for every new comment on the blog post without opting in, and are unable to opt out without first joining the group. because The current behaviour violates opt-in as well as the principal of least astonishment. Further, I have had 4 users ask for my assistance in stopping the email stream they were receiving due to this behavior.

nathan.diehl@agr.gc.ca - 2/7/2017 12:42:26

**Comment by ToferC** [comment]
Plan of action:
* Will proceed with notification digest to address major user pain point
* Assess as bug and clarify in terms of notification functionality
