### ISSUE TITLE
Bug in Ideal Start Date/Application Deadline

### ISSUE THREAD

**Issue by Eldoraaoun** [gctools-outilsgc/gcconnex#779]
BUG - When creating an opportunity, there is no error message when opportunity creator marks an application deadline after the selected ideal start date. 

See photo: 

![idealstartdate applicationdeadline](https://cloud.githubusercontent.com/assets/25466632/22711607/d0411d92-ed4f-11e6-9c7f-0f2474f4d806.JPG)

**Comment by ethanWallace** [comment]
@Eldoraaoun The "Ideal start date" may not be a set in stone start date so the application deadline may extend past the start date to allow for more applicants if needed.

**Comment by Eldoraaoun** [comment]
@ethanWallace oh I see! If the user wishes to extend the opportunity start date, than they would also need to edit the application deadline. As a GCconnex user, if I saw that the ideal start date has already past, I would assume that the opportunity is no longer active - or be extremely confused since the application deadline contradicts. So we should encourage users to manually edit and change the Ideal Start Date (& by association the Application Deadline) if they do wish to extend their opportunity to more applicants.
