### ISSUE TITLE
"Remember me" option on login page checked but does not work

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#780]
On the log-in page there is a box to tick that says "Remember Me" which I am lead to believe that, once checked, would negate having to re-enter the user's email address/username next time he accesses the login page.
After log out, IE closed, reopened and back to the login page, the field does not populate with the email address/username.

**Comment by ToferC** [comment]
This can be related to local session settings that would controlled by the
host department. Suggest that user contacts their local helpdesk.
@kevinchagnon

**Comment by KevinChagnon** [comment]
The "Remember Me" feature does not work for me either.
I put the checkmark beside "Remember Me" on the Login page, after entering my username or email address; After log out, IE closed, reopened and back to the login page, the field does not populate with the email address/username.
I verified my IE settings and there is no indication there as to why it would not retain my username for this site...

**Comment by Troy-Lawson** [comment]
@KevinChagnon This appears to be a misunderstanding about the functionality. The intended functionality of "remember me" is to keep you logged in through the browser closing(remembering that you are logged in). This is different than what you describing. You are describing something that remembers the username you last logged in with and auto fills that out in the page. That is not the intended functionality. I am marking this issue closed.
