### ISSUE TITLE
gcconnex: A live stream of Ambassador outreach activities to show up on the wire. For instance if an Ambassador adds an activity to the outreach corner on our GCpedia page then a wire post will be shown from the GCTools or as a banner saying that Ambassador X completed a presentation on the GCTools. If the cross platform between GCconnex and GCpedia is not able to work then we can come up with ways for them to post directly on the Ambassador Network GCconnex group to pull the data

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#794]
New Feature Request
As a Super User, I need A live stream of Ambassador outreach activities to show up on the wire. For instance if an Ambassador adds an activity to the outreach corner on our GCpedia page then a wire post will be shown from the GCTools or as a banner saying that Ambassador X completed a presentation on the GCTools. If the cross platform between GCconnex and GCpedia is not able to work then we can come up with ways for them to post directly on the Ambassador Network GCconnex group to pull the data because 1) Ambassadors seeing that their peers are giving presentations and performing outreach activities will make them more inclined to give presentations. It gamifies being an Ambassador since they want to be the one with the most presentations.
2) Having a message on the wire appear to all GCconnex users will make users aware of the existence of the Ambassador if they were unaware, and it promotes the GCTools internally

erin.chapman@tbs-sct.gc.ca - 2/17/2017 9:07:28

**Comment by Phanoix** [comment]
Sounds like this might be a customized use of the "share on GCconnex feature".

**Comment by Troy-Lawson** [comment]
May not be applicable after rebuild
