### ISSUE TITLE
Feature on The Wire so that duplicate "shares" only show up once per page. 

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#797]
User expresses a need to have duplicate "shares" of posts on the Wire be displayed only once per page as to maximize the available real-estate for new posts/shares.  A suggestion could be to group the duplicate "shared" items with an option to drop down a list of all "shares" of the same post.

**Comment by Troy-Lawson** [comment]
will close as enhancement to legacy system
