### ISSUE TITLE
Branching out from #65: group deletion - a deletion process for groups with multiple members

### ISSUE THREAD

**Issue by Phanoix** [gctools-outilsgc/gcconnex#80]
Continuation of gctools-outilsgc/gcconnex#65 beyond the suggested usability improvement.

**Comment by Troy-Lawson** [comment]
@Phanoix was this implemented already?

**Comment by Phanoix** [comment]
This was barely started, beyond the initial functionality to allow groups with only 1 member to be easily deleted this is supposed to add a process for deleting larger groups that minimizes the chance of accidental deletion.

**Comment by Troy-Lawson** [comment]
closed as assumed this will not be worked on
