### ISSUE TITLE
French Group Forum "Is Sticky" option is in English

### ISSUE THREAD

**Issue by marc-m** [gctools-outilsgc/gcconnex#800]
The "Is Sticky" option when editing  for the Group Forums is in English only, 

French option should have French text.

The English title "Sticky Topics" displays as "Sujets délicats" in French title so I think that the "Is Sticky" checkbox would become "Est délicat" when editing in French, although I am not certain of this translation.

![gcconnex - group forums - is sticky - french](https://cloud.githubusercontent.com/assets/13544463/23142264/0b4f00a0-f789-11e6-9a06-45c2f86eb1e2.png)
![gcconnex - group forums - is sticky - english](https://cloud.githubusercontent.com/assets/13544463/23142263/0b4eeb06-f789-11e6-8d5e-d762b76a26ea.PNG)

**Comment by pandurx** [comment]
See for more information and update : #1014
