### ISSUE TITLE
Correction to french title / links in "My Colleagues"

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#811]
When language selection is set to French;
The Title of this section is displayed as "Kevin Chagnon' mes collègues" - should be something in the likes of "Les collègues à Kevin Chagnon"
The link "Inviter des mes collègues" should be changed to "Inviter mes collègues"

![colleagues](https://cloud.githubusercontent.com/assets/23527358/23270713/c6489a52-f9c2-11e6-8171-cf0aaaf0babc.JPG)

**Comment by KevinChagnon** [comment]
When a user has not yet added colleagues, the following message is also displayed:
"Cet utilisateur n'a pas encore ajouter de mes collègues à ce jour"
![colleagues - none](https://cloud.githubusercontent.com/assets/23527358/23765334/e35793d4-04ce-11e7-86b0-9e80e17f5dae.jpg)

It should read: "Cet utilisateur n'a pas encore ajouté des collègues à ce jour"

**Comment by joshcampbell191** [comment]
Hackathon: Claiming this one for team NOP

**Comment by smellems** [comment]
A fix was pulled for this.  Will update in related Issue #1103
