### ISSUE TITLE
Federal Youth Network GCconnex group bugs

### ISSUE THREAD

**Issue by ErinChapman** [gctools-outilsgc/gcconnex#815]
I have made two discussion posts on the Federal Youth Network over the past two days. When I post I only click submit once and then I get an error message. When I go back into the group yesterday it posted the discussion 5 times and today it posted twice even though I only clicked submit once. A user commented on my discussion yesterday and even though the notification bell was on, I was not notified that someone commented on my post.

**Comment by Phanoix** [comment]
Did it time out while trying to save your post?

**Comment by ErinChapman** [comment]
I don't think it did. I did even get a loading page or anything, the page didn't change at all when I clicked submit. I have not ran in to this issue again since I created this ticket

**Comment by Troy-Lawson** [comment]
duplicate to #904 and others.
