### ISSUE TITLE
Add reports_to relationship and org chart

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#821]
Add the "reports_to" relationship to GCconnex with the following parameters:
- Connects one user (supervised) with another user (supervisor)
- Can only report to one person at a time
- Tracks start-date and end-date of reporting relationship
- supervisor or supervised can end reporting relationship (need management console in profile)

Adds an organizational chart view that shows the supervised, the supervisor and other individuals with the reports_to relationship with the supervisor, i.e., work colleagues.

[Sample](https://en-ca.wordpress.org/plugins/simple-org-chart/screenshots/).

User Stories:
As a regular user, I need to be able to identify who I report to in my work environment so that my organization can have an organic and always up to date org chart.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
