### ISSUE TITLE
No link to User's reply/original discussion provided in "like" notification email (or link to user who "Liked" the reply)

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#827]
Dec. 07 2016, user: **Howard.Jones** replied to a Discussion post within a group:

https://gcconnex.gc.ca/discussion/view/23721980/a-conundrum-what-constitutes-a-document-for-the-purposes-of-atip?offset=10#group-replies

Another user "Liked" the reply and an email Notification was sent to user:  **Howard.Jones**

The Notification email did not provide a link to the Discussion, the Reply from Howard.Jones, or a link to the profile of the user who Liked the reply.

![like notification](https://cloud.githubusercontent.com/assets/23527358/23469698/4bff50f6-fe72-11e6-9623-cd2c92938bd8.JPG)

Other email Notification provide a like to the Discussion. Example:

![new discussion notification](https://cloud.githubusercontent.com/assets/23527358/23469950/1d44592c-fe73-11e6-8810-b432ea605bc1.JPG)

However, this does not seem to happen with all "Like" Notifications.  This examples is from a Like on a Wire post:

![like wire post](https://cloud.githubusercontent.com/assets/23527358/23470056/65ecc218-fe73-11e6-93c2-d529896f4b04.JPG)

**Comment by KevinChagnon** [comment]
The links make it possible to return to the relevant content to confirm the details or continue the discussion.

**Comment by pandurx** [comment]
see pull request gctools-outilsgc/gcconnex#768 for fix
