### ISSUE TITLE
Modal Accessibility

### ISSUE THREAD

**Issue by ethanWallace** [gctools-outilsgc/gcconnex#844]
Modals that need to be modified for accessibility: ajax lightbox, profile edit, GEDS, opportunities platform opt-in, and onboarding.

Things that need to be done
  - Focus on modals
  - Have correct aria tags on each modal
  - Try using WET4 modals (Have js error on load)

**Comment by piet0024** [comment]
Testing at the hackathon. The wire onboard modal is not getting picked up by users tabbing through the modal. Tester was trying to tab through and the focus was not on the modal.

@CoolColin

**Comment by ToferC** [comment]
@piet0024 - I know you've done a lot of work on this. Please review and update or close if possible.
