### ISSUE TITLE
gcconnex: I need to embed WebEx recordings into bookmarks and other content types

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#854]
Enhancement of existing feature
As a Regular User, I need I need to embed WebEx recordings into bookmarks and other content types because Becuase I want to embed WebEx videos just like how YouTube videos get automatically embeded (also in some cases like Vimeo videos)

david.sampson@canada.ca - 3/20/2017 10:24:24

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
