### ISSUE TITLE
Profile “Second Language Evaluation” update to  “Language Proficiencies" section 

### ISSUE THREAD

**Issue by Eldoraaoun** [gctools-outilsgc/gcconnex#856]
Change the title “Second Language Evaluation” in user profile to “Language Proficiencies”. 

Add free text box (or auto-suggest) for the language + columns “Written”, “Oral” and “Comprehension” with drop down menus for user to select their proficiency (Beginner, Intermediate, Fluent, Native). Attached is an illustration of what the section would look like:

![language p](https://cloud.githubusercontent.com/assets/25466632/24170449/4e560bca-0e57-11e7-8fd0-ed1f2da500e1.JPG)

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
