### ISSUE TITLE
Add functionality to open opportunity to selected/multiple departments

### ISSUE THREAD

**Issue by Eldoraaoun** [gctools-outilsgc/gcconnex#859]
Add functionality to open an opportunity to certain clusters of departments. 

Currently the tool has a check box when creating an opportunity, to make the opportunity only available within own department – add ability to open opportunity to selected/multiple department(s). For example, all science depts. or all enforcement, or all central agencies. The user would have to select all desired depts.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
