### ISSUE TITLE
gcconnex: I want a count of how many bookmarks, discussions, files, bookmarks, and other content types there are in a given areas

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#861]
Enhancement of existing feature
As a Regular User, I need I want a count of how many bookmarks, discussions, files, bookmarks, and other content types there are in a given areas because So that I can use metrics to help make decisions on the use of a tool, such as how many bookmarks have users created in my group (eg https://gcconnex.gc.ca/bookmarks/group/24857571/all)

david.sampson@canada.ca - 3/22/2017 9:57:56

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
