### ISSUE TITLE
gcconnex: I need some basic web stats about each of the groups I own, belong to, and moderate. Such as page views (Total, last 30,60,90,365 days and all time), including average time they stay in a group or on specific content, what other areas of GCConnex link to my groups and content. I also want a breakdown by department, and also know who my top 100 users are.

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#862]
New Feature Request
As a Super User, I need I need some basic web stats about each of the groups I own, belong to, and moderate. Such as page views (Total, last 30,60,90,365 days and all time), including average time they stay in a group or on specific content, what other areas of GCConnex link to my groups and content. I also want a breakdown by department, and also know who my top 100 users are. because In Support of "Experimentation Direction for Deputy Heads" (http://www.pco-bcp.gc.ca/index.asp?lang=eng&page=innovation&doc=pubs/pubs1-eng.htm) I want to apply experimentation principles and measure the impact and effectiveness of my stakeholder outreach. NOTE: If you need help implementing this let me know I have experience in this field.

david.sampson@canada.ca - 3/22/2017 10:04:25

**Comment by ToferC** [comment]
linked to issue #105 - duplicate.

**Comment by Phanoix** [comment]
Closing duplicate.
