### ISSUE TITLE
Opportunity Platform creator selection error where multiple email addresses exist

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#874]
The Opportunity Platform identifies an opportunity creator based on an email address, which can be duplicated for certain accounts (i.e., admin accounts).

In two cases, even though the account was created by a user, because the admin account has the same email, the OP creator was identified as the admin account.

A fix may include changing Opportunity Creator to a user.id.  Low priority as only applies to admins.

@smellems - I think this is what happened with you.

**Comment by Steph4104** [comment]
Can I have a screenshot or a link where we can see the problem? Because I can't replicate the problem on my local version and I take a look a the opportunity of Sebastien and everyting look fine.

**Comment by ToferC** [comment]
I tested thisbagain today and again had an opportunity created by admin.Chris. 

I'll stop by and we can walk through it together.

**Comment by ToferC** [comment]
Hi @Steph4104 - I created a new opportunity here: https://gcconnex.gc.ca/missions/view/24960976 - same issue.
