### ISSUE TITLE
Clicking on username in a blog should bring to user's profile page

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#875]
When a person's name is hyperlinked, it should link to the person's profile, not to content (blogs) related to them. 

On this page: https://gcconnex.gc.ca/blog/all 

For each blog, the blog title is hyperlinked and when you click on it, it brings you (as you would expect) to the blog. Also for each blog, the author's name is hyperlinked. But when you click on it, instead of bringing you to the author's profile page (as you would expect), it brings you to the page with all of that person's blogs on it. 

The same thing happens in other areas in GCconnex, too. When I click on the username it doesn't bring you to their profile page; it brings you to a list of their blog posts. There is no way then to click to get to their profile via the blog post. If you want to look at that person's profile, you have to type it into the search field. 

User: "That seems very counter-intuitive. No other social media that I use seems to operate that way"

**Comment by amisima** [comment]
Hackathon: claiming this one for team NOP
