### ISSUE TITLE
Users get Ajax erorr when trying to edit comment made on blog

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#881]
When a user attempts to edit a comment they made on a blog, they get an Ajax error when they click edit:

![blog edit ajax error](https://cloud.githubusercontent.com/assets/23527358/24418220/4def3e1a-13b9-11e7-9f5f-b6256730ea95.JPG)

I got the same error as the user reported when I tried to edit my comment made here:

https://gcconnex.gc.ca/blog/view/15950694/test-blog

**Comment by Steph4104** [comment]
close with pull request #882
