### ISSUE TITLE
gcconnex: I would like to request an increase to the size limits for hosting videos on GCTube.  The current 32MB does not meet needs - especially for learning communities that wish to share larger videos for innovation and collaboration purposes.

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#887]
Enhancement of existing feature
As a Regular User, I need I would like to request an increase to the size limits for hosting videos on GCTube.  The current 32MB does not meet needs - especially for learning communities that wish to share larger videos for innovation and collaboration purposes. because Some of the learning videos I would like to post run about 1 hour + in length; they're long but the content is pertinent to my audience.

 - 3/29/2017 11:37:50

**Comment by Phanoix** [comment]
I don't think we have the server capacity for this right now, but if we did is this something we want to do? GCconnex isn't a video streaming site.

**Comment by Troy-Lawson** [comment]
duplicate to gctools-outilsgc/gcconnex#902
