### ISSUE TITLE
gcconnex: An easy ‘back’ feature without hitting the back button on your browser

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#895]
New Feature Request
As a Regular User, I need An easy ‘back’ feature without hitting the back button on your browser because When you do that, it often takes you back to main ‘Groups’ page or ALL blogs, ALL events, etc, not just your group’s. Navigation within a group or page is especially difficult.

 - 3/30/2017 9:43:55

**Comment by gpierre** [comment]
My understanding is that the breadcrumbs are not displaying the trail the user took to get to where he is. Therefore can't go back to where he came from using the breadcrumbs. Issue 646 exposes the breadcrum issue and I would merge this enhancement request into issue 646.

**Comment by pabrams** [comment]
Is the issue that the back button doesn't work as expected?  I'm not able to reproduce the described behavior.  As far as I can tell, the browser's back button does bring the user back to the previous page, but maybe I'm not reproducing the correct steps.  Here's what I tried: 

1.  Visit group (  https://gcconnex.gc.ca/groups/profile/25330100/group-trying-to-reproduce-github-issue-895 )
2.  Click subgroup (browser goes to https://gcconnex.gc.ca/groups/profile/25330184/subgroup-trying-to-reproduce-github-issue-895)
3.  Click "Pages" (browser stays on same URL as step 2)
4.  Click "Page in subgroup" (browser goes to https://gcconnex.gc.ca/pages/view/25330213/page-in-subgroup) 
5. Click  browser back button  (browser returns to page at step 2/3 - seems okay - I think @GCToolsEnhancement is saying that this is where their browser takes them to https://gcconnex.gc.ca/pages/all, instead, which was never actually visited )
6. Click Back again (browser returns to page at step 1).

In the above scenario, back button seems to be working as expected.  Are there situations where the back button does not bring the user back to the previous page?

**Comment by gpierre** [comment]
This enhancement request is asking that users don't have to use the back button. I first tought the user wanted to go back from a few pages prior. The breadcrumbs actually do not reflect the user's trail to a page. So if you go groups and then a specific group then a bookmark, then the user will have to use the back button twice because the breadcrumbs will no longer include the "groups/all" at it's root but rather "bookmarks/all". Even tough he never visited bookmarks/all.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
