### ISSUE TITLE
Uploading Images on Blog uploads thumbnail instead of image

### ISSUE THREAD

**Issue by Lavoiec** [gctools-outilsgc/gcconnex#900]
As a user of GCconnex using the blog function to publish image heavy content, I need to be able to upload images easily and properly. Currently, using the "embed content" button allows me to easily access my uploaded files, however the content embedded is the thumbnail of the image, rather than the actual image itself. The result is a tiny image, and any attempts to blow up the thumbnail to a readable size ends up exactly as one would expect: the image does not enhance as it does in CSI:Miami, rather it becomes a pixelated mess. 

@smellems  showed me a quick fix by editing my post through the source code. The fix was to replace the src="...", changing it from the link to the thumbnail to actually linking the image.

While I'm lucky enough to work with a team of individuals more web-savvy than me, most people aren't so fortunate. I suggest changing the embed content to uploading the source file rather than the thumbnail from the beginning.

**Comment by klecuyer** [comment]
+1

**Comment by klecuyer** [comment]
+1 still copying the image _thumbnail_ URL to embed content. @LemieuxGen maybe a good one to consider for next sprint?
