### ISSUE TITLE
gcconnex: To embed a WebEx Recording

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#901]
Enhancement of existing feature
As a Regular User, I need To embed a WebEx Recording because So users can view the webex within GCConnex. Similar to how youtube and video embeded videos work. See notes here :https://gcconnex.gc.ca/discussion/view/25038798/notes-on-recording-my-first-webex-to-share-on-gctube see example bookmark here: https://gcconnex.gc.ca/bookmarks/view/25038839/environment-canada-data-management-program-data-catalogue-project-iteration-demo-76-webex

david.sampson@canada.ca - 4/4/2017 9:39:12

**Comment by Troy-Lawson** [comment]
As far as i know, webex exists as a stand alone desktop application, and therefore cannot be embedded onto a webpage. If webex was able to be embedded, then it should already work on gcconnex in the same manner that a youtube video would
