### ISSUE TITLE
gcconnex: As a video publisher using GCTube (https://gcconnex.gc.ca/groups/profile/24857571/gctube) I want to upload large video files (1 hour MP4 @ 600MB?)

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#902]
Enhancement of existing feature
As a Regular User, I need As a video publisher using GCTube (https://gcconnex.gc.ca/groups/profile/24857571/gctube) I want to upload large video files (1 hour MP4 @ 600MB?) because So that I can share internally produced videos within GOC without hitting GCConnex and GCpedia upload limits: Notes: https://gcconnex.gc.ca/discussion/view/25038798/notes-on-recording-my-first-webex-to-share-on-gctube, Idea: https://gcconnex.gc.ca/ideas/view/25047450/support-ulpoad-of-large-video-files ; discussion: https://gcconnex.gc.ca/discussion/view/24941315/hosting-large-video-files

David.sampson@canada.ca - 4/4/2017 9:46:22

**Comment by ToferC** [comment]
Note GCvideo platform is a possible stand-alone addition to the GCtools
this FY depending on CIO interest and funding.

**Comment by Troy-Lawson** [comment]
closing forissue clean up. an increase in storage will lead to an increase in allowed file size
