### ISSUE TITLE
"Pages" Widget missing for groups

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#906]
New Feature Request
As a Super User, I need A "Pages" Widget for the main Group Page because Because the Pages content for this page would be an excellent set of materials for front-page presentation.

jared.pachan@canada.ca - 4/4/2017 17:26:01

**Comment by LemieuxGen** [comment]
The "Page" widget was available before in groups. The [GCTools group ](https://gcconnex.gc.ca/groups/profile/226392/gctools)uses it to display its pages. In the GCTools group, the widget is currently activated (with the titled "Updates / Mises à jour". However, the Page widget doesn't appear in the list of available widgets anymore.

**Comment by ToferC** [comment]
Will assess as part of the Summer 2017 refresh milestone as content types are consolidated.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
