### ISSUE TITLE
Any change in language occurring on a page must be tagged with the lang attribute

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/gcconnex#915]
WCAG 3.1.2 Language of Parts.

Wrap any change in change in language occurring with a <span lang="fr"></span> or <i lang="fr"></i>
This could include:
- Splash
- Lang toggle
- French content on english page
- Vice Versa 

@CoolColin

**Comment by Troy-Lawson** [comment]
accessibility hire

**Comment by Troy-Lawson** [comment]
@piet0024 @ethanWallace still need this issue?

**Comment by Troy-Lawson** [comment]
closed as will be addressed as part of a new service
