### ISSUE TITLE
Language tagging on the wire

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/gcconnex#921]
WCAG 3.1.2 Language of Parts

When users create content on the wire they can post content in any language. This language will need to be tagged with the proper lang attribute so that screen readers will know to switch language. 

We could extend the language toggle feature developed for other content types on the wire so we know what language the content is.

@CoolColin

**Comment by Troy-Lawson** [comment]
on hold for accessibility hire

**Comment by Troy-Lawson** [comment]
@piet0024 @ethanWallace Is still incomplete #issuecleanup

**Comment by Troy-Lawson** [comment]
close as will address as part of a new service
