### ISSUE TITLE
Changing the characters of the tools to capital letters 

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/gcconnex#924]
Screen readers currently read GCconnex as "G-connex" GCpedia as "G-pedia". If the third character was upper case it will read properly. "GCConnex", "GCPedia"

@CoolColin

**Comment by claudielarouche** [comment]
I a working on this one now. How about GCDocs, should we put a capital D as well?

**Comment by claudielarouche** [comment]
Oh I've just been told that this would actually require management decision so the change might not be implemented right away, so I've stopped working on this.

**Comment by CoolColin** [comment]
Why was this closed without being addressed or without any feedback regarding if it will in fact be addressed or not? I am aware it is a fairly miniscule item but I'm still curious.

**Comment by ToferC** [comment]
Hi Colin,

Sorry - we discussed today but didn't consider that it was an externally
created issue when we closed it.

We spent a lot of time in branding discussions last year and a number of
folks came together to select the GC <insert_name> format for the GCtools.

We decided we want the branding to remain the same and will investigate
other ways to get screen readers to pick the right context for users.

Hope that makes things clear and thank you so much for the great work on
these issues.

**Comment by CoolColin** [comment]
No worries. Coming from a communications background I can totally understand your stance. Again as I mentioned it was a very miniscule thing I had brought to the table in comparison to some of the others. Thanks for the reply though! Cheers!!
