### ISSUE TITLE
Polls input accessibility 

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/gcconnex#925]
Poll radio buttons have labels inside labels. Take a look at multiple polls. EX Polls by Remy Bernard in GCTools group. 

Fieldset and legend for the radio button groups.

**Comment by Troy-Lawson** [comment]
@ethanWallace @piet0024 is this still an issue?

**Comment by ethanWallace** [comment]
@Troy-Lawson I do not believe anyone has addressed this issue yet

**Comment by piet0024** [comment]
I've been going through the polls on production and I do not believe this is an issue anymore. It may have been addressed in updates over the years. If this continues we can reopen the issue.
