### ISSUE TITLE
Multifile upload caused an error and did not upload the files

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/gcconnex#932]
To replicate
- go to a group 
- go to files -> upload a file -> multifile 
- click browse -> user selected 3 photos all under 500kbs (no issue with max file size)
- click upload
- progress bar goes 100% and an error pops up "Internal server error database exception)

* We should also display the max file size when uploading files

* Update uploading single files were also causing fatal errors at this time.

Look at groups/profile/summary.php line 23

@CoolColin

**Comment by Troy-Lawson** [comment]
multi file upload has been changed
