### ISSUE TITLE
(enhancement) Request skill endorsement for profile enhancement

### ISSUE THREAD

**Issue by pscrevs** [gctools-outilsgc/gcconnex#934]
[From the GCConnex poll results](https://gcconnex.gc.ca/polls/view/25244032/hello-all-we-are-participating-in-the-gc-tools-hackathon-and-are-curious-as-to-what-gcconnex-enhancement-appeals-to-you-the-most-as-a-public-servant-please-select-the-option-that-appeals-to-you-the-most)

Similar to LinkedIn's skills endorsements, where colleagues can endorse an individual's skills. 
With GCConnex’s recent SKILLS feature within one’s profile, other GCConnex users can endorse you (by clicking on that skill). But what this new feature is proposing is to have individual request endorsement to other GCConnex users. For example, I can request endorsement for “Architecture” to my manager and, as such, build my GCConnex profile even more.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
