### ISSUE TITLE
(enhancement) Receive recommendations for GCConnex groups based on other users's skills and their group memberships

### ISSUE THREAD

**Issue by pscrevs** [gctools-outilsgc/gcconnex#935]
[From the GCConnex poll results](https://gcconnex.gc.ca/polls/view/25244032/hello-all-we-are-participating-in-the-gc-tools-hackathon-and-are-curious-as-to-what-gcconnex-enhancement-appeals-to-you-the-most-as-a-public-servant-please-select-the-option-that-appeals-to-you-the-most)

Another way to find GCConnex Groups that may be of interests to you!

By knowing what your GCConnex colleagues and other users of similar skills than you, GCConex can give you recommendations of group membership. 

For example, you may not be aware that there's a "Open Source Community" group on GCConnex, but if you're colleague "John" is a member of that group, GCConnex could present this option as a recommendation on your GCConnex home page.

In addition, with the recent addition of skills as part of your profile, GCConnex can also recommend groups for you to follow by knowing what other GCConnex users with similar skills are members of.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
