### ISSUE TITLE
(enhancement) Real time chat box in a GCConnex group

### ISSUE THREAD

**Issue by pscrevs** [gctools-outilsgc/gcconnex#936]
[From the GCConnex poll results](https://gcconnex.gc.ca/polls/view/25244032/hello-all-we-are-participating-in-the-gc-tools-hackathon-and-are-curious-as-to-what-gcconnex-enhancement-appeals-to-you-the-most-as-a-public-servant-please-select-the-option-that-appeals-to-you-the-most)

Instead of creating a new chatroom from scratch and inviting individuals to that chatroom, this feature would essentially automatically create a chatroom for each GCConnex group, and have that chatroom available as a “widget” on the GCConnex group page itself. So anyone going on a GCConnex group could start chatting with the group’s members (as long as those members are online of course).

**Comment by ToferC** [comment]
What do folks think of this? Each group would have buttons to create a Riot chatroom and a Wekan project management board.

**Comment by marc-donofrio** [comment]
GCmessage was used for this feature.
