### ISSUE TITLE
(enhancement) Carpooling search app

### ISSUE THREAD

**Issue by pscrevs** [gctools-outilsgc/gcconnex#938]
[From the GCConnex poll results](https://gcconnex.gc.ca/polls/view/25244032/hello-all-we-are-participating-in-the-gc-tools-hackathon-and-are-curious-as-to-what-gcconnex-enhancement-appeals-to-you-the-most-as-a-public-servant-please-select-the-option-that-appeals-to-you-the-most)

Leverage the GCConnex platform to find carpooling buddies. This plugin would be beneficial in case of public transit strikes, or when coordinating large events.

The concepts makes use of Goole Maps to display available car ride routes. Care ride routes are defined by "drivers" that are willing to make their cars available for people to carpool. "Passengers" can search through this plugin for car ride routes within proximity of their "pickup" and "drop off" location.

gctools-outilsgc/gcconnex#937

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
