### ISSUE TITLE
Closed group content is showing up as open to all 

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#954]
A user reported having issues with posting content closed to a group, which was showing up open to all. Further information is required to assess the issue.

User posted on the Wire: 
•	Tanya Snook 47 minutes ago
Aaaah. Seriously hating that everything I post as closed to my group is showing up as open to all post-save. #fail

**Comment by Steph4104** [comment]
Should be fixe in pull request gctools-outilsgc/gcconnex#1038
