### ISSUE TITLE
Configure Azure CI/CD for pre-production environments

### ISSUE THREAD

**Issue by nschonni** [gctools-outilsgc/gcconnex#957]
Identified during the hackathon https://github.com/gctools-hackathon-ircc/gcconnex/issues/6
The IRCC team didn't get the full setup completed, but it was down to having a Docker-Compose file for CI
https://docs.microsoft.com/en-us/azure/container-service/container-service-setup-ci-cd

**Comment by ToferC** [comment]
@sdkibb @markwooff - do we need this or has work gone beyond this point. Please close if possible. Thanks!

**Comment by sdkibb** [comment]
Don't think was ever needed in the end.
