### ISSUE TITLE
Lessons Learned for next time from the IRCC team

### ISSUE THREAD

**Issue by nschonni** [gctools-outilsgc/gcconnex#958]
Sharing our lessons learned/things to tell next years team:
- Setup environment ahead of time
- Ensure OS versions are compatible with setup
- Review the Elgg developer documentation beforehand http://learn.elgg.org/en/stable/guides/index.html
- Setup and check Docker
- Verify the install instructions and PR fixes to them in advance
- Fixing (accessibility) issues coming from Core is difficult and hard to find source of issue
- Cloning repos takes a fairly long time because it is using the full Elgg history instead of requiring just the needed components
- Setup GitHub accounts and verify logins beforehand
- Using a separate GH organization to manage team forks was helpful
- Attend the setup tutorial in advance
- Reveal.js is good for a GH-pages hosted presentation
- The GH kanban ("Projects") didn't add much value
- Clone and add all Git remotes with the same name so everyone is talking about the same thing (origin/ircc/upstream)

**Comment by ToferC** [comment]
Great lessons learned. Thank you!
