### ISSUE TITLE
CSS and JS not rendering in GCTools group

### ISSUE THREAD

**Issue by ToferC** [gctools-outilsgc/gcconnex#967]
As above. Dev console error == '$' is undefined.

Not sure if this is happening in other groups, but we should investigate as a priority, just in case.

https://gcconnex.gc.ca/groups/profile/226392/gctools

**Comment by LemieuxGen** [comment]
@Troy-Lawson @cdegrass Can we look at this ASAP? I looked at other groups, and didn't find any other group that had the same issue (for the moment). Thanks!
