### ISSUE TITLE
Groups - Return to Main Group Landing Page

### ISSUE THREAD

**Issue by massierick** [gctools-outilsgc/gcconnex#970]
Hackathon Team 3 - When you're in a group module (discussion, files, blog, etc.) there is no clear way to get back to the main group page. The breadcrumbs are greyed out, and clicking on the heading (group name) doesn't work. I would think users would most logically click on the Group name/heading. Instead, they have to click "about" which is not intuitive, at least to me and others I've talked to.

**Comment by massierick** [comment]
Inserting this script near the bottom of group pages should solve the issue:

<script>
		var rickurl = $("a[title='About']").attr('href')	  
 $( ".group-title" ).wrap('<a href="' + rickurl + '"> </a> ');
 $(".au_subgroups_group_icon").wrap('<a href="' + rickurl + '"> </a> ');
			  </script>


I don't really know the structure of ELGG very well, so am not sure how I would include it in all group pages. I tested using a static html page with all the GCConnex themes/scripts loaded.

**Comment by ToferC** [comment]
@massierick - I think we'd want this coded into Elgg. @beckyjeong is reviewing group usability right now and will flag as part of her work.

**Comment by massierick** [comment]
Awesome. That's a big part of the equation that I need training in - getting code/ideas into the ELGG system. Right now I only have the knowledge to develop a page-by-page solution, but am looking forward to working with Jeff Outram to learn more about how to do it!

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
