### ISSUE TITLE
Duplicated menu option in Contact Form

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#971]
The contact form on GCconnex, has multitude duplicated option in the dropdown menu for the field "Please select a reason (required)". Please remove duplicated options. 
![contact form menu](https://cloud.githubusercontent.com/assets/15378977/24972652/24b818e6-1f8a-11e7-8302-4b2c503baac3.png)

**Comment by LemieuxGen** [comment]
@Steph4104 had you looked at this issue in the past? As admin, can we delete the duplicated options easily? Thanks!

**Comment by Steph4104** [comment]
Hey @LemieuxGen , yes there is a way too delete options in the admin panel under setting/contactform.
But, I did it for now because they was too much duplicate. I was sure it was fix in the past but I will fix this again.
