### ISSUE TITLE
Ability to move a group from GCconnex to GCcollab

### ISSUE THREAD

**Issue by ghost** [gctools-outilsgc/gcconnex#979]
Group owners should have the ability to migrate a group from GCconnex to GCcollab, bring content and members (some who would have to be prompted to join GCcollab).

**Comment by ToferC** [comment]
Will review as part of work to connect GCconnex and GCcollab in cloud.

**Comment by marc-donofrio** [comment]
New enhancements on hold due to maintenance mode.
