### ISSUE TITLE
Content set as "only me" for access levels still showing up to all group members

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#984]
As a frequent user, I need to be able to post content within a group and set the access level to "only me" and have the content only viewable by me, and not all group members, so that I can work on content and preview it before publishing it to all. 

I created a page on the GCTools group, and set the access level to "only me". When I saved the page, the page was made available to all group members and a notification was sent out to group members as well. The access level still showed "only me", but it was viewable to all. As a result, I continued working on the page, and saved it a few times, and multiple notifications were sent out (when it should of been private with no notifications sent).
See attached screen shot showing access levels, and PDF attachment of the notification received by user for that private content. 
![access level group](https://cloud.githubusercontent.com/assets/15378977/25237997/28a3f016-25ba-11e7-922f-ee4524570721.JPG)
[RE_ A new page was posted in group GCTools _ Une nouvelle page a été affichée dans le groupe GCTools.pdf](https://github.com/gctools-outilsgc/gcconnex/files/943961/RE_.A.new.page.was.posted.in.group.GCTools._.Une.nouvelle.page.a.ete.affichee.dans.le.groupe.GCTools.pdf)

@Phanoix : As discussed, would it be possible to look into this issue as soon as possible? (you or other developer?)
cc: @cdegrass

**Comment by KevinChagnon** [comment]
+1

**Comment by LemieuxGen** [comment]
@Troy-Lawson @Steph4104 is there a status on fixing this bug? This is very disconcerting for users that the content they publish, which should only be accessible to them, sends out notifications to others. 
CC: @ToferC

**Comment by Steph4104** [comment]
I have a pull resquest in review right now
