### ISSUE TITLE
Notification Digest - default language is French

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#992]
The notification digest is defaulted to French when a user turns it on fir the first time. Please have it default to the language set in the users preference (or English if not possible).

**Comment by LemieuxGen** [comment]
@Phanoix, is this something that can be easily changed and pushed this weekend along with the other stuff? 
@pandurx FYI

**Comment by Phanoix** [comment]
Should be, I'll take a look.
